### ISSUE TITLE
git rebase Progress

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#102]
New in git 1.8.3:

> During a git rebase session the prompt string generator (in contrib/completion/) will show how many changes there are in total and how many have been replayed.

Can we do this?

**Comment by rkeithhill** [comment]
BTW I'd be happy with a simple indicator that says we're in the middle of a merge/rebase operation that needs to be continued or aborted.

**Comment by dahlbyk** [comment]
> I'd be happy with a simple indicator that says we're in the middle of a merge/rebase operation that needs to be continued or aborted.

That already exists, e.g `[my-branch|REBASE-i]`.

**Comment by rkeithhill** [comment]
Cool.  Guess I need to pay better attention when I'm in that state.  :-)
