### ISSUE TITLE
Start-SshAgent hangs when module is being loaded

### ISSUE THREAD

**Issue by noamkfir** [dahlbyk/posh-git#103]
When I run powershell.exe, it hangs. If I comment out Start-SshAgent in profile.example.ps1, it stops hanging.

If I call Start-SshAgent manually in ISE, the SSH agent is added successfully, but it produces the following output:

```
ssh-add.exe : Identity added: C:\Users\MyUser\.ssh\id_rsa 
(C:\Users\MyUser\.ssh\id_rsa)
At C:\Users\MyUser\Code\posh-git\GitUtils.ps1:285 char:25
+         if ($sshPath) { & $sshAdd $sshPath }
+                         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Identity added:...MyUser\.ssh\id_rsa): 
   String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

This output does not appear when the module is being loaded.

Stepping through the code, everything seems ok. I don't know if these two issues (hanging and NativeCommandError output) are related, but it does seem like a strange coincidence.

**Comment by Morgy93** [comment]
Open since Jun 2013? Well..
I'm having the same issue on PowerShell ISE startup:
![unbenannt](https://cloud.githubusercontent.com/assets/7961978/11931256/1a719d16-a7eb-11e5-9a2e-e6311a5b4cc4.PNG)

Any help?

**Comment by rkeithhill** [comment]
The error generate in ISE is harmless.  *nix utilities have a habit of using stderr to output info.  ISE converts all stderr output to an ErrorRecord.   This is an old enough issue (starth-sshagent hanging) and given that OpenSSH support on Windows provides an ssh-agent Windows service, I'm closing this.  If someone runs into this issue again, I suggest trying the `posh-sshell` module to see if the issue still exists.  If it does, file an issue in https://github.com/dahlbyk/posh-sshell.
