### ISSUE TITLE
git reset HEAD@{1} results in error

### ISSUE THREAD

**Issue by kenwarner** [dahlbyk/posh-git#106]
I issued the command `git reset HEAD@{1}` and I got the following message

> error: unknown switch `e'

The same command works fine from Git Bash

**Comment by dougludlow** [comment]
@JayBazuzi, you're a lifesaver.

**Comment by taeguk** [comment]
+1

**Comment by Far3** [comment]
@JayBazuzi  Thank you!

**Comment by JawadS** [comment]
Will there be a resolution for this in `posh-git` or do we always have to omit those with single quotes?

**Comment by dougludlow** [comment]
@JawadS this is an issue with PowerShell, not posh-git.

**Comment by JawadS** [comment]
Hmm, Such a shame, I enjoyed using `posh` but a few issues like these forced me to switch back to `git-bash`

**Comment by dougludlow** [comment]
@JawadS - I think it makes sense to use whatever works best for you. I like poshgit and haven't found it limiting.

**Comment by jmacc** [comment]
Gracias por la observacion.

**Comment by babaie774** [comment]
+1
