### ISSUE TITLE
Tab completion for tags

### ISSUE THREAD

**Issue by Haacked** [dahlbyk/posh-git#108]
I went to checkout a tag and typed:

```
git checkout tags/
```

And started hitting `{tab}` hoping it would cycle through my tags but it didn't. Would be a nice touch to add that.

**Comment by joshgo** [comment]
Also, tag completion doesn't seem to work with the `push` command:

`git push origin v`   then hit {tab key} and nothing

Note, the **v** is there because all our version tags start with a **v** ... semver.

**Comment by rkeithhill** [comment]
@Haacked  This works for checkout but you don't specify `tags/`.  In fact, when I try `git checkout tags/<checkout` in Bash, that doesn't auto-complete either.  What does work in both Bash and posh-git is: `git checkout v<tab>` for the semver approach where you prefix with a `v`.

@joshgo `git push origin v<tab` works for me with the latest bits.

I'm going close this.  Feel free to re-open if you still think there is an issue here.
