### ISSUE TITLE
Git Checkout from Powershell ISE displayes error message but works fine.

### ISSUE THREAD

**Issue by robianmcd** [dahlbyk/posh-git#109]
When I checkout a branch from Powershell ISE I get an error message like this:

git : Switched to branch 'newBranch'
At line:1 char:1
- git checkout newBranch
- ~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (Switched to branch 'newBranch':String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

If I checkout from powershell console I don't get the message. The answer for this question http://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide explains how Powershell Console and Powershell ISE handle standard error differently but I don't understand why anything is getting sent to standard error when you checkout.

Any idea what's going on here?
Thanks,
Rob

**Comment by giggio** [comment]
I know this is an old one, but just in case anyone reads this after me: you can use `-q` option to stop progress reporting, like this: `git clone -q <otherparams>`. This will remove all the unnecessary info powershell would show.

**Comment by leftler** [comment]
Another option besides the suggestion of @giggio suggested another option is add the flag `--porcelain` on to the command, this formats the text that is meant to be used with scripting.

Here is a comparision of the two with git push (running in powershell with 0.7.1 version of the posh-git module)
````
C:\Source [master ↑14]> git push
git : To https://hsah.visualstudio.com/BlueSkyNA/_git/RXWorks
At line:1 char:1
+ git push
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (To https://hsah...NA/_git/RXWorks:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   dd132d3..559e3ef  master -> master

C:\Source [master ≡]> git push --porcelain
To https://hsah.visualstudio.com/BlueSkyNA/_git/RXWorks
=	refs/heads/master:refs/heads/master	[up to date]
Done
```

**Comment by j2jensen** [comment]
It [looks like](https://stackoverflow.com/a/47232450/120955) you can now redirect stderr to stdout throughout your powershell script by simply setting an environment variable:

    $env:GIT_REDIRECT_STDERR = '2>&1'
