### ISSUE TITLE
Different Themes

### ISSUE THREAD

**Issue by dunckr** [dahlbyk/posh-git#115]
I prefer a only displaying the current directory but I appreciate that others like showing the full path or only a [portion](https://github.com/dahlbyk/posh-git/pull/58).

I propose that multiple themes could be added to a subfolder and users could specify a particular version on install.

This would prevent the default profile example from being overridden but still allow other users to share their customisations.

**Comment by rkeithhill** [comment]
@dahlbyk Can we close this as A) partially out of scope, B) partially addressed by the sample prompts added to the README.md and C) will be further addressed by implementing #345?

**Comment by dahlbyk** [comment]
Sure. I'm still not opposed to using the wiki here for folks to share their custom `prompt` fanciness (color or otherwise).

**Comment by rkitover** [comment]
@dahlbyk Thank you so much for your work on this.

I have been working on this theme for a while:

https://gist.github.com/rkitover/61b85690896e29b42897b99c2486477c

any objections to me publishing it on the gallery?

**Comment by rkitover** [comment]
@dahlbyk 

Also, should we have a namespace for theme modules?
Like `posh-git-theme-<whatever>` or something.

**Comment by rkitover** [comment]
@dahlbyk @dunckr 

I finally published my theme on the gallery:

https://www.powershellgallery.com/packages/posh-git-theme-bluelotus

. This is the repo:

https://github.com/rkitover/posh-git-theme-bluelotus

. If anyone wants to use this for scaffolding their own theme, please feel free.

And if you have any suggestions or if I'm doing anything wrong, please let me know.
