### ISSUE TITLE
Suggestion: merge (some) features from legit project

### ISSUE THREAD

**Issue by sergionalin** [dahlbyk/posh-git#122]
Have you considered merging in some of the functionality offered by legit? (https://github.com/kennethreitz/legit)

I'm thinking of the "switch" alias/command (automatically stash current changes when switching to other branch, auto-unstash when switching back, very handy!)

You could actually install legit beside posh-git, but legit requires Python which is kinda overkill plus getting legit to work properly on Windows is quite a pain.

**Comment by dahlbyk** [comment]
I have settled on focusing this module on prompt and tab expansion. Thanks for the tip on legit, though!
