### ISSUE TITLE
GitPromptSettings.DefaultForefroundColor becomes foreground color EVERYWHERE

### ISSUE THREAD

**Issue by MichaelPaulukonis** [dahlbyk/posh-git#123]
Unless I'm enabling posh-git incorrectly, it runs from my profile, and resets the `$Host.UI.RawUI.ForegroundColor` each and every time to the `GitPromptSettings.DefaultForefroundColor`

My expected behavior would be that when we are NOT in a git repository, the foreground color should not be modified.

**Comment by dahlbyk** [comment]
I haven't seen any issues with this recently... feel free to reopen if it's still a problem.
