### ISSUE TITLE
Case sensitivity with file paths

### ISSUE THREAD

**Issue by nycdotnet** [dahlbyk/posh-git#130]
Posh-git displays strange behavior if you navigate to a directory using the wrong case.

Imagine a directory called "code" with a subdirectory called "Model".  The posh-git prompt is in code.  User types "cd model" (all lower-case, so technically the incorrect case).  PowerShell handles this fine and will show the prompt as "code\model", but if you do git status (for example) it will show any changes in the Model folder as "..\Model\changedfile.txt" instead of "changedfile.txt".  This is technically correct if Git is assuming that both the model and Model directories exist. Other commands such as git mv OLD NEW, don't work at all as Git will warn that the file is not under source control.

Is there any way to get posh-git to intercept and fix cases on cd commands (or at least error/warn if a case is invalid)?  I'm willing to look into this a bit if it sounds like this is something that you're interested to address.  Thanks!

**Comment by dahlbyk** [comment]
Not sure when this was fixed, but I can no longer reproduce this in git 2.10.2.

**Comment by nycdotnet** [comment]
ty
