### ISSUE TITLE
Exclamation mark meaning

### ISSUE THREAD

**Issue by vorou** [dahlbyk/posh-git#131]
It is said in the readme that exclamation mark denotes conflicted files. However, it also appears when there is an untracked file in working dir. Is it by design?

**Comment by 304NotModified** [comment]
This can issue is resolved and can be closed?

**Comment by abbiekressner** [comment]
I'm a Linux/Mac convert, so I may be misunderstanding something really basic here, but I don't quite understand the exclamation point in the following since I do not have any untracked files.
````
\\dtu-storage\aakress\binary-mask-errors [master ≡ +0 ~1 -0 !]> git status
On branch master
Your branch is up-to-date with 'bit/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   setup/createXMLSetup.m
````

Furthermore, `UntrackedText` does not appear to be a property of `$GitPromptSettings`. Has there been a change in the code without an update to the README?
````
Exception setting "UntrackedText": "The property 'UntrackedText' cannot be found on this object. Verify that the property exists and can be set."
At line:1 char:1
+ $GitPromptSettings.UntrackedText = ''
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
````

Thanks in advance for any help anyone can provide me!

**Comment by dahlbyk** [comment]
Sorry for the confusion! In addition to adding the ahead/behind symbol, #202 also expanded the "!" to indicate any unstaged change (in contrast with "~", which indicates only staged changes).

> Furthermore, `UntrackedText` does not appear to be a property of `$GitPromptSettings`. Has there been a change in the code without an update to the README?

Yes! See https://github.com/dahlbyk/posh-git/pull/202#commitcomment-13095293 for the adjustment. I finally got around to merging #221, but will further adjust for this settings change. Thanks for the correction!
