### ISSUE TITLE
Executable script code found in signature block

### ISSUE THREAD

**Issue by rmegal** [dahlbyk/posh-git#134]
I get this error when firing up a PowerShell window after installing posh-git using Choclatey:

At C:\Users\Ray\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:69 char:1
- . 'C:\tools\poshgit\dahlbyk-posh-git-c481e5b\profile.example.ps1'
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Executable script code found in signature block.
  - CategoryInfo          : ParserError: (:) [], ParseException
  - FullyQualifiedErrorId : TokenAfterEndOfValidScriptText

Any ideas?

**Comment by snpolshin** [comment]
> Moving the load of the posh-git profile before the signature solves the problem.

ty rmegal, it's work!
