### ISSUE TITLE
Long Branches

### ISSUE THREAD

**Issue by MHM5000** [dahlbyk/posh-git#142]
Hi
<a href="http://imgur.com/RwQyK2o"><img src="http://i.imgur.com/RwQyK2o.jpg?1" title="Hosted by imgur.com" /></a>
How can I fix the long Branching?

**Comment by bcdady** [comment]
`git branch --unset-upstream master` doesn't sound like a complete resolution to the symptoms called out by Mohammad and Jeremy. Is there any more info needed to reconcile this, or should we mark it as 'wontfix'?

**Comment by dahlbyk** [comment]
Definitely not a satisfactory resolution, but I'm closing for now... If past or future visitors are able to provide more info maybe we can figure it out?
