### ISSUE TITLE
"WARNING: Could not find ssh-agent" is displayed whenever I launch powershell

### ISSUE THREAD

**Issue by vivmaha** [dahlbyk/posh-git#160]
This started happening after I installed posh-git.
![capture](https://cloud.githubusercontent.com/assets/6677347/4963501/9145bfa0-6717-11e4-9169-a3178c3fc563.PNG)

**Comment by kh-nguyen-le** [comment]
This popped up for me after upgrading to git for windows 2.5.0 (not the github client).
Just so people who google this know: ssh-agent's location changed from /git/bin to /git/usr/bin.

**Comment by holytshirt** [comment]
For git for windows 2.5.0 as @kh-nguyen-le said the ssh-agent location has changed and is also now x64. I've modified my ```Microsoft.PowerShell_profile.ps1``` and added ```$env:path += ";${env:ProgramFiles}\Git\usr\bin"``` 
```powershell
$env:path += ";${env:ProgramFiles}\Git\usr\bin"
# Load posh-git example profile
if(Test-Path Function:\Prompt) {Rename-Item Function:\Prompt PrePoshGitPrompt -Force}
. 'C:\tools\poshgit\dahlbyk-posh-git-7acc70b\profile.example.ps1'
```

**Comment by dahlbyk** [comment]
I just merged a fix that checks `Git/usr/bin` after `Git/bin`. Let me know if the issue persists.
