### ISSUE TITLE
Deprecate PowerShell 2.0 Support

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#163]
Dropping support for PowerShell 2.0 means fewer workarounds like #162. Before we do so, it would be good to warn those using 2.0 about the change:

* [ ] Add warning mentioning that PowerShell 2.0 will no longer be supported.
* [ ] Provide link to [PowerShell 3.0 download](https://www.microsoft.com/en-us/download/details.aspx?id=34595).
* [ ] Provide link to this issue for those wishing to express dissent.
* [ ] Provide a setting to disable the warning?

**Comment by Neon22** [comment]
just getting this warning now. but the link suggested:
- https://www.microsoft.com/en-us/download/details.aspx?id=34595
This download includes Windows PowerShell 3.0, WMI, WinRM, Management OData IIS Extension, and Server Manager CIM Provider
All of which seem essential to make powershell work. but are labelled as incompatible with the Configuration Manager, and System Center Virtual Machine Manager and some others.

Does not donwloading this mean I can't use github for windows, or github anymore ?

**Comment by dahlbyk** [comment]
@Neon22 what version of Windows Server are you using? You might try jumping straight to [PowerShell 4.0](https://www.microsoft.com/en-us/download/details.aspx?id=40855) or [PowerShell 5.0](https://www.microsoft.com/en-us/download/details.aspx?id=50395)?

**Comment by Neon22** [comment]
oh... completely unaware - good solution - thanks...

**Comment by dahlbyk** [comment]
Done: https://github.com/dahlbyk/posh-git/commit/83caec17642f1d2b4322d13c97f5fbc3f6a66642

**Comment by Tracy-Tra** [comment]
Hrm... well, I just now started getting the "get version 3.0" warning yesterday. I'm still using windows 7 and those links to get the newer powershell just take me to an "upgrade to windows 10" link, which I don't really want to do. Any suggestions aside from telling me to upgrade to windows 10? Would it hurt anything to just suppress the warning for now?

**Comment by coridrew** [comment]
fwiw, I have to dev on an x86 win7 machine for a current client, and was able to successfully upgrade Powershell on that dinosaur :)

**Comment by Tracy-Tra** [comment]
so how do I do that? Links to instructions would be wonderful....  going to google it, but hopefully maybe you'll have some direction for me as well.

**Comment by Tracy-Tra** [comment]
*sigh* Never mind and thanks for the replies. I just realized the link only has an advert for windows 10... not that I have to install it.... hehe. Sorry all!

**Comment by sanjanat** [comment]
![ps](https://cloud.githubusercontent.com/assets/3365838/15960678/874083fc-2f1e-11e6-9d31-8b9b1e7a81aa.png)

Which one shall I select ?

**Comment by dahlbyk** [comment]
> Which one shall I select ?

Which OS and architecture (32- or 64-bit) do you have?

**Comment by SnailSword** [comment]
Where is the setting to disable the warning

**Comment by theaquamarine** [comment]
$NoVersionWarn, https://github.com/dahlbyk/posh-git/blob/master/posh-git.psm1

**Comment by lZzozZl** [comment]
dahlbyk commented on Jun 10
Which one shall I select ?
Which OS and architecture (32- or 64-bit) do you have?



i have windows 7 ultimate 64-bit

**Comment by dahlbyk** [comment]
> i have windows 7 ultimate 64-bit

Vista = Windows6.0
Win7 = Windows6.1

x86 = 32-bit
x64 = 64-bit

So for Win7 64-bit you want `Windows6.1-KB2506143-x64.msu`.

**Comment by lZzozZl** [comment]
ty

**Comment by chrisdemetriad** [comment]
I am on Windows Server 2008 R2. Will probably look for something else then.

**Comment by theaquamarine** [comment]
2008 R2 is Windows6.1, so would use Windows6.1-KB2506143-x64.msu
2008 is Windows6.0.

**Comment by rainecyt** [comment]
PowerShell 4.0/ PowerShell 5.0/ PowerShell 3.0 are not fit my PC ,can not updata ,what I can do next

**Comment by dahlbyk** [comment]
What OS are you using that you're unable to upgrade to PS 3?

I'm not all that interested in trying to preserve compatibility with Vista or XP, but you could certainly maintain a fork that maintains PS 2.0 compatibility and back-ports new features. Or just use an older version of posh-git.

**Comment by gherson** [comment]
> WARNING: posh-git support for PowerShell 2.0 is deprecated; you have version 2.0.
> To download version 5.0, please visit https://www.microsoft.com/en-us/download/details.aspx?id=50395
> For more information and to discuss this, please visit https://github.com/dahlbyk/posh-git/issues/163

To lose the above error I d/l'ed and installed Win7AndW2K8R2-KB3134760-x64.msu on my Win7 SP1 system (twice) as instructed then rebooted as it requested, and /still have the error/.  The only folder I see under C:\Windows\System32\WindowsPowerShell is v1.0.  (Just FYI; I'm giving up on this for now.)

**Comment by rkeithhill** [comment]
The folder name `C:\Windows\System32\WindowsPowerShell\v1.0` is the same for all versions of Windows PowerShell.  To tell which version you are running, type `$PSVersionTable` at the PowerShell prompt and hit enter.

**Comment by gherson** [comment]
Good to know, thanks.  
PowerShell version is still v2.0 after installing aforementioned .msu:

```
~\Documents\GitHub> $PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

**Comment by dahlbyk** [comment]
`BuildVersion` confirms you're on Win7 SP1, which is supported, so not sure why the installer would not be working for you. Does the Event Log have anything to say?

**Comment by gherson** [comment]
Good call! thanks: 
Control Panel\System and Security\Windows Update\View update history shows that my first install of KB3134760 yesterday failed (silently but with code 80070308) and that my second install was "Successful".  After another reboot, Git Shell and PowerShell v5.0 are working with no complaints.
