### ISSUE TITLE
Branch name tab expansion does not work with aliases

### ISSUE THREAD

**Issue by Haacked** [dahlbyk/posh-git#164]
I have the following alias in my `.gitconfig` (To test, I cleared out everything else so my gitconfig only contained the following).

``` ini
[alias]
    co = checkout
```

A long time ago, Posh-Git tab expansion for branch names would work with this. But now it doesn't.

Expected: Given a repo with branches, `git co x{tab}` would expand a branch name that starts with "x"
Actual: Nothing happens.

**Comment by dahlbyk** [comment]
> Let me double check and get back to this.

@Haacked since you mentioned this last month, are you still not seeing alias expansion?

**Comment by Haacked** [comment]
I'm still not seeing it @dahlbyk. I just updated to the latest version too.

**Comment by dahlbyk** [comment]
Fascinating, still works for me. Are you seeing any `$Errors`? Glad to screen share and have a look.

**Comment by dahlbyk** [comment]
@Haacked how about now? 😞

**Comment by rkeithhill** [comment]
Aliases work for me as well.

**Comment by dahlbyk** [comment]
Pretty sure @Haacked is just trolling me. If someone else is able to reproduce, I'd love to know more about the environment.

**Comment by Haacked** [comment]
@dahlbyk sorry, we just updated Posh-Git in Desktop to master a week ago and I still get the problem.

Is there a command I could run that would tell you which version of Posh-Git is loaded in case I happen to have a rogue installation?

**Comment by rkeithhill** [comment]
Try `Get-Module posh-git | Format-Table Version, ModuleBase`

**Comment by Haacked** [comment]
0.6.1.20160330

**Comment by rkeithhill** [comment]
That is the old version.  New version should be something like `0.7.0-pre*`.  We updated the version number on January 26th.  A bit more than a week ago.

**Comment by Haacked** [comment]
Ah, I might not have shipped the update to Posh-Git in Desktop yet.

**Comment by dahlbyk** [comment]
@Haacked If you're going to ship a Desktop update of posh-git, hang tight for a few days so we can get 0.7 finalized.

I'd love a GIF or something of the config/behavior you're expecting to tab-complete that isn't. Can anyone else on the Desktop team repro what you're seeing?

**Comment by Haacked** [comment]
@dahlbyk so here's what I did. I cleared out my `.gitconfig` to be just the following.

```
[alias]
    co = checkout
```

Then I ran the following set of commands...

![image](https://cloud.githubusercontent.com/assets/19977/22986078/3ef42530-f35f-11e6-8c5a-bd5c3cd04833.png)

So in the last part, I typed `git co ` and then I hit the TAB key and I expected it to cycle through the branch names but it auto-completed with `.\.git`

**Comment by rkeithhill** [comment]
I can't repro this:

![posh-git-tab-completion2](https://cloud.githubusercontent.com/assets/5177512/22986931/5e6d3144-f36a-11e6-8bde-7703515d0f73.gif)

**Comment by Haacked** [comment]
@rkeithhill I wonder if it's something with the way we load Posh-Git in GitHub Desktop. If you try it with GitHub Desktop, can you repro it?

**Comment by rkeithhill** [comment]
I will try that later tonight.  Does it matter if I have git.exe already installed (from git-scm.com)?

**Comment by Haacked** [comment]
> I will try that later tonight. Does it matter if I have git.exe already installed (from git-scm.com)?

I don't think so. If you launch the shell from our shortcut (or from the app by hitting the `~` key) it'll use our Git. We use the `.gitconfig` from the same place though `%UserProfile\.gitconfig`.

**Comment by rkeithhill** [comment]
I downloaded Windows for GitHub for a Windows 8 VM I have.  It didn't come with posh-git 0.7.0 so I updated to 0.7.0.  With that I can repro what you are seeing.  Now let me see if I can figure out what is going on.  

Also, we reorg'd the posh-git dir structure we'll need to work with ya on how to configure your AppData\Local\GitHub\PoshGit... dir.

**Comment by rkeithhill** [comment]
OK seems to be failing a regex check because we are getting back two co aliases.   If I try an alias that isn't duplicated, then it works:
```
2> git config --get-regexp alias\.co
alias.co checkout
alias.co checkout
```

**Comment by rkeithhill** [comment]
Logged as #421.  PR coming soon.

**Comment by Haacked** [comment]
@rkeithhill thanks for figuring this out! In the short run, I'll just remove my local one. 😄

**Comment by rkeithhill** [comment]
@Haacked  BTW how does GH4W start PowerShell?  Is it using a PS console file or just starting the PowerShell.exe process?

**Comment by Haacked** [comment]
> @Haacked BTW how does GH4W start PowerShell? Is it using a PS console file or just starting the PowerShell.exe process?

We start the the PowerShell.exe process. We look in the following places for `powershell.exe`:
- `%PATH%`
- `%SystemRoot%\System32`
- `%SystemRoot%\System32\WindowsPowerShell\v1.0`

If you have `$GITHUB_PROFILE` defined, we'll load that profile only (with these flags `-NoProfile -File "$GITHUB_PROFILE"`) where `$GITHUB_PROFILE` is replaced with the path to your GitHub Profile file.

If you don't have `$GITHUB_PROFILE` defined, we'll use the following flag ` -File "PATH/TO/profile.example.ps1"`

That way we load your $PROFILE if it exists and the example profile for PoshGit.

**Comment by rkeithhill** [comment]
Thanks for the explanation!  Was a bit worried that the change in dir structure might mess up GH4W but since you're using profile.example.ps1 there shouldn't be any issues.

**Comment by Haacked** [comment]
> but since you're using profile.example.ps1 there shouldn't be any issues.

Except that I keep getting a warning now that 

> WARNING: posh-git's profile.example.ps1 will be removed in a future version. To avoid a change in behavior, copy its contents into your ....Microsoft.PowerShell_profile.ps1

😛 

I guess our workaround could be that we could keep loading a private copy of `profile.example.ps1` to make it easy for users.

**Comment by dahlbyk** [comment]
You should be using 0.7, which doesn't have that warning. 😜

But seriously, as of  #444 you can hide the warning by calling `profile.example.ps1` with `choco` as its first arg. (I would accept a PR that switches that to a proper parameter, if you care to make the hack not Chocolatey-specific.) Or just stop using `profile.example.ps1` now in favor of something like:

```powershell
Import-Module $env:github_posh_git\posh-git.psd1
Start-SshAgent -Quiet
```

For the record, `profile.example.ps1` won't actually go away until everything* breaks in 1.0.

\* not actually everything.

**Comment by dahlbyk** [comment]
And just now I am noticing the previous entries in the thread. Context helps.

> If you don't have `$GITHUB_PROFILE` defined, we'll use the following flag `-File "PATH/TO/profile.example.ps1"`

My recommendation would be for you to start using a GitHub-specific "default profile" that could probably be a bit simpler/smarter than our `profile.example.ps1` needs to be.
