### ISSUE TITLE
Indicate current branch is an up-to-date remote tracking branch

### ISSUE THREAD

**Issue by terrajobst** [dahlbyk/posh-git#172]
As discussed in #125: some folks (including myself) liked the behavior that posh-git rendered the remote branch. An alternative would be using a different color or some other visual clue that the current branch is a remote tracking branch that is-up-date. Otherwise, when I see a branch rendered in cyan its'c unclear whether it's a local branch or an up-to-date remote tracking branch.

**Comment by dahlbyk** [comment]
I wonder if we should add another state to #190 that's `=` or something to indicate a tracking branch that's up to date?

**Comment by bazzilic** [comment]
Probably, should be optional. I'd say that `=` is not intuitive and in this case it might be better to not show anything than show a confusing symbol.

**Comment by dahlbyk** [comment]
Any suggestions for a better indicator? Or if each indicator is configurable this one could default to empty and be left to individuals to pick something meaningful.

To some extent, though, it's just docs and familiarity - `~` for "modified" probably isn't necessarily intuitive for all.

**Comment by paulmarsy** [comment]
What about something like this?

paulmarsy/posh-git@6c69c0efe67191303c85f0451b080ac9af9eeb8f

Using U+2191 for the up ↑ arrow and U+2193 down the down ↓ arrow as they seem supported by most fonts.

**Comment by rkeithhill** [comment]
@dahlbyk A PR was merged for this.  Can this issue be closed?

**Comment by dahlbyk** [comment]
This was closed by #202.
