### ISSUE TITLE
Tab completion when checking out remote branches

### ISSUE THREAD

**Issue by andyphilpotts** [dahlbyk/posh-git#177]
I do a fetch with a (Stash based) remote, and see a new remote branch, "origin/bugfix/XXX-999-pdf-to-tiff-quality"

I try "git checkout bugfix/XXX" then tab, nothing completes. I can see why, the branch is not local yet, but git itself would accept "git checkout bugfix/XXX-999-pdf-to-tiff-quality" , I get no completion because git treats branch names in special ways in some cases.

I hope I am just missing something, if not, I'll fork and fix if I can!

**Comment by dahlbyk** [comment]
You're not missing anything - the `gitBranches` function to look up branch names is not aware that Git will let you checkout remote branches without the remote prefix.

**Comment by andyphilpotts** [comment]
Well, I guess I better fix that, unless it is in progress with someone
else, I may be a bit slow, but... yo-ho, yo-ho, it's off to clone I go!

**Comment by andyphilpotts** [comment]
I think I can see how to fix this, the code is pretty easy to understand,
simpler than I expected, thanks.

**Comment by dahlbyk** [comment]
Glad to hear it. You've probably noticed, but we currently handle `checkout` along with a larger list of commands that use refs - probably need to separate `checkout` out from the others.

**Comment by andyphilpotts** [comment]
yup, i was adding a specific match as you say, the slightly trickier bit was to figure out unique branch names, as if two remotes use the same name, that must be excluded from the match, i plan to wrap this up tonight, if i can, and am happy to do so, i use posh-git and want to pay back by contributing

--
Andy

**Comment by dbarrett84** [comment]
Was there ever a fix made for this???

**Comment by petterek** [comment]
Any progress?

**Comment by dahlbyk** [comment]
This was fixed by #352
