### ISSUE TITLE
Setting TERM=cygwin unnecessarily?

### ISSUE THREAD

**Issue by floyd-may** [dahlbyk/posh-git#178]
After interacting with the colorama team, is posh-git setting TERM=cygwin when it's not necessary?

Please see the colorama issue here:
https://code.google.com/p/colorama/issues/detail?id=63

Thanks!

**Comment by dahlbyk** [comment]
We do that to [enable colors](https://github.com/dahlbyk/posh-git/blob/869d4c5159797755bc04749db47b166136e59132/GitUtils.ps1#L209-L211): added with https://github.com/dahlbyk/posh-git/commit/26318c790c7fd93f96e04e4a470117b8a45843a2 based on [this thread](https://groups.google.com/forum/#!topic/posh-git/uP6AOZmxihA).

This is really the first I've heard of it causing a problem... Do you still get Git colors if you remove the `Enable-GitColors` call from `profile.example.ps1`?

**Comment by floyd-may** [comment]
Commenting out `Enable-GitColors` in `profile.example.ps1` appears to have no effect: the prompt still shows up in color, as does the output of a `git status`. The thread you referenced is pretty old; seems like `TERM=cygwin` might not be necessary anymore?

**Comment by chenbojian** [comment]
I think floyd-may is right. I also met this problem when I use pytest(a python package use colorama).
After I set $env:TERM="", pytest show color correctly.
`git status` can still show color.

**Comment by dahlbyk** [comment]
My testing shows the same - see #191.

**Comment by lukebakken** [comment]
FWIW, I just updated my clone of posh-git and now receive this warning:

```
C:\Users\lbakken\Documents\WindowsPowerShell\Modules\posh-git
[master]$ git grep foo
WARNING: terminal is not fully functional
```

This isn't the end of the world as I can just set `TERM` in my user env vars, but removing the setting from posh-git did have an effect. Having said that, it's not really posh-git's responsibility to set that variable.

**Comment by dahlbyk** [comment]
> Having said that, it's not really posh-git's responsibility to set that variable.

I support this. So many environments out there, so it seems the less we try to do here maybe the better?
