### ISSUE TITLE
Measure the length of the Git prompt

### ISSUE THREAD

**Issue by JayBazuzi** [dahlbyk/posh-git#179]
When the prompt gets really long, there's not much room to write commands. That's why my `prompt()` looks something like:
```
$width = ($Host.UI.RawUI.WindowSize.Width - 2 - $(Get-Location).ToString().Length)
Write-Host -NoNewline -ForegroundColor Red (Get-Location)
Write-Host -NoNewline " "
Write-Host -NoNewline -ForegroundColor Red (New-Object System.String @('-',$width))
"PS> "
```
The result looks like:
```
C:\Users\Jay -----------------------------------------------------
PS> _
```
where the red dashes fill the full width of the console. I want to include the PoshGit results in that line, but I can't calculate the length of what it will produce.

I wish I could do something like:
````
$vcsStatusLength = (Write-VcsStatus).Length
```

**Comment by dahlbyk** [comment]
Hrm... Since `Write-VcsStatus` includes applying colors to the host I'm not sure what our options are here. Any ideas?

I wonder if you could write out status and then use the host cursor API (whatever it's called) to calculate how many more dashes to write?

**Comment by JayBazuzi** [comment]
Yep, that's what I ended up doing.
