### ISSUE TITLE
Posh-git cmdlets misbehave if you have $ErrorActionPreference = "Stop"

### ISSUE THREAD

**Issue by mnaoumov** [dahlbyk/posh-git#182]
One of the most annoying if you go to the repository folder with detached head then prompt function fails and shows ugly _C:\MyProjectPS>_

**Comment by rkeithhill** [comment]
Is this still a problem?  I don't see any issues when HEAD is detached. I see:
```
[(sha1...) <rest of status info>] <path>
> _
```

**Comment by dahlbyk** [comment]
I can't reproduce either - if you can, please include what you see in `$Error` when the prompt fails.

**Comment by dahlbyk** [comment]
This may have been fixed by https://github.com/dahlbyk/posh-git/pull/307
