### ISSUE TITLE
git log not working for deleted files

### ISSUE THREAD

**Issue by bill-sorensen** [dahlbyk/posh-git#185]
The technique from http://stackoverflow.com/a/16635324/161457 does not work with posh-git.

`git log -- pathOfDeletedFile` gives "ambiguous argument" under posh-git but works under Git Bash.

**Comment by theaquamarine** [comment]
It appears to be working properly for me. What version of Powershell are you using? V2 doesn't handle the ```--``` right and needs it to be wrapped in quotes.

```$PSVersionTable.PSVersion``` to find the version.

**Comment by bill-sorensen** [comment]
@theaquamarine V2. Sounds like that's the issue. Thanks!
