### ISSUE TITLE
TFS Support?

### ISSUE THREAD

**Issue by jbruett** [dahlbyk/posh-git#188]
Tried to do a clone of a TFS Online library and received the following...maybe i'm missing something, but the tab completion worked when i had git tfs <tab> it presented options, so it new what i wanted to do.  listed version of the posh-git is 0.0, just re-downloaded from this repo.

``` powershell
git tfs clone 'https://<url to project>/'
git: 'tfs' is not a git command. See 'git --help'.

Did you mean one of these?
        notes
        stash
        tag
```

**Comment by jeremysawesome** [comment]
Is git tfs in your path? You might need to add it to your path before it's recognized. 

The git-tfs readme talks about this here:
https://github.com/git-tfs/git-tfs#get-git-tfs

Just a thought.

**Comment by dahlbyk** [comment]
Yeah, this doesn't ship with `git-tfs`, it just knows about some of its commands. I'm pretty sure it ships with GitHub for Windows, which also includes posh-git, if you want to try that.
