### ISSUE TITLE
Git runs but posh-git doesn't when standard user

### ISSUE THREAD

**Issue by CSeilr** [dahlbyk/posh-git#189]
When running under Windows 8.1 and as standard user, git commands work, but posh-git functions do not (no fancy prompt, no tab autocompletes).  When I run Powershell as administrator, posh git works as expected.  What might I be missing?

**Comment by dahlbyk** [comment]
Try `Get-Module posh-git` and `git --version` from the prompt where it doesn't work?

**Comment by CSeilr** [comment]
Thanks for the response.  When I do `Get-Module posh-git` it returns directly to the command prompt.  When I do  `git --version` it says `git version 1.9.5.msysgit.1`

**Comment by dahlbyk** [comment]
`Get-Module` returning nothing means PowerShell isn't being loaded in your non-Administrator profile. You can confirm with `select-string 'posh-git' $PROFILE`.

I'd suggest running `install.ps1` from your non-admin shell, which should create or update the current `$PROFILE`.

**Comment by CSeilr** [comment]
Thanks.  That was it.  Not sure why I needed that step as I don't recall running the install.ps1 for the non-admin account on my Windows 7 machine, but it could be that I just misremembered it.
