### ISSUE TITLE
Idea: Optional indication of being ahead/behind of remote branch with up/down arrows

### ISSUE THREAD

**Issue by bazzilic** [dahlbyk/posh-git#190]
The idea is from this prompt for zsh: https://github.com/sindresorhus/pure

In my opinion that would be easier to understand than coloring. Okay, green makes sense; red is more or less understandable as well. But cyan and yellow seem to me as random colors and I find it difficult to recall by seeing cyan branch name what it actually means.

Also, me and many others use powershell through ConEmu, which has themes that remap colors. Originally cyan might end up as a different color when actually displayed on screen. Probably, other console emulators do the same.

Arrow up: you can push.
Arrow down: you can pull.
No arrows: you are matched with the remote

**Comment by dahlbyk** [comment]
I support this. Would be nice for the ahead/behind text to be configurable, defaulting as you propose. Seems reasonable for the coloring of the indicator to align with the branch color?

**Comment by paulmarsy** [comment]
What about something like this?

paulmarsy/posh-git@6c69c0efe67191303c85f0451b080ac9af9eeb8f

Using U+2191 for the up ↑ arrow and U+2193 down the down ↓ arrow as they seem supported by most fonts.

**Comment by bazzilic** [comment]
Do you have a screenshot of the changes you've made in action?

**Comment by paulmarsy** [comment]
No problem..
The changes extend the usage of the existing symbol at the end.

Branch in sync:
![in sync](https://cloud.githubusercontent.com/assets/1769405/8295533/77309ef4-193d-11e5-97d4-41a458093e25.PNG)
Uncommitted change with branch in sync:
![uncommited changes](https://cloud.githubusercontent.com/assets/1769405/8295525/652aa236-193d-11e5-8f24-f9d84c6cb06d.PNG)
Staged files with branch in sync:
![staged in sync](https://cloud.githubusercontent.com/assets/1769405/8295544/91868912-193d-11e5-9fd9-283c58b39921.PNG)
Local branch ahead of origin:
![ahead](https://cloud.githubusercontent.com/assets/1769405/8295508/38df59e2-193d-11e5-8287-928576d5d373.PNG)
Local branch is both ahead and behind origin (the parentheses shouldn't be there):
![ahead and behind](https://cloud.githubusercontent.com/assets/1769405/8295519/537877e8-193d-11e5-9a0a-ffcacdc285f9.PNG)
Local branch is behind origin:
![behind](https://cloud.githubusercontent.com/assets/1769405/8295607/456896f0-193e-11e5-95ff-3ec6b01af8f3.PNG)

**Comment by RandomlyKnighted** [comment]
@paulmarsy I love the colors..green yellow and red in addition to the arrows certainly makes it clearer what the status is

**Comment by dahlbyk** [comment]
It may just be me, but I think I'd prefer the ahead/behind indicator to immediately follow the branch name. Thoughts?

> the parentheses shouldn't be there

:+1:

**Comment by dahlbyk** [comment]
I'm also not sold on `~` indicating equivalence, since `~` also represents staged/unstaged modifications.

Since we're already using Unicode, could go with `≡` "Identical To".

**Comment by paulmarsy** [comment]
How about this:

Unstaged changes:
![unstaged change](https://cloud.githubusercontent.com/assets/1769405/8303669/5214d7ca-1997-11e5-9a82-f342504443bc.PNG)
Staged changes:
![staged change](https://cloud.githubusercontent.com/assets/1769405/8303668/520f0f8e-1997-11e5-8a14-eaa3b8422dda.PNG)
Both staged and unstaged changes:
![staged unstaged files](https://cloud.githubusercontent.com/assets/1769405/8303743/dc47062a-1997-11e5-8660-fd65f6dfbe44.PNG)

Branch in sync:
![branch identical](https://cloud.githubusercontent.com/assets/1769405/8303666/5202e006-1997-11e5-824e-63703c6f6d94.PNG)
Local branch ahead of origin:
![branch ahead](https://cloud.githubusercontent.com/assets/1769405/8303670/52197398-1997-11e5-87fd-a2cee9ca8413.PNG)
Local branch is both ahead and behind origin:
![branch ahead and behind](https://cloud.githubusercontent.com/assets/1769405/8303672/52202f62-1997-11e5-9567-7a1478eb9f08.PNG) 
Local branch is behind origin:
![branch behind](https://cloud.githubusercontent.com/assets/1769405/8303665/51f8fe7e-1997-11e5-9b8f-af6489efb2f4.PNG)

paulmarsy/posh-git@083cb7b43c08bba2485e0cafdb7c3a805b214a99

**Comment by bazzilic** [comment]
For ahead and behind case there's a symbol  ⇅, might be useful here.

Better check if popular mono-spaced fonts have these symbols though. For what comes to mind: Lucida Console, Ubuntu Mono, Droid Sans Mono, Consolas, Monaco, Source Code Pro... Am I missing something?

**Comment by dahlbyk** [comment]
I think my preference would be to always show the ahead/behind status indicator, independent of whether the working directory or index have changes, but that may just be me. I'm not sure I even really pay attention to the untracked `!` at the end, but by now people are probably used to it?

**Comment by dahlbyk** [comment]
@paulmarsy open PR with your change?

**Comment by dahlbyk** [comment]
On a clean Windows 8.1 install, ↑ ↓ ↕ ≡ work with the default font but ⇅ does not:
![2015-06-23_10-24-58](https://cloud.githubusercontent.com/assets/133987/8309829/2a6d0c10-1992-11e5-8792-84f5953dbc77.png)

**Comment by bazzilic** [comment]
Same behavior with Ubuntu Mono.

![clipboard02](https://cloud.githubusercontent.com/assets/1805832/8311828/953dca74-1a0b-11e5-951f-ec02e1e8088c.png)

**Comment by terrajobst** [comment]
I love the proposal form @paulmarsy. It's compact and communicates the state quite visually. 

> I think my preference would be to always show the ahead/behind status indicator, independent of whether the working directory or index have changes, but that may just be me.

I'd second that. Given that those indicators are independent of the working copy/index I'd prefer them to be present at all times as well.

> I'm not sure I even really pay attention to the untracked ! at the end, but by now people are probably used to it?

I wouldn't say I pay attention to it, but I found that information to be valuable at times.

**Comment by ctolkien** [comment]
Some further inspiration:
https://github.com/arialdomartini/oh-my-git

**Comment by dahlbyk** [comment]
This was closed by #202.
