### ISSUE TITLE
Strange newline behavior in emacs

### ISSUE THREAD

**Issue by miabrahams** [dahlbyk/posh-git#194]
Using posh-git in an emacs inferior shell and powershell.el (https://github.com/jschaf/powershell.el) gives somewhat odd behavior.  It seems to insert an extra newline  after the angle bracket in the PS prompt.  So my cursor would appear here: 

PS C:\Users\miabrahams\.emacs.d> 
_

(Reproduces in a blank emacs config using only powershell.el.)

**Comment by dahlbyk** [comment]
In your prompt function (typically in `$PROFILE` or posh-git's `profile.example.ps1`), try replacing `return "> " ` with `Write-Host "> " -nonewline`.

**Comment by JayBazuzi** [comment]
Remember that the `Prompt()` function must return *something*, even a string consisting of only a space.

**Comment by dahlbyk** [comment]
Ah, that's probably why it returns what it does. Haven't touched that in years...

@miabrahams do you see the same behavior if you don't load posh-git?

**Comment by miabrahams** [comment]
`Write-Host "> " -nonewline` did the trick.  Thank you!

**Comment by dahlbyk** [comment]
Two questions:

1. Does the extra line come back if you add a `return " "`?
2. Do you see the extra line with the default prompt when the posh-git prompt isn't loaded?

As @JayBazuzi said, it's apparently expected that the prompt function returns something ([source](https://technet.microsoft.com/en-us/library/hh847739.aspx)):

> Because `Write-Host` writes to the current host application but does not return an object, this function includes a `Return` statement. Without it, Windows PowerShell uses the default prompt, "PS>".
