### ISSUE TITLE
POSH-GIT Color features not showing

### ISSUE THREAD

**Issue by tobitech** [dahlbyk/posh-git#198]
Below is the content of my Microsoft.PowerShell_profile.ps1

Rename-Item Function:\Prompt PoshGitPrompt -Force
function Prompt() {
if(Test-Path Function:\PrePoshGitPrompt){
++$global:poshScope; 
New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor,
 `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;
$private:p = PrePoshGitPrompt;

if(--$global:poshScope -eq 0) {
Remove-Item function:\Write-Host -Force
}
}
PoshGitPrompt
}

What do I need to do to enable this coloring features. I installed poshgit using chocolatey

**Comment by dahlbyk** [comment]
Not sure I understand the problem - you're not seeing colors in the prompt? Do you see colors from `git status`? What host/shell are you using?

**Comment by tobitech** [comment]
No I don't see colours from git status

**Comment by tobitech** [comment]
I am hosting on Visual Studio Online

**Comment by tobitech** [comment]
Yeah, I've fixed it. I just had to clone the posh-git to my local drive and ran .\install.ps1 and reloaded my profile . $profile and it worked. I am happy to see these poshgit features, makes things interesting

**Comment by dahlbyk** [comment]
VS Online is your Git host? What about your local PowerShell? Default or something like Console2/ConEmu?

Glad it's working, but would like to understand if there's another Chocolatey-specific issue.
