### ISSUE TITLE
Hide zero counts?

### ISSUE THREAD

**Issue by jkodroff** [dahlbyk/posh-git#205]
So I've been searching around on how to make [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) as awesome as posh-git, and I came across the [Racotechnic theme](https://github.com/elboletaire/zsh-theme-racotecnic), which is based off posh-git.

I noticed that it hides 0-count items in the file count summary:

![oh-my-zsh racotechnic theme](https://github.com/elboletaire/zsh-theme-racotecnic/raw/master/screenshot.png)

I think this could be a good idea for posh-git since it tightens up the length of the prompt and I don't think the 0's provide much useful info.  Thoughts?

**Comment by dahlbyk** [comment]
My gut says I wouldn't like this because I now have to read the symbol before the number (rather than "pattern matching"), but I wouldn't be opposed to supporting an option to hide the zeroes.

**Comment by rkeithhill** [comment]
Maybe this sort of thing can be addressed with #345?

**Comment by rkeithhill** [comment]
This has been implemented.  Just set the following setting:
```
$GitPromptSettings.ShowStatusWhenZero = $false
```
