### ISSUE TITLE
Very Slow prompt return

### ISSUE THREAD

**Issue by developingchris** [dahlbyk/posh-git#21]
It takes several seconds for the branch and change stuff to show up.
Is this a core thing in posh-git.

I'd love to understand more about the implementation of how the information is gathered from the repo.

**Comment by rkeithhill** [comment]
Maybe we should close this issue given its age and the fact that I'm seeing prompt times in the area of  <100 ms on small repos and ~300 ms on medium size repos (6500 files).

**Comment by dahlbyk** [comment]
Between improvements in Git for Windows, #208, and various posh-git optimizations, I think we're doing about as well as we can.
