### ISSUE TITLE
Distinguish no upstream from up-to-date

### ISSUE THREAD

**Issue by mattdeckard** [dahlbyk/posh-git#212]
Currently if you have checked out a local branch with no upstream branch set, the prompt shows the (in my opinion, misleading) "triple equals" character. It would be nice if that character were omitted when there is no upstream set, so the user doesn't get the wrong impression that a remote branch is set up which the local branch is up-to-date to.

FWIW, this is how the [__git_ps1](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) bash script works

**Comment by dahlbyk** [comment]
Good call. I also noticed the branch color for untracked/matching (cyan) and ahead (green) switched with #202.

Have this mostly done locally, will have a PR out shortly.

**Comment by mattdeckard** [comment]
Awesome. One of my coworkers also noticed that color switch. I assume you'll include that fix in the PR as well?

**Comment by dahlbyk** [comment]
I will!
