### ISSUE TITLE
Installing with Chocolately via OneGet?

### ISSUE THREAD

**Issue by RandomlyKnighted** [dahlbyk/posh-git#214]
After installing with Chocolatey is there anything else that I'm supposed to do in order to get posh-git to work? I installed it but I'm not seeing any information in the PowerShell window when I navigate to a project's folder.

**Comment by dahlbyk** [comment]
The Chocolatey install should be sufficient - if `git status` works, you should see a prompt.

What do you see in your `$PROFILE`?

**Comment by RandomlyKnighted** [comment]
```git status``` shows me the modified and untracked files like expected but I'm not seeing any of the poshgit information that I should be seeing.

When I typed ```$PROFILE``` It gave me this:

```
C:\Users\Tyler\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by dahlbyk** [comment]
What's in the file?

Tip: `gc $PROFILE | clip` to copy to clipboard.

**Comment by RandomlyKnighted** [comment]
When I try that I get the following error:

```
gc : Cannot find path 'C:\Users\Tyler\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' because it does
not exist.
At line:1 char:1
+ gc $PROFILE | clip
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Tyler\...ell_profile.ps1:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by dahlbyk** [comment]
OK, seems the Chocolatey install failed - I would expect it to look something like this:

```
if(Test-Path Function:\Prompt) {Rename-Item Function:\Prompt PrePoshGitPrompt -Force}
# Load posh-git example profile
. 'C:\tools\poshgit\dahlbyk-posh-git-fc7c407\profile.example.ps1'
Rename-Item Function:\Prompt PoshGitPrompt -Force
function Prompt() {if(Test-Path Function:\PrePoshGitPrompt){++$global:poshScope; New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor, `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;$private:p = PrePoshGitPrompt; if(--$global:poshScope -eq 0) {Remove-Item function:\Write-Host -Force}}PoshGitPrompt}
```

Try a `cinst poshgit -force` from an elevated prompt and drop what shows up in `C:\ProgramData\chocolatey\logs\chocolatey.log` here?

**Comment by RandomlyKnighted** [comment]
I'm using Chocolatey via OneGet on Windows 10 so I don't have the cisnt command. When I force the installation via the ```Install-Package poshgit -force``` the log file is not created.

**Comment by dahlbyk** [comment]
@ferventcoder any ideas?

**Comment by ferventcoder** [comment]
Don't use Chocolatey through OneGet for now. It's known to have issues.

**Comment by ferventcoder** [comment]
Wait for an official announcement from the Chocolatey team before you do. For now, please use only the official client.

**Comment by ferventcoder** [comment]
@dahlbyk can you update the title here to reflect that this was OneGet using Chocolatey to install?

**Comment by rkeithhill** [comment]
I think @ferventcoder suggestion to not use Chocolatey through OneGet aka PackageManagement is the answer to this.  In fact, given that this is a PowerShell module it is best to use the PowerShellGet provider in PackageManagement.  That is, just use the v5 built-in `Install-Module` command.  For PS v3/4 you can get the PackageManagement install and also use `Install-Module`.  For PS v2, use Chocolatey directly - `choco install poshgit`.

**Comment by ferventcoder** [comment]
:)

My suggestion for Chocolatey is to use choco.exe and sit tight for the official OneGet Chocolatey Provider to be released.
