### ISSUE TITLE
Unicode characters displays wrong

### ISSUE THREAD

**Issue by ulve** [dahlbyk/posh-git#219]
when i do a git  status and a file containing åäöÅÄÖ it displays like this:
![unicode](https://cloud.githubusercontent.com/assets/3851206/9907896/853508e0-5c91-11e5-8c29-f94da4dd9962.png)

it should say
Test\Acceptanstester\FärdigställaFöreläggande\EditeraFöreläggandeTextKorrektUtformat.feature

**Comment by dahlbyk** [comment]
Try `git config --global core.quotepath off`

**Comment by ulve** [comment]
Great! It works!
