### ISSUE TITLE
Wrong version check with latest git

### ISSUE THREAD

**Issue by illagrenan** [dahlbyk/posh-git#222]
When I run new terminal window I get this warning:

```
WARNING: posh-git requires Git 1.7.2 or better. You have .
```
Altough I have installed this version of git (Git for Windows from https://git-scm.com/):

```
git --version
git version 2.5.3.windows.1
```

**Comment by theaquamarine** [comment]
Strange, I'm running 2.5.3 and it's working properly. Can you run 
````(git --version) -match '(?<ver>\d+(?:\.\d+)+)'; $Matches['ver']; [Version]$Matches['ver'] -lt [Version]'1.7.2'````
and post the output?

**Comment by illagrenan** [comment]
Here is output:
```
True
2.5.3
False
```

**Comment by caveman-dick** [comment]
I was getting the same issue and for me it looks like an incompatability issue with the latest version of ConEmu and NVIDIA drivers https://github.com/Maximus5/ConEmu/issues/347. Running in a normal PowerShell window works as expected. Once I renamed the NVIDIA folder as described here: https://conemu.github.io/en/CoProcManager.html it started working in ConEmu too.

**Comment by Maximus5** [comment]
If the original issue was about ConEmu console, than it's fixed in [build 151006](https://conemu.github.io/blog/2015/10/06/Build-151006.html), but it may introduce same crashes as described in Maximus5/gh-272 which I can't check.

**Comment by illagrenan** [comment]
After latest update of ConEmu is PoshGit working without version check warning. Thanks @Maximus5!

**Comment by caveman-dick** [comment]
Sorry @Maximus5 I didn't realise you had already fixed it! Great work as always! :+1:
