### ISSUE TITLE
Chocolatey Deprecating A Function

### ISSUE THREAD

**Issue by LogoiLab** [dahlbyk/posh-git#226]
as seen here, chocolatey will be deprecating the the get-binroot function:

Get-BinRoot is going to be deprecated by v1. Many packages no longer require it since the folders no longer have versions on them.
![psgiterror](https://cloud.githubusercontent.com/assets/5545218/10436090/388bad8a-70f2-11e5-8612-0cb7e6f2b8ab.png)

**Comment by dahlbyk** [comment]
I'm torn if it would be better to address this for 0.7 (after https://github.com/dahlbyk/posh-git/pull/358) or wait until 1.0.

**Comment by rkeithhill** [comment]
Well, for 1.0 we're unlikely to even provide a Chocolatey package anymore, right?  And since the 0.7 branch will live for a while to support v2 (and possibly v3/4), it seems like we should switch to a non-deprecated function.

**Comment by dahlbyk** [comment]
> Well, for 1.0 we're unlikely to even provide a Chocolatey package anymore, right?

I'm open to discussion on this. There are likely a number of devs who wouldn't use PS Gallery for anything other than posh-git, so keeping some sort of Chocolatey package seems reasonable.

Is fixing this really as simple as [using `$env:ChocolateyBinRoot` instead](https://github.com/chocolatey/choco/wiki/CreatePackages#3-path-provided-by-the-get-binroot-helper---will-be-deprecated-later-closer-to-v1-but-okay-to-use-for-now)?

**Comment by rkeithhill** [comment]
I think the replacement is `Get-ToolsLocation` - https://github.com/chocolatey/choco/issues/631

**Comment by dahlbyk** [comment]
I think we're fine leaving `Get-BinRoot` for v0.7, so moving to v1.0. Or maybe we could quickly publish v0.8 that only replaces `Get-BinRoot` with `Get-ToolsLocation` and requires Chocolatey 0.10.3? @ferventcoder is there a best practice for packages to handle deprecations?

Also worthy of consideration: https://chocolatey.org/packages/poshgit#comment-2816165073

> As currently configured this package installs itself in the chocolatey BinRoot/ToolsLocation (which defaults to c:\tools as far as I can tell). Based on the discussion around https://github.com/chocolatey/... this location seems to be intended for portable tools, but that doesn't seem to make any sense to me for posh-git, which needs to be integrated into the user's powershell environment to be of any use.
>
> It seems like it would be more appropriate to install the posh-git package in one of the powershell module locations. In fact some other powershell enhancements (I'm thinking of Oh-My-PoSH right now) rely on posh-git being in a location that's discoverable by `Get-Module -ListAvailable` for it to be recognized.

**Comment by ferventcoder** [comment]
It's actually 0.9.10 when it was introduced. We try to document most of these kinds of things to ease transition and help folks decide when is best - https://chocolatey.org/docs/helpers-get-toolslocation

Typically after 6 months of release, we are okay with the transition on the community package repository.

This also gives you access to `chocolateyBeforeModify.ps1`, an additional script that will assist prior to upgrade and prior to uninstall. Run `choco new test` and look at the output to see the docs.

**Comment by ferventcoder** [comment]
0.9.10 was released on June 17, 2016 so you are good to go.

**Comment by ferventcoder** [comment]
But you could also go for adding it as a PowerShell Module location if that is more appropriate.
