### ISSUE TITLE
Stash status

### ISSUE THREAD

**Issue by PiterGoCompany** [dahlbyk/posh-git#227]
Hi,
is there any possibility to add info about stash to prompt, for example number of stash entries?

**Comment by cmarcusreid** [comment]
I think what you're looking for was added in https://github.com/dahlbyk/posh-git/pull/215.

"$global:GitPromptSettings.EnableStashStatus = $true" should turn this functionality on.

**Comment by PiterGoCompany** [comment]
Thank you, works great.
