### ISSUE TITLE
push origin branchname sometimes pushes to parent instead

### ISSUE THREAD

**Issue by joeldart** [dahlbyk/posh-git#229]
~~First things first, I do my push from an alias, and am going to try a period where I switch to being explicit to see if that changes anything~~ **Confirmed it happens when spelling it out explicitly**. That out of the way, here is the issue I am seeing in the event there are any logs I could get, etc.

I've recently moved to github desktop on windows from msysgit. I use a git flow where I go master (or sometimes longer-lived feature branch) -> feature-issuenum -> origin + pull request back into master/LLfeature-branch. In this case it was feature-windows10

I was on a branch created by git checkout -b feature-4762 origin/feature-windows10.

I popped down to posh git to do a more complex operation (last time it was a rebase -i, this time it was a add -p) and then after my commit I did a git push origin feature-4762. 

```
Counting objects: 40, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 762 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To https://github.com/DyKnow/dyknow5.git
   68f64af..123686d  feature-4762 -> feature-windows10
```

I then popped over to the compare operation to make my PR, but feature-4762 DNE. Then I look at feature-windows10 and my commit's sitting on top without as if I'd just YOLO merged it. Note, this is not happening everytime as this is my normal workflow.

**Comment by joeldart** [comment]
It does indeed reproduce when not using an alias.

**Comment by dahlbyk** [comment]
I completely overlooked this issue, sorry! As far as I can tell, nothing here would be specific to posh-git (just prompt + tab expansion). If you're still having an issue, I'd suggest asking your Git question on StackOverflow.

**Comment by joeldart** [comment]
I'm not sure I understand how this is prompt/tab expansion. Let me lay out specific steps as this is very different behavior than I get for other git clients, even msysgit.

Here is what I get with git on macos or msysgit
```
git fetch
git checkout -b feature-xyz origin/master
#make changes
git add .
git commit -am "bla bla"
git push origin feature-xyz
#github now has a branch feature-xyz
```

here is what I get sometimes with posh-git (and just got again just now)
```
git fetch
git checkout -b feature-xyz origin/master
#make changes
git add .
git commit -am "bla bla"
git push origin feature-xyz
#github does not have a branch feature-xyz
#master now has a new commit "bla bla" which is unexpected and in my opinion a bug
```

**Comment by dahlbyk** [comment]
What I was trying to say is that posh-git just provides prompt and tab expansion. It shouldn't have any impact on Git's actual behavior.

A few questions, based on what you've shared:

* Can you take a screenshot of what you're seeing?
* What `git --version`?
* What does `git config push.default` return, if anything?
* After `git checkout -b feature-xyz origin/master` are you seeing the prompt show you're on `feature-xyz`?
* After your `git commit`, are you able to confirm the new commit is in your local `feature-xyz` branch but not local `master`? (Try `git log master feature-xyz --oneline --graph --decorate`)
* What's the output of `git push origin feature-xyz`?

The only thing I can of that might be causing something resembling what you describe is if your `feature-xyz` branch is somehow set up to track `origin/master` (check `git config branch.feature-xyz.merge`), but an explicit `git push origin feature-xyz` should ignore branch tracking information anyway.

**Comment by joeldart** [comment]
ahh, so posh-git isn't the git implementation, it's the hooks into powershell to make the experience better. ha, I exclusively hear "posh-git" when people talk about github desktop on windows and made a couple wrong conclusions. Yes, I can see the commits locally in the log for feature-xyz but not master, the version is ```git version 2.10.2.windows.1``` but none of this is your problem anymore. Thanks for your patience

**Comment by dahlbyk** [comment]
No worries, it's a common misconception. I just don't want to take credit (or responsibility!) for more than we're trying to do. If you do end up asking on StackOverflow, or finding an answer, please let me know - now I'm curious. :wink:
