### ISSUE TITLE
WARNING: Could not find ssh-agent

### ISSUE THREAD

**Issue by Stephanevg** [dahlbyk/posh-git#230]
Hi

I first had the same error as here : Start-SSHAgent missing in v0.5.0.2015 #224

I applied the work around sugested by t0yv0 and added the missing exported commands to the posh-git.psd1.

When I re-open the posh prompt I get the following message:

WARNING: Could not find ssh-agent

It seems like this is what also blocks me to push changes to my repository

Environment infos:
Windows 10
$psversion: 5.0.10240.16384
Path: contains 
C:\Program Files\git\cmd
C:\Program Files\Git\cmd

downloaded version from PSGallery

**Comment by Stephanevg** [comment]
It seems like the issue came from a missing path in the $env:path variable.

Executing the following line in my ISE and re opening a fresh powershell prompt solved this issue for me.

$MyPath = $env:Path + ";" + "${env:ProgramFiles}\git\usr\bin"
[Environment]::SetEnvironmentVariable("Path", $($MyPath ), "Machine")

**Comment by akovalev-econiq** [comment]
It seems that one workaround was suggested already. I found another solution which seems to be a little bit cleaner for me.
I added git executables into a path
```powershell
$Script:GitPath = "$env:ProgramFiles\Git"
```
Add ``$GitPath\bin`` and ``$GitPath\cmd`` to a ``PATH`` environment variable.
Add aliasies for ssh executables
```powershell
Set-Alias ssh-agent "$GitPath\usr\bin\ssh-agent.exe"
Set-Alias ssh-add "$GitPath\usr\bin\ssh-add.exe"
```
