### ISSUE TITLE
Adding keys from .ssh/config

### ISSUE THREAD

**Issue by tofutim** [dahlbyk/posh-git#232]
It would be nice if posh-git would parse the config file for the keys to add...

**Comment by tofutim** [comment]
It would be nice if it parsed it, and then checked if a passphrase was already setup previously. Right now each new PowerShell window I have to re-enter the passphrase.

**Comment by JeremySkinner** [comment]
I've migrated this issue over to the posh-ssh repository. @dahlbyk could you close this here?
