### ISSUE TITLE
Incorrect tab expansion for `git push --option <remote>`

### ISSUE THREAD

**Issue by DoCode** [dahlbyk/posh-git#234]
### Alias

Define the alias `ps` as `push --follow-tags`
### Execution

I would delete the remote branch named `issue-1234`

**Expected**

``` bash
git push [TAB]=>origin [TAB]=>develop...
```

**Current**

```
git ps [TAB]=>develop[TAB]=>develop
```

> Is this the current behavior? Should we strip off the arguments on tab completion?

**Comment by rkeithhill** [comment]
Duplicate with #257

**Comment by dahlbyk** [comment]
This definitely isn't a duplicate of #257, and I'm pretty sure it's not actually a bug with alias expansion (in general) either. I'm pretty sure the `git push <remote>` pattern is just too restrictive - it's recognizing the first token, `--follow-tags`, as the remote name, and thus proceeding on to match branch names.

This would be a good up-for-grabs fix.

**Comment by rkeithhill** [comment]
Oops. Sorry about that.  Maybe the issue title should be changed?
