### ISSUE TITLE
Check for case sensitivity when checking out a branch

### ISSUE THREAD

**Issue by jacobholm** [dahlbyk/posh-git#235]
This is more of a feature than an issue.

Recently I used the wrong case when checking out my branch, say I have a branch named "My-Branch". Then I checked out "my-branch" and everything looked ok, no complaints. But when I push my changes a new branch is created, so now I have "My-Branch" and "my-branch".

It seems that this issue occurs since Linux is case-sensitive while Windows isn't. Running "git branch -a" does not show my duplicate branch, only the first one. If I run "git ls-remote --heads origin" I can see all of the latest commits on each branch, and here I see both branches.

In the same way that I cannot check out a branch that does not exist, I shouldn't be able to check out a branch with the wrong letter-case. Is this something that could easily be implemented in posh-git, or do you see it as something that should be up to git?

Thanks in advance,
Jacob Holm

**Comment by dahlbyk** [comment]
Hey @jacobholm, thanks for the question. Unfortunately, I'm not sure there's much we can do for you here. What you're seeing is actually a behavior of https://github.com/git-for-windows/git, not posh-git, and we don't do anything to intercept calls out to `git.exe` from PowerShell. We do, at least, correct the branch case if you hit tab (i.e. `git checkout Master<tab>` corrects to `git checkout master`).

For what it's worth, I'm able to reproduce (git version 1.9.5.github.0) pretty easily - maybe worth reporting as a bug if we can reproduce on newer versions?

```
C:\Temp\sandbox [master ≡]> git checkout Master
Switched to branch 'Master'
C:\Temp\sandbox [Master]> git push
fatal: The current branch Master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin Master

C:\Temp\sandbox [Master]> git push origin HEAD
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/dahlbyk-demo/sandbox.git
 * [new branch]      HEAD -> Master
C:\Temp\sandbox [Master]> git ls-remote origin
9ca3d7637ac9f0ab843784f19019f0897b0d6620        HEAD
9ca3d7637ac9f0ab843784f19019f0897b0d6620        refs/heads/Master
9ca3d7637ac9f0ab843784f19019f0897b0d6620        refs/heads/master
```

**Comment by jacobholm** [comment]
Ah, ok. I will consider reporting it there. Thanks!
