### ISSUE TITLE
git unable to read current working directory no error

### ISSUE THREAD

**Issue by giacomocerquone** [dahlbyk/posh-git#236]
Hi, I'm working in windows 10. I updated github for windows right yesterday (actual version 3.0.9.0, don't know if it means something) and git --version returns `git version 2.5.3.windows.1`
Now my problem is that every command I try to execute with git it returns: `git unable to read current working directory no error` (obviously the working directory isn't absolutely empty, and I also tried to create a new directory and initialize a new repo wit git init but it returns always the same error).

To use git I edited the profile.ps1 of powershell in this way:
`. (Resolve-Path "$env:LOCALAPPDATA\GitHub\shell.ps1")`
`. $env:github_posh_git\profile.example.ps1`

Could it possibly be a bug?

**Comment by dahlbyk** [comment]
Are you seeing that error in directories without a Git repo, directories with a Git repo, or both?

**Comment by giacomocerquone** [comment]
Both

**Comment by giacomocerquone** [comment]
I really don't know what to do, I must work on git and the GUI app is killing me

**Comment by dahlbyk** [comment]
I assume the error goes away if you comment out the line to include posh-git?

**Comment by dahlbyk** [comment]
(And probably reopen your prompt - it won't pick it up automatically.)

**Comment by giacomocerquone** [comment]
If I remove those two lines to include git in powershell, obviously powershell doesn't even know what the command "git is" and others powershell's errors come up of course

**Comment by giacomocerquone** [comment]
Ok, so I discovered that only the dir that contains 7/8 repo is not working. Could be this an ssd problem? Or should I change some configuration of that directory?

**Comment by dahlbyk** [comment]
> only the dir that contains 7/8 repo is not working

What do you mean by "7/8 repo"?

The error doesn't seem like a real Git or posh-git error, so I tend to think it's some sort of repo or disk corrpution?

**Comment by giacomocerquone** [comment]
I meant seven or eight folder where there were repos initialized in them! Honestly I thought was an SSD problem but I checked it and it's completely ok. It's strange that in whatever folder (located in the document folder) I try to initialize a git repo, it comes up with this error. Could be some directory permission problem?

**Comment by dahlbyk** [comment]
This looks like https://github.com/git-for-windows/git/issues/473 - try some of the suggestions there?

**Comment by giacomocerquone** [comment]
It seems to be the exact same problem and now that I think at it more carefully, it happened not only when Github was updated, but also when Windows 10 updated itself with the rollout of the new november version and in that situation some sort of siymlink could be created... Now I don't understand actually where I can find this symlink and delete it!

**Comment by dahlbyk** [comment]
Closing here in favor of that issue, since this isn't really specific to posh-git. Good luck!
