### ISSUE TITLE
Uninstall through Chocolatey

### ISSUE THREAD

**Issue by ferventcoder** [dahlbyk/posh-git#239]
https://chocolatey.org/packages/poshgit#comment-2409077345

> So, I ran "cuninst poshgit" to uninstall, but it didn't remove anything. Posh-git is still running in my shell. For anyone wanting to remove it, remove it from your $profile file and delete the "c:\tools\poshgit" folder. If un-installation could be implemented in the chocolatey package, that would be great!

**Comment by dahlbyk** [comment]
Thanks for capturing this, @ferventcoder

**Comment by rkeithhill** [comment]
I think we need some docs on uninstall.  Do we want to put these in the README.md or another location?  Perphaps a FAQ wiki page or something that we could reference from the README.md file?
