### ISSUE TITLE
Skip opening/creating file by Posh Git

### ISSUE THREAD

**Issue by 304NotModified** [dahlbyk/posh-git#254]
As of today ` git commit --amend` will open a new text file in my text editor.

It's not fully clear why that is needed. Can this be disabled? It's really interrupting my command line work.

**Comment by theaquamarine** [comment]
Isn't that normal behaviour? `git commit --amend` should open the editor populated with the commit being amended's message if not given `--no-edit`.

What version of git do you have?

**Comment by 304NotModified** [comment]
git version 2.5.3.windows.1

So I just need to append `--no-edit`? Was this different before?

**Comment by theaquamarine** [comment]
I don't think so. This isn't really posh-git, it's git's functionality.

**Comment by 304NotModified** [comment]
OK thanks!

**Comment by dahlbyk** [comment]
> I believe that should do it, and I don't think this is new.

Yeah, not new. Fixing typos in commit messages is a common `--amend` use case.
