### ISSUE TITLE
Pass PowerShell aliases down to posh-git TabExpansion autocomplete function

### ISSUE THREAD

**Issue by jkymarsh** [dahlbyk/posh-git#257]
I have PS aliases for git, defined as such:

``` powershell
function git-branch-delete { git branch -D $args }
Set-Alias gbd git-branch-delete

function git-checkout { git checkout $args }
Set-Alias gco git-checkout
```

The `$args` represents a branch name, which posh-git would typically autocomplete. However, since aliases are not passed down to posh-git, autocompletion doesn't work.

I monkey-patched this functionality myself, using the technique described in [this SO answer](http://stackoverflow.com/a/23607803):

``` powershell
function TabExpansion($line, $lastWord) {
    # aliases that have some form of tab autocomplete functionality
    # NOTE: ADDED POST-INSTALL BY USER
    $line = $line -replace '^gco ', 'git checkout '
    $line = $line -replace '^gbd ', 'git branch '
    # end aliases

    # rest of the function...
}
```

It'd be super rad if posh-git could somehow retrieve existing PS aliases related to git functionality like this and patch it into posh-git's autocompletion functionality.

I prefer to use PS aliases over git aliases, primarily for brevity - I'm able to do `gcm` instead of `git co` or similar.

**Comment by dahlbyk** [comment]
Working through open issues and realized that I never commented. This is a great idea and I would totally accept a PR for a generalized version of this.

**Comment by MisinformedDNA** [comment]
I can easily see aliases working, but functions are tricky.

For aliases, we just need to insert `(Get-Alias $alias).Definition` somewhere.

Assuming we have 

```powershell
function git-checkout { git checkout $args }
set-alias gco git-checkout
```

I have no idea how I would interpret that. Would I grab the ScriptBlock to do a find/replace? But what if it's multiple lines? What if I executed something in the ScriptBlock? Well we can't run the function as is because we aren't ready to execute. We still want tab completion. But what if the `function` returned a `string`? Assume

```powershell
> function git-checkout { "git checkout" }
> set-alias gco git-checkout
```

Then we could run the following:

```powershell
$command = (Get-Alias $alias).Definition
if (Test-Path Function:/$command) {    # Check if the command is actually a function
    $command = & $alias    # execute
}
```

Since we are now only dealing with strings we could just create a "dictionary file", kind of like from `Export-Alias`.

Thoughts?

**Comment by dahlbyk** [comment]
posh-git wouldn't be responsible for executing the function, we just need to tease out the definition.

You can get the function definition like [this](https://github.com/dahlbyk/posh-git/blob/37e5ba7f38cfd38b2b108a75b05a6b64c29c8e95/src/posh-git.psm1#L151). I would try a regex to match the definition on `git <args> $args`, then swap the match in before expansion.

**Comment by MisinformedDNA** [comment]
What would you do if there were multiple lines in the definition?

**Comment by dahlbyk** [comment]
> What would you do if there were multiple lines in the definition?

Similar to how we parse [`$lastBlock`](https://github.com/dahlbyk/posh-git/blob/37e5ba7f38cfd38b2b108a75b05a6b64c29c8e95/src/GitTabExpansion.ps1#L416), I think you'd want to match between `[;|]`. I haven't tested it, but something like ```"(^|[|;])\s*(?<cmd>$(Get-AliasPattern git).* \`$args)\s*($|[|;])"```, then `Expand-GitCommand $matches['cmd']`.

This would be a great opportunity to TDD handling different function definitions. 😀

**Comment by terryaney** [comment]
Hi, I have a git alias of dt for difftool and in posh-git 0.7.3 I was able to make it run simply by putting dt anywhere in the GitTabExpansion.ps1 where difftool was

someCommands = ... 'diff','difftool','dt','fetch', ...

# Handles git diff/difftool <path>

**Comment by terryaney** [comment]
Actually I found something, but I'm not sure how to address.

My git alias is `dt = !sh -c 'git difftool --no-prompt $2 ${1+-- "$1"}' -` and in `GitTabExpansion($lastBlock)` $lastBlock = "git dt" in 0.7.3, but in 1.*, it is "!sh -c 'git difftool --no-prompt $2 ${1+-- "$1"}' -".

I'm not sure how to address trying to fix that.  Any ideas on your end?

**Comment by Clijsters** [comment]
I would grab this, since I realized something similiar some months ago.

**Comment by jrusbatch** [comment]
I'd also love to see this! I alias `git` to `g` out of laziness, and I only just now realized that that was the reason I can't tab-complete branch names anymore.

**Comment by dahlbyk** [comment]
> @jrusbatch: I'd also love to see this! I alias `git` to `g` out of laziness, and I only just now realized that that was the reason I can't tab-complete branch names anymore.

If `g` is a normal PowerShell alias (i.e. `Set-Alias g git`) it should Just Work™️. Are you finding that not to be the case?

**Comment by jrusbatch** [comment]
@dahlbyk Correct. Although, I was declaring my alias with `New-Alias -Name g -Value git -Option Private` in my `Profile.ps1`. After removing `-Option Private` the tab completion functionality works. I don't remember why I specified that option so I think I'm good for now. Thanks!

**Comment by szelpe** [comment]
@dahlbyk I have the exact same setup, i.e. having `Set-Alias g git` in my $profile and tab completion with `g` worked in `beta2` and `beta3` but now broken in `beta4`. Simply does nothing if I type `g fet<TAB>`.

**Comment by szelpe** [comment]
Also, if I set the `UseLegacyTabExpansion` to `$True` it starts to work again.

**Comment by rkeithhill** [comment]
@szelpe Your bug is a little different since you alias directly to the git executable as opposed to aliasing to a custom function.  You can submit a new issue?

It turns out PowerShell's built-in Register-ArgumentCompleter does not take into account aliases to native apps that have registered completers.  I think the fix for this is pretty easy.

**Comment by szelpe** [comment]
> @szelpe Your bug is a little different since you alias directly to the git executable as opposed to aliasing to a custom function. Can you submit a new issue?
> 
> It turns out PowerShell's built-in Register-ArgumentCompleter does not take into account aliases to native apps that have registered completers. I think the fix for this is pretty easy.

Sure: https://github.com/dahlbyk/posh-git/issues/769

**Comment by rkeithhill** [comment]
Implemented via PR #779.  Thanks @csc027!

**Comment by suhaibbaba** [comment]
How can do that?

**Comment by MisinformedDNA** [comment]
I use the same alias, but this library won't help you on its own. It needs another layer to make it work, like an auto-completer that calls another auto-completer?

**Comment by MisinformedDNA** [comment]
```powershell
$scriptBlock = {
     param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

     Expand-GitCommand 'git checkout -b '
 }

Register-ArgumentCompleter -CommandName gcob -ScriptBlock $scriptBlock
```

**Comment by suhaibbaba** [comment]
@MisinformedDNA  
Thanks but It doesn't autocomplete from last word
I mean 
`gcbo mas`
It should complete it to `gcob master`

**Comment by MisinformedDNA** [comment]
Try this:

```powershell
$scriptBlock = {
>     param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
>
>     Expand-GitCommand "git checkout -b $commandName"
> }
> Register-ArgumentCompleter -CommandName gcob -ScriptBlock $scriptBlock
```

**Comment by suhaibbaba** [comment]
@MisinformedDNA Thank you and it's working fine
but can you please explain it? and if I need to create multiple custom commands, do I need to create multiple script-blocks?
I mean, I need to create
1. gco => git checkout
2. gcob => git checkout -b
3. gp => git push

like this

Now my profile 
```
function gcob {
    param ($commandComplete)
    git checkout -b ${commandComplete}
}

$scriptBlock = {
     param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
     Expand-GitCommand "git checkout -b $commandName"
}

Register-ArgumentCompleter -CommandName gcob -ScriptBlock $scriptBlock
```

**Comment by MisinformedDNA** [comment]
Yes, you need separate script blocks for each one.

**Comment by suhaibbaba** [comment]
@MisinformedDNA gotcha!
Thanks for helping

**Comment by MisinformedDNA** [comment]
I find that passing in a parameter doesn't work correctly in certain scenarios. For instance, if you run this:

```powershell
function gl { 
    param ($commandComplete)
    git log $commandComplete
}
$scriptBlock = {
    param($wordToComplete, $commandAst, $cursorPosition)

    Expand-GitCommand "git log $wordToComplete"
}
Register-ArgumentCompleter -Native -CommandName gl -ScriptBlock $scriptBlock

gl-<TAB>
```

You will get

> gl -commandComplete

Instead, I use:

```powershell
function gl { git log @args }
$scriptBlock = {
    param($wordToComplete, $commandAst, $cursorPosition)

    Expand-GitCommand "git log $wordToComplete"
}
Register-ArgumentCompleter -Native -CommandName gl -ScriptBlock $scriptBlock
```

NOTE: I've also explicitly set the native parameter (even though it is implied) and changed the names of the script parameters to reflect [the native parameters](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.3#example-3-register-a-custom-native-argument-completer).

**Comment by mrbeardad** [comment]
The code below works well for me. It will complete the parameter of git subcommand or subsubcommand correctly. 
```pwsh
function RegisterGit {
  Invoke-Expression -Command "function global:$($args[0]) { git $($args[1]) @args }"
  $tab = [Scriptblock]::Create("
    param(`$wordToComplete, `$commandAst, `$cursorPosition)
    `$cmdline = `$commandAst.ToString().Replace(`"$($args[0])`", `"`")
    if (`$wordToComplete.Length -ne 0) { `$tail = '' } else { `$tail = ' ' }
    Expand-GitCommand `"git $($args[1]) `$cmdline`$tail`"
  ")
  Register-ArgumentCompleter -CommandName $args[0] -ScriptBlock $tab
}

# define function gst to execute git remote, and register the tab completer for it.
RegisterGit gr "remote"
```

**Comment by Bristopher** [comment]
That works great!
Only thing is how can I adapt it for an alias like 'git sw' below for auto-completing branch names?
```
git config --global alias.curr '!git log --all --oneline --graph ^origin/indx~; echo "\n"; git diff-tree --no-commit-id --name-status HEAD -r'
git config --global alias.sw '!git checkout $1; git curr #'
```
