### ISSUE TITLE
Prompt disappear on ctrl+c

### ISSUE THREAD

**Issue by Zougi** [dahlbyk/posh-git#259]
Prompt disappear on ctrl+c (SIGINT)

Instead of `C:\folder [(master)]>` it's replaced by `C:\folder PS`

If I hit enter, prompt goes back to `C:\folder [(master)]>`

I just installed posh git with psget from within powershell on a fresh install of windows 8.1.

PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

Edit: reproducible on windows 10 with posh-git version 869d4c5159797755bc04749db47b166136e59132

```
C:\Users\i301937\Documents\GitHub\saplinks [master]> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10240.16384
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10240.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by Zougi** [comment]
Not reproducible with version 0.5.0.2015 got with oneGet on windows10

**Comment by dahlbyk** [comment]
I see the PS periodically when I hit Ctrl-C, but the Git prompt always comes back by hitting Enter again so I have never bothered to try to figure out why. I doubt there is much we could do to intercept the Ctrl-C anyway…?

**Comment by Zougi** [comment]
apparently we can with TreatControlCAsInput 
see http://stackoverflow.com/questions/1710698/gracefully-stopping-in-powershell
I haven't tried though

**Comment by dahlbyk** [comment]
Yeah, if I spam Ctrl-C I can get it to happen.

> I don't know if it's worth spending time on that.

I tend to agree, though if someone wants to tackle it I'm curious what they could come up with.

**Comment by adamk33n3r** [comment]
Just noticed this happening when I was creating my own script that did a `Read-Host`. I can get it to happen more consistently while ctrl-c'ing there.
```
C:\dev\project [master ≡]> Read-Host "asdf? "
asdf? :<hit ctrl-c here>
PS>
```
