### ISSUE TITLE
Please publish latest version on powershellgallery

### ISSUE THREAD

**Issue by Zougi** [dahlbyk/posh-git#260]
https://github.com/dahlbyk/posh-git/issues/224 is still reproducible.

**Comment by dahlbyk** [comment]
I just pushed a new version, but got a warning that suggests #242 may not have been sufficient. Give it a try?

> WARNING: This module 'C:\Users\Keith\AppData\Local\Temp\1744033178\posh-git\posh-git.psd1' has exported functions. As a best practice, include exported functions in the module manifest file(.psd1). You can run Update-ModuleManifest -FunctionsToExport to update the manifest with ExportedFunctions field.

**Comment by theaquamarine** [comment]
It looks like `Test-ModuleManifest` doesn't pick up the exported functions or aliases properly (except `Invoke-NullCoalescing`, oddly), but actually importing the module processes everything properly.

Moving exported functions from `Export-ModuleMember` to being directly declared in the manifest causes them to appear properly with `Test-ModuleManifest` so I'd guess that would fix the warning.

**Comment by lzybkr** [comment]
The warning message should be improved.  Using wildcards results in poor performance on V3 and beyond when using module auto-loading (so could be any command).  PowerShell has to analyze the script/dll/whatever when you use wildcards, but if you avoid wildcards, PowerShell skips that potentially slow work.

So best practice is to use:

```
FunctionsToExport = @('Get-Thing1', 'Get-Thing2')
# no aliases to export, be explicit, don't omit this
AliasesToExport = @()
# no cmdlets to export, be explicit, don't omit this
CmdletsToExport = @()
```

Instead of:

```
# Don't use wildcards
FunctionsToExport = "*"
# Don't omit any of the *ToExport entries
## CmdletsToExport = "*"
# Don't use $null, it's handled just like it was omitted
AliasesToExport = $null
```

**Comment by dahlbyk** [comment]
So can we drop https://github.com/dahlbyk/posh-git/blob/5f8e87858db093497029e4ddb70bcb67629f9efa/posh-git.psm1#L30-L48 altogether or do we need to maintain the export list in two places?

**Comment by lzybkr** [comment]
By default, all functions, cmdlets, and aliases are exported, so if that's what you're doing, it's not necessary.  But if you have have internal functions or aliases, then maintaining the list in both places is unfortunately necessary for the best performance.

**Comment by dahlbyk** [comment]
> By default, all functions, cmdlets, and aliases are exported, so if that's what you're doing, it's not necessary.

Does this include exporting `function private:Do-Something`? If not, we could make a sweep through to privatize (lol) anything that's not be exported.

**Comment by lzybkr** [comment]
I had a feeling private wouldn't have any effect, but had to test to be sure.  And indeed, private functions get exported.  That is probably an oversight, but it doesn't help you if it gets fixed, so you should stick with Export-ModuleMember.

**Comment by dahlbyk** [comment]
I'd like to clean up the PS Gallery versioning process as part of the push to 1.0: https://github.com/dahlbyk/posh-git/issues/328

**Comment by rkeithhill** [comment]
I'm closing this since the latest version *is* posted to the PSGallery.  And the current posh-git.psd1 no longer uses `*`.  In fact, the only warning it generates is for using `ModuleToProcess` instead of `RootModule`.
