### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by michaeldtaylor** [dahlbyk/posh-git#262]
This probably isn't the place, but since upgrading GitHub Desktop (Windows) my PowerShell Git sessions in ConEmu is no longer working. The problem seems to be that there is no folder:

LocalAppData\GitHub\PoshGit_f71b6366513fdb40f2126bf1d303ebd749cac2d2

The GitHub shell.ps1 file still references this, but the folder isn't there.

$env:github_posh_git = Resolve-Path "$env:LocalAppData\GitHub\PoshGit_f71b6366513fdb40f2126bf1d303ebd749cac2d2"

My ConEmu console was set to:

powershell -noexit -command Set-ExecutionPolicy bypass;.$env:LocalAppData\GitHub\shell.ps1;.$env:github_posh_git\profile.example.ps1 -new_console:a:C:\Projects\  -new_console:d:C:\Projects\

I've tried reinstalling GitHub Desktop but no folder or equivalent PoshGit folder has been recreated,

Any idea on how to fix this?

**Comment by michaeldtaylor** [comment]
Ok, well I still have no idea why the problem occurred (has GitHub Desktop removed PoshGit?) but for now I fixed it by recreating the folder PoshGit_f71b6366513fdb40f2126bf1d303ebd749cac2d2 and cloning master and copying the files to there. I have a weird new three bar equals symbol, but apart from that everything seems to be working.

**Comment by shiftkey** [comment]
@michaeldtaylor which OS version are you running? I'm looking into a Win7-specific issue, and I'm curious if that overlaps with what you're seeing...

**Comment by michaeldtaylor** [comment]
Windows 10 - I just did the automatic update in GitHub Desktop. Hadn't opened it for a while!

**Comment by shiftkey** [comment]
@michaeldtaylor 

> I now have a weird new three bar equals symbol on the command line prompt, but apart from that everything seems to be working.

That's one of the new features in Posh-Git #202

Not sure why the new folder wouldn't be recreated on update, but I'll keep an eye out for other cases like that.

**Comment by shiftkey** [comment]
@michaeldtaylor @dahlbyk this issue seems to be GitHub Desktop specific, rather than Posh-Git itself

**Comment by dahlbyk** [comment]
> this issue seems to be GitHub Desktop specific, rather than Posh-Git itself

Feel free to reopen if this proves not to be the case.

**Comment by vgrigoriu** [comment]
Same thing happened to me, `PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b` dissapeared. I even uninstalled Github Desktop, deleted `$env:LocalAppData\GitHub\` and re-installed it, and it's not there.

**Comment by dahlbyk** [comment]
@vgrigoriu can you drop a note to support@github.com with your debug log (Settings > About > Open debug log)?

**Comment by vgrigoriu** [comment]
First of all, sorry for posting here, I realised just after hitting Send that this was obviously a Github Desktop issue, not a posh-git one. Second, I deleted everything and re-installed, and on first run of Github Desktop PoshGit appeared, so problem solved.
