### ISSUE TITLE
Get variables from remote machine and store them in an excel file in local machine

### ISSUE THREAD

**Issue by AbdelhakimMahj** [dahlbyk/posh-git#264]
Hello everybody!
Actually i'm working in a project that use powershell scripts,and i would like to get the content of variables executed in the remote machine that i can store them in an excel file existed in the local machine how i can do this? Thanks you

**Comment by bazzilic** [comment]
Hi,
This is a repo for powershell _git_ extension, which has nothing to do with general powershell questions. Also, github issues is not the best place to ask general questions, it's main purpose is reporting issues and bugs. You might want to ask that question on https://superuser.com/
