### ISSUE TITLE
Can't find 64 bit ssh-agent or ssh-add

### ISSUE THREAD

**Issue by d-richard** [dahlbyk/posh-git#265]
I have 64bit git installed, but the posh-git utils script seems to be looking for the 32 bit versions of ssh-agent & ssh-add.  How do I get around this?

![image](https://cloud.githubusercontent.com/assets/974328/13683047/835fa266-e6b9-11e5-8f9f-0c6b15e2164b.png)

**Comment by d-richard** [comment]
Actually I installed the 32 bit version of GIT and it still doesn't work, because the actual path to the needed items is "c:\program files (x86)\git\**usr**\bin".  Do I have a missing environment variable or some such?

**Comment by dahlbyk** [comment]
Interesting... we should be using `usr/bin` if the exe isn't found in `bin/`:
https://github.com/dahlbyk/posh-git/blob/5f8e87858db093497029e4ddb70bcb67629f9efa/GitUtils.ps1#L289-L293

What does PowerShell show from a `Get-Command ssh-agent`? What version/distribution of Git are you using?

**Comment by d-richard** [comment]
![image](https://cloud.githubusercontent.com/assets/974328/13688669/328b3606-e6d8-11e5-8ac6-267a5972c6fd.png)

using Git-2.7.2-32-bit from git-scm.com.  I manually copied the exe's from usr/bin to bin and the process found the commands.  Obviously, this isn't right way to do it...

**Comment by d-richard** [comment]
After manually copying ssh-agent & ssh-add to bin/ I now get the following error:

![image](https://cloud.githubusercontent.com/assets/974328/13711463/94c70160-e773-11e5-930c-74f4ad908ce3.png)

**Comment by theaquamarine** [comment]
That's odd, `ssh-agent` should be appearing as an application, not an alias. Can you post the output from `Get-Command ssh-agent`?

**Comment by dahlbyk** [comment]
Very interesting... What version of PowerShell, for our reference?

**Comment by d-richard** [comment]
![image](https://cloud.githubusercontent.com/assets/974328/13747792/39f1e962-e9b7-11e5-975f-d4ef5cfba1fa.png)

![image](https://cloud.githubusercontent.com/assets/974328/13747838/7d4b606c-e9b7-11e5-8706-96cfa0955594.png)

**Comment by theaquamarine** [comment]
Well, that explains why posh-git is trying to run the 32-bit version of ssh-agent. Do you have something along the lines of `Set-Alias ssh-agent "C:\Program Files (x86)\git\bin\ssh-agent.exe` in your profile, and the same for `ssh-add`?

**Comment by d-richard** [comment]
Well, it's official, I'm an idiot.  That was the problem.  I don't even remember setting the aliases in my profile.  Works fine now with 64bit git.
