### ISSUE TITLE
Help! Chocolatey Upgrade Issues

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#272]
I'd love some help figuring out why Chocolatey upgrades are failing. I'm barely familiar with how the posh-git Chocolatey install works, but it feels way overcomplicated, not very PowerShell-y, and out of date with how Chocolatey has evolved.

Does anyone know of a similar PowerShell module package that installs/upgrades cleanly? Or would it make sense to take a dependency on newer PowerShell package management stuff to DRY up the various ways people are now getting posh-git?

---

https://chocolatey.org/packages/poshgit#comment-2569064630

> Command ['C:\ProgramData\chocolatey\tools\7za.exe' x -aoa -o"C:\tools\poshgit" -y "C:\Users\David\AppData\Local\Temp\chocolatey\poshgit\0.6.0.20160310\dahlbyk-posh-git-v0.4-178-g194..."] exited with '0'.
> 7za exit code: 0
> C:\tools\poshgit
> WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception' instead.
> ERROR: Cannot bind argument to parameter 'Path' because it is null.
> at Write-ChocolateyFailure, C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1: line 24
> at <scriptblock>, C:\ProgramData\chocolatey\lib\poshgit\tools\chocolateyInstall.ps1: line 66
> at <scriptblock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
> at <scriptblock>, <no file="">: line 1

---

https://chocolatey.org/packages/poshgit#comment-2571834761

> Chocolatey v0.9.10-beta1-181-g7c2a76c Professional
> Upgrading the following packages:
> poshgit
> By upgrading you accept licenses for the packages.
> You have poshgit v0.5.2.20150825 installed. Version 0.6.0.20160310 is available based on your source(s).
> 
> poshgit v0.6.0.20160310
> Attempting to remove existing 'C:\tools\poshgit' prior to install.
> Downloading poshgit
> from 'https://github.com/dahlbyk/pos...
> Overiding original url for private download cache file.
> Progress: 100% - Completed download of 'dahlbyk-posh-git-v0.4-178-g194...' (33.91 KB).
> Download of 'dahlbyk-posh-git-v0.4-178-g194...' (33.91 KB) completed.
> Virus check: 0/57 scan engines flagged this assembly.
> Due to possible false positives we fail at 5 minimum positives.
> Virus scan engines indicate this file is probably safe. For details see
> https://www.virustotal.com/fil...
> WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception' inste
> ad.
> ERROR: Chocolatey expected a file at 'C:\Users\David\AppData\Local\Temp\chocolatey\poshgit\0.6.0.20160310\dahlbyk-posh-g
> it-v0.4-178-g1941da2.zip' to be of length '34861' but the length was '34723'.
> The upgrade of poshgit was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\poshgit\tools\chocolateyInstall.ps1'.
> See log for details.
> 
> Chocolatey upgraded 0/1 package(s). 1 package(s) failed.
> See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> Failures:
> - poshgit

**Comment by dahlbyk** [comment]
Related: https://github.com/chocolatey/choco/pull/327

**Comment by rkeithhill** [comment]
I think it would be expected to use PowerShellGet >= v5. I think it is reasonable to ask folks to install PackageManagement for v3/v4 (vs installing Chocolatey).  Unfortunately, for v2 there will be no PackageManagement solution from the PowerShell team.  Maybe we just make do with using Chocolatey for PS v2 users?

**Comment by dahlbyk** [comment]
> Unfortunately, for v2 there will be no PackageManagement solution from the PowerShell team. Maybe we just make do with using Chocolatey for PS v2 users?

I'm fine with this, since we're dropping v2 support for [1.0](https://github.com/dahlbyk/posh-git/issues/328).

I suppose it wouldn't hurt to try to fix the Chocolatey upgrade process before 0.7 drops? I have never bothered with Chocolatey prereleases, but it seems like a good idea for this big release.

**Comment by dahlbyk** [comment]
I believe this is all resolved by #358. If anyone stumbles on this using posh-git 0.7 or newer, please leave a note (or open a new issue).
