### ISSUE TITLE
$GitStatus.Branch only updating after script execution

### ISSUE THREAD

**Issue by brianmaher84** [dahlbyk/posh-git#285]
I am using Chocolatey installation updated to latest version of Git and Posh-Git.

I have scripted a git checkout branch change via powershell and echo status from $GitStatus variable.  My script works after two executions because although I change branch to master from branch develop in my script, it is only after script execution that $GitStatus reads the update.

I have tried putting in a sleep for 8 seconds in case it was a timing issue but it does not appear that is the problem.  It waits for the powershell script to execute then updates the variable details.

To me, this looks like a bug in posh-git?

`echo $GitStatus (develop)

$GitBranchName = $GitStatus.Branch 

echo $GitBranchName (develop)

if($GitStatus.Branch.ToString().Trim() -ne 'master') {
    echo "switching to master and sleeping"
    icm -ScriptBlock { git checkout master -q }
    Start-Sleep 8
}

git status
echo $GitStatus.Branch (develop)

if($GitStatus.Branch.ToString().Trim() -ne 'master') {
    echo "failed to change to master because reasons" $GitStatus.Branch (develop)
    exit
}`

## Versions:
Posh-GitHub 0.0.2 
powershell-packagemanagement 10.0.10586.117 
poshtools-visualstudio2012 1.0.5 
poshtools-visualstudio2013 3.0.299 
poshtools-visualstudio2015 3.0.299

git version 2.8.1.windows.1

**Comment by theaquamarine** [comment]
I think $GitStatus is only updated when the prompt function is called, by default.

**Comment by brianmaher84** [comment]
Ah OK, it is not so useful operating like that I think at least for my needs.

I have started running git commands and parsing command output instead.

**Comment by dahlbyk** [comment]
> I think `$GitStatus` is only updated when the prompt function is called, by default.

Correct, `$GitStatus` is just a cache of what was last shown on the prompt.

> Ah OK, it is not so useful operating like that I think at least for my needs.
>
> I have started running git commands and parsing command output instead.

We do export the `Get-GitStatus` function, which is what populates `$GitStatus` within the prompt: https://github.com/dahlbyk/posh-git/blob/e415a03bd92d26a23e11f2b9a898ec8707c26bf3/GitPrompt.ps1#L269-L270. So rather than parsing Git output yourself, you could rely on our parsing.

I'm going to go ahead and close the issue, but feel free to comment with additional questions.

**Comment by brianmaher84** [comment]
Ah ok your suggestion worked, it looks much cleaner in my script to use your function.

Thanks for your help.
