### ISSUE TITLE
Is it possible to use Posh-Git inside the PowerShell Interactive Window of VS2015 and get a color prompt?

### ISSUE THREAD

**Issue by wpostma** [dahlbyk/posh-git#288]
I set up my poshTools_profile.ps1 like this:

```

<#
  configure environment for the PowerShell Interactive Window (PoshTools Shell) inside visual studio.
#>

#posh-git-integration-start
Push-Location (Split-Path -Path $MyInvocation.MyCommand.Definition -Parent)

# Load posh-git module from current directory
Import-Module .\posh-git

# If module is installed in a default location ($env:PSModulePath),
# use this instead (see about_Modules for more information):
# Import-Module posh-git


# Set up a simple prompt, adding the git prompt parts inside git repos
function global:prompt {
    $realLASTEXITCODE = $LASTEXITCODE

    Write-Host($pwd.ProviderPath) -nonewline

    Write-VcsStatus

    $global:LASTEXITCODE = $realLASTEXITCODE
    return "> "
}

Pop-Location

Start-SshAgent -Quiet
#posh-git-integration-stop

# more stuff here unrelated to posh git.


```

What I see is (a) no colored powershell prompt (because perhaps conhost.exe and powershell interactive window have different handling of ANSI escapes or whatever posh git is doing?) (b) the greater-than character is on its own line instead of on the same line.

It's somewhat usable in that I can see the [master] part of my prompt, it looks like this:

```
D:\dev\PowerShellProject1 [master]
> 

```

What is the recommended setup?   Perhaps it is possible to write the global:prompt function in a way that is friendlier for the PowerShell Interactive window?  Are the colors handled differently if I want to use the posh-git module inside powershell interactive window?

**Comment by wpostma** [comment]
It appears that attempts to use Write-Prompt to set the colors just do not work and the limitation is in PowerShell  Interactive window?

`Write-Prompt "test" -ForegroundColor Yellow -NoNewline
`

* Above JUST WORKS in real PowerShell in conhost

* Above does NOT work in PowerShell Interactive Window.

**Comment by theaquamarine** [comment]
Unfortunately not- it's a known problem with PoshTools' REPL. There's an issue open for it (with posh-git specifically mentioned!) but it's not been active in a while. https://github.com/adamdriscoll/poshtools/issues/168
