### ISSUE TITLE
How to add multiple keys using ssh-agent

### ISSUE THREAD

**Issue by musmo** [dahlbyk/posh-git#289]
In my powershell profile I have
```
# Load special features come from posh-git
 if ($gitStatus) {
    Enable-GitColors
    Start-SshAgent -Quiet
 }
```
everytime I start powershell I get prompted to enter my passphrase for id_rsa. How can I add additional keys to ssh-agent? I tried   Add-SshKey  however, everytime I restart ssh-agent it forgets about this key

**Comment by theaquamarine** [comment]
Adding Add-SshKey to your profile would load the keys every time powershell launches. Unfortunately, ssh-agent doesn't remember anything about keys between runs and posh-git can't tell if it's been restarted so they have to be re-added manually.

**Comment by musm** [comment]
Gotcha, so is there an easy way to add multiple keys and for posh-git to remember them between powershell sessions?

**Comment by dahlbyk** [comment]
> Gotcha, so is there an easy way to add multiple keys and for posh-git to remember them between powershell sessions?

Remembering keys depends on the lifecycle of `ssh-agent`. I suppose we could update `Start-SshAgent` to return a value indicating whether the service needed to be started (e.g. return process ID of new instance, if one was started), allowing you to decide if additional keys should be added?
