### ISSUE TITLE
not support bare repository

### ISSUE THREAD

**Issue by Aimeast** [dahlbyk/posh-git#291]
Hi, sometimes in server side we need manage bare repository, but when I `<cd>` to `xx.git` folder, no state display, posh-git not working in bare repository.

**Comment by dahlbyk** [comment]
I know this worked once upon a time, but I'm pretty sure it has been broken since 0dc174df6ade46de4eadc0751bf9d05d8d984b37.

**Comment by rkeithhill** [comment]
@dahlbyk I'm looking at that commit.  Is there a reason why this was changed to not use `git rev-parse --git-dir`?  I'm tempted to just change the code back perhaps with a resolve-path thrown in i.e. if you are in the root of a bare repo that git command returns `.`.
