### ISSUE TITLE
Tab expansion starting with '#' needs to be escaped

### ISSUE THREAD

**Issue by Morten242** [dahlbyk/posh-git#293]
When using tab-expansion on branch-names, if they start with '#' then it, and the rest of the line will get ignored by powershell since '#' marks the start of a line comment. Escaping it with ` does help though, e.g.:

`
git checkout `#1-branch-name
`

This is only necessary when the name starts with the pound-sign though, as names like `feature/#1-branch-name` works fine without any escaping.

**Comment by rkeithhill** [comment]
Yup, `#` is a special char in PoweShell (comment). There are a number of special characters most of which are punctuation like `$`, `@`, `(`, `{`, `;`.

**Comment by dahlbyk** [comment]
And Git supports branches starting with all of them:
![image](https://cloud.githubusercontent.com/assets/133987/21653085/0fcc8d84-d275-11e6-920d-270b2f412451.png)

**Comment by rkeithhill** [comment]
PowerShell will automatically quote paths during tab expansion that contain special chars or spaces.  I'm guessing we could do something similar when tab expanding branch names.  How about remote names? Can you have special chars in remote names as well?

**Comment by dahlbyk** [comment]
> Can you have special chars in remote names as well?

Yep. I'm inclined to add a guard against special characters in _any_ tab completed string.

**Comment by rkeithhill** [comment]
@dahlbyk There are some tab completed strings that are already escaped via single quotes (stashes and TF shelvesets).

**Comment by lzybkr** [comment]
@rkeithhill - I think I've solved this problem completely in TabExpansionPlusPlus, see https://github.com/lzybkr/TabExpansionPlusPlus/blob/master/TabExpansionPlusPlus.psm1#L64 - feel free to take that code as you see fit (I guess V3 and beyond only).
