### ISSUE TITLE
Unstaged files read as unchanged instead of showing unstaged changes in interactive commit

### ISSUE THREAD

**Issue by ricyje** [dahlbyk/posh-git#296]
Output:

Use of uninitialized value in sprintf at C:\Users\Name\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\mingw32/libexec/git-core\git-add--interactive line 567.

**Comment by dahlbyk** [comment]
This seems like an issue with Git proper (via GitHub Desktop). What do you get from `git --version`? How about the version listed under GitHub Desktop's About page?

/cc @shiftkey

**Comment by shiftkey** [comment]
@ricyje could you also include the commands you ran in the lead up to receiving this error?

**Comment by ricyje** [comment]
I really only started the interactive commit after making a few code changes ("git commit --interactive")

output of git --version:

git version 2.5.3.windows.1

github desktop version: Only You Can Shave Yakkind (3.0.12.0) c42ff11

**Comment by shiftkey** [comment]
@ricyje can you force an update of GitHub Desktop by clicking the cog icon and then *About GitHub Desktop*? There's been several updates since 3.0.12 (to Git 2.8.1 and Posh-Git) and I'd like to confirm this isn't occurring on the latest public release...

**Comment by ricyje** [comment]
Looks like it's not happening in the latest release.

**Comment by rkeithhill** [comment]
@ricyje @dahlbyk since this is not happening anymore, can we close this issue?
