### ISSUE TITLE
Problem on opensource powershell

### ISSUE THREAD

**Issue by palxex** [dahlbyk/posh-git#301]
OSX version 6.0.0.alpha9 pkg version
PS > Import-Module posh-git
Exception calling "GetCurrent" with "0" argument(s): "Operation is not supported on this platform."
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitPrompt.ps1:93 char:1
- $currentUser = [Security.Principal.WindowsPrincipal]([Security.Princi ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : PlatformNotSupportedException

You cannot call a method on a null-valued expression.
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitPrompt.ps1:94 char:1
- $isAdminProcess = $currentUser.IsInRole([Security.Principal.WindowsBu ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitUtils.ps1:231 char:23
-     $path = Join-Path ($Env:TEMP) ".ssh\$key.env"
-                       ~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitUtils.ps1:232 char:19
-     if (Test-Path $path) {
-                   ~~~~~
  - CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitUtils.ps1:231 char:23
-     $path = Join-Path ($Env:TEMP) ".ssh\$key.env"
-                       ~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/posh-git/0.6.1.20160330/GitUtils.ps1:232 char:19
-     if (Test-Path $path) {
-                   ~~~~~
  - CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

**Comment by theaquamarine** [comment]
What platform is this on?

`[Security.Principal.WindowsIdentity]::GetCurrent()` isn't supported, which is responsible for the first two errors. I've mentioned that in #302.

Looks like `$env:Temp` isn't populated under PowerShell on Linux. I'm not sure how important that is, as all the supported platforms have ssh agents which work some other way and I think that's all we use it for.

**Comment by palxex** [comment]
Powershell OSX 6.0.0.alpha9. Sorry forgot mentioning in title.

**Comment by rkeithhill** [comment]
I have checked in a fix for this. See PR #312
