### ISSUE TITLE
Tig Integration Wiki Page

### ISSUE THREAD

**Issue by brianmaher84** [dahlbyk/posh-git#305]
I have created a wiki page to describe how to use Tig within PowerShell which will be useful for many Posh-Git users I think.  It is useful for me anyway.

Let me know if you think it doesn't belong within the posh-git Wiki and I can remove it.  It might not since it doesn't have much to do with Posh-Git directly but it a useful tool for PowerShell Git users who I assume are mostly using Posh-Git.

https://github.com/dahlbyk/posh-git/wiki/Tig-Integration-With-PowerShell-(using-Cygwin)

**Comment by dahlbyk** [comment]
Works for me, thanks for opening an issue to let us know about the change!
