### ISSUE TITLE
Upgrade git version 2.10.0 from current 2.8.1.windows.1

### ISSUE THREAD

**Issue by hotwilson** [dahlbyk/posh-git#306]
After installation, when I do git --version I see
git version 2.8.1.windows.1

But on my Mac I see:
git version 2.10.0

**Comment by dahlbyk** [comment]
How did you install Git and posh-git? With GitHub Desktop, Chocolatey, or something else?

Closing this, since it's not directly a posh-git issue, but glad to help you figure it out.
