### ISSUE TITLE
Clarify README for Install-Module

### ISSUE THREAD

**Issue by voltagex** [dahlbyk/posh-git#308]
I've run `Install-Module Posh-Git -Scope CurrentUser` but it's unclear what to do after that.

I'm assuming the answer is "Go to Documents\WindowsPowerShell\Modules\posh-git\0.6.1.20160330 and run install.ps1".

**Comment by villasv** [comment]
In my case there's no such posh-git folder, and I see no side effects from running `Install-Module Posh-Git`  as administrator.

**Comment by jackjwilliams** [comment]
Same for me as well. Not exactly what to do after install-module Posh-Git.

**Comment by caddac** [comment]
I tried running the install script at the location mentioned by @voltagex but nothing changed for me. However, manually installing worked fine.

**Comment by rkeithhill** [comment]
I believe this has been cleared up in the README.md.  If you disagree, reopen this issue.
