### ISSUE TITLE
posh-git hangs (30+% CPU usage) when navigating to a large repo

### ISSUE THREAD

**Issue by voltagex** [dahlbyk/posh-git#309]
After enabling posh-git and reloading my profile, when I navigate to a large (>100MB) repository, the prompt / powershell freezes.

I'm not sure what other info I can give you. 

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by voltagex** [comment]
Apologies - looks to be a duplicate of https://github.com/dahlbyk/posh-git/issues/50

Unfortunately it seems like I can't use posh-git for now (40 000+ lines from `$GitPromptSettings.Debug = $true`!)

**Comment by dahlbyk** [comment]
@voltagex keep an eye on https://github.com/dahlbyk/posh-git/pull/208, I'm going to try to finally review and merge that Very Soon™.
