### ISSUE TITLE
prompt hangs if git status is large

### ISSUE THREAD

**Issue by ittayd** [dahlbyk/posh-git#314]
I have a branch with a lot of changes (10,000). git status takes ~1 second to return. However Get-GitStatus takes ~1 minute.  This of course makes it unusable. I think either the function needs to be rewritten to be more performant, or it should give up after N number of lines / seconds and return 'too many changes'.

**Comment by rkeithhill** [comment]
`Get-GitStatus` has been updated to improve performance.  When we release the next version shortly, can you check the perf on this situation?

**Comment by ittayd** [comment]
sure, tell me when you release (and how to update)

**Comment by dahlbyk** [comment]
> and how to update

How did you get posh-git? Chocolatey, PowerShell Gallery, `git clone`...?

**Comment by ittayd** [comment]
i think gallery, not sure

**Comment by rkeithhill** [comment]
If you installed via the PowerShell Gallery using `Install-Moduile`, you can run `Update-Module posh-git` to update - after the update has been published.

**Comment by rkeithhill** [comment]
@ittayd Since we haven't published the next release to the PSGallery yet, can you clone this repo and follow these steps to test this for us?
1. Start powershell with no profile e.g. execute `powershell.exe -noprofile` from Win+R
2. Import and configure posh-git with the following commands:
```
Import-Module <path-to-posh-git-repo>\src\posh-git.psd1
$GitPromptSettings.DefaultPromptEnableTiming = $true
```
3. Cd to some of your larger repos and observe the prompt processing time e.g:
```
~\GitHub\rkeithhill\vscode [master ↑1116] 202ms>
```
For my VSCode repo (6546 files), the prompt took 202 milliseconds.  Thanks.

**Comment by dahlbyk** [comment]
v0.7.0 was released last week to Chocolatey and the PSGallery. Has performance improved?

**Comment by ittayd** [comment]
No improvement. Still very slow. Is there a way to disable it on selected repositories? Or maybe set a timeout to give up?

**Comment by ittayd** [comment]
Also PS is showing at ~25% in task manager meaning it is maxing out one of the CPUs. This means to me it is doing more CPU work than IO.

**Comment by ittayd** [comment]
Even just hitting 'enter' takes a long time for the prompt to appear

**Comment by dahlbyk** [comment]
From the readme:

> …you can disable [file status] on a repo-by-repo basis by adding individual repository paths to `$GitPromptSettings.RepositoriesInWhichToDisableFileStatus`.

I do like the idea of a timeout, though not sure if PowerShell would support that. You could also try [git-status-cache](https://github.com/cmarcusreid/git-status-cache-posh-client) by @cmarcusreid.
