### ISSUE TITLE
Spin off SSH Agent module?

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#338]
As I alluded to in https://github.com/dahlbyk/posh-git/issues/328#issuecomment-269794084, a [nontrivial number of issues and open PRs here](https://github.com/dahlbyk/posh-git/search?q=agent&type=Issues) are dedicated to managing `ssh-agent` and Pageant.

Since that problem has nothing to do with Git other than Git for Windows being a common distribution path for MSYS, I'd like to spin the SSH Agent bits off into a separate module. Is anyone interested in taking that on?

cc people who have tried to contribute SSH fixes: @theaquamarine (#133) @paulmarsy (#162) @c-mu (#195) @hjoelr (#297) @StefanScherer (#238) @Ventajou (#148) @nitin88 (#295)

**Comment by dahlbyk** [comment]
Also cc @pcx (#155) @GrahamTheCoder (#211) @kayukin (#316)

**Comment by pcx** [comment]
@dahlbyk I guess you wanted to cc: @pxc :)

**Comment by dahlbyk** [comment]
> @dahlbyk I guess you wanted to cc: @pxc :)

I suppose I did. You're welcome to help, too. 😉

**Comment by rkeithhill** [comment]
@dahlbyk do you want to host this?  If so, what would we call it?  `posh-git-ssh`?  There is already a [posh-ssh](https://www.powershellgallery.com/packages/Posh-SSH/1.7.7) on the PowerShell Gallery but it doesn't seem to deal with the agent or keys.

**Comment by dahlbyk** [comment]
> @dahlbyk do you want to host this? If so, what would we call it? posh-git-ssh? There is already a posh-ssh  on the PowerShell Gallery but it doesn't seem to deal with the agent or keys.

I might as well. @drusellers suggested `posh-sshit`, but that may be slightly inappropriate. Maybe `posh-ssh-agent`? [Twitter can decide.](https://twitter.com/dahlbyk/status/834118721983676417)

> Also, will the upcoming Win32-OpenSSH implementation impact this?

Several of the open issues here are or have been about Win32-OpenSSH, so yes that's in scope.

**Comment by rkeithhill** [comment]
+1 for `posh-ssh-agent`.

**Comment by nigurr** [comment]
Posh-ssh-agent sounds good. :)

**Comment by nitin88** [comment]
I am very bad at naming 😛
`posh-ssh-agent` sounds good 👍

**Comment by tamj0rd2** [comment]
Has anything happened with this? I'd be down to work on it

**Comment by dahlbyk** [comment]
Thanks for the offer, @tamj0rd2! Nobody is actively working on this, as far as I know.

Before we spawn off a new repo, it seems like a good idea to try to review/merge the [four existing Pull Requests](https://github.com/dahlbyk/posh-git/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22SSH+Agents%22). Do you want to start by taking a look at those, and bringing them up-to-date (conflicts everywhere!) if the changes are good? My time is relatively limited at the moment, but I'm glad to help and answer questions as I'm able.

**Comment by nitin88** [comment]
I am not sure whether we should support this anymore for windows.
Currently Windows git client ships with git-credential-manager written by Microsoft. It's more reliable and much better compared to ssh-agent in Windows.

**Comment by dahlbyk** [comment]
git-credential-manager is great for HTTPS, but as far as I know it doesn't handle SSH keys: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/25. I did find https://github.com/elsteelbrain/ssh-agent-helper via that issue.

At this point I'm tempted to just drop the `ssh-agent` helpers from 1.0.0 and deal with complaints (if any). Maybe someone will be motivated to pick up where we've left off here?

**Comment by nitin88** [comment]
HTTPS is the way. We should discourage someone using HTTP ;)
Yes. Indeed we should decouple ssh-agent and poshgit

**Comment by JeremySkinner** [comment]
Hi @dahlbyk et all, as I mentioned on twitter I'm planning to do some work on this over the weekend.

This is what I'm currently thinking:
- I'll add support for win10 1803 openssh (#583)
- Even though win10 provides its own ssh-agent now, I think we should still provide this functionality. There may be legitimate reasons that users may want to run the openssh that ships as part of git for windows, or pageant.
- I'll split up sshutils.ps1 into a separate module remove posh-git's dependency on it
- Where do we want to host the module? I'm happy to host it under my github account, or you can host it under yours. Let me know. 
- I'll try and increase the test coverage while I'm at it

If anyone else has any thoughts on this please let me know

I'll post updates on this issue.

**Comment by JeremySkinner** [comment]
Current progress: https://github.com/dahlbyk/posh-git/pull/585

- [ ] Remove SshUtils from posh-git
- [ ] Stop posh-git adding start-sshagent to profile 
- [ ] Remove tests for ssh utils
- [ ] Remove all text/comments referencing ssh 
- [ ] Ensure tests still pass!
- [ ] Create new posh-ssh module
- [ ] Split SshUtils.ps1 into separate files
- [ ] Copy and utility methods that the Ssh Utils need from posh-git
- [ ] Add new `Add-PoshSshToProfile` similar to `Add-PoshGitToProfile`
- [ ] Tests for ssh functions
- [ ] Tests for `Add-PoshSshToProfile`
- [ ] Support for win10 openssh

**Comment by rkeithhill** [comment]
The primary advantages I see with the Windows the openssh ssh-agent is that A) because it runs as a service, I don't have to configure PowerShell to start the agent.  The agent is always running.  And B), I don't have to launch my dev tools (Visual Studio) from PowerShell in order for them to work with the ssh-agent.  I can launch Visual Studio from my taskbar - which is how I prefer to do that.

**Comment by dahlbyk** [comment]
For starters, I'm inclined to fix up the low-hanging SSH stuff (at least #583, maybe look at the open PRs assigned to the [SSH Agents milestone](https://github.com/dahlbyk/posh-git/milestone/3)?) in the `v0` branch for a v0.8 release.

Once that's stable, we can cut it loose into a separate module and drop it from `master` here for the next v1 beta.

> Where do we want to host the module? I'm happy to host it under my github account, or you can host it under yours. Let me know.

No preference. I can create a repo here, we can use a repo of your own, or we can see about hosting it under [PoshCode](https://github.com/PoshCode).

**Comment by rkeithhill** [comment]
Also, it would actually be nice to have native argument completion for ssh, ssh-keygen, ssh-keyscan, ssh-add, sftp, and scp.  :-)

**Comment by JeremySkinner** [comment]
> Also, it would actually be nice to have native argument completion for ssh, ssh-keygen, ssh-keyscan, ssh-add, sftp, and scp. :-)

It would! I'd like to address that too.

> For starters, I'm inclined to fix up the low-hanging SSH stuff (at least #583, maybe look at the open PRs assigned to the SSH Agents milestone?) in the v0 branch for a v0.8 release.

I'll do separate PRs for these and keep them separate from the work on the standalone module.

**Comment by dahlbyk** [comment]
>> Where do we want to host the module? I'm happy to host it under my github account, or you can host it under yours. Let me know.
> 
> No preference. I can create a repo here, we can use a repo of your own, or we can see about hosting it under PoshCode.

Or, option 3: keep it in this repo, and just manage it better. @JeremySkinner glad to make you a maintainer here to that end.

**Comment by rkeithhill** [comment]
Another feature `posh-ssh` could provide is configuring Git to use Window's OpenSSH implementation via the env var `GIT_SSH`.  That env var would need to be created at user or machine scope so that tools launched from the Start menu/taskbar would benefit.  Then again, this might be something that Git for Windows supplies at some point?

**Comment by dahlbyk** [comment]
> Or, option 3: keep it in this repo, and just manage it better.

I've already talked myself out of this. We'll want to tag posh-ssh versions separately from posh-git.

**Comment by JeremySkinner** [comment]
> Another feature posh-ssh could provide is configuring Git to use Window's OpenSSH implementation via the env var GIT_SSH. 

Yes I think that's a good idea. We can always take it out in the future once git for windows supports it natively. 

Do you think the env var is better than modifying the global .gitconfig?

**Comment by JeremySkinner** [comment]
Another thing I'd like to add is bookmark manager commands for manipulating the .ssh/config file (similar to how stormssh works). I have a couple of very messy scripts for doing this at the moment. Once the module is split out I'd like to tidy them up and bring them across.

**Comment by dahlbyk** [comment]
We can move it elsewhere if y'all want, but I've created https://github.com/dahlbyk/posh-ssh if you want to start creating issues there with a wishlist. Once we get `v0` here in a good state, I'm thinking I'll just push this repo there and we can set about deleting all things posh-git. Unless you'd rather the repo not have posh-git baggage?

**Comment by JeremySkinner** [comment]
Soundo good, thanks

**Comment by rkeithhill** [comment]
I'd call this issue resolved by the creation of `posh-sshell`.
