### ISSUE TITLE
Export function to manipulate GitPromptSettings

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#340]
Spawned from https://github.com/dahlbyk/posh-git/pull/256#discussion_r94244778, similar to #111.

Pros:
- Discoverability (module definition, etc)
- Tab completion
- Parameter Validation (e.g. `BranchBehindAndAheadDisplay` "enum")

Cons:
- More code to maintain
- Migration path from `$GitPromptSettings`? Or does function just manipulate the global?

**Comment by rkeithhill** [comment]
Pertinent to this discussion (and the discussion on module install script) - https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/79

**Comment by rkeithhill** [comment]
You get tab completion/Intellisense with the $GitPromptSettings variable so that really isn't a "pro" for a function.

**Comment by rkeithhill** [comment]
For 1.0.0 we're going in the direction of a more structured, strongly typed GitPromptSettings object.  If you disagree or think this needs to be reopened, please reopen it.
