### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by Abdullah2993** [dahlbyk/posh-git#353]
Any estimated time for the next release?

**Comment by dahlbyk** [comment]
You can follow along at https://github.com/dahlbyk/posh-git/milestone/1 and https://github.com/dahlbyk/posh-git/pull/327 in particular. I'm hoping pretty soon, but we have a bit more triage of the issue backlog to get through first.

**Comment by rkeithhill** [comment]
@dahlbyk I was thinking that we complete PRs:  #358, #336 and #327.  Then we’d be ready to cut 0.7.0, create a release/maintenance branch for it.  After that, we can start 1.0 work on master.  What’s your thinking on this?

**Comment by dahlbyk** [comment]
@Abdullah2993 a prerelease is now out on Chocolatey, if you want to help test: [v0.7.0-pre4](https://chocolatey.org/packages/poshgit/0.7.0-pre4).

PowerShellGet doesn't support pre-releases, so that's waiting on just a few more issues to be closed.

**Comment by Abdullah2993** [comment]
@dahlbyk sure...no problem

**Comment by dahlbyk** [comment]
And [v0.7.0-pre5](https://chocolatey.org/packages/poshgit/0.7.0-pre5) is now pending moderation.

**Comment by rkeithhill** [comment]
If all goes as to plan, `0.7.0` will release today.  If not, I guess we can reopen this.  :-)
