### ISSUE TITLE
Error in $profile after poshgit installed?

### ISSUE THREAD

**Issue by ewgoforth** [dahlbyk/posh-git#355]
I'm seeing the following message when my $profile gets executed:

```
Rename-Item : Cannot rename because item at 'Function:\Prompt' does not exist.
At C:\Users\myuser\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:66 char:1
+ Rename-Item Function:\Prompt PoshGitPrompt -Force
```

here's what the relevant line looks like:

```
. 'C:\tools\poshgit\dahlbyk-posh-git-464601f\profile.example.ps1'
Rename-Item Function:\Prompt PoshGitPrompt -Force
function Prompt() {if(Test-Path Function:\PrePoshGitPrompt){++$global:poshScope; New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor, `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;$private:p = PrePoshGitPrompt; if(--$global:poshScope -eq 0) {Remove-Item function:\Write-Host -Force}}PoshGitPrompt}

```

**Comment by rkeithhill** [comment]
Are you using latest bits from this repo or the latest poshgit from Chocolatey?  

**If** you are using the latest bits from this repo (the not yet released 0.7.0) you can comment out the these lines e.g.:
```powershell
# Rename-Item Function:\Prompt PoshGitPrompt -Force
# function Prompt() {if(Test-Path Function:\PrePoshGitPrompt){++$global:poshScope; New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor, `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;$private:p = PrePoshGitPrompt; if(--$global:poshScope -eq 0) {Remove-Item function:\Write-Host -Force}}PoshGitPrompt}
```
Even if you're not using the latest repo bits, you might try commenting out the lines above.  

BTW which version of PowerShell are you using (check with `$PSVersionTable.PSVersion`)?

**Comment by dahlbyk** [comment]
> Are you using latest bits from this repo or the latest poshgit from Chocolatey?

`C:\tools\poshgit\dahlbyk-posh-git-464601f` SHA is the merge of #349: https://github.com/dahlbyk/posh-git/commits/464601f. For the record, this is why we need to pin the Chocolatey package to the tagged version rather than `master`. 😒 

I would not expect loading `profile.example.ps1` to result in `Function:\Prompt` being missing. It looks like we might be getting confused if `Function:Prompt` doesn't exist when the module is imported?

------------------------------------

For reference, this is what a Chocolatey-installed `$PROFILE` looks like:

```powershell
if(Test-Path Function:\Prompt) {Rename-Item Function:\Prompt PrePoshGitPrompt -Force}

# Load posh-git example profile
. 'C:\tools\poshgit\dahlbyk-posh-git-464601f\profile.example.ps1'

Rename-Item Function:\Prompt PoshGitPrompt -Force
function Prompt() {if(Test-Path Function:\PrePoshGitPrompt){++$global:poshScope; New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor, `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;$private:p = PrePoshGitPrompt; if(--$global:poshScope -eq 0) {Remove-Item function:\Write-Host -Force}}PoshGitPrompt}
```

I'd love for all of this to be replaced in 1.0 with `Import-Module posh-git`.

**Comment by dahlbyk** [comment]
Yeah, the code to set `prompt` is definitely broken if `prompt` doesn't exist: #357

Thanks for the bug report, @ewgoforth!

**Comment by dahlbyk** [comment]
I would uncomment the second line and delete the other three - they shouldn't be necessary, and will be removed when we move to 1.0.

**Comment by ewgoforth** [comment]
I did that like so:

```
#if(Test-Path Function:\Prompt) {Rename-Item Function:\Prompt PrePoshGitPrompt -Force}
# Load posh-git example profile
. 'C:\tools\poshgit\dahlbyk-posh-git-464601f\profile.example.ps1'
#Rename-Item Function:\Prompt PoshGitPrompt -Force
#function Prompt() {if(Test-Path Function:\PrePoshGitPrompt){++$global:poshScope; New-Item function:\script:Write-host -value "param([object] `$object, `$backgroundColor, `$foregroundColor, [switch] `$nonewline) " -Force | Out-Null;$private:p = PrePoshGitPrompt; if(--$global:poshScope -eq 0) {Remove-Item function:\Write-Host -Force}}PoshGitPrompt}

```
and I seem to have the full poshgit functionality.

**Comment by rkeithhill** [comment]
So as an action item for this issue, is there something in the Chocolatey package that needs to be tweaked for 0.7.0?  Also, just removing those lines probably wouldn't help someone who has a previously (Chocolatey) installed version of poshgit.  What should we do there?

**Comment by dahlbyk** [comment]
@ewgoforth if you don't mind, could you do a `choco install poshgit --force` to get latest and verify that the error doesn't return if you uncomment all those lines?

> So as an action item for this issue, is there something in the Chocolatey package that needs to be tweaked for 0.7.0?

I believe #357 is technically sufficient, but we have #239 marked for 0.7 so: #358.
