### ISSUE TITLE
Use LibGit2Sharp

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#37]
Hopefully faster than multiple git calls...

**Comment by rkeithhill** [comment]
Looks like we are still using git.exe and given that MS has switched with VS 2017 to use git.exe instead of some variant of libgit, maybe we just close this issue?

**Comment by dahlbyk** [comment]
Fasterness option 1: #208 
Fasterness option 2: [Powerline](https://github.com/Jaykul/PowerLine) with [PSGet](https://github.com/PoshCode/PSGit)
