### ISSUE TITLE
git branch -vv shows blue on blue

### ISSUE THREAD

**Issue by mj1856** [dahlbyk/posh-git#373]
Using `git branch -vv` to show remote tracking details shows in blue foreground.  On the PS background default blue, it's unreadable.  Highlighting helps as a workaround, but thought I'd let you know.

(Low priority)

posh-git version: 0.5.0.2015
PSVersion: 5.1.14393.693
git version 2.10.2.windows.1
OS: Microsoft Windows NT 10.0.14393.0

**Comment by dahlbyk** [comment]
posh-git doesn't do anything to the colors that Git uses by default, so I would expect you to see this coloration even without posh-git enabled (try `powershell -noprofile`).

To disable Git colors on `git branch`, set [`color.branch = never`](https://git-scm.com/docs/git-config#git-config-colorbranch). You can also try adjusting `color.branch.upstream`.

**Comment by mj1856** [comment]
Thanks!
