### ISSUE TITLE
Problem with branch name encoding

### ISSUE THREAD

**Issue by PiterGoCompany** [dahlbyk/posh-git#374]
### System Details

- posh-git version: 0.6.1.20160330
- PowerShell version: 5.1.14393.693
- Git version: 2.11.0.windows.3
- Operating system name and version: Microsoft Windows NT 10.0.14393.0

### Issue Description

I am experiencing a problem with encoding branch name displayed in status. My branch name is something like "wpłata" but posh git displays it as "wp┼éata". Is there any possibility to resolve this problem?

**Comment by dahlbyk** [comment]
This should be fixed by https://github.com/dahlbyk/posh-git/pull/359, which will be [released](https://github.com/dahlbyk/posh-git/pull/327) 🔜

**Comment by PiterGoCompany** [comment]
Thank you for information.
