### ISSUE TITLE
choco install poshgit ate my prompt!

### ISSUE THREAD

**Issue by dhirschfeld** [dahlbyk/posh-git#375]
Even after uninstalling, force reinstalling and uninstalling again my prompt is now simply
```
PS>
```
no matter which directory I'm in. It also doesn't show the poshgit prompt when I'm in a git repo.

Any idea how I can get my prompt back? Or is it a chocolatey problem? :(

**Comment by dhirschfeld** [comment]
There was a leftover line in my profile causing the problem. Sorry for the noise...

**Comment by dahlbyk** [comment]
No worries. #239 should make the uninstall experience better.
