### ISSUE TITLE
Should tab expansion match anywhere in string (other than start)?

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#380]
Right now when I tab complete branch names, there is a lot of text at the beginning that is the same e.g.:
```
rkeithhill/branch1
rkeithhill/branch2
user/hillr/branch3
user/hillr/branch4
```
It would like it if I typed `git checkout 1` and it matched the first branch above.  

You could also imagine tab completing `ma` to not only `master` but also `origin/master` for cases like `rebase`.

BTW I'm not proposing fuzzy matching, just removing the start anchor metachar from some of the regexes.

**Comment by dahlbyk** [comment]
This does seem like a potentially nice feature, but probably one we would want to disable by default. This isn't how tab expansion works anywhere else in PowerShell, is it?

I suppose I should probably start namespacing my branches here, eh? We do on [HuBoard](https://huboard.com/) and I use an alias to take care of pushing my local branches to an appropriately-named remote branch:

```
!git push -u origin HEAD:dahlbyk/$(git symbolic-ref --short HEAD)
```

This lets my use `git pnb` for local `my-branch` to push to `origin/dahlbyk/my-branch`.

**Comment by rkeithhill** [comment]
> This isn't how tab expansion works anywhere else in PowerShell, is it?

True.  VS Code Intellisense for parameters works this way but not tab expansion.  Yeah, let's table this for now.

> This lets my use git pnb for local my-branch to push to origin/dahlbyk/my-branch.

Nice!
