### ISSUE TITLE
Add option to abbreviate home directory in prompt

### ISSUE THREAD

**Issue by shawmanz32na** [dahlbyk/posh-git#386]
Currently, posh-git abbreviates my home directory to `~` in the prompt. By default, PowerShell prints out the whole path, which I prefer.

`PS C:\Users\kshaw>` becomes `~>` with posh-git

After upgrading recently (thanks to Github for Windows), I noticed that my home directory is now abbreviated, and went looking for a `GitPromptSetting` that would allow me to turn off the abbreviation, but to no avail.

I'd like to see an `AbbreviateHomeDirectory` (or similar) setting in the `GitPromptSettings` that would allow me to enable or disable this home directory abbreviation.

**Comment by rkeithhill** [comment]
Seems reasonable.  Using `~` is a common convention (borrowed) from Bash/Linux, where the prompt width can be shortened a bit.

**Comment by JayBazuzi** [comment]
Why is this a post-git request? isn't putting the CWD in the prompt outside of the scope of posh-git?

**Comment by rkeithhill** [comment]
posh-git 0.7.0, when it releases, will set the user's prompt with one that displays Git status summary info.  It will not do this if the user has their own custom prompt function.  We get so many questions about - I installed posh-git and then I imported it and I still don't see Git status summary info in my prompt.  :-(

**Comment by JayBazuzi** [comment]
That makes sense, thanks @rkeithhill .

**Comment by rkeithhill** [comment]
@JayBazuzi But your question makes me wonder if the default for `$GitPromptSettings.DefaultPromptAbbreviateHomeDirectory` should be $false instead of $true.  Hmm....

**Comment by JayBazuzi** [comment]
`~` is not just a *nix convention, it's part of PowerShell. You can do:

   PS> cd ~

So don't feel like you're pulling in a foreign notion.

**Comment by shawmanz32na** [comment]
I'm familiar with the `~` convention, just personally prefer the powershell default. I don't mind the feature, I just wish it was configurable, hence the issue.

@rkeithhill Our thoughts align. As a user, I thought it strange that posh-git changed my prompt. As a matter of fact, I suspected that something was seriously broken when I didn't see my default prompt (I expected the additional git summary, just not the changes to my existing prompt, and it took me a little while to figure out it was a feature, not a bug. In the pending pull request, I defaulted to `$true` only because it wouldn't change the current functionality, which I presumed was the way it is for a reason. However, if there are many others like me that are caught off-gaurd by the change, printing the default prompt (instead of the abbreviated prompt) by default might be a good idea. I'd vote that the abbreviation be turned off by default.

**Comment by rkeithhill** [comment]
Let me think about the default value for the setting and get @dahlbyk opinion.  Setting it to false would probably be the "safer" way to go.

**Comment by rkeithhill** [comment]
While we are at it, should we add a `DefaultPromptPrefix` setting that defaults to `PS `?  With this setting, the posh-git default prompt, would look just like the PowerShell default prompt except when in a Git repo.  Then it would have the Git status summary inserted between the path and the `>` char.  And if anyway wants to reclaim those three chars, they can set `$GitPromptSettings.DefaultPromptPrefix = ''`.

**Comment by dahlbyk** [comment]
> While we are at it, should we add a `DefaultPromptPrefix` setting that defaults to `'PS '`?  With this setting, the posh-git default prompt, would look just like the PowerShell default prompt except when in a Git repo.  Then it would have the Git status summary inserted between the path and the `>` char.  And if anyone wants to reclaim those three chars, they can set `$GitPromptSettings.DefaultPromptPrefix = ''`.

I'm inclined to go the other direction, at least until 1.0: support `DefaultPromptPrefix` such that it's possible to mimic the default `prompt`, but have it default to empty for consistency with posh-git 0.6 and earlier. Maybe I'm overestimating folks' attachment to "the way things have been"? Would be curious how many people actually notice any of these details. Sigh.

**Comment by rkeithhill** [comment]
> have it default to empty for consistency with posh-git 0.6 and earlier

Sounds good. I'll submit a PR for that tonight.

**Comment by rkeithhill** [comment]
PR submitted #393
