### ISSUE TITLE
Put current working directory on its own line

### ISSUE THREAD

**Issue by JayBazuzi** [dahlbyk/posh-git#388]
CWD + Git Status can take up a lot of space, leaving little in which to type commands.

Put the CWD on its own line. Add a horizontal bar to make it easy to scroll back and see where each command begins/ends.

        $width = ($Host.UI.RawUI.WindowSize.Width - $(Get-Location).ToString().Length) - 2
        Write-Host -ForegroundColor Yellow "$(Get-Location) $(New-Object System.String @('-',$width))"

**Comment by rkeithhill** [comment]
I pitched a two line prompt ror the default prompt and we decided to leave it as single line to not deviate too much from PowerShell's default prompt.  However, you can easily get a two line prompt with the posh-git default prompt by changing this "default" setting:
```powershell
$GitPromptSettings.DefaultPromptSuffix = '$(''>'' * ($nestedPromptLevel + 1)) '
```
tp
```powershell
$GitPromptSettings.DefaultPromptSuffix = '`n$(''>'' * ($nestedPromptLevel + 1)) '
```
That will give you a prompt like this:
```
~\GitHub\dahlbyk\posh-git [master ≡ +0 ~1 -0 !]
>
```
And of course, folks are free to create their own custom prompt function and configure it however they like: https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt
