### ISSUE TITLE
Git Version Parsing Incorrect. Warns me it's not high enough when it is.

### ISSUE THREAD

**Issue by haacked** [dahlbyk/posh-git#39]
Posh-Git gave me the following warning:

```
WARNING: Posh-Git requires git 1.7.2 or better. You have 1.7.1
```

![](http://content.screencast.com/users/haacked/folders/Jing/media/7a602577-0bd4-484c-8a50-ab346643d8bd/2012-04-12_1011.png)

Au Contraire, Mon Frère! I have 1.7.10! :)

**Comment by planto** [comment]
I do have a similar Warning except there is no current version shown:
"WARNUNG: posh-git requires Git 1.7.2 or better. You have .
Error connecting to agent: Protocol wrong type for socket"
![posh-git-warning](https://cloud.githubusercontent.com/assets/7996182/12219543/57b689a6-b705-11e5-8f6d-11672a3c3a8a.jpg)
I just downloaded and installed the newest GitHub desktop client,  
git --version
git version 2.5.3.windows.1

any suggestions?

**Comment by ethanhardy** [comment]
I'm seeing this problem as well.  Any advice?

**Comment by dahlbyk** [comment]
Sorry for the lack of response here. @ethanhardy, do you see the same warning and have the same result from `git --version`?

**Comment by planto** [comment]
Hi, I found out, that my firewall was the whole time auto sandboxin the shell, so turning it off did the trick for me.
