### ISSUE TITLE
$PSModulePath: The specified module was not loaded

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#391]
Running `Add-PoshGitToPrompt` (via `install.ps1` or directly) is correctly finding my posh-git clone in `$PSModulePath` (and inserting `Import-Module posh-git` instead of an absolute path), but that `Import-Module posh-git` call fails with:

```
import-module : The specified module 'posh-git' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ import-module posh-git
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-git:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand 
 ```

<img width="1086" alt="powershell_2017-02-01_08-59-42" src="https://cloud.githubusercontent.com/assets/133987/22512064/59f6da42-e85d-11e6-9f8f-fc6a6c0c5d51.png">

Any ideas to troubleshoot, @rkeithhill?

### System Details

- posh-git version: 33ed60210eb2aef7c6b6c49e7d735db341ae5efc
- PowerShell version: 5.1.14393.693
- git version 2.7.1.windows.2
- OS: Microsoft Windows NT 10.0.14393.0

**Comment by rkeithhill** [comment]
I think Import-Module is looking for a particular directory scheme `<module-name>[module-version]` under each path in PSModulePath.  

If you remove `C:\Dev\OSS\posh-git\src` from PSModulePath and remove the import command from your profile, then impo from `C:\Dev\OSS\posh-git\src` and then run Add-PoshGitToProfile, it should use the full path.

**Comment by dahlbyk** [comment]
Yep, that's it. Moving the module into `src/` means a normal posh-git clone no longer matches the expected pattern. Few options:

1. Move `src/*` to `src/posh-git/*`
2. Skip our `$PSModulePath` check if `(SplitPath $ModuleBasePath -Leaf) -eq 'src'`
3. Add a `Get-Module posh-git -ListAvailable` sanity check after a `$PSModulePath` match

Leaning toward 2️⃣

**Comment by rkeithhill** [comment]
I think we should leave in the PSModulePath to handle the normal install-module install.  Before that check we could check for current dir of src and/or ../.git and then import by path. That would cover the git clone case.

**Comment by marc88** [comment]
Hello,

I have PS version 2. Hence, am using Chocolatey to install posh-git.  Any ideas how to go about it?
Sorry for being a noob.

**Error:**

The "=" operator is missing after a named argument.
ERROR: The module to process 'posh-git.psm1', listed in field 'ModuleToProcess' of module manifest 'C:\tools\poshgit\dah
lbyk-posh-git-a4faccd\src\posh-git.psd1' was not processed because no valid module was found in any module directory.

![image](https://user-images.githubusercontent.com/22036025/32714346-69a05472-c873-11e7-9d83-7887f98ea3aa.png)

**Comment by dahlbyk** [comment]
@marc88 try renaming the `C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src` folder from `src` to `posh-git` and update your `$PROFILE` accordingly. In other cases we've seen PowerShell be picky about loading modules if the folder name doesn't match the module name. (Which is really silly behavior, I might add.)

**Comment by marc88** [comment]
@dahlbyk : Thank you for the solution!
It worked indeed. But, I tried upgrading powershell to v3.0 and I found Import-Module added the module base directly to my profile. That's when I realised what was actually wrong :)

**Comment by thomashoddinott** [comment]
@dahlbyk Followed those steps and worked for me too. Cheers.

**Comment by Vishnu05** [comment]
![image](https://user-images.githubusercontent.com/32086222/86438071-74d76680-bd23-11ea-87fd-4c5f58c818d3.png)

Where I'm going wrong I'm not able to fix this one, need some help

**Comment by rkeithhill** [comment]
Does your home dir name really have a space in it? I could see how that might cause PS to have issues loading modules.  What do you get when you execute `$env:PSModulePath`.  Also, try to specify the full path to the module like so:
```
import-module "$HOME\Documents\WindowsPowerShell\Modules\posh-git\<version-number>\posh-git.psm1"
```

**Comment by Jan-Karasinski** [comment]
@dahlbyk Hi, what's the outcome of this issue? I've set up posh-git today and found out this issue still persists, at least for choco.
Btw, the last suggestion works too, I've used it myself as it's really the only way to make importing it future-proof.

**Comment by rkeithhill** [comment]
@Jan-Karasinski What are the contents of your profile - `gc $profile` and `gc $profile.CurrentUserAllHosts`?  I just tested a choco install of posh-git in a Windows Sandbox instance and got this for $profile contents ($profile.CurrentUserAllHosts didn't exist):
```
Import-Module 'C:\tools\poshgit\dahlbyk-posh-git-9bda399\src\posh-git.psd1'
```
And posh-git imported successfully.

**Comment by Jan-Karasinski** [comment]
@rkeithhill It was empty and I had to modify it manually, with the full path. Also, my PowerShell env was fresh, I was using it just to execute simple commands that were not requiring any kind of modifications/privileges.

**Comment by rkeithhill** [comment]
@Jan-Karasinski So you up and running with posh-git?

**Comment by Jan-Karasinski** [comment]
@rkeithhill Yep, it works like a charm.
