### ISSUE TITLE
Installed but no custom prompt

### ISSUE THREAD

**Issue by caddac** [dahlbyk/posh-git#398]
### System Details

- posh-git version: 0.6.1.20160330
- PowerShell version: 5.1  build:14393  revision 693
- git version 2.11.0.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

I installed posh-git using:
`Install-Module posh-git`
`Import-Module posh-git`

When I `cd` to a git repo auto complete of `git fe` works (implying posh-git is installed and imported). I also updated my profile to import it automatically. That works great. 

However the PS prompt doesn't change. Its just the normal prompt. 
I also tried to update the prompt but got an error:
```
PS C:\Users\DaveC> D:
PS D:\> cd .\Github\BAT
PS D:\Github\BAT> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
PS D:\Github\BAT> $GitPromptSettings.DefaultPromptSuffix
PS D:\Github\BAT> $GitPromptSettings.DefaultPromptSuffix = '`n$(''>'' * ($nestedPromptLevel + 1)) '
Exception setting "DefaultPromptSuffix": "The property 'DefaultPromptSuffix' cannot be found on this object. Verify
that the property exists and can be set."
At line:1 char:1
+ $GitPromptSettings.DefaultPromptSuffix = '`n$(''>'' * ($nestedPromptL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

PS D:\Github\BAT>
```

**Comment by rkeithhill** [comment]
Thanks for providing version details. In this case, you are using the current version on the PowerShell Gallery and we're still about a week or so from updating that to posh-git 0.7.0.  It is version 0.7.0 that supports changing the prompt function when the module is imported.  For now, you can put the following in your PowerShell profile.  To edit your profile, run `notepad.exe $profile` from PowerShell.  
```powershell
function prompt {
    $origLastExitCode = $LASTEXITCODE
    Write-Host $ExecutionContext.SessionState.Path.CurrentLocation -NoNewline
    Write-VcsStatus
    $LASTEXITCODE = $origLastExitCode
    "$('>' * ($nestedPromptLevel + 1)) "
}

Import-Module posh-git
```
Be sure to put the prompt function before the line that executes `Import-Module posh-git`.  Then dot source you profile again `. $profile`.  Now you should see the prompt.

When 0.7.0 does release, you might want to remove that prompt function from $profile.  posh-git will not install its prompt function if the user already has a customized prompt function.

**Comment by caddac** [comment]
So you're saying that as of now (version 0.6) doesn't change the prompt when you Import-Module? The readme.md implies it should change.

Your suggestion did make the prompt change to the posh-git prompt I was expecting.

**Comment by rkeithhill** [comment]
> The readme.md implies it should change.

That is correct.  The README you see here is for the master branch.  It is what is currently under development and development of 0.7.0 has stretched out longer than I had anticipated when I made the changes to the README.  In the future, I'll try to wait until much closer to release to do that.

**Comment by caddac** [comment]
sounds good. Thanks for that clarification.
