### ISSUE TITLE
Git errors and regular output start appearing as red error records

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#404]
### System Details

- posh-git version: 0.7.0
- PowerShell version: 5.1.14393.693
- git version 2.10.0.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

This is what I see after a while:
```
259:49ms> git checkout master
Your branch is behind 'origin/master' by 66 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
git : Switched to branch 'master'
At line:1 char:1
+ git checkout master
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Switched to branch 'master':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

If I close and restart a new PowerShell console this problem goes away, at least for a while.  Not sure what is triggering it to start acting differently.

**Comment by dahlbyk** [comment]
Fascinating...I have never seen this. So a valid/successful `git checkout master` is now reporting itself as being error-full?

**Comment by rkeithhill** [comment]
Yes but it seems to take a while - like when I have a console running for days.  Closing and restarting the console fixes it ... for a while.

**Comment by dahlbyk** [comment]
What do you see in `$Errors` and the module's private `$invokeErrors` when this occurs?

**Comment by rkeithhill** [comment]
`$invokeErrors` was empty and `$errors` contained only a few records corresponding to the git errors I saw previously.  I did try to checkout a branch that didn't exist.  I believe that generated the first error.

**Comment by rkeithhill** [comment]
@lzybkr Do you know of any scenarios where calling an application (like git.exe) starts generating error records for both stdout & stderr output in the PowerShell console?

**Comment by lzybkr** [comment]
Sorry - I don't think I've seen that behavior before.

**Comment by rkeithhill** [comment]
Yeah, it's really kind of weird, not easy to repro and probably going to be hard to debug.  Lucky me.  :-)

**Comment by rkeithhill** [comment]
@lzybkr @daviwil I can repo this by using the PowerShell extensions new ability to attach to PowerShell host processes.  After disconnecting I notice that git stdout is incorrectly getting routed to stderr.

@dahlbyk I believe this is corner case enough that it shouldn't hold up 0.7.0.  In fact, it is very likely there is nothing posh-git can do to fix this.

**Comment by dahlbyk** [comment]
> I believe this is corner case enough that it shouldn't hold up 0.7.0. In fact, it is very likely there is nothing posh-git can do about this.

👍 Closing until we can confirm this is our fault.
