### ISSUE TITLE
Display not working worktree folder

### ISSUE THREAD

**Issue by skeept** [dahlbyk/posh-git#407]
### System Details

- posh-git version: 0.7.0
- PowerShell version: 4.0
- git version 2.11.1.windows.1
- OS: Microsoft Windows NT 6.1.7601 Service Pack 1

### Issue Description

When in a worktree usually shown information is not displayed (it just behaves as if the current folder was not under git)

**Comment by rkeithhill** [comment]
I see the issue. I have it fixed by tonight.

**Comment by rkeithhill** [comment]
@dahlbyk For this I can read the contents of the .git file but I'm thinking I shouldn't rely on that implementation detail but use `git rev-parse --git-dir` instead.

**Comment by rkeithhill** [comment]
@skeept Can you try this fix - https://github.com/dahlbyk/posh-git/pull/408

**Comment by skeept** [comment]
@rkeithhill I tried it and it works fine. Thank you.
