### ISSUE TITLE
Posh-Git prompt just won't show up

### ISSUE THREAD

**Issue by isochronous** [dahlbyk/posh-git#409]
### System Details

- posh-git version: 0.6.1.20160330
- PowerShell version: 5.1.14393.693
- git version 2.11.1.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

I've been using Posh-Git for years, have successfully set it up on several machines, and have helped many others do the same... but today I've run into a problem I've not been able to get around: the posh-git prompt just does not show up.

First off, I have my execution policy set to unrestricted.

I installed posh-git via Install-Module, added `Import-Module posh-git` to my PS profile, and upon opening powershell and navigating to my project dir (which is, of course, a fully-initialized git repo), I still get the same prompt as always -- "PS [current path]>".

I tried installing posh-git via chocolatey instead, and got the exact same results.  I even copied the full "check for posh-git, import if present, install and then import if not" logic from your example profile ps1 script, but no dice.  I even installed the Github Desktop client, and its Powershell git shell, which has always had posh-git worked flawlessly for me in the past, gives me the standard powershell prompt.

 I've even navigated directly to the Appdata\local\Github\posh-git<some guid> folder and executed the GitPrompt.ps1 file that's there, and upon navigating back to my repo folder, same unenhanced prompt.

At this point I'm rather at a loss.  Oh, and the Add-PoshGitToProfile command that's referenced several times in this repo's readme doesn't seem to exists either. I have no idea if that's related, but I figured I'd mention it.  The $GitPromptSettings object also tells me it has no property called DefaultPromptSuffix, which is either a pretty glaring error in the readme or another symptom of my problem.

Anyone have any ideas?

**Comment by isochronous** [comment]
Okay, so I went to the posh-git installation folder (in My Documents\WindowsPowershell\Modules) and ran the install.ps1 script there, and now everything is working just perfectly.  I've no idea why it works when nothing else did, but as long as it's working, that's all I care about.

**Comment by rkeithhill** [comment]
That install script modifies your PowerShell profile to dot source profile.example.ps1.  That is what overrides the default PowerShell prompt with one that display status summary info.  

When we release 0.7.0 and you update to it, you should remove the line that dot sources profile.example.ps1 and replace it with the line `Import-Module posh-git`.

**Comment by isochronous** [comment]
Well, I guess I'm just curious why the install.ps1 script wasn't run on installation.  Neither the Install-Module nor the nuget installation gave me any errors on install.  In addition, the readme on this repo makes no mention of having to run the script yourself.  I also have no idea why I was unable to run Add-PoshGitToProfile myself (after having Imported the Posh-git module) but running it through install.ps1 worked fine.

It just seems like the readme for this repo is a little out-of-sync with the state of the code, as it indicates that one can already get posh-git working by just adding `Import posh-git` to one's powershell profile, which obviously is not the case, and it refers to at least one property on the $GitProfileSettings object that doesn't, according to powershell's property list, exist.

**Comment by rkeithhill** [comment]
Only the Chocolatey install runs the install.ps1 script.  PowerShellGet's `Install-Module` **only** downloads and unzips.  It has no hooks for running scripts.  This is why we've expended quite a bit of effort for 0.7.0 to not need an install script.  You would simply execute:
```
Import-Module posh-git -Scope CurrentUser
Add-PoshGitToProfile
```
and you're set.

> seems like the readme for this repo is a little out-of-sync with the state of the code

Yup, that is what happens when there is active development happening on the master branch.  :-)   The README.md got updated at a time when I thought we were close to releasing.  As is the case with a lot of software development, this release has taken longer than originally anticipated.

**Comment by isochronous** [comment]
I don't mean to be critical, as this is a supremely useful bit of software that's being maintained for free, but having inaccurate docs is a rather bad thing.  Surely it's not too difficult to create a new branch to preserve the readme updates, and then revert the master readme back to the actual, accurate version?  I'd offer to do it myself, but those aren't the kind of changes easy to make via pull requests.

**Comment by rkeithhill** [comment]
Not worth it at this point.  We're shooting for early next week to release.  But for 1.0.0, we'll definitely look into doing that work on `develop` branch.

**Comment by isochronous** [comment]
Gotcha.  I guess I just had bad timing.  Early congrats on that 1.0.0 release!

**Comment by JoshMcCullough** [comment]
I was following the README on the `master` branch, thinking "maybe this is not current" when things weren't working. Apparently that is true, and v.7 work is not in the `release-v0.7.0` branch? This was confusing for me. So, path forward for pre v.7?

**Comment by rkeithhill** [comment]
Yeah, README reflects tip of master - current development of 0.7.0.  This should be rectified early by next week when we release 0.7.0 (unless we find a showstopper bug).  

In the meantime, you can clone this repo and try out 0.7.0 (on master) or you can use Chocolatey to install a pre-release of 0.7.0.  Unfortunately the PowerShell Gallery doesn't support prereleases at this time.

If you clone, execute `Import-Module <path-to-clone-dir>\src\posh-git.psd1` after cloning.  If you've never configured posh-git in your profile before, then run `Add-PoshGitToProfile`.  

FWIW we would love to get more folks testing prerelease bits.

**Comment by isochronous** [comment]
I tried running the Add-PoshGitToProfile command after installing posh-git, first via powershell 5 and then via nuget, and got an error saying that wasn't a recognized command or script.  This was after adding the import module to my powershell profile and restarting the console, too.  I even installed the -pre version of the nuget package and got the same result.  If it's not something that gets added to the path, mentioning its location would be helpful.

**Comment by rkeithhill** [comment]
> after successfully installing posh-git, first via powershell 5 

PowerShell Gallery does not have a prerelease of 0.7.0 yet because PowerShell Gallery does not support publishing/distributing prerelease pkgs.  What version of posh-git do you have loaded (`get-module posh-git`)?   If it is 0.6.1.20160330, that is the old version which doesn't support the new command (or the new prompt settings).

> I even installed the -pre version of the nuget package 

So you installed using Chocolatey  `choco install poshgit -pre`?  If so, it should have taken care of modifying your profile to import posh-git.  See issue #350

BTW you can always wait until next week and hopefully by then we will have published 0.7.0 to the PowerShell Gallery.  :-)

**Comment by isochronous** [comment]
Whatever version was listed in the original issue is the one that's
installed... And yeah, I meant chocolatey, not nuget :P

**Comment by dahlbyk** [comment]
We really just need to get 0.7.0 out ASAP. The old Chocolatey versions in particular are a challenge because they always download `master` instead of a specific version of the code. As `master` has progressed, the old installers get less and less likely to work. ☹️

**Comment by geekgurl-muraco** [comment]
eeeek and all this for a newby - eek - all I can see is the directions don't fit the task. UGH makes learning very difficult. Thank you to all for letting me know it wasn't me. (I was wondering where posh git was as I watching the MS Virtual Academy lesson on GitHub and it mentioned the Posh Git.

**Comment by dahlbyk** [comment]
@geekgurl-muraco the directions should be better now than a few months ago, with 0.7 having been released. If you run into issues, or have suggestions on how we can improve, please let us know!
