### ISSUE TITLE
SuppressMessage not availabe on V2

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#414]
### System Details

- posh-git version: 0.7.0-pre
- PowerShell version: 2.0
- Git version: 2.11.0.windows.1
- Operating system name and version: Windows 7

### Issue Description

Get this error on PS v2:

![image](https://cloud.githubusercontent.com/assets/5177512/22914185/6f7036ce-f22c-11e6-8ba0-71a6794148ba.png)

**Comment by dahlbyk** [comment]
Fixed by #415
