### ISSUE TITLE
Track Code Coverage (Coveralls.io)

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#416]
To get coverage data from Pester:

```powershell
cd test
Invoke-Pester -CodeCoverage (gci ..\src\* -include *.ps1,*.psm1)
```

For starters, here's the PowerShell script that pushes to Coveralls.io for PowerShell/PowerShell:
https://github.com/PowerShell/PowerShell/tree/a042dc1ff1db71e4baede19d9eedf47e0004587c/test/tools/CodeCoverageAutomation

**Comment by JanJoris** [comment]
I managed to do this for my own repo, I just need to make a module from that code and it's good to go. You can see the result [here](https://coveralls.io/github/JanJoris/oh-my-posh)

The PS script used by PowerShell/PowerShell isn't useable as it works with OpenCover to check the powershell.exe coverage and not powershell written file coverage.

Can I assume you want to use the wildcard `gci ..\src\* -include *.ps1,*.psm1` to fetch the files which need to be included in the coverage results?

Expect a PR this week to tackle this one.

**Comment by dahlbyk** [comment]
Yeah, those are the right files.

> Expect a PR this week to tackle this one.

Awesome!

**Comment by JanJoris** [comment]
@dahlbyk I've used my [module](https://www.powershellgallery.com/packages/coveralls) on posh-git using the info you provided which results in [this](https://coveralls.io/github/JanJoris/posh-git) on Coveralls. Can you let me know if this feels allright? If so, I'll create a PR (it's super easy, really)

**Comment by JanJoris** [comment]
I found an issue with my module when Pester is ran outside of the repository's root folder. In that case I the paths come out wrong and Coveralls can't link the files. A fix is currently building, I'll push new data to Coveralls as soon as it's live.

**Comment by JanJoris** [comment]
The [second](https://coveralls.io/github/JanJoris/posh-git) "build run" now has the links to the files. I'll be waiting for your review.
