### ISSUE TITLE
Question: How to uninstall posh-git ?

### ISSUE THREAD

**Issue by Exocomp** [dahlbyk/posh-git#417]
Hi,

In the case were you no longer require posh-git, how does one go about uninstalling it ?

Thanks,
E

**Comment by rkeithhill** [comment]
It depends on how you installed it.  If you used Chocolatey, I think the command would be `choco uninstall poshgit`.  If you used `Install-Module` (PowerShellGet), then use `Uninstall-Module posh-git`.

**Comment by Exocomp** [comment]
hmm, appears I just ran .\install.ps1

**Comment by rkeithhill** [comment]
In that case, remove the folder containing the install.ps1 file.  Edit your profile by executing `notepad $profile`, remove any lines that refer to posh-git or `profile.example.ps1`.  If there are no lines in this file, then check `notepad $profile.CurrentUserAllHosts` and remove those lines from this file.

**Comment by Exocomp** [comment]
hmm, Uninstall-Module posh-git, throws this error:

`PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'posh-git'`

**Comment by rkeithhill** [comment]
So, you didn't install with `Install-Module`.  Did you install using Chocolatey?  Or did you git clone this repo?

**Comment by Exocomp** [comment]
Here is a screenshot of what I did:

![posh-git-install](https://cloud.githubusercontent.com/assets/25571083/22938518/9724cb7e-f2a1-11e6-981f-7569805afdc7.jpg)

**Comment by Exocomp** [comment]
There was an entry in the profile ($profile) to posh-git and I removed it.  Since Uninstall-Module posh-git is failing, can you tell me how I can verify it is uninstalled ? :)

**Comment by rkeithhill** [comment]
Delete the file `C:\Users\Exocomp\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` and remove the `R:\posh-git` folder (unless that's a shared folder other folks use).

To verify it is uninstalled from PowerShell's perspective, run `Get-Module -ListAvailable posh-git`.  That should return nothing.

So you set your execution policy back to `Restricted`? I take it you don't normally run PowerShell scripts or modules?

**Comment by Exocomp** [comment]
Lately I have been using Powershell quite a bit with managing a few servers and in TeamCity for my CI server, I normally change the policy and run the scripts I need and go back to restricted, I'm a bit paranoid when it comes to security.  However, I don't call my self a powershell guru by any means, :)

Anyway, nothing wrong with posh-git it is just that I got used to gitbash and I thought I'd try posh-git.

The command "Get-Module -ListAvailable posh-git" returns nothing.  But I don't understand how I was using posh-git and then have it disappear.  See pic here where it was working:

![post-get-2](https://cloud.githubusercontent.com/assets/25571083/22938959/f1ec8884-f2a2-11e6-98c9-9fbcaefcc8c6.jpg)

Any other ideas or should just consider this done and move on? :)

**Comment by rkeithhill** [comment]
It was working because you profile was likely dot sourcing (including) the profile.example.ps1 file.  That file overrides PowerShell's prompt function to display Git status summary information.  When you removed that from your profile, your prompt is no longer being overridden when PowerShell starts.

**Comment by Exocomp** [comment]
Ok, so what your telling me is it was never installed on the system to being with, it was just loading the profile and importing the module from git repo for that session ?

**Comment by rkeithhill** [comment]
That is what I suspect but it's hard for me to say for sure.  It appears that posh-git is located on your `R:` drive.  Is that a network share?  How did the posh-git bits get to be in `R:\posh-git`?

**Comment by Exocomp** [comment]
Appears I cloned it.

![posh-git-3](https://cloud.githubusercontent.com/assets/25571083/22940500/b21ca3f6-f2a7-11e6-9d5b-e626d2ba670c.jpg)

It is a temporary drive.  I think it is just my confusion so basically I thought that by calling install.ps1 it installed it on the machine but all it did was update the profile and load it from R:/posh-git for every session.  That makes sense to me.  If that make sense to you then I can move one.  What say you? :)

**Comment by rkeithhill** [comment]
> all it did was update the profile and load it from R:/posh-git for every session

That is correct.

**Comment by Exocomp** [comment]
Excellent, thanks for your assistance!

**Comment by frvo** [comment]
get-module posh-git | remove-module

**Comment by redteamsoft** [comment]
> get-module posh-git | eliminar-módulo
funciono gracias

**Comment by tsullyman** [comment]
I just ran $env:PSMODULEPATH to get my onedrive path, deleted the module and powershell folder from that onedrive path and that fixed it. Issue is using -Scope currentuser when installing it and it goes to onedrive files on demand. Terrible from MS to not give it rights to uninstall cleanly in powershell. I also tried the 3+ versions of powershellget to no avail. erghhhhhhhhhhhhhhhh
