### ISSUE TITLE
why not adopt cmdlet?

### ISSUE THREAD

**Issue by chantisnake** [dahlbyk/posh-git#419]
I think powershell cmdlet are pretty great, why don't you guy adopt it, and still uses functions?

**Comment by rkeithhill** [comment]
There are other projects that attempt to do that.  Checkout [PSGit](https://github.com/PoshCode/PSGit)  This project is for folks who want to use git.exe but would like tab completion and a helpful Git prompt.

**Comment by dahlbyk** [comment]
Before PSGit, this idea was discussed in depth over in https://github.com/dahlbyk/posh-git/issues/97.
