### ISSUE TITLE
OSX prompt suffix showed two times

### ISSUE THREAD

**Issue by neman** [dahlbyk/posh-git#426]
### System Details

- posh-git version: 0.7.0
- PowerShell version: 6.0.0-alpha.16
- Git version: 2.10.1
- Operating system name and version: OSX Sierra 10.12.3

### Issue Description

I have installed Powershell to OSX using `powershell-6.0.0-alpha.16.pkg` from the following link https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.16

After that, I have installed posh-git using command `PowerShellGet\Install-Module posh-git -Scope CurrentUser`

I have imported posh-git module using `Import-Module posh-git` command

I have created simple repo using `git init` and committed initial branch.

As you can see, i have two prompt information.
![screenshot_001](https://cloud.githubusercontent.com/assets/350314/23093569/a4c807de-f5e7-11e6-81f7-5fc9d01803ee.png)
And when I start typing, terminal does not show first one, as you can see onthe secon screen shot.
![screenshot_002](https://cloud.githubusercontent.com/assets/350314/23093585/f8f819de-f5e7-11e6-97a8-ac72a1118e62.png)
And this is the result when I hit enter
![screenshot_003](https://cloud.githubusercontent.com/assets/350314/23093594/278fde58-f5e8-11e6-824f-74a598e72b0f.png)

Is this some issue with powershell or posh-git?

`$GitPromptSettings.DefaultPromptSuffix` showed `$('>' * ($nestedPromptLevel + 1)) `

**Comment by dahlbyk** [comment]
Is this the 4th bullet on #302?

**Comment by rkeithhill** [comment]
Yeah, this is ultimately a PSReadLine problem being tracked [here](https://github.com/lzybkr/PSReadLine/issues/468).  You can work around this by removing PSReadLine but man it's painful to use PowerShell without PSReadLine.

**Comment by rkeithhill** [comment]
Closing this as it is a PowerShell/PSReadLine issue.
