### ISSUE TITLE
MIssing update-index from tab completion

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#443]
### System Details

- posh-git version/path: 0.7.0  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.0
- PowerShell version: 5.1.14393.693
- git version 2.11.1.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

Tab completion is not tab-completing the command `update-index`.

**Comment by dahlbyk** [comment]
`update-index` is not considered a "porcelain" command, so I would suggest we not complete it by default. It completes correctly with `$GitTabSettings.AllCommands = $true`.

**Comment by rkeithhill** [comment]
Ya know, by the third time you tell me this I'm hoping I'll remember it.  :-)
