### ISSUE TITLE
Install throws an exception

### ISSUE THREAD

**Issue by andrewducker** [dahlbyk/posh-git#448]
### System Details

- posh-git version/path: 0.7.1.0 pre0 C:\zzzz\posh-git-master\src
- PowerShell version: 4
- Git version: 2.8.1.windows.1
- Operating system name and version: 6.1.7601.65536

### Issue Description

I am experiencing a problem with...
The install.ps1 file throws an exception:
```
Unable to find type [System.Management.Automation.SignatureType]. Make sure that the assembly that contains this type is loaded.
At C:\zzzz\posh-git-master\src\Utils.ps1:164 char:13
+         if ($sig.SignatureType -eq [System.Management.Automation.SignatureType]: ...
```

**Comment by dahlbyk** [comment]
Fascinating... What does this give you?

```powershell
Get-AuthenticodeSignature $PROFILE | Format-List
```

**Comment by rkeithhill** [comment]
Doh!  That's my bug.  I had checked for `SignatureStatus` on v2 but not `SignatureType`.  Apparently that is is new in PS v5.  I'll submit a PR for this later tonight.

**Comment by rkeithhill** [comment]
@andrewducker When you get a chance, can you verify the fix?  Thanks.

**Comment by andrewducker** [comment]
Yup, worked fine.  Thanks!
