### ISSUE TITLE
git rm tab completion issues

### ISSUE THREAD

**Issue by taylorc** [dahlbyk/posh-git#45]
Running the command git rm <tab> no longer tabs through files to be deleted

For instance
deleted /FolderA/fileA
deleted /FolderA/fileB
deleted /FolderB/fileA

git rm <tab> used to give 
git rm /FolderA/fileA --first tab
git rm /FolderA/fileB --secondtab

now it gives 
git rm ./FolderA -- first tab
git rm ./FolderB -- second tab

**Comment by snowe2010** [comment]
I'm getting this exact same problem, though it occurs with any file completion. The files once completed but now they don't. 

```
λ ~\Drop\Tyle\pers\proj\root\rewrite git status -sb
## master
M  app.coffee
R  assets/css/master.css.styl -> assets/css/header.css.styl
M  assets/css/master.css.styl
A  "assets/img/kaboompics.com_Boats on the river.jpg"
A  "assets/img/kaboompics.com_Girl sitting on the boat.jpg"
M  assets/js/main.coffee
M  views/header.jade
?? assets/img/pexels-photo.jpg
?? ps/
?? ps2DA0.tmp
?? ps49C1.tmp
λ ~\Drop\Tyle\pers\proj\root\rewrite $GitStatus.Working
λ ~\Drop\Tyle\pers\proj\root\rewrite echo $GitStatus.Working
```

I think I was dumping $GitStatus.Working correctly there, but as you see nothing was output.

**Comment by dahlbyk** [comment]
I can't reproduce either of these... I'm going to go ahead and close, but if anyone is still struggling to get tab completion to work for `rm` please leave any details you can.
