### ISSUE TITLE
Play Nice with VMWare PowerCLI 6.5

### ISSUE THREAD

**Issue by admoseley** [dahlbyk/posh-git#465]
### System Details

- posh-git version/path: 0.7.1  C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src
- PowerShell version: 5.1.14393.693
- git version 2.12.0.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

I am experiencing a problem with...
Running Posh-git with VMWare PowerCLI6.5
I would like to autostart both of these modules as I update scripts that work with vSphere. However, everytime i initialize the PowerCLI modules, it wipes the Posh-Git Prompt.

Before with posh-git loaded:
C:\Users\username\dev\script [master ≡]>

After I initialize PowerCLI
i've tried 

.'C:\Program Files (x86)\VMware\Infrastructure\PowerCLI\Scripts\Initialize-PowerCLIEnvironment.ps1'
Gives me: PowerCLI C:\> 
and 
Import-module vmware.vimautomation.core
Gives me: C:\>

This also occurs if i reverse the order and Load PowerCLI first and Posh-git second.

**Comment by dahlbyk** [comment]
Try importing posh-git after VMWare PowerCLI specifying module arguments (specifically, the second should force setting `prompt`):

```
Import-Module C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src\posh-git.psd1 -ArgumentList $true,$true
```

**Comment by admoseley** [comment]
works perfectly. thanks!
