### ISSUE TITLE
Write-Prompt 0.7.1 from PSGallery does not allow -ForegroundColor Black

### ISSUE THREAD

**Issue by ayrtonmassey** [dahlbyk/posh-git#470]
### System Details

- posh-git version/path: `0.7.1` **from the PowerShell Gallery**.
- PowerShell version: `5.1.14393.1198`
- Git version:  `2.7.1.windows.2`
- Operating system name and version: 
  - Edition: `Windows 10 Enterprise`
  - Version: `1607` 
  - Build: `14393.1198`

### Issue Description

`Write-Prompt` checks to see if the `$ForegroundColor` parameter is empty by performing the check `!$ForegroundColor`. This works in all cases except when `$ForegroundColor` is `[ConsoleColor]::Black`, since `Black` evaluates to `0` and `!0 == True`.

The offending line is [posh-git/src/GitPrompt.ps1:135](https://github.com/dahlbyk/posh-git/blob/master/src/GitPrompt.ps1#L135):
```posh
function Write-Prompt($Object, $ForegroundColor = $null, $BackgroundColor = $null) {
    $s = $global:GitPromptSettings
    if ($s -and !$ForegroundColor) {
        $ForegroundColor = $s.DefaultForegroundColor
    }
```

I see that this was fixed by #454 on GitHub (the condition is now `($null -eq $ForegroundColor)`) but the copy I obtained from PSGallery via `Install-Module` earlier today does not have this fix.

**Comment by dahlbyk** [comment]
This was actually fixed by https://github.com/dahlbyk/posh-git/pull/468, which has not been released yet. I'll try to make that happen :soon:

**Comment by bergmeister** [comment]
@dahlbyk When is 0.7.2 getting released?

**Comment by dahlbyk** [comment]
> When is 0.7.2 getting released?

Probably next week while I'm off work. 🎄

**Comment by dahlbyk** [comment]
https://www.powershellgallery.com/packages/posh-git/0.7.2-pre1 is available now; the release will be finalized soon. Sorry for the delay!
