### ISSUE TITLE
onpolicy

### ISSUE THREAD

**Issue by hogbinj** [dahlbyk/posh-git#471]
### System Details

- posh-git version/path:
- PowerShell version:
- Git version:
- Operating system name and version:

### Issue Description

I am experiencing a problem with...

**Comment by rkeithhill** [comment]
What issue you are encountering?

**Comment by hogbinj** [comment]
Apologies.  No clue how that happened

Have just changed my passwords/MFA in case I was hacked

J/.

James Hogbin
Director 
 
IP Sentinel 
t. 01825 701 870
m. +44 7786910895
w. http://ip-sentinel.com
