### ISSUE TITLE
Provide DefaultPromptPrefixColor and DefaultPromptSuffixColor options

### ISSUE THREAD

**Issue by ryanewtaylor** [dahlbyk/posh-git#474]
### System Details

- posh-git version/path: 0.7.1  C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src
- PowerShell version: 5.1.15063.296
- git version 2.13.0.windows.1
- OS: Microsoft Windows NT 10.0.15063.0

### Issue Description

I would like to be able to easily customize the default prompt prefix and suffix colors independently from each other and the default foreground color. Perhaps this could be provided with DefaultPromptPrefixColor and DefaultPromptSuffixColor properties in $GitPromptSettings?

In prior versions I overrode the prompt function to accomplish this, however, it would be very nice to be able to change these colors without needing to override the prompt function via the enhanced $GitPromptSettings properties.

**Comment by dahlbyk** [comment]
Give https://github.com/dahlbyk/posh-git/pull/520 a try?
![image](https://user-images.githubusercontent.com/133987/34754476-9bb57928-f583-11e7-80d7-f156c300a359.png)
