### ISSUE TITLE
EnablePromptStatus should not affect Get-GitStatus

### ISSUE THREAD

**Issue by jpludens** [dahlbyk/posh-git#475]
### System Details

- posh-git version/path: 0.7.1  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.1
- PowerShell version: 5.1.14393.1198
- git version 2.10.0.windows.1
- OS: Microsoft Windows NT 10.0.14393.0

### Issue Description

I have a use case which needs to disable the command prompt status while still using the Get-GitStatus function. Disabling the prompt is easy: set GitPromptSettings.EnablePromptStatus to false. But, Get-GitStatus also checks that setting, making the command ineffective.

If this coupling is not intentional, I propose adding a separate setting, such as EnableGetStatus or EnableGetGitStatus, so that these pieces of functionality can be managed separately.

If it is intentional, a simple enough workaround is wrapping Get-GitStatus with a function that temporarily changes the GitPromptSettings.

**Comment by dahlbyk** [comment]
The `EnablePromptStatus` check living in `Get-GitStatus` is an artifact of decisions made a few years ago, but I'm hesitant to change it now to avoid breaking customized `prompt` functions.

Would it work for you if we added `-Force` option to `Get-GitStatus` that would override `EnablePromptStatus`?

**Comment by jpludens** [comment]
Yeah, that would certainly get the job done. Thank you!

**Comment by dahlbyk** [comment]
> @rkeithhill self-assigned this

Did you start on this?

**Comment by rkeithhill** [comment]
I looked at it and was starting to come to the same conclusion you had - nervous about the change.  Unfortunately, it affects all the new `Write-Git*Status` commands because they need a status object to operate on.

**Comment by rkeithhill** [comment]
That said, I'm OK punting on this for the first beta.

**Comment by dahlbyk** [comment]
> Would it work for you if we added `-Force` option to Get-GitStatus that would override `EnablePromptStatus`?

Let's just do this. It can easily target v0.x and be pulled into v1.

**Comment by rkeithhill** [comment]
I have a fix for this.  Waiting on PR #533.

**Comment by rkeithhill** [comment]
This is fixed in the upcoming 1.0.0-beta2.
