### ISSUE TITLE
Ssh-Agent.exe inherits handles from calling powershell process

### ISSUE THREAD

**Issue by SteveBenz** [dahlbyk/posh-git#476]
### System Details

- posh-git version/path: 0.0  C:\Program Files (x86)\Poshgit
- PowerShell version: 5.1.16231.1000
- git version 2.12.2.gvfs.2.23.g7ceb83e
- OS: Microsoft Windows NT 10.0.16231.0
### Issue Description

If ssh-agent is not currently running, and you invoke powershell with Posh-Git installed and you do it in such a way that it waits for the handles to close, e.g.

for /F "tokens=*" %I in ('powershell -command Get-Date') do set d=%%I

Then you'll find that statement hangs indefinitely.

It does so because Post-Git launches ssh-agent, which inherits process handles from its parent, and ssh-agent survives the end of the powershell script.

The offending line is 486 of GitUtils.ps1.  I'm not much good at powershell, but this change will fix it:

```
< & $sshAgent | ForEach-Object {
> cmd /c "$sshAgent 2>&1 < nul:" | foreach {
```

I'll grant that the "for..." statement I wrote was already wrong.  It should be invoking powershell with "-NoProfile", but when somebody forgets that, the penalty shouldn't be so awful.

**Comment by rkeithhill** [comment]
@JeremySkinner Do you have perms to move this issue to the posh-sshell project?

**Comment by JeremySkinner** [comment]
@rkeithhill no I don't, sorry

**Comment by rkeithhill** [comment]
@SteveBenz If this is still an issue with the new `posh-sshell` module please submit this issue to that project - https://github.com/dahlbyk/posh-sshell.

**Comment by SteveBenz** [comment]
If it's not gonna get any more attention there than here, then no, sorry, not gonna waste my time.

**Comment by JeremySkinner** [comment]
@SteveBenz the ssh functionality was moved out of posh-git and into posh-sshell (https://github.com/dahlbyk/posh-sshell) precisely so that it can be maintained and supported separately from the git functionality. So if this is still an issue with the latest posh-sshell bits then please let me know and I will take a look at it.
