### ISSUE TITLE
Get-GitStatus properties?

### ISSUE THREAD

**Issue by mwoffenden** [dahlbyk/posh-git#481]
I'm working on some code that I wrote a while ago.  I can't remember how I see the "intellisense" to show the return values.  I'm using VisualStudio 2017.

For example:

```
$myGitStatus = Get-GitStatus
$behindByCommits = $myGitStatus.BehindBy
```

How do I see the _other_ valid properties of Get-GitStatus?

**Comment by rkeithhill** [comment]
In PowerShell run `Get-GitStatus | Get-Member`. That will show all the properties on the returned object.

**Comment by mwoffenden** [comment]
Great, I'll give that a try!

**Comment by dahlbyk** [comment]
Do let us know if you have any other questions, but closing since this does not seem to be an actual issue.
