### ISSUE TITLE
Prompt 

### ISSUE THREAD

**Issue by dennisdoomen** [dahlbyk/posh-git#482]
### System Details

- posh-git version/path: 0.7.1  C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src
- PowerShell version: 5.1.15063.447
- git version 2.12.1.windows.1
- OS: Microsoft Windows NT 10.0.15063.0

### Issue Description

After upgrading to Poshgit 7.1 from 6.x, I ran into some problems and uninstalled it using Chocolatey and removed all remnants from my Powershell profiles. I then installed it using:

`PowerShellGet\Install-Module posh-git -Scope CurrentUser`

Everything installed, but still don't get a prompt. I even tried to add the example prompt function from your wiki into my profile.ps1, but nothing happens. Running `Add-PoshGitToProfile` gives me this:

```
WARNING: Skipping add of posh-git import to file 'C:\Users\dennisd\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
WARNING: posh-git appears to already be imported in one of your profile scripts.
WARNING: If you want to force the add, use the -Force parameter.
```

Running `Get-GitStatus` gives me:

```
HasWorking   : False
Branch       : CrossCompile
AheadBy      : 0
Working      : {}
Upstream     : origin/CrossCompile
StashCount   : 0
Index        : {}
HasIndex     : False
BehindBy     : 0
HasUntracked : False
UpstreamGone : False
GitDir       : C:\Workspaces\fluentassertions\.git
```

**Comment by rkeithhill** [comment]
What is the output of:
```posh
gmo posh-git | ft Version,Path
```
Also, it appears you're using PowerShellGet to install the module but the path you list before that appears to be a chocolatey path.  Which are you using to install posh-git?

Also, can you list the relevant bits of `C:\Users\dennisd\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` here?

**Comment by dennisdoomen** [comment]
This is in that profile:

```
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}

Import-Module 'C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src\posh-git.psd1'

function prompt {
    "PS $($ExecutionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
}
```

This is result of running the requested statement:

```
Version Path
------- ----
0.7.1   C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src\posh-git.psm1
```

0.6.x was installed through Chocolatey, but after upgrading my Posh-Git prompt was gone. That's why I uninstalled it and tried the steps from your repo's readme.

**Comment by rkeithhill** [comment]
OK, so you are loading the posh-git installed via chocolatey.  That's fine.  I recommend that you remove the prompt function definition in that profile and then restart PowerShell.  

Posh-git will configure your prompt function when it is `imported`.  Your profile whacks that posh-git prompt with a new prompt function that doesn't display Git status info.

**Comment by dennisdoomen** [comment]
I just added that prompt to see if that fixes the problem. Your release notes mentioned something about 0.7.0 about not adding a default prompt anymore.

**Comment by rkeithhill** [comment]
We don't add a prompt function to **your profile** anymore in 0.7.x.  That's because if you have a prompt function in your profile, you typically want **that** customized prompt function.  However, when you execute `Import-Module posh-git` and it see's that the prompt function is the generic one provided by PowerShell, the posh-git module will then create a prompt function that displays git status.

BTW you left this line `Import-Module 'C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src\posh-git.psd1` in the profile, right?

If you have no custom prompt function defined in **any of your profiles** and you have imported posh-git and that directory is in a git repo, you should be seeing git status info in the prompt.  

What is the output of these two commands?
```posh
gcm prompt | % definition
[Runspace]::DefaultRunspace.InitialSessionState.Commands['prompt'].Definition
```

**Comment by dennisdoomen** [comment]
I couldn't find any prompt anywhere.

Running `gcm prompt \| % definition` gives:

```
Update-ZLocation $pwd

"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
# .Link
# https://go.microsoft.com/fwlink/?LinkID=225750
# .ExternalHelp System.Management.Automation.dll-help.xml
```

Running `[Runspace]::DefaultRunspace.InitialSessionState.Commands['prompt'].Definition` gives:

```
"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
# .Link
# https://go.microsoft.com/fwlink/?LinkID=225750
# .ExternalHelp System.Management.Automation.dll-help.xml
```

**Comment by dahlbyk** [comment]
Does `Get-Module posh-git` show that it's loaded? Try `Add-PoshGitToProfile` again - it didn't install before because your `$PROFILE` seems to have already had posh-git installed. If you get that warning again with a clean `$PROFILE`, I would be very curious to know what's causing the false-positive.

**Comment by dennisdoomen** [comment]
I removed the existing import from my `C:\Users\dennisd\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`, ran `Add-PoshGitToProfile`, restarted my PowerShell, and then ran `Get-Module posh-git`: 

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.7.1      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, Get-AliasPattern...}
```

Still no prompt...

**Comment by dahlbyk** [comment]
* Did `Add-PoshGitToProfile` report success?
* Did you get any warnings? 
* I assume `gcm prompt | % definition` reports the same thing it used to?

**Comment by rkeithhill** [comment]
Also, when you reported the output of those two commands, one was a bit different.  It had an extra couple of lines:
```
Update-ZLocation $pwd

```
Was that a copy/paste error?  If not, then another module could be updating your prompt function.

Basically, if the output from these two commands is not exactly the same then posh-git assumes you have customized your prompt function and therefore, will **not** modify it.  

You can force posh-git to create its prompt function by modifying the import command in your profile to this:
```
Import-Module posh-git -Arg $false,$true
```
Then make sure you are in a directory that is part of a Git repo and you should see the posh-git prompt:
```
C:\Users\Keith\Git\test [master]>
```

**Comment by dennisdoomen** [comment]
So I suspect ZLocation is getting in the way. It tracks the current folder and allows you to quickly jump to a previous folder using `z` instead of `cd`. What should be prompt definition be?

**Comment by dahlbyk** [comment]
> What should be prompt definition be?

Long. https://github.com/dahlbyk/posh-git/blob/9b6ee1cb5f178e80b9b0aa69ca85196e0f487c5c/src/posh-git.psm1#L57-L117

The posh-git module won't replace `prompt` unless it's still the default value, so if ZLocation is providing its own `prompt` then posh-git's won't load.

Does your `$PROFILE` define that updated `prompt`, or is that handled automatically by ZLocation? You might try importing posh-git before ZLocation?

**Comment by rkeithhill** [comment]
Let's do a quick test to see if that is the case.  Press <kbd>Win+r</kbd> and enter `powershell.exe -noprofile`.  When that PowerShell session starts, execute `Import-Module posh-git` then cd to `C:\Workspaces\fluentassertions`.  At this point you see Git status in the prompt.  

If that works, then you can try importing ZLocation **after** posh-git.  Hopefully ZLocation will just prepend it's one command to the start of posh-git prompt.  OTOH if it whacks the posh-git prompt with its own then you will probably need to define a custom prompt function that display's posh-git status and calls the ZLocation command.  You'll have to find out how to prevent ZLocation from whacking the prompt.  For details on how to create a custom posh-git prompt see https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt

**Comment by dennisdoomen** [comment]
You were right. It was ZLocation that was screwing up the prompt before posh-git got a chance. But they were each imported through different profile files. After ensuring ZLocation is imported _after_ posh-git, it started to work. 

Many thanks for all the effort you put in this issue.
