### ISSUE TITLE
Upgrade to Pester 4 

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#485]
Build is breaking at least due to https://github.com/pester/Pester/pull/859 ([example](https://ci.appveyor.com/project/dahlbyk/posh-git/build/0.7.335#L187)).

Workaround: https://github.com/dahlbyk/posh-git/pull/484/commits/3aa739b3911677e29e564137ff0a7dcce3f95007

**Comment by rkeithhill** [comment]
I'll take a look at this tonight.
