### ISSUE TITLE
Prompt colour/color tweak?

### ISSUE THREAD

**Issue by imran-uk** [dahlbyk/posh-git#497]
### System Details

- posh-git version/path: 0.7.1  C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src
- PowerShell version: 5.1.14409.1005
- Git version: git version 2.11.1.windows.1
- Operating system name and version: Microsoft Windows NT 6.3.9600.0

### Issue Description

Is there a way I can tweak some of the colours used? When there are changes in my working directory the prompt status is dark and hard to see.

Screenshot:

![2017-10-02 14_14_20-virtualbox](https://user-images.githubusercontent.com/542530/31079373-4d8803d2-a77d-11e7-945a-56889213fa9c.png)

**Comment by dahlbyk** [comment]
Yes! Edit your `$PROFILE` and set properties on `$GitPromptSettings` after posh-git is imported, e.g.

```powershell
Import-Module posh-git
$GitPromptSettings.LocalWorkingStatusForegroundColor = [ConsoleColor]::Red
$GitPromptSettings.WorkingForegroundColor = [ConsoleColor]::Red
```

A full list of color options is available in [`GitPrompt.ps1`](https://github.com/dahlbyk/posh-git/blob/v0.7.1/src/GitPrompt.ps1#L5-L86).
