### ISSUE TITLE
Rename to pwsh-git?

### ISSUE THREAD

**Issue by felixfbecker** [dahlbyk/posh-git#498]
https://github.com/PowerShell/PowerShell/issues/4214#issuecomment-335989245

**Comment by rkeithhill** [comment]
I don't see a good reason to.  I think `posh-git` is widely recognized and the exe for Windows PowerShell is still powershell.exe.  This change only affects PowerShell Core where we barely have posh-git limping along.  :-)

**Comment by dahlbyk** [comment]
More importantly, calling someone a "pwsh git" doesn't mean anything. 😏

**Comment by lzybkr** [comment]
But it's pronounced "pshaw git", right? 🤷‍♂️

**Comment by SteveL-MSFT** [comment]
Community can/should continue to use `Posh` as nickname for PowerShell.
