### ISSUE TITLE
Write-VcsStatus - configuration to show numbers of branches of the repo?

### ISSUE THREAD

**Issue by ALIENQuake** [dahlbyk/posh-git#503]
Hi,

I would like to see numbers of branches of the current repository:
- when there is only one branch - show nothing instead of 1
- when there is more than one branch - show numbers of branches

is there way to achieve it via configuration?

**Comment by rkeithhill** [comment]
Yes, you can do this by adding the following setting to your profile after you have imported posh-git:
```posh
$GitPromptSettings.DefaultPromptSuffix = '$($cnt = (git branch | measure-object).count; if ($cnt -gt 1) { " $cnt"}) $(">" * ($nestedPromptLevel + 1))'
```
This outputs:
```
C:\Users\Keith\GitHub\dahlbyk\posh-git [rkeithhill/refactor-write-prompt ≡] 9 >
```
The `9` at the end tells me I have nine local branches.  The placement of this value is limited - either it is a DefaultPromptPrefix (put value at very beginning of prompt string) or DefaultPromptSuffix (put value at end of prompt string).

If you need more flexibility than this see the wiki topic - https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt.
