### ISSUE TITLE
git checkout <Tab> tab-completion shows duplicated branch entries for branches that exist also on the remote

### ISSUE THREAD

**Issue by bergmeister** [dahlbyk/posh-git#505]
### System Details

- posh-git version/path: 0.7.1  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.1
- PowerShell version: 5.1.16299.98
- git version 2.15.0.windows.1
- OS: Microsoft Windows NT 10.0.16299.0
- default settings, no customisation of `posh-git`

### Issue Description

Given a Git repo with branch `B1` being locally and on the remote upstream and branch `B2` being only locally and trying to tab complete as follows:
````powershell
git checkout B<Tab>
````

#### Expected Result
Tab completion should show 2 branches to tab complete

`B1 B2`

#### Actual Result

Branches that exist locally and on the remote are shown twice:

`B1 B1 B2`

**Comment by dahlbyk** [comment]
Good catch! If someone wants to take a crack at fixing this, it should be as simple as concatenating [these results](https://github.com/dahlbyk/posh-git/blob/c2a92dda7d11097558f62681de0a1a3989854ba3/src/GitTabExpansion.ps1#L362-L364) and adding a `Sort-Object -Unique`.

**Comment by bergmeister** [comment]
Thanks for the pointer, very helpful. That's exactly how open source should be. :-)
I opened a PR with a fix for it.
