### ISSUE TITLE
Feature Idea: Helper to automatically set upstream

### ISSUE THREAD

**Issue by bergmeister** [dahlbyk/posh-git#508]
Everytime I create a new branch and want to push it, I have to keep setting the upstream although git tells me everytime how to do it.
It would be nice to have a helper of some kind (a function, a git alias or whatever) to set the upstream using the default suggested by git. Let me know what you think.

**Comment by dahlbyk** [comment]
You're looking for the [`-u` option on `git push`](https://stackoverflow.com/questions/5697750/what-exactly-does-the-u-do-git-push-u-origin-master-vs-git-push-origin-ma/5697856#5697856), which will set the upstream branch for you.

I use a `pnb` (push new branch) alias to push the current branch to a branch of the same name with tracking:

`git config --global alias.pnb "push -u origin HEAD"`

On projects with a convention of pushing to branches namespaced by username, I override that alias with:

`git config alias.pnb "!git push -u origin HEAD:dahlbyk/$(git symbolic-ref --short HEAD)"`

------------------

I'm going to go ahead and close this, as this isn't really PowerShell-specific. Let me know if I've misinterpreted your idea.

**Comment by bergmeister** [comment]
Thanks for the input. I found that the following (only tested in `PowerShell`) works nicely as well to push and automatically set the upstream in one go
````powershell
git push -u origin (git rev-parse --abbrev-ref HEAD)
````

**Comment by dahlbyk** [comment]
If `HEAD` isn't a symbolic reference, `git symbolic-ref --short HEAD` fails before the `push`, whereas `git rev-parse --abbrev-ref HEAD` returns `HEAD` and fails during the `push`:

```
error: unable to push to unqualified destination: HEAD
```

As far as I can tell, `git push -u origin HEAD` is essentially identical to yours. I'd probably stick with my `symoblic-ref` version for constructing a different branch name to avoid accidentally pushing to `dahlbyk/HEAD` or whatever.

**Comment by bergmeister** [comment]
Thanks

**Comment by mattack1** [comment]
Since there is "git push --tags", I wish there was the analogous "git push --branch" or something like that... just to _do what I want_.  Personally, I NEVER want a local branch named anything except the exact same thing on the server.

**Comment by dahlbyk** [comment]
@mattack1: try `git push --all`

> Push all branches (i.e. refs under `refs/heads/`); cannot be used with other `<refspec>`.

**Comment by mattack1** [comment]
But again, that's making the normal use case difficult.  I think current SHOULD be the default, and someone who wanted something OTHER than current should be the one to have to do hard to find/learn/use commands.

**Comment by bergmeister** [comment]
Now git will automatically set upstream with this new setting starting in `2.37.0`:
git config --global --add --bool push.autoSetupRemote true`
