### ISSUE TITLE
Auto-Update Upon Opening Powershell (optional)

### ISSUE THREAD

**Issue by jptoto** [dahlbyk/posh-git#55]
Add a parameter and functionality so the user has the option to enable "auto-update" functionality whereby upon opening Powershell, a git pull request will trigger causing the user's posh-git scripts to be updated to the latest version.

**Comment by rkeithhill** [comment]
I think this is probably outside the scope of posh-git and an issue for the PowerShell module ecosystem in general.  On the positive side, if you are using PS v5 you can use `Install-Module posh-git` to install from the PSGallery.  After that,  you can use `Find-Module posh-git` to see what the latest version is.   And you can use `Update-Module posh-git` to update to the latest version.

Even if you are on v3/4, there is a PackageManagement installer that will provide you with these commands.

**Comment by jptoto** [comment]
Wow I didn't even remember opening this issue. And yes, this is now a solved problem.

**Comment by rkeithhill** [comment]
Thanks!
