### ISSUE TITLE
question about how posh-git manages repo

### ISSUE THREAD

**Issue by csurf** [dahlbyk/posh-git#550]
I've found that if I navigate to a particular git repo directory that I normally manage with posh-git using a cygwin terminal, and do 'git status', it'll show the working as completely modified. OTOH, posh-git will show it as clean.

Are there differences in the way posh-git manages a repo internally that cause it to break compatibility with trying to use git in a non-posh-git environment/terminal?

**Comment by rkeithhill** [comment]
It is possible that git under Cygwin sees the repo as modified because on the Windows side, git has modified the line-endings of each file from LF to CRLF?

**Comment by csurf** [comment]
how would I verify this and/or fix this? I don't want posh-git changing my line endings...

**Comment by csurf** [comment]
ok, apologies, found the fix...
I had to set the following in cygwin terminal, since its version of git had a different default config:

`git config --global core.autocrlf true`
