### ISSUE TITLE
Feature request:   Powershell object output

### ISSUE THREAD

**Issue by nebosite** [dahlbyk/posh-git#551]
I am currently writing some powershell scripts to facilitate a certain git workflow.   It's super-clear while doing that that having git actually output an object in the powershell way would make this task much, much easier.   Are there any plans to accomplish this?

**Comment by rkeithhill** [comment]
The primary focus of posh-git is to provide tab-completion of git commands/branches/refs and a Git savvy prompt.  That said, you can use `Get-GitStatus` to get back structured "status" data e.g.:
```
Working      : {}
AheadBy      : 0
HasIndex     : False
StashCount   : 0
BehindBy     : 0
Branch       : rkeithhill/fix-pester-tests
UpstreamGone : False
Upstream     : origin/rkeithhill/fix-pester-tests
Index        : {}
HasUntracked : False
GitDir       : C:\Users\hillr\GitHub\dahlbyk\posh-git\.git
HasWorking   : False
```
Beyond this one object, there are no plans to provide more "Git command output to object" conversions.

**Comment by nebosite** [comment]
Sweet, that does help a lot!

**Comment by dahlbyk** [comment]
@nebosite also, check out https://github.com/PoshCode/PSGit
