### ISSUE TITLE
Cannot validate argument Error after installation

### ISSUE THREAD

**Issue by ursenzler** [dahlbyk/posh-git#558]
- posh-git version/path: 0.7.1  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.1
- PowerShell version: 5.1.16299.251
- git version 2.16.1.windows.4
- OS: Microsoft Windows NT 10.0.16299.0

### Issue Description

I followed your instruction on how to add posh-git to PowerShell. When I navigate into a git repository I get the following error message instead of the information about the branch:

C:\Projects\someproject\somerepo [Error: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command
 again.]>

**Comment by dahlbyk** [comment]
Were you able to resolve this?

If not, we're going to need more details. Can you please patch your install's `src/GitPrompt.ps1` with the change from #560? Then open a new PowerShell session and set `$GitPromptSettings.Debug = $true` to get more details about the error. Thanks!

**Comment by dahlbyk** [comment]
(Or without patching, you can probably see what the problem is in `$Error`.)

**Comment by ursenzler** [comment]
I found the reason with the help of `$Error`. 

I had the following function defined in my `Microsoft.PowerShell_profile.ps1`

```
function get-location ($exe)
{
    Get-Command $exe | Select-Object -ExpandProperty Definition
}
```

After removing this function, git-posh works.

But I still have no clue why the above function makes git-posh fail?!!?  It is just defined, not executed.

Thanks for your help!

**Comment by ursenzler** [comment]
The name `get-location` is the problem. Changing the name solves the problem as well.

**Comment by dahlbyk** [comment]
Yeah, you were stepping on the built-in `Get-Location` cmdlet.

PowerShell experts: would it be possible/wise for us to ensure we are using the built-in commands?

**Comment by rkeithhill** [comment]
Absolutely.  We should start to module prefix the built-in commands we use e.g.:
```posh
Microsoft.PowerShell.Management\Get-Location
```
