### ISSUE TITLE
[Request] Export GitTabExpansion

### ISSUE THREAD

**Issue by igrep** [dahlbyk/posh-git#562]
I've written a tiny module to configure aliases for git subcommands to omit typing `git`.

https://gitlab.com/igrep/pwsh-git-aliases/blob/master/GitAliases.psm1

Then, I want to configure `TabExpansion` for the generated aliases by reusing the `GitTabExpansion` function.
So can you export `GitTabExpansion` to make it reusable?

P.S. Thank you for an excellent module! I use it every day!

**Comment by dahlbyk** [comment]
Sure: #563

> P.S. Thank you for an excellent module! I use it every day!

You are very welcome.

**Comment by dahlbyk** [comment]
Aside: instead of...

```
Enable-GitAliases([boolean] $avoidConflicts = $true)
```

It would be more PowerShell-y to use:

```powershell
Enable-GitAliases([switch] $AllowClobber)
```
