### ISSUE TITLE
Consider shorter WindowTitle for when we get a tabbed console in Windows 10 1809

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#565]
With a [tabbed console](https://blogs.msdn.microsoft.com/commandline/2018/04/13/tabbed-console-starts-here/) coming:

![image](https://user-images.githubusercontent.com/5177512/38969299-cdc29bbe-434c-11e8-93ee-69cbed5b4757.png)

We should rethink our WindowTitle in 1.0.0 a bit:

![image](https://user-images.githubusercontent.com/5177512/38969325-e7a9ff68-434c-11e8-8371-a12f3bd948b0.png)

I like that we put the PowerShell version/arch/pid info to the right.  Folks should be able to hover over the tab and get a tooltip with that info.  However the `posh~git ~` will take up valuable, visible tab space.  We should think about nuking that prefix and go with just:

![image](https://user-images.githubusercontent.com/5177512/38969394-5a199374-434d-11e8-9a77-210fc212e79d.png)

Another thought - with a tabbed interface like this it might be handy to display the current working dir in the title but only when *not* in a repo e.g.:

![image](https://user-images.githubusercontent.com/5177512/38969444-9b16a8e4-434d-11e8-935c-5d4e67869b74.png)

Finally, I've been thinking about tweaking the `Get-PromptPath` function so that when `DefaultPromptAbbreviateHomeDirectory` is $true and you are in your home dir, you get the full path e.g. `C:\Users\Keith`.  It is only when you go down a level that you get the `~` e.g. `~\GitHub\dahlbyk\posh-git`.  That would turn this somewhat odd looking prompt:
```
~
04-18 21:17:58 33ms 9>
```
into
```
C:\Users\Keith
04-18 21:17:58 33ms 9>
```
but still give me a shortened path in this case:
```
~\GitHub\dahlbyk\posh-git\src
04-18 21:17:58 33ms 9>
```

**Comment by dahlbyk** [comment]
> However the `posh~git ~` will take up valuable, visible tab space. We should think about nuking that prefix and go with just:

Agreed. Let's just drop it. (cc https://github.com/dahlbyk/posh-git/pull/538)

> with a tabbed interface like this it might be handy to display the current working dir in the title but only when not in a repo

Even without a tabbed interface this seems useful.

> Finally, I've been thinking about tweaking the `Get-PromptPath` function so that when `DefaultPromptAbbreviateHomeDirectory` is `$true` and you are in your home dir, you get the full path e.g. C:\Users\Keith. It is only when you go down a level that you get the `~` e.g. `~\GitHub\dahlbyk\posh-git`.

Agree that just `~` is an odd prompt. It would make sense to switch to `~/...` once you navigate into a subfolder, or we could switch to a length limit to condense the path name (e.g. #58). I could see the logic working something like...

- If current folder is too long, show `…\long-project-name`
- If path is too long and inside `$Home`, swap in `~`
- If path is still too long, include as many full directories as possible (`…\dahlbyk\posh-git`)

**Comment by rkeithhill** [comment]
PR #567 addresses the primary issue here. Do you want to tackle the modification to `Get-PromptPath` to elide paths?  If you don't have time, I'll take a crack at it in a separate PR.

**Comment by dahlbyk** [comment]
Separate PR is fine, whoever gets there first. Good TDD exercise. 😁
