### ISSUE TITLE
How to uninstall posh-git.git

### ISSUE THREAD

**Issue by znjnthrps** [dahlbyk/posh-git#569]
Hello. I would like to uninstall posh-git.get and remove the path changes and any registry changes.
It is currently  installed in C:\WINDOWS\System32\posh-git
I installed the software using git clone https://github.com/dahlbyk/posh-git.git

### System Details

- PowerShell version: 5.1.16299.251
- Git version: 2.17.0.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.16299.0
- posh-git version/path: 
You cannot call a method on a null-valued expression.
At line:1 char:55
+ ... e posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.Prerele ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

### Issue Description

I am experiencing a problem with...

**Comment by znjnthrps** [comment]
Thank you. Very happy for the quick response. 


Sent from my Galaxy Tab® S2
-------- Original message --------From: Keith Dahlby <notifications@github.com> Date: 5/2/18  00:34  (GMT-06:00) To: dahlbyk/posh-git <posh-git@noreply.github.com> Cc: znjnthrps <glassmonkey@gmail.com>, Author <author@noreply.github.com> Subject: Re: [dahlbyk/posh-git] How to uninstall posh-git.git (#569) 
Just two steps to uninstall:

Remove the Import-Module posh-git line from whichever $PROFILE you installed to, using a text editor of your choice.
Delete the posh-git folder.

posh-git does not touch the Windows Registry.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dahlbyk/posh-git","title":"dahlbyk/posh-git","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dahlbyk/posh-git"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dahlbyk in #569: Just two steps to uninstall:\r\n\r\n1. Remove the `Import-Module posh-git` line from whichever `$PROFILE` you installed to, using a text editor of your choice.\r\n2. Delete the posh-git folder.\r\n\r\nposh-git does not touch the Windows Registry."}],"action":{"name":"View Issue","url":"https://github.com/dahlbyk/posh-git/issues/569#issuecomment-385869299"}}}

**Comment by dahlbyk** [comment]
I'm closing this, but please follow up if you have any other issues.
