### ISSUE TITLE
Repo Status in Submodule

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#57]
Currently we show "(unknown)" when the current directory is within a submodule. Should display part of the submodule SHA instead (like bash).

**Comment by rkeithhill** [comment]
Is this still an issue?  I don't see unknown but the SHA1 for commit we are using for a particular submodule:
```
[(e19af12...)] ~\GitHub\rkeithhill\PowerShellEditorServices\submodules\PSScriptAnalyzer
24>
```
