### ISSUE TITLE
Syntax error in installation instructions

### ISSUE THREAD

**Issue by CaspecoRamis** [dahlbyk/posh-git#573]
In the installation instructions, there is a typo/syntax error in the PowerShell command for installing posh-git, it should be `AllowPreRelease`, not `AllowPrelease`.

Issue introduced by commit https://github.com/dahlbyk/posh-git/commit/b6ade29dcb25c59923a19ef680d6915e57e12a81

**Comment by dahlbyk** [comment]
Fixed, thanks!
