### ISSUE TITLE
Customize Profile prompt GitPromptSettings changed

### ISSUE THREAD

**Issue by wsmelton** [dahlbyk/posh-git#584]
### System Details

- posh-git version/path: `0.7.3   C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3`
- PowerShell version:`5.1.17134.48` 
- Git version:`2.17.1`
- Operating system name and version: `Windows 10 | 10.0.17134.48`

### Issue Description

I am experiencing a problem with...`$GitPromptSettings` appears to have changed as the Wiki article on customizing has some options that don't exit and I'm not able to find the proper setting:
https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt

I'm interested in if anyone happens to know what the new setting that replaced this is now: `$GitPromptSettings.DefaultPromptPrefix.ForegroundColor`

I've tried `$GitPromptSettings.BeforeForegroundColor = [ConsoleColor]::Cyan` and that does not seem to have any effect.

**Comment by schwindelig** [comment]
I had the same issue, but noticed that the described properties are for version >1.0.0. Updating the module to the latest pre-release made them available.

**Comment by wsmelton** [comment]
Which would be what version? I'm on `0.7.3`

**Comment by schwindelig** [comment]
Should be `1.0.0-beta2`. See https://www.powershellgallery.com/packages/posh-git/1.0.0-beta2

**Comment by dahlbyk** [comment]
@schwindelig is correct. There's an incomplete [v0 section](https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt#v0x---customizing-the-posh-git-prompt) on that wiki page, but for a full list it's best to consult the v0 source: https://github.com/dahlbyk/posh-git/blob/v0.7.3.1/src/GitPrompt.ps1#L4-L119. The prompt customization experience, including adjusting colors for `DefaultPromptPrefix` (and basically everything), is greatly improved by upgrading to `1.0.0-beta2`.

If you don't wish to upgrade to v1, you can cheat a bit to colorize `DefaultPromptPrefix`:

```
$GitPromptSettings.DefaultPromptPrefix = '$(Write-Host (Get-History -Count 1 | % Id) -ForegroundColor Cyan -NoNewLine) '
```
