### ISSUE TITLE
The property 'ForegroundColor' cannot be found on this object

### ISSUE THREAD

**Issue by the-j0k3r** [dahlbyk/posh-git#588]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.17134.112
- git version 2.17.1.windows.2
- OS: Microsoft Windows NT 10.0.17134.0

### Issue Description

I am experiencing a problem with...

adding `$GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500`

spits out

```
The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At line:1 char:1
+ $GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```

So is this just UNIX and Linux and Im being dim or what?

**Comment by dahlbyk** [comment]
You're running into the same issue as https://github.com/dahlbyk/posh-git/issues/582: `DefaultPromptPath.ForegroundColor` only works on [v1.0.0-beta2](https://www.powershellgallery.com/packages/posh-git/1.0.0-beta2)! You can upgrade with `PowerShellGet\Update-Module posh-git --AllowPrerelease`.

We really just need to ship 1.0 so it's what folks get by default. 🔜

**Comment by dahlbyk** [comment]
Oops, I referenced the wrong issue. Check out https://github.com/dahlbyk/posh-git/issues/584#issuecomment-393277958.

**Comment by the-j0k3r** [comment]
So release, when its ready no doubt. I learned not to ask or more details :)

**Comment by dahlbyk** [comment]
No worries, there are dozens of settings you could have searched for and come up empty. The entire customization scheme changes pretty significantly.

Do let us know if you have any other issues!

**Comment by the-j0k3r** [comment]
Yea... 

```
Update-Module : A positional parameter cannot be found that accepts argument '--AllowPrerelease'.
At line:1 char:1
+ PowerShellGet\Update-Module posh-git --AllowPrerelease
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Update-Module
```

**Comment by dahlbyk** [comment]
Prerelease support was introduced in 1.6:

```
Update-Module PowerShellGet
```

**Comment by the-j0k3r** [comment]
And there we go, thanks.

**Comment by the-j0k3r** [comment]
Looks great now only need a working terminal for atom :( using powershell outside standalone sucks for git work

**Comment by the-j0k3r** [comment]
Has v1.0.0 been released yet? If not I fully expect answers like when its ready. :rofl:

**Comment by dahlbyk** [comment]
It's close, I have just been ignoring the project while work stuff is hectic. I should get back in the saddle later this month.

**Comment by the-j0k3r** [comment]
Ayo Silver.

**Comment by prubini87** [comment]
> Yea...
> 
> ```
> Update-Module : A positional parameter cannot be found that accepts argument '--AllowPrerelease'.
> At line:1 char:1
> + PowerShellGet\Update-Module posh-git --AllowPrerelease
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
>     + FullyQualifiedErrorId : PositionalParameterNotFound,Update-Module
> ```

You wanted -AllowPrerelease, not --Allowprerelease.

**Comment by the-j0k3r** [comment]
> You wanted -AllowPrerelease, not --Allowprerelease.

I guess its caffeine time =)
