### ISSUE TITLE
The property '***' cannot be found on this object. Verify that the property exists and can be set.

### ISSUE THREAD

**Issue by LimitlessWorkaround** [dahlbyk/posh-git#589]
### System Details

- posh-git version/path: 1.0.0.0 beta2x E:\Users\Daniel\Documents\GitHub\posh-git\src
- PowerShell version: 5.1.16299.492
- git version 2.18.0.windows.1
- OS: Microsoft Windows NT 10.0.16299.0

### Issue Description

I want to use Gitlab with PowerShell, so I followed this tutorial: https://www.develves.net/blogs/asd/articles/using-git-with-powershell-on-windows-10/

My Document folder is on another drive then my profile so the environment variables doesn't link to them. Because of this I hardcoded every $Env:USERPROFILE to E:\Users\"USERNAME"\Documents
All worked out until the point I had to set up a ssh-key. When I'm running the script for that (Windows PowerShell (posh-git) from the tutorial) I get the following error messages:

![grafik](https://user-images.githubusercontent.com/21292736/41922232-e758b902-7964-11e8-9866-187ecdc6ca30.png)

Is it possible that some variables changed now that were different when the tutorial was written?

This is the part of the script where these variables get changed:

![grafik](https://user-images.githubusercontent.com/21292736/41922371-3c6e4e66-7965-11e8-94b8-51845f00ef5c.png)

**Comment by rkeithhill** [comment]
Yes, the settings infrastructure changed between posh-git 0.x and 1.x to better handle Windows 10 support for ANSI ESC/VT sequences for color.  I suggest you check out the 1.x readme - https://github.com/dahlbyk/posh-git/blob/master/README.md. 

You probably don't need to set those colors unless you're background is something like DarkMagenta.  Anyway, the above translates to in v1:
```
$s.LocalDefaultStatusSymbol.ForegroundColor = [ConsoleColor]::Green
$s.LocalWorkingStatusSymbol.ForegroundColor = [ConsoleColor]::Red

$s.BeforeIndex.ForegroundColor = [ConsoleColor]::Green

$s.IndexColor.ForegroundColor = [ConsoleColor]::Green
$s.WorkingColor.ForegroundColor = [ConsoleColor]::Red
```

**Comment by rkeithhill** [comment]
If this doesn't resolve your issue, let me know.
