### ISSUE TITLE
Enhance prompt function to show username/hostname in SSH connection

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#591]
As I've been using Windows 10 OpenSSH's sshd service and connecting to my Windows 10 system using ssh, I've been missing seeing the `[username@hostname]` info the PowerShell prompt on the remote system that I'm used to seeing when I ssh into a Linux box.

We could rectify that by adding the following to our prompt function (somewhere before the prompt suffix):
```powershell
"$(if (Test-Path Env:\SSH_CONNECTION) {" [$([System.Environment]::UserName)@$([System.Environment]::MachineName)]"})"
```
A few notes, you get the remote system's PowerShell prompt when you A) ssh into the remote system with OpenSSH sshd running and configured with this subsystem:
```
Subsystem	powershell	C:/Program Files/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile
```
And no, I'm not quite sure why we get the posh-git prompt when the above specifies `-NoProfile`.  Anyway, I've modified my posh-git prompt to this:
```
$global:GitPromptSettings.DefaultPromptBeforeSuffix.Text = '`n$([DateTime]::Now.ToString("MM-dd HH:mm:ss"))$(if (Test-Path Env:\SSH_CONNECTION) {" [$([System.Environment]::UserName)@$([System.Environment]::MachineName)]"})'
```
So that when I ssh into this system, I see this prompt:
```
C:\Users\hillr
06-27 09:51:19 [hillr@HILLR2] 1>
```
Note that when you use PS Remoting over SSH, PowerShell controls the prompt.  In that case, you currently get just the hostname in the prompt:
```
06-27 09:51:57 8> Enter-PSSession -HostName hillr2
hillr@KEYSIGHT@hillr2's password:
[hillr2]: PS C:\Users\hillr\Documents>
```
But that is changing - see https://github.com/PowerShell/PowerShell/issues/7156 &  https://github.com/PowerShell/PowerShell/pull/7191

So, should we consider covering this scenario with our prompt function or just add an example of how to customize the posh-git prompt if you want this feature?

**Comment by rkeithhill** [comment]
Which variables folder are looking in?  `Auto` or `Local` or `Script` or `Global`?  FWIW `Auto` is a "best guess" attempt to limit the variables to what the extension believes is relevant.  If that is where you are looking, check the other folders for the variables you are looking for.

**Comment by dahlbyk** [comment]
How is prompt handled for other PowerShell remoting situations?

**Comment by rkeithhill** [comment]
If I use WinRM as a transport instead of SSH, I get:
```
06-27 11:39:07 9> Enter-PSSession -ComputerName hillr2
[hillr2]: PS C:\Users\hillr\Documents>
```
That's pretty much the only other remoting scenario I can think off.  Note: it is subtle but the parameter `-ComputerName` on `Enter-PSSession` causes the command to use WinRM while the  `-HostName` parameter causes the command to use SSH.

**Comment by dahlbyk** [comment]
If the default behavior is to put the remote host before `PS $pwd>`, I'm inclined to follow suit with remote host information in `DefaultPromptPrefix` value. Is there a downside to using environment variables, compared with the implementation over in https://github.com/PowerShell/PowerShell/pull/7191?

**Comment by rkeithhill** [comment]
OK, back from vacation … that's a great thought but when you are ssh'd into a remote system where PowerShell has been configured as the default shell, the `Runspace.ConnectionInfo` property is $null.  That's because as far as PowerShell is concerned, it isn't involved in remoting.  This is still useful info though in the (non-remoting) ssh scenario.
