### ISSUE TITLE
Glyphs not working on latest versions with conemu

### ISSUE THREAD

**Issue by isaac2004** [dahlbyk/posh-git#593]
### System Details

- posh-git version/path: tried 1.0.0beta2 and 0.7.3
- PowerShell version: 5.1.17134.137
- Git version: 2.18.0.windows.1
- Operating system name and version: Windows 10.0.17134.0

### Issue Description

I recently wiped my machine, which had a working version of this process. I use conemu and posh git to work on my repos, and trying to setup my console has been challenging. I use UbuntuMono NF which has some good glyphs on it, but I cannot get those glyphs to work with the latest version of posh-git, for instance

![image](https://user-images.githubusercontent.com/8878502/42333101-cf019416-8047-11e8-9c0e-898cd0f5501e.png)

Renders

![image](https://user-images.githubusercontent.com/8878502/42333126-dc76a672-8047-11e8-8550-0971309b1713.png)

I have validated the font is installed correctly as I can see the glyph on vscode and by pasting it into conemu proper. I have tried setting AnsiConsole to true and false but have the same results.

**Comment by dahlbyk** [comment]
Interesting. @JanDeDobbeleer any ideas?

**Comment by JanDeDobbeleer** [comment]
I always convert them to a char. You can see this in the [default settings](https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/defaults.ps1) of oh-my-posh. I am on the latest ConEmu preview and I've got everything working here.

**Comment by isaac2004** [comment]
So you pass in the Unicode into a char constructor? What changed that broke this as it used to work just fine

**Comment by JanDeDobbeleer** [comment]
I don't know. All I know is that I always did it this way as it was the most reliable. Sometimes you decide not to shave yaks and just get stuff done 😂

**Comment by isaac2004** [comment]
Well if I have a particular glyph, how do I get it? :)

**Comment by dahlbyk** [comment]
> What changed that broke this as it used to work just fine? I am going to figure out what version works and which change broke it.

I would have guessed ANSI support in posh-git v1, but if you're struggling with v0 as well then it seems like it might be something in your ConEmu config? Maybe check out https://conemu.github.io/en/UnicodeSupport.html?

**Comment by JanDeDobbeleer** [comment]
Ok, in order to get the glyphs, and you're going to laugh, currently I use Word to get that information. Works like a charm 😎

**Comment by isaac2004** [comment]
Well here is something odd. Look at this

![image](https://user-images.githubusercontent.com/8878502/42401203-9387aa82-8142-11e8-91bb-5733a6e40640.png)

**Comment by dahlbyk** [comment]
With `AnsiConsole = $true`, what does `$PoshGitLastPrompt` show?

**Comment by isaac2004** [comment]
This is on 0.7, ansi console is not available

**Comment by dahlbyk** [comment]
What does [`chcp`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chcp) show?
