### ISSUE TITLE
How do you save settings?

### ISSUE THREAD

**Issue by simkessy** [dahlbyk/posh-git#598]
Every time I restart my shell the settings are reset? V0.x

**Comment by rkeithhill** [comment]
What are  your settings and how are you setting them?  The primary way to "persist" your settings is to open your profile script (whichever one is doing the `Import-Module posh-git` and then putting script to set your settings after the import.  

Here is an example (contents of `~\Documents\WindowsPowerShell\profile.ps1`:
```
Import-Module posh-git
$GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true
```

**Comment by simkessy** [comment]
Oh okay so it needs to be stored in the profile, got it. Thanks!
