### ISSUE TITLE
SQL Server Snapin

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#60]
Changing into `SQLSERVER:\sql` yields an error:

> The term 'w' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by dahlbyk** [comment]
@rkeithhill we would expect this to be fixed, now, right?

**Comment by rkeithhill** [comment]
I think so. You can cd into `cert:\` and "hklm:\` today with no error.
