### ISSUE TITLE
Which value in GitPrompt.ps1 controls the diff colors?

### ISSUE THREAD

**Issue by StingyJack** [dahlbyk/posh-git#601]
The DarkRed and DarkGreen are hard for me to read. I'd like to change them to just Red and Green, but I dont see any diff coloring choices in the GitPrompt.ps1.
![image](https://user-images.githubusercontent.com/15381181/43074075-faaba614-8e49-11e8-8022-07f1c807230b.png)

**Comment by rkeithhill** [comment]
Those colors are controlled by git.exe.  You will need to tweak the corresponding color indexes in your console window's properties (or associated shortcut).  I find it easier to use colortool to set my color palette (my pref is OneHalfDark) - https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/

**Comment by dahlbyk** [comment]
> Those colors are controlled by git.exe.

Specifically, you can find the many, many `color.*` settings documented under [git config](https://git-scm.com/docs/git-config). I don't know of a comprehensive list of the color slots and what their default values are, but for `diff` in particular you could set:

```
git config --global color.diff.old 'red bold'
git config --global color.diff.old 'green bold'
```

Or, you can disable PowerShell's default yellow on blue completely via the Registry, by removing the PowerShell-specific colors for `DarkMagenta` and `DarkYellow` and letting screen colors default to `Gray` on `Black`.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe]
"ColorTable05"=-
"ColorTable06"=-
"ScreenColors"=-

[HKEY_CURRENT_USER\Console\%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe]
"ColorTable05"=-
"ColorTable06"=-
"ScreenColors"=-
```

To put the PowerShell defaults back:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe]
"ColorTable05"=dword:00562401
"ColorTable06"=dword:00f0edee
"ScreenColors"=dword:00000056

[HKEY_CURRENT_USER\Console\%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe]
"ColorTable05"=dword:00562401
"ColorTable06"=dword:00f0edee
"ScreenColors"=dword:00000056
```
