### ISSUE TITLE
Preview all branches starting with specified pattern

### ISSUE THREAD

**Issue by vasiliy-kuznetsov** [dahlbyk/posh-git#603]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.16299.547
- Git version: 2.16.2.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.16299.0'

### Issue Description

I'm working with a huge repository and we have more that 1000 active branches.
In git bash when I type "git checkout feature/SMFTTIII-" and then press double tab I can see all branches which start with specified string:
![image](https://user-images.githubusercontent.com/1743090/44105113-566d5c52-9ff9-11e8-88fb-c31d3c1da8f4.png)

Is it possible configure posh-git for such behavior? If not, what should be done to be able to do so?

**Comment by dahlbyk** [comment]
Try https://github.com/jasonmarcher/PowerTab?

**Comment by vasiliy-kuznetsov** [comment]
Out of the box it doesn't solve the issue.
After I do Import-Module PowerTab all git commands autocompletion stops working.

**Comment by lzybkr** [comment]
PSReadLine supports bash style completion in Emacs mode, or bind <kbd>Tab</kbd> to `Complete` in Windows mode.

**Comment by dahlbyk** [comment]
> After I do `Import-Module PowerTab` all git commands autocompletion stops working.

Interesting. Try importing PowerTab before posh-git gets imported? It's supposed to work (cc @jasonmarcher):

https://github.com/dahlbyk/posh-git/blob/b428c3ceb8dd54f447d545b37db37636724cbe55/src/GitTabExpansion.ps1#L443-L454

**Comment by jasonmarcher** [comment]
>After I do Import-Module PowerTab all git commands autocompletion stops working.

For that, PowerTab needs to be imported before anything that uses it.

**Comment by rkeithhill** [comment]
You can do this if you have PSRL loaded which should be loaded by default in PS v5 and newer e.g..
```
git checkout feature/SMFTTII-<ctrl+space>
```
This module provides all matches.  It is up to PS/PSRL to determine how that information is shown.
