### ISSUE TITLE
Looks for .ssh folder in wrong location?

### ISSUE THREAD

**Issue by jumoel** [dahlbyk/posh-git#61]
(I'm posting this here, because GitHub said I should - I encountered this issue when launching the console from the GitHub for Windows app)

I (used to) use MsysGit, which looks in %HOME% for the .ssh folder. posh-git looks in %HOMEPATH%. This leads to two different .ssh folders.

Could posh-git be changed, so it looks for the .ssh-folder in %HOME% if this variable is present and falls back to %HOMEPATH% if it isn't? That way the transition from MsysGit to posh-git (or the use of both) would be a lot easier.

**Comment by rkeithhill** [comment]
I have changed this to use PowerShell's built-in $HOME variable, which isn't itself an env var; however it is derived from the env vars `%HOMEDRIVE%%HOMEPATH%`. 

In PowerShell `~` is the same as $HOME **except** when you are located in a provider other than the filesystem e.g.:
```
12> cd cert:
\
13> resolve-path ~  | fl *
resolve-path : Home location for this provider is not set. To set the home location, call "(get-psprovider
'Certificate').Home = 'path'".
At line:1 char:1
+ resolve-path ~  | fl *
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Resolve-Path], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.ResolvePathCommand
```
So it is better to avoid `~` if possible.  However I'm curious how msysGit seems to work better with just `%HOMEPATH%` i.e. the home path sans drive name - `\users\keith`?  

Is msysGit more *nixy and not like drive specifiers?  If so, we could search $Home first and if .ssh is not found there, then we could search $Home with the drive specified stripped off.

**Comment by dahlbyk** [comment]
I had forgotten the module still [includes](https://github.com/dahlbyk/posh-git/blob/18d600a20d93ba05554068d81b5f7ce4e5648268/posh-git.psm1#L22-L23):

```powershell
if (!$Env:HOME) { $Env:HOME = "$Env:HOMEDRIVE$Env:HOMEPATH" }
if (!$Env:HOME) { $Env:HOME = "$Env:USERPROFILE" }
```

So really it should be pretty safe to use `$Env:HOME` instead of `$Home` to align with Git/MSYS.

> Is msysGit more *nixy and not like drive specifiers?

Yeah, in Git Bash you will see `/c/Windows` instead of `C:\Windows`.

**Comment by rkeithhill** [comment]
I think 0.7.0 should resolve this but I don't run msysGit, so I can't test if it really is fixed.

**Comment by dahlbyk** [comment]
> I don't run msysGit, so I can't test if it really is fixed.

msysGit of 2012 is what we now call Git for Windows.

At this point I'm basically content to let SSH issues sit (as if I hadn't been before 🙄) until someone gets fed up enough to spin off a project for it (#338).

**Comment by rkeithhill** [comment]
SSH functionality has been spun off into the `posh-sshell` module (https://github.com/dahlbyk/posh-sshell) so closing this issue.
