### ISSUE TITLE
git commit -a not working

### ISSUE THREAD

**Issue by mrehanabbasi** [dahlbyk/posh-git#611]
### System Details

- posh-git version/path: 1.0.0
- PowerShell version: 5      1      17134  228
- Git version: 2.18.0.windows.1
- Operating system name and version: Win32NT 10.0.17134.0

### Issue Description

Whenever I try to do a commit by using the `git commit -a` command, none of the changes are staged and no commit is made.

**Comment by dahlbyk** [comment]
I have no idea how posh-git could be impacting this. Does `git commit -a` work from Git Bash at the same location?

Note `git commit -a` will not commit new files, only changes to existing files that are known to Git.

**Comment by mrehanabbasi** [comment]
`git commit -a` works in Git Bash for the same project..

**Comment by dahlbyk** [comment]
I've never seen anything like this. What does git show you if you set `$Env:GIT_TRACE = 'true'`?

**Comment by dahlbyk** [comment]
You might also need to set `$Env:GIT_TRACE_PERFORMANCE = 'true'` and/or `$Env:GIT_TRACE_SETUP = 'true'` to see enough detail to help troubleshoot.

**Comment by mrehanabbasi** [comment]
Don't know why but it's working now.. I just used this command `$Env:GIT_TRACE = 'true'`.. Didn't change anything else..
