### ISSUE TITLE
Modify prompt while keeping posh-git modifications

### ISSUE THREAD

**Issue by farzadmf** [dahlbyk/posh-git#613]
Hi,

This is more of a question rather than an issue, and I couldn't think of a better place to ask it. I'd appreciate if you help me.

I'm trying to modify the prompt using `function prompt`. More specifically, I'm using ConEmu and in order for ConEmu to be aware of my current working directory, I have to implement the `function prompt` function (More about this feature in ConEmu is [here](https://conemu.github.io/en/ShellWorkDir.html))

So, the problem I have with this approach is that it's overriding the changes made by `posh-git` when inside of a git directory.

I was wondering if there's a way for me to somehow know inside my `function prompt` what `post-git` has outputted, and just append/prefix stuff to it?

Thank you in advance

**Comment by rkeithhill** [comment]
If you are using a beta of posh-git v1, then it is pretty simple.  Look at the very last example in this section of the README: https://github.com/dahlbyk/posh-git#customizing-the-posh-git-prompt  It shows how to use the global variable `$GitPromptScriptBlock` to do what you want.

**Comment by dahlbyk** [comment]
You can also execute arbitrary code via string expansion, so I think you could get away with updating `$GitPromptSettings.DefaultPromptSuffix`, e.g.

```powershell
$GitPromptSettings.DefaultPromptSuffix = '$(
  # Default posh-git suffix
  $out = "$(">" * ($nestedPromptLevel + 1)) "
  
  # https://conemu.github.io/en/PowershellPrompt.html
  # Check for ConEmu existance and ANSI emulation enabled
  if ($env:ConEmuANSI -eq "ON") {
    # Let ConEmu know when the prompt ends, to select typed
    # command properly with "Shift+Home", to change cursor
    # position in the prompt by simple mouse click, etc.
    $out += "$([char]27)]9;12$([char]7)"

    # And current working directory (FileSystem)
    # ConEmu may show full path or just current folder name
    # in the Tab label (check Tab templates)
    # Also this knowledge is crucial to process hyperlinks clicks
    # on files in the output from compilers and source control
    # systems (git, hg, ...)
    if ($loc.Provider.Name -eq "FileSystem") {
      $out += "$([char]27)]9;9;`"$($loc.Path)`"$([char]7)"
    }
  }

  return $out
)'

**Comment by farzadmf** [comment]
Thank you both @rkeithhill @dahlbyk for your answers.

I'm not sure what I am missing in @dahlbyk 's solution, but @rkeithhill suggestion of using `$GitPromptScriptBlock` seems to do the trick for me.

As suggested by ConEmu's maintainer, I'm going to create a PR in their documentation with a sample `prompt` function.

Going to close this one as I got my answer

**Comment by farzadmf** [comment]
[This is the link](https://conemu.github.io/en/ShellWorkDir.html#PowerShellPoshGit) to ConEmu documentation in case anyone ends up here looking for answers
