### ISSUE TITLE
Slowliness in all operation

### ISSUE THREAD

**Issue by guillemsola** [dahlbyk/posh-git#618]
### System Details

- posh-git version/path: 0.7.3 tested with current scope user and choco
- PowerShell version: 5.1.17134.1
- Git version: 2.18.0.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.17134.0

### Issue Description

Installed it both using choco and as a local module and it is damn slow on my dev machine., Just loading the prompt takes 2 seconds. Operations like `git checkout` and let the autocomplete work take even more. I have also tested with same configuration on an Azure new VM and speed it's the correct one.

I reviewed some closed issues about similar experience and tried to follow tips there but improvements where very low. How can I debug this to see what can be causing this slowliness? I have many other things in my computer like WSL, ConEmu, sophos...

![image](https://user-images.githubusercontent.com/610476/45149606-4392bb80-b1ca-11e8-8940-e3ca2d79e3be.png)

**Comment by rkeithhill** [comment]
I don't believe there is much we can do when `git status` is slow.
