### ISSUE TITLE
git log completion does not recognize --patch and --stat

### ISSUE THREAD

**Issue by chillum** [dahlbyk/posh-git#619]
### System Details

- posh-git version/path: 0.7.3  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5      1      17134  228
- Git version:  2.18.0.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.17134.0

### Issue Description

I am experiencing a problem with posh-git completion for `git log`: I frequently use `git log --patch` and `git log --stat`, but posh-git does not know about them.

**Comment by dahlbyk** [comment]
This should be a pretty simple change, if anyone wants to contribute:

https://github.com/dahlbyk/posh-git/blob/926fb60baa64574bd38e6f25550c63de47e15e5e/src/GitParamTabExpansion.ps1#L61

Bonus points for refactoring such that the [`git diff` common options](https://github.com/git/git/blob/c05048d43925ab8edcb36663752c2b4541911231/contrib/completion/git-completion.bash#L1450-L1465) can be reused across related commands (e.g. `show` is missing them).

Curiously, `git-completion.bash` doesn't handle `--patch` either!

**Comment by chillum** [comment]
but zsh completion does have this out of the box,
`git diff --stage` also is missed

I'll see whether I can make a PR myself.

**Comment by chillum** [comment]
created a PR: #620

**Comment by dahlbyk** [comment]
> but zsh completion does have this out of the box

Interesting. I don't see it in [`git-completion.zsh`](https://github.com/git/git/blob/c05048d43925ab8edcb36663752c2b4541911231/contrib/completion/git-completion.zsh), so I'm curious why it would be working?

Regardless, thanks for the PR!
