### ISSUE TITLE
Not working for git-flow compatible branch names?

### ISSUE THREAD

**Issue by dragGH102** [dahlbyk/posh-git#623]
### System Details

- posh-git version/path: latest (v0.7.1, I assume)
- PowerShell version: 5.1
- Git version: 2.17.1.windows.2
- Operating system name and version: Windows 10.0, build 17134

### Issue Description

I use git flow to generated branch names. I am aware a git flow extension for git-post exists but after quickly checking the code I don't see any reference to branch names (aside from what git flow does behind the hood).

The issue is: git checkout f<tab> shows only FETCH_HEAD whereas I have plenty of branches in git flow format, such as `feature/X`

**Comment by rkeithhill** [comment]
Have those feature branches been fetched onto your local machine?  I do branch name tab completion quite a bit with feature branches and haven't had any problems.  Does `git branch -a` show your feature branches?

**Comment by dahlbyk** [comment]
You can also check output of `git show-ref`

**Comment by dragGH102** [comment]
Thanks for your followup.

It now seems to work (I guess it could be due to having actually tried with the git-flow extension)

Closing
