### ISSUE TITLE
Option to *not* modify the prompt

### ISSUE THREAD

**Issue by MartinBonner** [dahlbyk/posh-git#624]
- posh-git version/path: 0.7.3.1  C:\tools\poshgit\dahlbyk-posh-git-9bda399\src
- PowerShell version: 5      1      17134  228
- Git version:
- Operating system name and version: Windows 10

### Issue Description

I want posh-git's tab-completion support, but actually, I *don't* want the git status in my prompt.  Is there a way to disable it?  If not, could this be added?

**Comment by dahlbyk** [comment]
Setting `$GitPromptSettings.EnablePromptStatus` after posh-git has loaded will suppress showing Git information in the prompt:

**Comment by rkeithhill** [comment]
Also note that if we detect that the prompt has been modified from the default, we will not install the posh-git prompt function.  And if you define a prompt function *after* importing posh-git, it will overwrite the posh-git prompt function.

**Comment by MartinBonner** [comment]
This is a perfectly good work-round, but the default prompt is fine for
me.  However creating a non-default prompt function with the same output as
the default, just to stop posh-git overwriting the function which does what
I want seems ... seems like a bit of a hack to me.

**Comment by rkeithhill** [comment]
It would be easy enough for us to add a way to do this.  The unfortunate part is that the way to invoke the setting would be a bit ... unusual.  That is, we can't put such a setting in `$GitPromptSettings ` because the prompt is installed when the module loads - before $GitPromptSettings is available.  So we'd either require an env var like @dahlbyk suggests or we'd have the user pass a parameter to the `Import-Module` command e.g.:
```
Import-Module posh-git -ArgumentList "-DisablePoshGitPrompt"
```
That's the part that is a bit unusual - passing in parameters to the module as it's being imported.

**Comment by MartinBonner** [comment]
Yes.  In my view, PoshGit shouldn't change the prompt when the module is
imported - doing so should be an additional call.  *However* that would
break all the existing users that expect it to, so it's too late for that.
Adding a parameter to the import doesn't feel *much* nicer than me
overriding the default prompt function - and has the distinct disadvantage
that it involves work on your part.

I suggest closing this as "Wont Fix"

Martin

**Comment by dahlbyk** [comment]
Module arguments are just not a good experience, so let's avoid those. I'd rather support `$Env:GIT_PROMPT = 'false'` as a guard against modifying `prompt`.

Leaving open as up-for-grabs, if someone wishes to implement that. @MartinBonner if you'd prefer to Close that's fine, too.

**Comment by MartinBonner** [comment]
Given where we are, either replacing the default prompt function before importing posh-git, or setting `$GitPromptSettings.EnablePromptStatus = $false` afterwards is as clean a solution as achievable.
