### ISSUE TITLE
Unable to set foreground of DefaultPromptPath

### ISSUE THREAD

**Issue by corbob** [dahlbyk/posh-git#631]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\PowerShell\Modules\posh-git\0.7.3
- PowerShell version: 6.1.0
- git version 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.17763.0 (1809)

### Issue Description

I am experiencing a problem with setting a foreground color for DefaultPromptPath following the samples in the Read Me.
```
PS>$GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500
The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At line:1 char:1
+ $GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyAssignmentException
```

**Comment by rkeithhill** [comment]
You need to install the pre-release version of v1 from the PSGallery.  That version supports the setting you're trying to use above.

**Comment by rkeithhill** [comment]
I believe the issue is that you're using the Readme from `master` whereas `0.7.3` is being supported on the `v0.x` branch.
