### ISSUE TITLE
Add-Type Error on Powershell Startup

### ISSUE THREAD

**Issue by mrehanabbasi** [dahlbyk/posh-git#636]
### System Details

- posh-git version/path: 1.0.0 beta2 C:\Program Files\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.17763.1
- git version: 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

Whenever I open powershell, I get the error as per [this screenshot](https://www.dropbox.com/s/m2y0288jvkd5nvo/Capture.JPG?dl=0) and prompt shifts to `PS>`. However, the error does not appear when I open powershell as administrator.

**Comment by rkeithhill** [comment]
If you open Windows PowerShell as admin, do you get this error?  Also, in a non-admin Window does this work:

**Comment by rkeithhill** [comment]
`

**Comment by rkeithhill** [comment]
If you open Windows PowerShell as admin, do you get this error?  Also, in a non-admin Window does this work:
```
Add-Type -TypeDefinition "public enum Foo { bar, baz };"
```
I suspect maybe your `$env:TEMP` environment variable is  not getting set to your profile's temp dir.  And it defaults to the Windows temp dir which you wouldn't have permission to write into.

**Comment by mrehanabbasi** [comment]
`Add-Type -TypeDefinition "public enum Foo { bar, baz };"` does not work in non-admin powershell.. Also, `$env:TEMP` is set to the Appdata\Temp folder..

**Comment by mrehanabbasi** [comment]
@rkeithhill Please help..

**Comment by mrehanabbasi** [comment]
The error disappeared after I deleted the contents of `C:\WINDOWS\Temp` folder..
