### ISSUE TITLE
Skip the ConsoleMode hack for new Windows versions

### ISSUE THREAD

**Issue by lhecker** [dahlbyk/posh-git#637]
### System Details

- posh-git version/path: 1.0.0 beta2 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.1.0
- git version 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

Thank you for this wonderful project!
Sadly though I'm a bit dissatisfied with the startup speed (1000-1300ms) and tried improving the situation.

While doing so I realized that if I remove these 2 lines:
* https://github.com/dahlbyk/posh-git/blob/653101c3aae676eafa0f2ebe6b20f066a8e4013d/src/posh-git.psm1#L5
* https://github.com/dahlbyk/posh-git/blob/653101c3aae676eafa0f2ebe6b20f066a8e4013d/src/GitPrompt.ps1#L847

everything still works as it used to - including ANSI escape codes!

*But now startup time is reduced by 30-50% down to around 500-600ms!*

Could this be because in the newest Windows versions `HKCU:\Console\VirtualTerminalLevel` is `1` by default now? Because I personally don't have that registry key set at all.

If we could add some kind of check for this we could skip running the [expensive ConsoleMode hack](https://github.com/dahlbyk/posh-git/blob/master/src/ConsoleMode.ps1#L11-L47), no-op the `Set-ConsoleMode` function and thus significantly improve startup time.

I'm fairly inexperienced in proper PowerShell scripting and thus I don't have a proper idea how we can do this in a backwards-compatible way, but I'm happy to help wherever I can. 🙂

**Comment by rkeithhill** [comment]
That's a good idea.  I'm looking into it.

**Comment by lhecker** [comment]
After pondering about this for a while I actually don't think that this is achievable by removing the `ConsoleMode` stuff.

But I found another way: `Add-Type` provides the `-OutputAssembly` and `-Path` options using which we can cache the assembled C# code in a .dll!
With this idea in mind I hacked together the following: https://github.com/dahlbyk/posh-git/compare/master...lhecker:master

I took the liberty to remove unused C# code and was thus able to remove more code than I added.
`GitPrompt.ps1` btw was encoded as UTF-8 with BOM - I removed the BOM. 🙂

**Comment by rkeithhill** [comment]
That might be part of the solution but not the whole solution.  Another option for creating a DLL would be to just do that as part of the module build process but I don't think we need to go there yet.  I've got a PR planned for later tonight that should address this if one of my assumptions is correct.  :-)
