### ISSUE TITLE
Saving prompt status settings

### ISSUE THREAD

**Issue by Akxe** [dahlbyk/posh-git#639]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.17134.228
- git version 2.16.2.windows.1
- OS: Microsoft Windows NT 10.0.17134.0

### Issue Description

My settings are not remembered upon opening new PowerShell. I read readme, and configuration options, but haven't found it...

I wanted to disable status as my IDE does it already. I use this command `$GitPromptSettings.EnablePromptStatus = $false`.

**Comment by rkeithhill** [comment]
You need to put that line in one of your profile scripts.  Search your ~\Documents\WindowsPowerShell dir for files named `*profile.ps1`.  Find the one that has the command `import-module posh-git` and add your setting right after the import.

**Comment by Akxe** [comment]
It indeed did the job. Let's put it in the **Customizing the posh-git prompt** section.

**Comment by rkeithhill** [comment]
This is covered by this line in that section of the README.md:
```
If you'd like to make any of these changes permanent, i.e. available whenever you start PowerShell, put the corresponding
setting(s) in one of your profile scripts **after** the line that imports posh-git.
```

**Comment by dsherret** [comment]
It might be nice to add subtitles in that section as it's a bit of a wall of text or add the word "save" to that sentence so it turns up easier when searching.
