### ISSUE TITLE
Issue with tab expansion and non-English file names

### ISSUE THREAD

**Issue by Haacked** [dahlbyk/posh-git#64]
Repro steps:
1. `touch 慣用音.txt`
2. `git add {tab}`

Expected: it expands the filename. 
Actual: it expands to:

```
git add "\346\205\243\347\224\250\351\237\263.txt"
```

That wouldn't be a problem except it doesn't work.
1. `git config core.quotepath true`
2. git add {tab}

Result: 
![](http://cl.ly/2q2E2r031P1V2S163H2U/garbled-chars.png)

**Comment by dahlbyk** [comment]
> It appears to work by adding `-c core.quotepath=false` to the `git status` command, but PowerShell is treating the command output differently when assigned to a variable (or piped to anything).

I had completely forgotten about this particular issue, but we fixed the output encoding with #359 and #397. #403 should do the rest.
