### ISSUE TITLE
Setup for Linux

### ISSUE THREAD

**Issue by peteichuk** [dahlbyk/posh-git#643]
**Very complicated setup for Linux**

alternative - [install from npm](https://github.com/leonardiwagner/npm-posh-git)

I can not understand from your documentation how to finally install "posh-git", could you divide the installation for the platforms into separate pages with all the details?

**Comment by rkeithhill** [comment]
Well, for the most part it is the same on every platform.  You use PowerShell's module system to install:
```
Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force
```
See https://github.com/dahlbyk/posh-git#installation 

I will update the section regarding PSReadLine for Linux/macOS.  That step is no longer necessary for 6.1 on Linux/macOS.

**Comment by rkeithhill** [comment]
The readme will be clarified for the 1.0.0-beta2 release via PR #660

**Comment by shravanngoswamii** [comment]
Just putting it here in case someone is looking for something  like posh-git in bash/zsh for linux/mac than gitflect is better alternative:
- https://github.com/shravanngoswamii/gitflect
- Website (Docs): https://shravangoswami.com/gitflect/
