### ISSUE TITLE
The property 'Text' cannot be found on this object.

### ISSUE THREAD

**Issue by martingbrown** [dahlbyk/posh-git#645]
### System Details

```
- posh-git version/path: 0.7.3.1  C:\tools\poshgit\dahlbyk-posh-git-9bda399\src
- PowerShell version: 5.1.16299.666
- git version 2.19.2.windows.1
- OS: Microsoft Windows NT 10.0.16299.0
```

### Issue Description

When I run the following command copied and pasted from the [README.md](https://github.com/dahlbyk/posh-git/blob/master/README.md#customizing-the-posh-git-prompt) file I get an error.

```
C:\Users\redacted> $GitPromptSettings.DefaultPromptBeforeSuffix.Text = '`n'
The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At line:1 char:1
+ $GitPromptSettings.DefaultPromptBeforeSuffix.Text = '`n'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
```

**Comment by rkeithhill** [comment]
We have a dual track system here where v0.x releases are on the `v0` branch, so for 0.7.3.1, use this [README.md](https://github.com/dahlbyk/posh-git/blob/v0/README.md).  Or, if you'd prefer the configuration options shown on the `master` branch README.md, you could follow the instructions in that README.md to install the `1.0.0-beta2` version of posh-git.
