### ISSUE TITLE
Function Get-GitBranch is missing from posh-git 1.0

### ISSUE THREAD

**Issue by pchung13** [dahlbyk/posh-git#646]
### System Details

- posh-git version/path: 1.0.0 beta2 ~\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.17134.407
- git version 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.17134.0

### Issue Description

Get-GitBranch functionality is missing in 1.0+.

```
[11-30 15:47:10] C:\Users\pachun
> Get-GitBranch
Get-GitBranch : The term 'Get-GitBranch' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-GitBranch
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-GitBranch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Looks like it is missing from the psm1 and psd1 files?

**Comment by rkeithhill** [comment]
This was removed in PR #427
