### ISSUE TITLE
How do you manually install this?

### ISSUE THREAD

**Issue by MrStonedOne** [dahlbyk/posh-git#648]
How do you manually install this on windows?

All of the instructions instruct me to use some package manager, but i see no reason to install a package manager for 1 package, and I have no reason to use them for any other package as this is the only mod to power shell i'm gonna want, as i do everything else in bash shell. (git doesn't work for me in bash shell for windows because it leaves files behind when you control+c out of an interactive commit and then further git operations fail until you manually remove those files, posh-git on github shell classic didn't have this issue and i'm hoping the same is true for posh-git proper)

**Comment by rkeithhill** [comment]
PowerShell v5 and higher come with a built-in package manager.  There is nothing else to install.  But you can always download a zip of this project, unzip it somewhere on your filesystem and specify the full path to the root/src/posh-git.psd1 to the import command.  Say you unzip to `$home\posh-git`, you can import the module like so `Import-Module $home\posh-git\src\posh-git.psd1`.
