### ISSUE TITLE
Distinguish git-svn repos

### ISSUE THREAD

**Issue by cromwellryan** [dahlbyk/posh-git#65]
I'll often jump into a git repo and forget whether it's pushing to other git repositories or an svn repo.  It throws me off for a few seconds when I see 'origin is not a repository'.

It would be nice if git-svn repositories had some type of distinguisher.  Maybe [svn:master] or different color set.

**Comment by dahlbyk** [comment]
I'd like to think we've made enough progress that folks would no longer benefit from this, but I'm still open to it if anyone thinks it's a good idea today.

**Comment by dahlbyk** [comment]
Glad to reopen if someone wishes to take this on, but this gets less relevant every year.
