### ISSUE TITLE
It should be easier to specify bold in various path parts

### ISSUE THREAD

**Issue by lzybkr** [dahlbyk/posh-git#650]
### System Details

- posh-git version/path: 1.0.0-beta2
- PowerShell version: 5.1
- Git version: not relevant
- Operating system name and version: Windows 10 1809

### Issue Description

It should be easy to specify that parts of my prompt (e.g. the path) are in bold. In some consoles like http://github.com/jwilm/alacritty - bold looks really nice.

I noticed `CustomAnsi` is an option and it works, but it is less friendly.

For some motivation, Here is a side by side comparison of the differences:

![image](https://user-images.githubusercontent.com/2148248/49970513-6aa30c80-fee0-11e8-9bea-32c1ebb2a790.png)

The left side (11-15) is conhost, the right side (39-42) shows alacritty as well as the settings. Both windows are using roughly the same font (Fira Code, but different sizes - as similar as I could make it look.)

At any rate, the point is that bold might not be that interesting for `conhost`, but it is definitely interesting for other consoles.

**Comment by lzybkr** [comment]
Ah, that's the reasoning I used in PSReadLine colors too - dropping the Foreground/Background options.

Feel free to close, just make sure to call out the breaking change between beta releases because at you now know at least 1 person is using `CustomAnsi`.

**Comment by dahlbyk** [comment]
It would be interesting to have a PowerShell module for constructing VT sequences (e.g. [chalk](https://github.com/chalk/chalk)), rather than add more formatting smarts to posh-git.

I'm going to go ahead and close this, since #616 (removing `CustomAnsi`) would compose well with such a helper.
