### ISSUE TITLE
posh-git not working on mac

### ISSUE THREAD

**Issue by TimJarvis** [dahlbyk/posh-git#654]
### System Details

- posh-git version/path: 1.0.0-beta2
- PowerShell version: 6.1.1
- Git version: 2.17.2 (Apple Git-113)
- Operating system name and version: Mac Os - Mojave (10.14.2)

### Issue Description
I am experiencing a problem with...

I installed posh-git via 

PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force

as per the instructions on the home page. Everything appears to install correctly, but it simply does not appear.

The module appears to be in my user modules folder and the environment when in powershell appears to have the PSModulePath value set (not present from iTerm though) - so I am unsure why it's not working.

![image](https://user-images.githubusercontent.com/753596/50942470-f490c600-14dc-11e9-97bc-ab20551db10c.png)

The modules seem to be installed as far as powershell is concerned.
PS /Users/tim/dev/Xap.KidsXap.Centres> Get-InstalledModule

```
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.0-beta3          PSReadLine                          PSGallery            Great command line editing in the PowerShell console host
1.0.0-beta2          posh-git                            PSGallery            Provides prompt with Git status summary information and tab completion for Git commands, parameters, remotes and branch names.
```

**Comment by rkeithhill** [comment]
Next step after installing it is importing it into your current PS session e.g.:
```
Import-Module posh-git
```
Since most folks want that done all the time, they add this command (plus any posh-git customization) to their profile script.  We have a command that will add the command above to your profile.  After you have imported the module, execute `Add-PoshGitToProfile -AllHosts`.

**Comment by TimJarvis** [comment]
hah - so simple in the end. Thanks for that. appreciated.
