### ISSUE TITLE
Start-SshAgent, Add-SshKey does not work inside of VSTS/Azure Devops

### ISSUE THREAD

**Issue by teejam2** [dahlbyk/posh-git#655]
### System Details

- posh-git version: 0.7.3
- path: C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1
- Git version: 2.20.1.windows.1
- Operating system name and version: Windows - VSTS agent

### Issue Description

I am experiencing a problem with Start-SshAgent and Add-SshKey when using this module inside of an Azure Devops pipeline. The errors are:

```
The term 'D:\VSTS_Agent\externals\git\usr\bin\ssh-agent C:\Program Files\Git\usr\bin\ssh-agent' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitUtils.ps1:491 char:11
 +         & $sshAgent | ForEach-Object {
 +           ~~~~~~~~~
 + CategoryInfo          : ObjectNotFound: (D:\VSTS_Agent\e...r\bin\ssh-age 
 nt:String) [], ParentContainsErrorRecordException
 + FullyQualifiedErrorId : CommandNotFoundException
```

and 
```
The term 'D:\VSTS_Agent\externals\git\usr\bin\ssh-add C:\Program Files\Git\usr\bin\ssh-add' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitUtils.ps1:564 char:19
 +                 & $sshAdd $value
 + CategoryInfo          : ObjectNotFound: (D:\VSTS_Agent\e...usr\bin\ssh-add:String) [], ParentContainsErrorRecordException
 + FullyQualifiedErrorId : CommandNotFoundException
```

I think the issue is that the Azure Devops agent has got 2 git utils in its path. I'm in a rush so I've worked around this by setting $sshAgent/$sshAdd in lines 491 and 564 explicitly to
`$sshAgent = "D:\VSTS_Agent\externals\git\usr\bin\ssh-agent"`

but obviously this is not ideal and not good practice, and I think this is not working as intended.

**Comment by rkeithhill** [comment]
Yup, it looks like this is failing because it is finding two executables.  You could have also fixed this by changing the `& $sshAgent | ...`  line to `& $sshAgent[0] | ...`.  But that solves it by picking the first one in PATH order which may or may not be what you want.  We probably need a preference variable to allow the user to specify the path to the desired ssh-agent impl when there is more than one in the PATH.

**Comment by rkeithhill** [comment]
@teejam2 Can you try the `posh-sshell` module and see if the ssh-agent related commands in that module work better?  It is unlikely there will be much time spent improving the ssh support in the v0.x branch given that we have a dedicated and separate module for this now.
