### ISSUE TITLE
Latest releases

### ISSUE THREAD

**Issue by kumarharsh** [dahlbyk/posh-git#656]
Seeing the changes in #586 for better supporting Window's bundled OpenSSH, I was trying some of the commands like `Get-NativeSshAgent`, etc. And none of them are there in the latest release installed by running: 

```
PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force
```

As I understand it, those changes are important for running posh-git and posh-sshell along with Windows' OpenSSH. Can those changes be published as a release?

**Comment by rkeithhill** [comment]
The `Get-NativeSshAgent` command is in the `posh-sshell`, so try:
```
PowerShellGet\Install-Module posh-sshell -Scope CurrentUser
```
Those changes "should" be in the latest posh-sshell version (0.3.1).  If not, it would be better to post an issue to the `posh-sshell` repo.  FWIW I've been using the Windows 10 built-in OpenSSH client without the support of any PowerShell module.  It is pretty easy to set up.  The commands you need to run from an elevated PowerShell prompt are:
```
Get-Service ssh-agent | Set-Service -StartupType Automatic -PassThru | Start-Service
ssh-add ~\.ssh\<path-to-private-key-file> # If prompted for passphrase, enter it
```
Finally, configure Git to use the built-in version of ssh.exe like so:
```
git config --global core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe
```
After that, you shouldn't be prompted for your passphrase again.  And if you are, check that the ssh-agent service is still running.  Major updates (1803 -> 1809) will result in the service being stopped and reset to manual start.
