### ISSUE TITLE
$GitPromptSettings.DefaultPromptPath.ForegroundColor = 'Green' treated as DarkGreen

### ISSUE THREAD

**Issue by pankajbharti** [dahlbyk/posh-git#661]
### System Details

- posh-git version/path: 1.0.0 beta2 C:\Program Files\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.17763.316
- git version 2.17.1.gvfs.2.5.g2962052
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

$GitPromptSettings.DefaultPromptPath.ForegroundColor = 'Green'

The actual color used is 'DarkGreen'

**Comment by rkeithhill** [comment]
When you set a color to `Green` that will first attempt to use the Html color `Green` e.g. `[System.Drawing.ColorTranslator]::FromHtml('Green')`.  If there is not an Html color corresponding to the named color, it will try to find a System.ConsoleColor named `Green`.  

You probably want the ConsoleColor, in which case, assign the value like so:
```
$GitPromptSettings.DefaultPromptPath.ForegroundColor = [System.ConsoleColor]::Green
```
Or you can specify a hex value (0xRGB):
```
$GitPromptSettings.DefaultPromptPath.ForegroundColor = 0x00FF00
```
