### ISSUE TITLE
Tab Completion For Custom Aliases

### ISSUE THREAD

**Issue by terryaney** [dahlbyk/posh-git#667]
### System Details

- posh-git version/path: modules/posh-git/1.0.0
- PowerShell version: 5.1.17134.590
- Git version: 2.20.1
- Operating system name and version: Win 10

### Issue Description

I have a git alias `git dt-c ref1 ref2 file` which is a short cut for 'differences between commits'.  I'm trying to modify tab completion to make it so that...

ref1 - cycles through a custom list of commit hints (head~, head~~, head~N)
ref2 - cycle through a custom list of commits **and** all tracked files (b/c this param is optional and they may be trying to provide a file now)
file - If they provided ref1 and ref2, this would just cycle through all tracked files

*Note*: I set up my alias as `dt-c = !git z-dt-c` where `z-dt-c` is a complex alias.  The reason I did this was to make the command/pattern matching easier in GitTabExpansion.

**Disclaimer**: My regex skills are zilch and my powershell skills aren't much better, which may stop me from doing anything in GitTabExpansion :)  I'm simply a C# developer trying to make my git experience in the command line a little more pleasant for myself and my team.

I attempted the following by basically cutting and pasting the `git pull` processing and trying to go from there:

````
        # Handles git prev/previous/dt-c <ref>
        "^(?:\!git z-dt-c)${ignoreGitParams}\s+(?<ref>\S*)$" {
            $cmdList = @()
            $cmdList += "HEAD~"
            $cmdList += "HEAD~~"
            $cmdList += "HEAD~N"
            $cmdList
        }
        # Handles git dt-c ref1 <ref2>
        "^(?:\!git z-dt-c)${ignoreGitParams}\s+(?<ref1>\S*).*\s+(?<ref2>[^\s\:]*)$" {
            $cmdList = @()
            $cmdList += "HEAD~~"
            $cmdList += "HEAD~~~"
            $cmdList += "HEAD~N"
            # How do I add tracked files?
            $cmdList += "<Tracked File>"
            $cmdList
        }
        # Handles git dt-c ref1 ref2 <path>
        "^(?:\!git z-dt-c)${ignoreGitParams}\s+(?<ref1>[^\s-]\S*).*\s+(?<ref2>\S*).*\s+(?<path>\S*)$" {
            $cmdList = @()
            $cmdList += "<Tracked File>"
            # How do I add tracked files?
            $cmdList
        }
````
So the problems I am facing are:

1. `git dt-c {tab}` - cycles my commit hints correctly, **but** it also includes staged files.  I have no idea where they are coming from.
1. `git dt-c HEAD {tab}` - is the same as the first item.  Included staged files but cycles my hints correctly.
1. `git dt-c HEAD HEAD~ {tab}` - Included *everything* from the second scenario plus my one additional 'Tracked File' (so there are two of those entries).

Any suggestions on how to fix this or any comments on how the system is working that I might research and try to solve myself?

Questions:
1. Does the order of the regex pattern matching matter?  I would assume it does since they seem to be in some sort of `switch` pattern matching.
1. Since those staged files are coming in, and I thought I was basically returning a brand new list of only my entries, is there somewhere else that controls/injects items into the list I return based on the current repository status?
1. I would assume the biggest (or possibly the only) cause of my problems are my regex patterns?

**Comment by terryaney** [comment]
Well, after 4 hours of trial and error, I think I have it working.  I'll post here to see if anyone has comments on it.  Regex's were a big part of the problem.  

For issue 2 above, I had another regex looking for `dt` which also matched when I typed in `dt-c`. Also, I had 'copied' the implementation of GitTabExpansion's `diff|difftool` syntax and it returns `Index.Modified` even if the command didn't include a `--cached` or `--staged` parameter. To fix my issues, I updated my regex to exclude 'dt-c' and excluded `Index.Modified` (wonder if the in-built `diff|difftool` would want to exclude as well?).  Here was my final match pattern for `dt`

````
"^(?!.\!git z-dt-c)(?:\!git z-dt) (?<files>\S*)$" {
    # gitDiffFiles returns Index.Modified no matter what.  I don't want that in my list
    # gitDiffFiles $GitStatus $matches['files'] $matches['staged']
    gitFiles $matches['files'] (@($GitStatus.Working.Unmerged) + @($GitStatus.Working.Modified))
}
````

For everything else, I reduced my regex case to 1 and I introduced a some helper functions to a) get my reference hints and b) to get all the tracked files in the repository.  I ended up with this:

````
# Handles git dt-c ref1 ref2 <path>
"^(?:\!git z-dt-c)\s+(?<ref1>\S*)\s*(?<ref2>\S*)?$" {
    if ( "$($matches['ref2'])" -ne "" )
    {            
        # If typed in a 'file filter' and hit tab, only returned tracked files matching
        gitTracked $matches['ref2']
    }
    elseif ( "$($matches['ref1'])" -ne "" )
    {            
        # If only first ref is filled in and they tab, return hints + all tracked files
        @(gitRefHints 1) + @(gitTracked $matches['ref2'])
    }
    else
    {
        # If tabbing immediately after the dt-c, just return hints
        gitRefHints 0
    }
}
````

and the helpers...

````
function script:gitRefHints($offset) {
    $refHints = New-Object System.Collections.Generic.List[string]

    if ( $offset -eq 0)
    {
        $refHints.Add("HEAD~")
    }
    $refHints.Add("HEAD~~")
    if ( $offset -eq 1)
    {
        $refHints.Add("HEAD~~")
    }
    $refHints.Add("HEAD~N")
    $refHints
}

function script:gitTracked($filter) {
    $git = Invoke-Utf8ConsoleCommand { (git ls-files) } |
        Where-Object { $_ -like "$filter*" } |
        quoteStringWithSpecialChars

    return $git
}
````

If anyone has any comments on how I should have done it.  I'd be happy for the constructive criticism.  Otherwise, feel free to close the issue.

**Comment by rkeithhill** [comment]
posh-git does support simple aliases like `co = checkout` but no, it doesn't support this scenario.  I don't believe this is common enough to warrant adding support. I anyone feels different, feel free to re-open this or submit a new issue.
