### ISSUE TITLE
BranchBehindAndAheadDisplay 'Minimal' Setting

### ISSUE THREAD

**Issue by rdnlsmith** [dahlbyk/posh-git#670]
### System Details

- posh-git version/path: 1.0.0 beta2 ~/.local/share/powershell/Modules/posh-git/1.0.0
- PowerShell version: 6.1.1
- git version 2.19.1
- OS: Unix 4.18.0.16

### Issue Description

Apologies if this has already been answered elsewhere. I did my best to search for relevant information first, but I couldn't find what I was looking for.

When the `BranchBehindAndAheadDisplay` setting was first introduced in #256, `Minimal` would show &#x2191;, &#x2193;, or &#x2195; as appropriate with no counts. As of commit [4d8e08c](https://github.com/dahlbyk/posh-git/commit/4d8e08c1002fe2a220a9288186e6d8c26619a90b), `Minimal` does not show any arrows, but the branch name is still colored red/green/yellow.

Was this a deliberate change? Obviously the color is sufficient to indicate its remote tracking status, but it seemed odd to me that the arrows would be removed given that it still displays the &#x2261; symbol when the branch is even with its remote. I couldn't find an issue where this might have been discussed, and it's not mentioned in the changelog for version 0.7.3, which was the next release after that commit.

I only noticed because I was working on an equivalent feature for lyze/posh-git-sh#37 and I wanted to ensure it behaved the same. I like `Full` myself :smiley:

Thanks for all your work! posh-git is fantastic.

**Comment by rkeithhill** [comment]
Good catch.  Does this display look better?

![image](https://user-images.githubusercontent.com/5177512/54963843-d9582300-4f2f-11e9-9cc6-884f653cdbcf.png)

**Comment by rdnlsmith** [comment]
Looks great!
