### ISSUE TITLE
PowerShell Core crashing on start up after installing posh-git

### ISSUE THREAD

**Issue by StaticSphere** [dahlbyk/posh-git#676]
### System Details

- posh-git version/path: 0.7.3 - C:\tools\poshgit\dahlbyk-posh-git-9bda399
- PowerShell version: 6.2.0
- Git version: 2.21.0.windows.1
- Operating system name and version: Windows 10 Professional, 1809

### Issue Description

I am experiencing a problem with...
After installing posh-git, PowerShell Core crashes on launch. If I remove posh-git, it works again.

I have this in my Windows Event log:
```
Faulting application name: pwsh.exe, version: 6.2.0.0, time stamp: 0x5c410542
Faulting module name: coreclr.dll, version: 4.6.27317.3, time stamp: 0x5c40be0f
Exception code: 0xc0000005
Fault offset: 0x000000000000298e
Faulting process id: 0x4b48
Faulting application start time: 0x01d4f3a9c24c7cf1
Faulting application path: C:\Program Files\PowerShell\6\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\6\coreclr.dll
Report Id: cac91910-7882-44f6-8ae2-ca34e25e8e72
Faulting package full name: 
Faulting package-relative application ID: 
```

And this as well:
```
Application: pwsh.exe
CoreCLR Version: 4.6.27317.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFFD7BF298E (00007FFFD7BF0000) with exit code 80131506.
```

Let me know if there's anything else I can do or provide to help.

**Comment by rkeithhill** [comment]
I'm somewhat skeptical posh-git is causing this. There have been several reports against the PowerShell repo of folks running into the same issue with event log entries very similar to yours - https://github.com/PowerShell/PowerShell/issues/9295

**Comment by StaticSphere** [comment]
Thanks for the link and info! I spent about 10 minutes digging through Google before I posted this, though I searched for "PowerShell Core posh-git" specifically.  I'll go ahead and close the issue.  Hopefully this gets resolved quickly on Microsoft's side.
