### ISSUE TITLE
Best way to abbreviate home path with custom prompt?

### ISSUE THREAD

**Issue by fredrikaverpil** [dahlbyk/posh-git#681]
### System Details

- posh-git version/path: v1.0.0b3
- PowerShell version: 6.2.1
- Git version: 2.21.0.windows.1
- Operating system name and version: Windows 10 Insiders 10.0.18362 (build 18362)

### Issue Description

I have this nice prompt in bash:

![Screenshot 2019-05-22 at 13 46 59](https://user-images.githubusercontent.com/994357/58172223-335b3780-7c98-11e9-8b1c-cf21115a9cc4.png)

...which I am trying to set up in Windows with posh-git. This is what I have in my `Profile.ps1`:

```powershell
Import-Module PSColor  # https://github.com/Davlind/PSColor
Import-Module posh-git  # https://github.com/dahlbyk/posh-git

function last_exit_code([int]$code) {
  if ($code -eq 0) {
    return Write-Prompt "0" -ForegroundColor "#bdd7a6"
  } else {
    return Write-Prompt "$($code)" -ForegroundColor "#ee8e96"
  }
}

function last_cmd_time {
  $command = Get-History -Count 1
  $dt = $command.EndExecutionTime - $command.StartExecutionTime

  if (!$command) {
    return ""
  } elseif ($dt.Seconds -lt 1) {
    return "(" + "$($dt.Milliseconds.toString())ms)"
  } else {
    return "(" + "$($dt.Seconds.toString())s, $($dt.Milliseconds.toString())ms)"
  }
}

function prompt {
  $origLastExitCode = $LASTEXITCODE

  $prompt = ""

  $prompt += Write-Prompt "$(last_exit_code($origLastExitCode)) "
  $prompt += Write-Prompt "$(last_cmd_time) `n"
  $prompt += Write-Prompt "$($env:username)@$($env:computername) " -Foreground "#bdd7a6"
  $prompt += Write-Prompt "$($ExecutionContext.SessionState.Path.CurrentLocation)" -ForegroundColor "#b0c3d4"
  $prompt += Write-VcsStatus
  $prompt += Write-Prompt "$(if ($PsDebugContext) {' [DBG]: '} else {''})" -ForegroundColor Magenta
  $prompt += "`n$('>' * ($nestedPromptLevel + 1)) "

  $LASTEXITCODE = $origLastExitCode
  $prompt
}
```

![Screenshot 2019-05-22 at 15 11 29](https://user-images.githubusercontent.com/994357/58177053-e8dfb800-7ca3-11e9-9ae0-deeeae1903e8.png)

Nice!
But as you can see, my home directory is not abbreviated into `~`, which I would like. Is there anything clever I can do to configure Posh-Git to fix this or do I have to replace this myself using a custom function?

**Comment by rkeithhill** [comment]
Well, you are writing the path yourself.  In `posh-git` v1 we actually abbreviate paths under HOME automatically.   `posh-git` also handles the debug prompt and nested prompt level.  Try this:

```powershell
function prompt {
  $origLastExitCode = $LASTEXITCODE

  $prompt = ""

  $prompt += Write-Prompt "$(last_exit_code($origLastExitCode)) "
  $prompt += Write-Prompt "$(last_cmd_time) `n"
  $prompt += Write-Prompt "$($env:username)@$($env:computername) " -Foreground "#bdd7a6"
  $prompt += & $GitPromptScriptBlock
  $LASTEXITCODE = $origLastExitCode
  $prompt
}
```
Also, PS Core 6.2 has a `Duration` property on HistoryInfo objects so you don't have to compute that unless you still need to have this prompt work on Windows PowerShell 5.  Finally, keep in mind that $LASTEXITCODE is "sticky".  It will remain indicating failure until you run another native exe that succeeds.  I've played around with displaying this in my prompt before and found that bothered me.

BTW in the next update to posh-git, I'm hoping to make it possible to display all of this info using the settings in $GitPromptSettings.  We just need to expose the initial state of `$LASTEXITCODE` and `$?` so they can be accessed from the settings.

**Comment by fredrikaverpil** [comment]
I tried your suggestion to add `$GitPromptScriptBlock` but I cannot get my home dir to get abbreviated to `~`. I even made sure I had this set:

    $GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true

I commented out the entire custom prompt and I still can't get `~` to show (with the above set to `$true`). Could there be a bug in 1.0.0b3?

> Also, PS Core 6.2 has a Duration property on HistoryInfo objects so you don't have to compute that unless you still need to have this prompt work on Windows PowerShell 5.

Ah, good to know! I actually _do_ want this to work in the good old version 5 too, so I will leave it as is for now.

> keep in mind that $LASTEXITCODE is "sticky". It will remain indicating failure until you run another native exe that succeeds. I've played around with displaying this in my prompt before and found that bothered me.

Oohhh.... :sad:

> BTW in the next update to posh-git, I'm hoping to make it possible to display all of this info using the settings in $GitPromptSettings. We just need to expose the initial state of $LASTEXITCODE and $? so they can be accessed from the settings.

👍 but it will still act as "sticky", right?

**Comment by rkeithhill** [comment]
> but it will still act as "sticky", right?

Yes.  That is my current thinking.

**Comment by rkeithhill** [comment]
RE the abbreviated path, I don't think there is a bug. I'm importing beta3 here with no profile tweaking settings:

![image](https://user-images.githubusercontent.com/5177512/58221009-3ffa8280-7cce-11e9-86de-76e2aafdc76c.png)

Make sure your are loading up v1.0.0-beta.3 with `gmo posh-git | % PrivateData | % PSData`.

**Comment by fredrikaverpil** [comment]
Hm, strange. Not sure why I can't get that to work then.

```powershell
> ipmo posh-git -PassThru | % PrivateData | % PSData

Name                           Value
----                           -----
Tags                           {git, prompt, tab, tab-completion…}
Prerelease                     beta3
ProjectUri                     https://github.com/dahlbyk/posh-git
LicenseUri                     https://github.com/dahlbyk/posh-git/blob/v1.0.0-beta3/LICENSE.txt
ReleaseNotes                   https://github.com/dahlbyk/posh-git/blob/v1.0.0-beta3/CHANGELOG.md
```

No biggie. This is my final and awesome prompt, defined in my `Profile.ps1`:

```powershell
# Import modules
# See modules paths with command: $env:PSModulePath
Import-Module PSColor  # https://github.com/Davlind/PSColor
Import-Module posh-git  # https://github.com/dahlbyk/posh-git


function last_cmd_time {
  $command = Get-History -Count 1
  $dt = $command.EndExecutionTime - $command.StartExecutionTime
  if (!$command) {
    return ""
  } elseif ($dt.Seconds -lt 1) {
    return "(" + "$($dt.Milliseconds.toString())ms)"
  } else {
    return "(" + "$($dt.Seconds.toString())s, $($dt.Milliseconds.toString())ms)"
  }
}


function last_exit_code([int]$code) {
  if ($code -eq 0) {
    return Write-Prompt "0" -ForegroundColor "#bdd7a6"
  } else {
    return Write-Prompt "$($code)" -ForegroundColor "#ee8e96"
  }
}


function path_shortener([string]$path) {
  if ($path.StartsWith("$($HOME)")) {
    $path = $path.Replace("$($HOME)", "~")
  }
  return $path
}


function prompt {
  $origLastExitCode = $LASTEXITCODE

  $prompt = ""

  $prompt += Write-Prompt "$(last_exit_code($origLastExitCode)) "
  $prompt += Write-Prompt "$(last_cmd_time) `n"
  $prompt += Write-Prompt "$($env:username)@$($env:computername) " -Foreground "#bdd7a6"
  $prompt += Write-Prompt "$(path_shortener($ExecutionContext.SessionState.Path.CurrentLocation))" -ForegroundColor "#b0c3d4"
  $prompt += Write-VcsStatus
  $prompt += "`n$('>' * ($nestedPromptLevel + 1)) "

  $LASTEXITCODE = $origLastExitCode
  $prompt
}
```
