### ISSUE TITLE
WindowTitle not showing in Windows Terminal preview

### ISSUE THREAD

**Issue by thomaslevesque** [dahlbyk/posh-git#685]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.18362.145
- git version 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.18362.0

### Issue Description

Even though `$GitPromptSettings.EnableWindowTitle` is true, the name of the repo doesn't appear in the tab title in [Windows Terminal](https://github.com/Microsoft/Terminal).

I first thought it was a problem in Windows Terminal itself, because it works fine in ConEmu, but now I wonder... Setting `$Host.UI.RawUI.WindowTitle` works fine in both ConEmu and Windows Terminal.

**Comment by rkeithhill** [comment]
Would you be willing to try a beta version of v1?  I use v1 with Windows Terminal and I don't see any issues.  I will warn you that if you've significantly customized `$GitPromptSettings`, that variable's structure has changed to take advantage of v5 classes.  You can upgrade to v1 beta.3 by running:
```
PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force
```
This [section of the readme](https://github.com/dahlbyk/posh-git#customizing-the-posh-git-prompt) covers how to customize your prompt with the updated structure of `$GitPromptSettings`.

**Comment by thomaslevesque** [comment]
@rkeithhill, thanks. v1 beta.3 doesn't solve the problem, but I think I found the culprit: I'm also using [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh). When I disable it, the window title is correctly set.
Not sure why it behaves like this only in Windows Terminal, but anyway, the problem doesn't seem to be in posh-git. Sorry for the false alarm!
