### ISSUE TITLE
Changing IndexColor or WorkingColor has no effect

### ISSUE THREAD

**Issue by JGCreator** [dahlbyk/posh-git#687]
### System Details

- posh-git version/path:
- PowerShell version:
- Git version:
- Operating system name and version:

### Issue Description

Similar to #112 when I change the value of `IndexColor` and `WorkingColor` from DarkGreen or DarkRed respectively to Green or Red respectively, there is no change to the output of the status for items in the index or in the working tree.

**Comment by rkeithhill** [comment]
What version of `posh-git`?  v0.7 or v1.0 beta?  Also, I can't repro this on v1 beta.3.  I have observed that quite often the color palette for the conhost using the same color for Red/DarkRed and Green/DarkGreen. Execute this and see what (bg) colors you get:
```powershell
0..15 | % { $consoleColor = [ConsoleColor]$_; Write-Host "  $consoleColor  " -BackgroundColor $consoleColor }
```
This is what I get:

![image](https://user-images.githubusercontent.com/5177512/62337135-a222f100-b490-11e9-96aa-995b18b38876.png)

**Comment by dahlbyk** [comment]
Do you mean the posh-git status (`[+1 ~1 -1]`) or the actual output of `git status`?

**Comment by JGCreator** [comment]
The output of `git status` used to output staged changed in green and unstaged or untracked items as red, but after installing the module those are dark green and dark red respectively.

Only configuring gits global config to "green bold" and "red bold" has restored the original colors.

**Comment by dahlbyk** [comment]
I would be astonished if installing posh-git had changed those colors; I can't think of anything we do that would affect that.

**Comment by dahlbyk** [comment]
I can't reproduce this. Please reopen if you can provide more details about what's not working as you expect.
![image](https://user-images.githubusercontent.com/133987/76676202-2e50d700-658f-11ea-8e9c-f453815f73f6.png)
