### ISSUE TITLE
Can I show the current revision/version of the branch in the prompt?

### ISSUE THREAD

**Issue by ramonsmits** [dahlbyk/posh-git#69]
Posh shows the current branch in the commandprompt but it would be nice if it could also show the current branch revision/version/shorthash.

Maybe this is already possible but I'm not a powershell wizard yet.

**Comment by rkeithhill** [comment]
See issue #345.  I think a better approach to such niche customization is to make it easier for folks to customize the content of the Git status summary text rather than adding more & more options to posh-git.
