### ISSUE TITLE
when using msys2 git it shows [39m~\wsr\Scripts [93m[[39m[96mdevelop[39m[31m

### ISSUE THREAD

**Issue by Johnleegy** [dahlbyk/posh-git#690]
### System Details

- posh-git version/path: 1.0.0.0 beta3x ~\wsr\Scripts\posh-git\src
- PowerShell version: 5.1.17763.592
- git version 2.22.0
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

posh-git used to be normal when I was using git for windows. I don't want two versions of git in my computer and I plan to use git under msys2. After I changed the path to msys2 git, the posh-git showed me like this:  [39m~\wsr\Scripts [93m[[39m[96mdevelop[39m[31m +0[39m[31m ~2[39m[31m -0[39m[31m ![39m......
Can I solve it by configing something?

**Comment by rkeithhill** [comment]
Try setting `$GitPromptSettings.AnsiConsole = $false`.

**Comment by Johnleegy** [comment]
> 
> 
> Try setting `$GitPromptSettings.AnsiConsole = $false`.

It works. thank a lot.

**Comment by Johnleegy** [comment]
I now use msys2 git. The prompt line is ok after I set $GitPromptSettings.AnsiConsole = $false.
The new problem is everytime when I type in git and press <tab>,  the git command become [93mgit[33m[45m [33madd[33m[45m[0m and the prompt line is still ok.
Any solution?

**Comment by Johnleegy** [comment]
Is there a setting like $GitTabSettings.AnsiConsole or $GitCompleteSettings.AnsiConsole?

**Comment by rkeithhill** [comment]
No, not in `posh-git`.  The only aspect of `posh-git` that is injecting VT esc seqs is the prompt display - not tab-completion.  And you have disable those VT esc seqs in the prompt with `$GitPromptSettings.AnsiConsole = $false`.   It looks like something (git?) is trying to display `git` in bright fg yellow and `add` in fg yellow / bg magenta.  That is ... odd.  What is your `$env:TERM` env var set to?

**Comment by Johnleegy** [comment]
SHELL=/usr/bin/bash
TERM=xterm
MSYSTEM=MSYS

Under cmder, all are ok. I'm using cmder now.

**Comment by Johnleegy** [comment]
> 
> 
> No, not in `posh-git`. The only aspect of `posh-git` that is injecting VT esc seqs is the prompt display - not tab-completion. And you have disable those VT esc seqs in the prompt with `$GitPromptSettings.AnsiConsole = $false`. It looks like something (git?) is trying to display `git` in bright fg yellow and `add` in fg yellow / bg magenta. That is ... odd.
> 
> What is your `$env:TERM` env var set to?

In powershell the $evn:TERM is unset.

**Comment by rkeithhill** [comment]
Wasn't sure if you were seeing this issue running PowerShell in its native conhost or running PowerShell in another terminal like Cmder, ConEn, WindowsTerminal, mintty.  So which one of these are you seeing the issue in - cmder?

**Comment by Johnleegy** [comment]
> 
> 
> Wasn't sure if you were seeing this issue running PowerShell in its native conhost or running PowerShell in another terminal like Cmder, ConEn, WindowsTerminal, mintty. So which one of these are you seeing the issue in - cmder?

I met this issue in its native conhost, in conhost the variable $env:TERM isn't set. and now I'm using cmder, because in cmder posh-git works fine with msys2 git.

**Comment by Johnleegy** [comment]
> 
> 
> > Wasn't sure if you were seeing this issue running PowerShell in its native conhost or running PowerShell in another terminal like Cmder, ConEn, WindowsTerminal, mintty. So which one of these are you seeing the issue in - cmder?
> 
> I met this issue in its native conhost, in conhost the variable $env:TERM isn't set. and now I'm using cmder, because in cmder posh-git works fine with msys2 git.

Oh, I forget to tell you, that my git for windows is portable version. Is that a problem?

**Comment by dahlbyk** [comment]
> It looks like something (git?) is trying to display `git` in bright fg yellow and `add` in fg yellow / bg magenta. That is ... odd.

I'm pretty sure this is PowerShell tab expansion injecting ANSI coloring. This is what I see in the normal host - note `git` in yellow:

![image](https://user-images.githubusercontent.com/133987/64659652-7fc2b280-d402-11e9-89bc-1e7c367b89dd.png)

And fg yellow + bg magenta is the default `ScreenColors` used for the blue PowerShell background.

------

It seems to me like PowerShell believes you're running in a Host that supports ANSI, so it's tab-completing with color codes. Can you check `$Host.UI.SupportsVirtualTerminal`?

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L42-L84

**Comment by dahlbyk** [comment]
I'm going to go ahead and close this, as it seems to be a PowerShell + msys2 issue rather than posh-git functionality, but please do share what you figure out.
