### ISSUE TITLE
Support completion for new `git switch` and `git restore` commands

### ISSUE THREAD

**Issue by kidonng** [dahlbyk/posh-git#691]
Git 2.23 brings some new features which include two new commands: `git switch` and `git restore`, which are meant to eventually provide a better interface for `git checkout`.

https://github.blog/2019-08-16-highlights-from-git-2-23/#experimental-alternatives-for-git-checkout

**Comment by rkeithhill** [comment]
Saw that yesterday.  These are still experimental and the blog post does mention that these could change (names, parameters, etc) before shipping in final form.  I'd be inclined to wait for the commands to be finalized before adding support for them in posh-git. But maybe @dahlbyk has a different take?

**Comment by pinkfloydx33** [comment]
This feature was automatically enabled for me the last time I updated git. I don't have any experimental flags enabled or anything like that, so I think its mainstream at this point.

I've updated my local copy of the module to support this command, will you take a PR for the update?

**Comment by kidonng** [comment]
@pinkfloydx33 Just show your fantastic work to the world☺️

**Comment by dahlbyk** [comment]
> will you take a PR for the update?

Yes!

**Comment by crackedmind** [comment]
> Saw that yesterday. These are still experimental and the blog post does mention that these could change (names, parameters, etc) before shipping in final form. I'd be inclined to wait for the commands to be finalized before adding support for them in posh-git. But maybe @dahlbyk has a different take?

I don't know why github blog said experimental about this feature. Because no mentions about this in official changelog. It's look stable
https://github.com/git/git/blob/master/Documentation/RelNotes/2.23.0.txt#L61

**Comment by rkeithhill** [comment]
@pinkfloydx33 Can you take a look at my PR (#702) and see how it compares to the changes you made to add support for these two commands.

**Comment by Himura2la** [comment]
How soon should it be available in PowerShell Gallery? Two extremely often-used commands are not live in half a year after merge, is it Really OK?

**Comment by rkeithhill** [comment]
The beta, which supports these two sub-commands, is in the PowerShell Gallery.

https://www.powershellgallery.com/packages/posh-git/1.0.0-beta4

**Comment by Himura2la** [comment]
@rkeithhill  thank you, I did not notice it
