### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by jbruns2019** [dahlbyk/posh-git#700]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.14409.1018
- git version 2.23.0.windows.1
- OS: Microsoft Windows NT 6.1.7601 Service Pack 1

### Issue Description

Can this module be used to list all projects that my login has access to or that my group has access to?

**Comment by dahlbyk** [comment]
> Can this module be used to list all projects that my login has access to or that my group has access to?

Nope, this  project is focused on tab completion and prompt status for the current repo.
