### ISSUE TITLE
Prompt error in remote PSSession

### ISSUE THREAD

**Issue by fullenw1** [dahlbyk/posh-git#708]
### System Details

- posh-git version/path: 0.7.3  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5      1      14409  1018 
- Git version: 1.9.5.msysgit.0
- Operating system name and version: Win32NT             6.3.9600.0 Microsoft Windows NT 6.3.9600.0

### Issue Description

When I am in a remote PSSession, the prompt displays an error message:

`C:\Repo [Error: Exception setting "OutputEncoding": "The handle is invalid.`
`"][ComputerName]: >`

When I am in a local PowerShell session on the same computer, the prompt works fine.

`C:\Repo [master ≡]>`

**Comment by rkeithhill** [comment]
Can you repro that and then execute `$error[0] | Format-List * -Force` and paste the output here.

**Comment by fullenw1** [comment]
PSMessageDetails      : 
Exception             : System.Management.Automation.SetValueInvocationException: Exception setting "OutputEncoding": "The handle is invalid.
                        " ---> System.IO.IOException: The handle is invalid.
                        
                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                           at System.Console.set_OutputEncoding(Encoding value)
                           at CallSite.Target(Closure , CallSite , Type , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-Utf8ConsoleCommand, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\Utils.ps1: line 42
                        at Get-GitStatus, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitUtils.ps1: line 236
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitPrompt.ps1: line 330
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitPrompt.ps1: line 324
                        at Global:Write-VcsStatus, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\GitPrompt.ps1: line 324
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3\posh-git.psm1: line 56
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by labrunning** [comment]
I'm getting the same on the following;

- git version 2.24.0.windows.2
- Windows Server 2012 RC2
- PowerShell Version 5.1.14409.1005
- post-git 0.7.3

**Comment by rkeithhill** [comment]
This is the offending code:
```
    $currentEncoding = [Console]::OutputEncoding
    $errorCount = $global:Error.Count
    try {
        # A native executable that writes to stderr AND has its stderr redirected will generate non-terminating
        # error records if the user has set $ErrorActionPreference to Stop. Override that value in this scope.
        $ErrorActionPreference = 'Continue'
        if ($currentEncoding.IsSingleByte) {
            [Console]::OutputEncoding = [Text.Encoding]::UTF8
        }
        & $cmd
    }
    finally {
        if ($currentEncoding.IsSingleByte) {
            [Console]::OutputEncoding = $currentEncoding # <<< errors here
        }
```
We are trying to revert the OutputEncoding to its original value.  I wonder if we need to be checking the value of `$currentEncoding` before trying to set it back.  Will need to look into this some more. It would be nice to know what the value of `$currentEncoding` is in this case.

**Comment by labrunning** [comment]
Here's what my `[Console]::OutputEncoding` is;

```
IsSingleByte      : True  
BodyName          : iso-8859-1  
EncodingName      : Western European (Windows)  
HeaderName        : Windows-1252  
WebName           : Windows-1252  
WindowsCodePage   : 1252  
IsBrowserDisplay  : True  
IsBrowserSave     : True  
IsMailNewsDisplay : True  
IsMailNewsSave    : True  
EncoderFallback   : System.Text.InternalEncoderBestFitFallback  
DecoderFallback   : System.Text.InternalDecoderBestFitFallback  
IsReadOnly        : True  
CodePage          : 1252  
```

I am remoting onto the server via `Enter-PSSession` if that's of any relevance.

**Comment by fullenw1** [comment]
I have exactly the same OutputEncoding as labrunning.

And indeed you've found the piece of code generating the error :)

```powershell
[Console]::OutputEncoding = [Text.Encoding]::UTF8
Exception setting "OutputEncoding": "The handle is invalid.
"
At line:1 char:1
+ [Console]::OutputEncoding = [Text.Encoding]::UTF8
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

**Comment by rkeithhill** [comment]
Can one of you try changing Utils.ps1 line 42 from this:
```
            [Console]::OutputEncoding = $currentEncoding
```
to
```
            try { [Console]::OutputEncoding = $currentEncoding } catch {}
```
I'm not crazy about just swallowing the exception but if it can get past this **and** still work correctly ...

**Comment by fullenw1** [comment]
Unfortunately, I get the same error.

**Comment by rkeithhill** [comment]
How about this:
```
try { $ErrorActionPreference = 'Stop'; [Console]::OutputEncoding = $currentEncoding } catch {}
```

**Comment by fullenw1** [comment]
Still the same error :(

**Comment by rkeithhill** [comment]
Huh.  And the error you get indicates it is coming from the line (42) that you modified in Utils.ps1?  Is it possible the error is originating from 36?  Maybe comment out line 36 and see if it still fails.

**Comment by labrunning** [comment]
Commenting out line 36 with the last suggested change to line 42 now works for me.

**Comment by fullenw1** [comment]
Yep! works for me too :)

**Comment by rkeithhill** [comment]
Since I'm not able to repro this, can one of you see if my PR branch above fixes the issue for you?  I'd like to verify that before merging it.

**Comment by o-l-a-v** [comment]
I had this problem in PowerShell ISE too.

```powershell
$Global:OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
```

Worked fine from a Windows PowerShell terminal, also PowerShell 7.2.1 from Microsoft Store. But in PowerShell ISE it gave:

```powershell
Exception setting "OutputEncoding": "The handle is invalid.
```

Then I figured out by goofing around that, if you've had any output from CMD first, like so for instance (see under), then it worked.

```powershell
$null = cmd /c ''
```

So in my jank script for using winget-cli to update certain apps if an update is available, due to the output of winget-cli being utf8, I now use following before using winget-cli:

```powershell
$null = cmd /c ''
$Global:OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
```

I thought this find might help others, so figured I should write this somewhere.
