### ISSUE TITLE
Enhancement request: Option to overwrite the current customized prompt

### ISSUE THREAD

**Issue by fullenw1** [dahlbyk/posh-git#709]
### Issue Description
According to the documentation:

> posh-git will not replace the prompt function if it has detected that you have your own, customized prompt function

Ok I have a customized prompt for my general usage. But when I am doing git operations I am completely ok to have a posh-git prompt replacing my current prompt. It better fits to the current situation.
Would it be possible to have the choice with a switch or something like that, so that people with a customized prompt could have the posh-git prompt too?

In #624 you say that passing a parameter to a module is a bit unusual.
But currently, when I open a new tab/console to make git operations, I am doing this, which is a bit unusual too.

```powershell
Remove-Item Function:\prompt
Import-Module posh-git
```

At least I have a not too annoying workaround :)

**Comment by rkeithhill** [comment]
If you have a customized prompt, you can ask `posh-git` for what it would display by executing this in your prompt function:
```
& $GitPromptScriptBlock
```
Be sure to import `posh-git` after you have defined your prompt function in your profile.  See the README for more details: https://github.com/dahlbyk/posh-git#gitpromptscriptblock

**Comment by fullenw1** [comment]
Thanks for this second workaround :)

**Comment by rkeithhill** [comment]
> Would it be possible to have the choice with a switch or something like that, so that people with a customized prompt could have the posh-git prompt too?

Our **solution** to this is to invoke `$GitPromptScriptBlock` as shown above inside your custom prompt function.

**Comment by fullenw1** [comment]
> Our **solution** to this is to invoke `$GitPromptScriptBlock` as shown above inside your custom prompt function.

Thanks @rkeithhill  for your tip! I improved my prompt function with it :-)

```powershell
Function prompt {

    if (Get-Module -Name 'Posh-Git') {
        & $GitPromptScriptBlock
    }
    else {
        #My custom prompt comes here
    }
}
```

When I import the posh-git module, I have the posh-git prompt.
And when I remove the posh-git module from the memory I have my custom prompt back :-)
