### ISSUE TITLE
Git status prompt doesn't work after installation of windows terminal 

### ISSUE THREAD

**Issue by zifeiq** [dahlbyk/posh-git#710]
### System Details

- posh-git version/path: latest as of today
- PowerShell version:
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
- Git version: git version 2.23.0.windows.1
- Operating system name and version: Windows 1903 OS Build 18362.418

### Issue Description

I installed Windows Terminal recently on my machine, and after that, posh-git git status prompt never worked again. Command auto-completion works as usual. 
$Function:promp returns only zlocation related lines.

Any idea on how to diagnose the issue?

Thanks

**Comment by theaquamarine** [comment]
Does it work outside of Windows Terminal? 

Which order are you importing ZLocation and posh-git in your profile? posh-git won't modify your prompt if it's already changed by something else, eg ZLocation. If ZLocation is loaded later, it'll replace your prompt with a line containing ```ZLocationOrigPrompt```, which will contain the prompt as it was before ZLocation loaded. It sounds like this is the issue, so here's how to check (reading your profile would also work).

If you run `$function:ZLocationOrigPrompt`, that'll output the contents of your prompt as ZLocation found it, which will either be something like the contents of https://github.com/dahlbyk/posh-git/blob/a64e5e073f6ce4dcd01394965bf0bbc91a0e3016/src/posh-git.psm1#L31-L117 if you installed posh-git v1 from the gallery and imported it first, or something like this from [the example in the 'Getting the Prompt function' section](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-5.1#getting-the-prompt-function) if ZLocation was imported first.
```powershell
"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
# .Link
# https://go.microsoft.com/fwlink/?LinkID=225750
# .ExternalHelp System.Management.Automation.dll-help.xml
```

**Comment by rkeithhill** [comment]
In your profile script, make sure you import posh-git before you import zlocation.  As long as you're using the latest zlocation, it will copy the original prompt function and invoke it after zlocation has updated with the current dir.  OTOH if posh-git sees you have a modified (from the PS default) prompt function, it does nothing to your prompt function.  It figures if you have made the effort to create a customized prompt function, it won't mess with it.

FWIW I've been using posh-git in Windows Terminal since May with no issues.

**Comment by zifeiq** [comment]
Putting posh-git before z-location solved my problem. Thank you all!
