### ISSUE TITLE
Tab completion doesn't work when TabExpansionPlusPlus module is imported before Posh-Git

### ISSUE THREAD

**Issue by kborowinski** [dahlbyk/posh-git#715]
### System Details

- posh-git version/path: 1.0.0.0 beta3x C:\Program Files\PowerShell\Modules\Posh-Git\1.0.0.0
- PowerShell version: 7.0.0-preview.5
- git version 2.24.0.windows.1
- OS: Microsoft Windows NT 10.0.18362.0

### Issue Description

When *TabExpansionPlusPlus* module is imported before *Posh-Git* module the tab completion for *git.exe* does not work anymore due to *Register-ArgumentCompleter* cmdlet name conflict. 

**Fix:**
Use module-qualified cmdlet name *Microsoft.PowerShell.Core\Register-ArgumentCompleter*

**Comment by kborowinski** [comment]
Apparently @rkeithhill is faster than light and merged my PR already before I was able to create the issue report. Please close this issue.

**Comment by rkeithhill** [comment]
:-)   Thanks for finding & fixing the issue.
