### ISSUE TITLE
Add support for git switch and git restore.

### ISSUE THREAD

**Issue by jsj1027** [dahlbyk/posh-git#717]
### System Details

- posh-git version/path: 0.7.3  ~\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.17763.771
- git version 2.23.0.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description
Git added two quality of life features in git switch and git restore.
Posh-Git could autocomplete these features.

Git Switch - fast way to switch branches.
Git Restore - fast way to roll files back to the current remote version.

**Comment by rkeithhill** [comment]
This has been implemented on the `master` branch.  It is targeted for release in v1.  Unfortunately, to use it now you'd have to git clone the repo and import the module from there.  Hopefully, we can get a v1 beta4 out in the not too distant future.  Then you would be able to install the beta from the PSGallery and try out the support for git restore/switch.
