### ISSUE TITLE
Update default color scheme

### ISSUE THREAD

**Issue by koistya** [dahlbyk/posh-git#72]
Dark red color is barely visible on the dark blue background of the PowerShell window :(

`C:\Projects\SiteSDK [master +0 ~1 -0]>`

**Comment by dahlbyk** [comment]
Pondering this today... I wonder if it would make sense for `$GitPromptSettings` to parse the `color.branch.<slot>` settings when the module loads to respect those if set, falling back on the [`git status` defaults](https://github.com/git/git/blob/e46fe3df01435bf523d2ab4f2755556c0e4e6f78/wt-status.c#L23-L33) if not?

**Comment by dahlbyk** [comment]
I'm finally coming around... proposed workaround: https://github.com/dahlbyk/posh-git/pull/197#issuecomment-107987397

**Comment by dahlbyk** [comment]
Fixed by #197.
