### ISSUE TITLE
posh-git is also on Scoop

### ISSUE THREAD

**Issue by Witchilich** [dahlbyk/posh-git#724]
### System Details

- posh-git version/path:
- PowerShell version: 5.1
- Git version:
- Operating system name and version: Windows 10

### Issue Description
The readme mentions Chocolatey, but its also on Scoop.
```
scoop bucket add extras
scoop install posh-git
```

**Comment by vincentmathis** [comment]
It can't find a manifest if i try to install trough scoop though.

**Comment by rkeithhill** [comment]
Is the ask here to add these instructions to the "installing" section of the README?

**Comment by elsassph** [comment]
Scoop and Chocolatey are at version 0.7.3.1 - isn't that out of date-ish?
It can really hurt to have outdated packages through these tools.

PS: it wouldn't hurt to add it to the readme

**Comment by rkeithhill** [comment]
Yeah, that is out of date except that 1.0 is still in beta (has been for over a year).  Ideally, we'd publish another beta of 1.0 and then do a 1.0 release.  But that's up to @dahlbyk.

**Comment by dahlbyk** [comment]
> Scoop and Chocolatey are at version 0.7.3.1 - isn't that out of date-ish?

Can't speak to Scoop, but I haven't decided for sure what the plan is for Chocolatey with 1.0: #328, #473.

I'm fine with listing Scoop as a distribution mechanism, if someone wants to submit instructions.

**Comment by jimleroyer** [comment]
@dahlbyk Just submitted instructions via this PR: https://github.com/dahlbyk/posh-git/pull/763

Regarding availability of official build vs beta releases, I've observed that Scoop treats the project as a different one with a `-beta` appended, e.g `posh-git-beta`. Hence we could offer it in Scoop without overriding the official release. That gist is a Scoop manifest example for *posh-git 1.0.0-beta4*. I might offer that one to the scoop-extras bucket so it's available to everyone interested in the beta, if you are okay with that.
