### ISSUE TITLE
PowerShell ForeGroundText changes to bright white after call

### ISSUE THREAD

**Issue by robmen** [dahlbyk/posh-git#730]
- posh-git version/path: 1.0.0.0 beta3x C:\Program Files (x86)\Git\Powershell\Modules\posh-git
- PowerShell version: 5.0.10586.51
- git version 2.24.0.windows.2
- OS: Microsoft Windows NT 6.3.9600.0

### Issue Description

I am experiencing a problem with...

Updated from 1.0.0.0 beta2 and after a call to `Write-VcsStatus` in the prompt, the cmd foreground text changes to bright white. The image below shows how the cmd foreground starts gray then changes to bright white after the first prompt display in the `example-repo`

![image](https://user-images.githubusercontent.com/131904/71753181-9ae48280-2e36-11ea-9247-33d66cd9c06a.png)

Notice the second `ls` command characters I typed are also bright white.

The salient parts of my profile:

```
$GitPromptSettings.WorkingColor.ForegroundColor = "Gray"
$GitPromptSettings.PathStatusSeparator = ''
$GitPromptSettings.AfterStatus.Text = '] '

$administrator = $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
```

and

```
$terminator = if ($administrator) { '!' } else { '$' }

$prompt = ""
$prompt += Write-Prompt "$($pwd.ProviderPath) `n" -ForegroundColor DarkGray
$prompt += Write-VcsStatus
$prompt += Write-Prompt "$terminator " -ForegroundColor DarkGray
```

Let me know if I can provide additional information.

**Comment by rkeithhill** [comment]
I'm trying to reproduce what you see but haven't been able to yet.  Are you using a `git clone` install of this module?  If so, are you using latest on `master`?  Also, how have you defined `$terminator`?

It looks like you're running this on Windows 8.1, right?  Can you confirm that either the `$host.UI.SupportsVirtualTerminal` property doesn't or if it does, it returns `$false`?  Sorry, I don't have any Windows 8 machines anymore to test on.

Finally, can you start PowerShell with `-noprofile` and do a `ls`?  I want to see what the default fg color should look like.

**Comment by robmen** [comment]
* Latest on `master`? Yes, cloned it this morning.
* How defined `$terminator`? Updated my profile code in the original question, it's just a char.
* Windows 8.1? Yes.
* `$host.UI.SupportsVirtualTerminal` property? Does not exist.
* PowerShell with -noprofile? Bright blue background with bright white foreground:

````
PS> $host.UI.RawUI

ForegroundColor       : DarkYellow
BackgroundColor       : DarkMagenta
CursorPosition        : 0,103
WindowPosition        : 0,54
CursorSize            : 25
BufferSize            : 120,3000
WindowSize            : 120,50
MaxWindowSize         : 120,118
MaxPhysicalWindowSize : 365,118
KeyAvailable          : False
WindowTitle           : Windows PowerShell
````

**Comment by rkeithhill** [comment]
Thanks for the extra info.  Can you edit `GitPrompt.ps1` and comment out line 900:
```
    Set-ConsoleMode -ANSI
```
And see if that changes the behavior you are seeing?

**Comment by robmen** [comment]
Commented out that line and it did _not_ seem to change anything. I noticed when I printed `$GitPromptSettings` I saw similar switching between normal gray font and bright white font. Maybe this is useful?

![image](https://user-images.githubusercontent.com/131904/71782408-6552ad00-2f8e-11ea-833e-58bd77c67ae2.png)

The end result is also bright white text in the prompt command and output.

**Comment by rkeithhill** [comment]
It is interesting that the `AnsiConsole` setting above shows `True`.  That must mean `$env:ConEmuANSI` is set. I suppose Cmder is setting that.  If you set `$GitPromptSettings.AnsiConsole = 0` does it behave any better?  That might be an OK workaround but doesn't solve the problem which "appears" to be arising from posh-git resetting to the default terminal FG/BG color after displaying ANSI text.  We could test that by firing up PowerShell in Cmder with no posh-git loaded.  Do an `ls` where you should see gray text then execute this line `"$([char]27)[39;49m"` (executes the FG;BG color reset).  Now execute `ls` again and see if the text is white(r).

**Comment by robmen** [comment]
Adding `$GitPromptSettings.AnsiConsole = 0` to my $profile did fix the coloring issue but also added `PS>` to the end of the prompt, like so:

    E:\src
    $ PS>

Strange.

I also tried `"$([char]27)[39;49m"` in various ways (without posh-git) but it didn't seem to make any difference. Not sure I executed the command correctly. Any additional detail I can provide?

**Comment by rkeithhill** [comment]
To fix the `$ PS>` issue, make sure the last line of your prompt function is this:
```
if ($prompt) { "$prompt " } else { " " }
```
This handles both the ANSI and non-ANSI cases.  In the non-ANSI case, which works better for you, the Write-Prompt/VcsStatus commands directly output the text and return an empty string.  However, if the `prompt` function doesn't return a string of at least 1 char, PowerShell will append the `PS>` automatically.  The `else` clause above handles this.  

You will want to change this line of your prompt from:
```
$prompt += Write-Prompt "$terminator " -ForegroundColor DarkGray
```
to
```
$prompt += Write-Prompt $terminator -ForegroundColor DarkGray
```
The extra space will be handled by the `if ($prompt) ...` line.

**Comment by rkeithhill** [comment]
Also, just noticed that the ANSI seq where the $GitPromptSettings output changes fg color is this `"$([char]27)93m[$([char]27)39m"`.  Try that and see if it displays a `[` char in a brighter white and if the fg stays at that brighter white or resets back to the gray.

**Comment by robmen** [comment]
Ahh, I did not realize `Write-Prompt`/`VcsStatus` wrote straight to the console but that makes complete sense. It fits together better.

I also ran your command `"$([char]27)93m[$([char]27)39m"` and I got this:

    E:\src
    $ "$([char]27)93m[$([char]27)39m"
    ←93m[←39m

Nothing ended up bright white, nothing changed color.

**Comment by rkeithhill** [comment]
Argh, sorry. It should be `"$([char]27)[93m[$([char]27)[39m"`.  I was missing a few `[` chars.

**Comment by robmen** [comment]
Yep, that did it.

![image](https://user-images.githubusercontent.com/131904/71839075-35c7a180-306f-11ea-95fe-6b56bcc5be2f.png)

**Comment by rkeithhill** [comment]
So the `"$([char]27)[39m"` is supposed to reset the fg color to the default terminal fg color.  So the question is how to set the "default" fg color.  Click on the Cmder icon and click on Properties and go to the Color tab.  Select "Screen text".  You should see something like this:

![image](https://user-images.githubusercontent.com/5177512/71839437-5cd6a100-3078-11ea-8b81-4828e438fb2a.png)

Now change that index's color to your preferred gray color.  After that, resetting back to that color should display gray text when not display the prompt.

**Comment by robmen** [comment]
Interestingly, that command changes the default colors. Here are the Properties when I start:

![image](https://user-images.githubusercontent.com/131904/71905560-3dde1a80-311d-11ea-9b27-faa0dd822550.png)

And after the command, the Properties are updated.

![image](https://user-images.githubusercontent.com/131904/71905627-6108ca00-311d-11ea-9f68-bb2926041f4e.png)

The "set to bright white command" is working too well. :smile:

**Comment by rkeithhill** [comment]
Interesting indeed.  I did not know this.  Thanks for letting us know.

**Comment by robmen** [comment]
Yeah, I'm good with `$GitPromptSettings.AnsiConsole = 0` as my solution.

Happy to help get to the root of it. Thanks for maintaining `posh-git`.
