### ISSUE TITLE
Powershell 6: Changes to $GitPromptSettings made from the profile do not take effect

### ISSUE THREAD

**Issue by lesscodetxm** [dahlbyk/posh-git#731]
### System Details

- posh-git version/path: 1.0
- PowerShell version: 6.0
- Git version: n/a
- Operating system name and version: Windows 10

### Issue Description

Example: 
$GitPromptSettings.AfterStatus.Text += "`n"

When this is run in a shell, it takes effect. When added to the profile, it doesn't.
Works fine from the profile in PS 5.x

**Comment by rkeithhill** [comment]
Make sure you put this line:
```
$GitPromptSettings.AfterStatus.Text += "`n"
```
After the line with `Import-Module posh-git`.  The order is import otherwise, if you import posh-git later, it will overwrite the existing $GitPromptSettings object.

**Comment by lesscodetxm** [comment]
I do indeed import the module before changing the setting.

**Comment by rkeithhill** [comment]
Try changing to this in your profile:
```
$global:GitPromptSettings.AfterStatus.Text += "`n"
```

**Comment by lesscodetxm** [comment]
Never mind - user error. I'd forgotten that for PS6 the user profile lives in `$HOME\Documents\Powershell` rather than `$HOME\Documents\WindowsPowershell`. posh-git is working correctly.

**Comment by nicmeriano** [comment]
I'm having a similar issue but with the following:
`GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true`
importing posh-git first and it's in the right profile file. Any ideas? I still get the full length path.

**Comment by rkeithhill** [comment]
If you execute this in the running console, does that cause the path to behave as expected?

**Comment by nicmeriano** [comment]
@rkeithhill No, now for some reason it's giving me the following error:

```
The term 'GitPromptSettings.DefaultPromptAbbreviateHomeDirectory' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by nicmeriano** [comment]
I missed the $ at the beginning so it's being recognized, but nothing happens even when I execute it in the running console.

**Comment by rkeithhill** [comment]
What's your prompt function look like -  `gcm prompt | % definition` ?  Also, what version of posh-git are you using?

**Comment by nicmeriano** [comment]
prompt function (using Paradox theme):

```
$lastCommandFailed = $global:error.Count -gt $sl.ErrorCount
        $sl.ErrorCount = $global:error.Count

        #Start the vanilla posh-git when in a vanilla window, else: go nuts
        if(Test-IsVanillaWindow) {
            Write-Host -Object ($pwd.ProviderPath) -NoNewline
            Write-VcsStatus
        }

        Reset-CursorPosition
        $prompt = (Write-Theme -lastCommandFailed $lastCommandFailed)

        if($sl.Options.ConsoleTitle) {
            $location = Get-Location
            $folder = (Get-Item $location.Path).Name
            $prompt += "$([char]27)]2;$($folder)$([char]7)"
            if ($location.Provider.Name -eq "FileSystem") {
                $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
            }
        }

        $prompt
```

posh-git version 0.7.3

**Comment by rkeithhill** [comment]
That isn't the prompt function provided by `posh-git`.  Only that prompt function looks at the `$GitPromptSettings.DefaultPrompt*` settings.  Looks like you are writing out your own path info in the prompt here:
```
            $folder = (Get-Item $location.Path).Name
            $prompt += "$([char]27)]2;$($folder)$([char]7)"
```

**Comment by nicmeriano** [comment]
I'm trying to figure out where that prompt function is coming from. I used `Get-PromptPath` but there is nothing in that directory..

**Comment by dahlbyk** [comment]
> I'm trying to figure out where that prompt function is coming from.

oh-my-posh! https://github.com/JanDeDobbeleer/oh-my-posh/blob/557b467cf3f7891c8de5906ad11b2445249dc4cd/oh-my-posh.psm1#L14-L37
