### ISSUE TITLE
Posh-git not loaded because no valid module file found

### ISSUE THREAD

**Issue by rfalanga** [dahlbyk/posh-git#734]
### System Details

- posh-git version/path: (this is the issue)
- PowerShell version: 6.2.3  (PowerShell Core)
- Git version: 2.25.0.windows.1
- Operating system name and version: Windows 10.0.18362

### Issue Description

I am experiencing a problem with trying to import posh-git. I already have posh-git installed, using Chocolatey. (I tried installing it again using Chocolatey; Chocolatey complained informing me that I already had it installed.) Then I tried issuing the Import-Module posh-git command to import posh-git, so I can use it. However, when I do I get this error:

> Import-Module : The specified module 'posh-git' was not loaded because no valid module file was found in any module directory.
> At line:1 char:1
> + Import-Module posh-git
> + ~~~~~~~~~~~~~~~~
> undException
> + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModule Command
> 

This confuses me. Is it installed or not?

**Comment by rkeithhill** [comment]
PowerShell's `Import-Module` only looks in specific locations for PowerShell modules.  You can see those locations in `$env:PSModulePath`.  If the module is not installed in one of those locations, it won't be found during import.  You have two options: 1) add the install path - wherever choco put the module in the PSModulePath env var or 2) use PowerShell's built-in command to install the module: `Install-Module posh-git -Scope CurrentUser -Force -AllowClobber -AllowPrerelease`.

**Comment by rfalanga** [comment]
@rkeithhill how do I find out where posh-git is installed?

**Comment by rkeithhill** [comment]
Look under `C:\ProgramData\chocolatey\`, particularly `C:\ProgramData\chocolatey\lib`.

**Comment by rkeithhill** [comment]
I forgot to mention, another option is to use the full path to posh-git.psd1 e.g. `Import-Module <full-path-posh-git.psd1>`

**Comment by dahlbyk** [comment]
> Look under `C:\ProgramData\chocolatey\`, particularly `C:\ProgramData\chocolatey\lib`.

More specifically, we use [`Get-ToolsLocation`](https://chocolatey.org/docs/helpers-get-tools-location):
https://github.com/dahlbyk/posh-git/blob/f69efd9229029519adb32e37a464b7e1533a372c/chocolatey/tools/chocolateyInstall.ps1#L2

Which there's been some discussion about: https://github.com/dahlbyk/posh-git/issues/473.

I'm going to go ahead and close this; please reopen if you're still not able to resolve this.

**Comment by hamjo** [comment]
I just ran into this issue as well. Maybe adding documentation to this command `Install-Module posh-git -Scope CurrentUser -Force -AllowClobber -AllowPrerelease` in the README.md could be useful for future users.

**Comment by rkeithhill** [comment]
Actually, you should remove the `-AllowPrerelease` parameter so that you can install the latest, stable version of posh-git.  There is a PR to update the README.md to remove this parameter from the instructions.

**Comment by SeriousLee13** [comment]
When importing the module with @rkeithhill 's `Import-Module <full-path-posh-git.psd1>`, make sure that no directory in the path string contains any spaces, and if one does, put it in double-quotes, e.g. `Import-Module D:\Users\"Name Surname"\Documents\...`.
I just spent a frustrating amount of time figuring that out.

**Comment by rkeithhill** [comment]
If there is a space in the path, I'd recommend quoting the whole path:
```powershell
Import-Module 'D:\Users\Name Surname\Documents\github\posh-git\src\posh-git.psd1'
```
In fact, if you start typing that at the console and use tab-completion for the path, PowerShell will put quotes around the path for you.

**Comment by vedanth-subramaniam** [comment]
My customization used to work fine but suddenly I started encountering this issue.
![image](https://user-images.githubusercontent.com/43824706/155875550-eed8b5c6-85cd-4eb9-9bce-a3a8adcc635e.png)

**Comment by agtenr** [comment]
I'm having the same issue as @vedanth-subramaniam . Any updates on this?

**Comment by dahlbyk** [comment]
It looks like the module just isn't available. I'm guessing your `$PROFILE` has simply `Import-Module posh-git`, and if you run `Get-Module posh-git` you won't find anything. (Same for `oh-my-posh`, in @vedanth-subramaniam's screenshot.)

`Import-Module` will look for `posh-git` in any of the folders listed in `$env:PSModulePath`. If you have posh-git installed elsewhere (e.g. an old version with Chocolatey), then you need to `Import-Module C:\full\path\to\posh-git.psd1`.

**Comment by agtenr** [comment]
Thanks @dahlbyk for the info. I was able to solve this by referencing the full path. Thanks

**Comment by vedanth-subramaniam** [comment]
> Thanks @dahlbyk for the info. I was able to solve this by referencing the full path. Thanks

Hey how were you able to locate the full path of posh-git?
