### ISSUE TITLE
Garbled output when typing "git gui"

### ISSUE THREAD

**Issue by patrikhuber** [dahlbyk/posh-git#738]
### System Details

- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.2.4
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.18362.0

### Issue Description

posh-git seems to work fine overall. However when typing `git gui`, the git gui window opens, but on the powershell prompt, the encoding of the characters is outputted and the cursor stays on that line. Only after pressing "Enter", the prompt becomes "normal" again.

```
~\MyProj [mybranch +2 ~2 -0 !]> git gui    <-- nicely colourised
~\MyProj [93m[[0m[96mmybranch[0m[31m[49m +2[0m[31m[49m ~2[0m[31m[49m -0[0m[31m ![0m[93m][0m>    <-- no colours, "weird" output. Have to press "enter" to get prompt to normal again.
~\MyProj [mybranch +2 ~2 -0 !]>    <-- nicely colourised
```

![image](https://user-images.githubusercontent.com/4967343/74587540-ab6a4a00-4feb-11ea-93fb-99cadce54d23.png)

**Comment by dahlbyk** [comment]
Fascinating. Closing here, as it seems not to be posh-git specific: https://github.com/microsoft/terminal/issues/4809.

Probably something that needs to be fixed in `git gui`?

**Comment by patrikhuber** [comment]
Thanks, I don't know how these things interact but I've followed your advise and opened https://github.com/prati0100/git-gui/issues/34.

**Comment by dahlbyk** [comment]
Quite the [conclusion](https://github.com/microsoft/terminal/issues/4921#issuecomment-599135352):

> Unfortunately, there isn't anything powershell (or the windows console!) can do to help this situation: the input mode is console-wide global state, and sh.exe is setting that global state to ignore powershell's text rendering commands.
