### ISSUE TITLE
posh-git does not work at all

### ISSUE THREAD

**Issue by rasolo** [dahlbyk/posh-git#739]
### System Details

- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.2.4
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

I have installed posh-git on two different Windows 10 laptops using every windows 10 installation method available in the readme and it refuses to work. I have gone through the FAQ and searched for answers such as https://github.com/dahlbyk/posh-git/issues/409 but I can't get it working.
The git prompt wont show up:

```
PS C:\Projects\website> import-module posh-git
PS C:\Projects\website> git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
PS C:\Projects\website>
```

**Comment by rkeithhill** [comment]
First, check to see if tab-completion is working.  From `C:\Projects\website> ` type `git chec<tab>` and see if that auto-completes to `checkout`.  If that works, then `posh-git` has been imported successfully.  That fact that it didn't change your prompt indicates it thinks you have already customized your prompt, in which case, it will not overwrite the prompt function.

**Comment by rasolo** [comment]
> 
> 
> First, check to see if tab-completion is working. From `C:\Projects\website> ` type `git chec<tab>` and see if that auto-completes to `checkout`. If that works, then `posh-git` has been imported successfully. That fact that it didn't change your prompt indicates it thinks you have already customized your prompt, in which case, it will not overwrite the prompt function.

@rkeithhill Thanks, the auto-complete does work! Do you know how I can get it o overwrite the prompt function?

**Comment by rkeithhill** [comment]
If you are not explicitly creating your own `prompt` function in your profile, then perhaps another module that you import is doing this.  First, let's see what your prompt function looks like.  Execute `Get-command prompt | % Definition` and post the output here.

**Comment by rasolo** [comment]
@rkeithhill I was able to fix it. I am using Z-location which override the default prompt or something which stops it working, I think.

But by posting this in the Powershell shell (and later my Powershell profile so that it is permanent) I was able to get it working:

```
function prompt {
    # Your non-prompt logic here

    # Have posh-git display its default prompt
    & $GitPromptScriptBlock
}
```

That will force the posh prompt to display:

```
> z web
C:\Projects\website
>  function prompt {
>>     # Your non-prompt logic here
>>
>>     # Have posh-git display its default prompt
>>     & $GitPromptScriptBlock
>> }
C:\Projects\website [develop ≡]>
```

Code taken from here: https://github.com/dahlbyk/posh-git/wiki/Customizing-Your-PowerShell-Prompt


Thanks for the help! Closing issue

**Comment by rkeithhill** [comment]
@rasolo Glad you got it working.  What is weird is that I've had a few PRs merged to Z-location to make it work better with posh-git.  Looks like I need to revisit Z-location to see why that isn't working anymore.  :-(

**Comment by rasolo** [comment]
@rkeithhill Thanks! Unfortunate that it seems to have stopped working.. Here is the output I get when I do not use the posh-git function, when it does not work:

```
PS C:\Users\Rasmus> Get-command prompt | % Definition

            Update-ZLocation $pwd
            ZLocationOrigPrompt

PS C:\Users\Rasmus>

```

**Comment by glenncarr** [comment]
Thanks for this!
