### ISSUE TITLE
Strange and unnecessary characters in the git prompt.

### ISSUE THREAD

**Issue by rasolo** [dahlbyk/posh-git#740]
### System Details

- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.2.4
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.18362.0
C:\Projects\react_crash_todo [master ≡ +

### Issue Description

Strange and unnecessary characters in the git prompt.
It looks like this:

`C:\Projects\react_crash_todo [master ≡ +0 ~2 -0 !]>`

Simply outputting master (branch name) would be enough.

My powershell profile looks like this:

```
import-module posh-git

 function prompt {
    # Your non-prompt logic here
    $GitPromptSettings.BranchNameLimit=15
    # Have posh-git display its default prompt
    & $GitPromptScriptBlock
}
```

On my other laptop it works great without the weird characters and the same powershell profile.

**Comment by rkeithhill** [comment]
Those strange characters are showing you your Git status i.e. you have 0 new (untracked) files, 2 files that have been modified and 0 deleted files.  See the README section on the [Git status summary](https://github.com/dahlbyk/posh-git#git-status-summary-information) for details.

If you do not want to see that information, then add the following to your profile after you import `posh-git`:
```
$global:GitPromptSettings.EnableFileStatus = 0
```
On your other laptop, I suspect your workspace is clean, in which case you only see the branch name (and sync status symbol).

**Comment by rasolo** [comment]
Thanks dude, this solved it!
