### ISSUE TITLE
Issue When Updating To Newest Beta v1.0.0-beta4

### ISSUE THREAD

**Issue by blackneuron** [dahlbyk/posh-git#748]
### System Details

- posh-git version/path: 1.0.0 beta3 ~\OneDrive\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.0.0
- git version 2.25.1.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

When I try to upgrade to the newest version, v1.0.0-beta4, I am getting the blow error. I am also attaching a screenshot.

**Index (zero based) must be greater than or equal to zero and less than the size of the argument list.**

![image](https://user-images.githubusercontent.com/1899346/76814575-80813a80-67d1-11ea-9b6b-4a906cdee523.png)

**Comment by rkeithhill** [comment]
There are issues with PoweShellGet/PackageManagement when it comes to pre-release packages.  Try this:
````
Install-Module posh-git -AllowPrerelease -Scope CurrentUser -Force
```

**Comment by blackneuron** [comment]
I had to run Remove-Module posh-git first then remove the folder and then the command above worked. I will check for a bug on PoweShellGet/PackageManagement and comment there. Thank you for your help.
