### ISSUE TITLE
Issue with posh git on PS 7

### ISSUE THREAD

**Issue by AtricoSoftware** [dahlbyk/posh-git#751]
### System Details
- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.0.0
- git version 2.25.1.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description
After upgrading to PS 7 (from 5) I can no longer get posh-git to work.
I have deleted modules, installed with both PowerShellGet and chocolatey (separately, now back with PSG version)
Get-InstalledModule shows 1.0.0-beta4 is installed
Import-Module is called from profile (and has been tried manually)
I have tried both normal and elevated shell.

No PG prompt is seen in any git repo (the same repos look fine using posh git in PS 5)
I've never had any trouble with PG before

**Comment by rkeithhill** [comment]
PS7 uses a different directory structure for its profile scripts.  If you have script to import posh-git and configure it in a profile script located in `$HOME\Documents\WindowsPowerShell`, move that profile into the folder `$HOME\Documents\PowerShell`.

**Comment by AtricoSoftware** [comment]
> PS7 uses a different directory structure for its profile scripts. If you have script to import posh-git and configure it in a profile script located in `$HOME\Documents\WindowsPowerShell`, move that profile into the folder `$HOME\Documents\PowerShell`.

Yep, done!
Module was installed from PS7 and is in the correct folder (as system details show)

**Comment by rkeithhill** [comment]
Is it working now? This is my exact setup.  Running beta4 in PS 7 and I've seen no issues.

**Comment by AtricoSoftware** [comment]
> Is it working now? This is my exact setup. Running beta4 in PS 7 and I've seen no issues.

No, no prompt at all, are there any settings I need to make, I don't remember anything in PS5

**Comment by rkeithhill** [comment]
There could be a number of issues.  Let's start with having you run (from the Windows+r) dialog `pwsh -noprofile`.  After that starts, execute `import-module posh-git -verbose -passhthru`.  You should see something like this:
```
PS C:\Users\Keith> Import-Module posh-git -Verbose -PassThru
VERBOSE: Loading module from path 'C:\Users\Keith\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module posh-git.
VERBOSE: Loading module from path 'C:\Users\Keith\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psm1'.
VERBOSE: Importing function 'Add-PoshGitToProfile'.
VERBOSE: Importing function 'Expand-GitCommand'.
VERBOSE: Importing function 'Format-GitBranchName'.
VERBOSE: Importing function 'Get-GitBranchStatusColor'.
VERBOSE: Importing function 'Get-GitDirectory'.
VERBOSE: Importing function 'Get-GitStatus'.
VERBOSE: Importing function 'Get-PromptConnectionInfo'.
VERBOSE: Importing function 'Get-PromptPath'.
VERBOSE: Importing function 'New-GitPromptSettings'.
VERBOSE: Importing function 'Remove-GitBranch'.
VERBOSE: Importing function 'tgit'.
VERBOSE: Importing function 'Update-AllBranches'.
VERBOSE: Importing function 'Write-GitBranchName'.
VERBOSE: Importing function 'Write-GitBranchStatus'.
VERBOSE: Importing function 'Write-GitIndexStatus'.
VERBOSE: Importing function 'Write-GitStashCount'.
VERBOSE: Importing function 'Write-GitStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatusSummary'.
VERBOSE: Importing function 'Write-Prompt'.
VERBOSE: Importing variable 'GitPromptScriptBlock'.

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0.0      beta4      posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-…
```
If that doesn't work, post here what you see for `$env:PSModulePath` in this pwsh console.

**Comment by AtricoSoftware** [comment]
Awesome, that works now
Must be something In my profile that broke it 
No idea what that is though, I guess I'll add them back in until it breaks again (although I only have a couple of non-related modules)
I'll post back here if I find anything I think will be useful for someone else

Thanks

**Comment by rkeithhill** [comment]
Yes, PS will auto-import a module when you use a command from that module.  

I'm going to close this.  If you think there is still an issue with `posh-git`, you can re-open it.
