### ISSUE TITLE
Location of posh-Git

### ISSUE THREAD

**Issue by eliassal** [dahlbyk/posh-git#754]
- posh-git version/path:
- PSVersion                      5.1.17763.771 :
- Git version:  2.8.1.windows.1
- Operating system name and version: Win 10 64bit

### Issue Description

I triggered setup using
`PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force`

then tried 
`Import-Module posh-git`
I get  

> Import-Module : The specified module 'posh-git' was not loaded because no valid module file was found in any module directory.

Searching my laptop for posh-git, surprisingly, I found the 3 files in 
C:\Users\salam.SALAM\AppData\Local\GitHub\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b

so they  are not in one of my modules directory
Thanks for your help

**Comment by rkeithhill** [comment]
This location `C:\Users\salam.SALAM\AppData\Local\GitHub\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b` is a version of posh-git that shipped with GitHub for Windows IIRC.  I'm pretty sure that isn't where you install put the module. Try installing but add the `-Verbose` so you can see where it installed the module.

**Comment by eliassal** [comment]
Thanks, I did a deep search, found that the install-module has created "tools" directory on the C drive as you can notice in the snapshot, so how should i proceed to be able to use it in PS and do the import module, thanks again
![poshgit](https://user-images.githubusercontent.com/8447864/78164354-eca6a400-7449-11ea-9d74-df513f8864cf.jpg)

**Comment by rkeithhill** [comment]
Looks like you previously did an install of posh-git using Chocolatey. I'm not sure that there is a v1 version of posh-git on Chocolatey.  To install v1, run:
```
PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force -Verbose
```
The very last line of verbose output should tell us where the module was installed.  Once we know that, we can go from there. Most likely, need to tweak our PSModulePath a bit.

**Comment by eliassal** [comment]
Yes, I used choco. Thes statement you suggest does not go through, following error is generated

> Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
> At line:1 char:58
> + ... t\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force  ...
> +                                                  ~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

**Comment by rkeithhill** [comment]
Ah, you're on 5.1 and likely an older version of PowerShellGet that doesn't support pre-release.  You can update PowerShellGet by opening PS 5.1 as ADMIN and running:
```
Update-Module PowerShellGet
```
After that has finished, restart PS 5.1 and retry the command to install the module.
```
PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force -Verbose
```

**Comment by eliassal** [comment]
Correct, after updating it went through. Tell me please how do I check or what command I need to use in order that I can work with posh-git, thanks in advance

**Comment by rkeithhill** [comment]
Let's make sure that import pulls in the prerelease you just installed. Run this:
```
Import-Module posh-git -verbose
```
The first line of verbose output should be something like:
```
VERBOSE: Loading module from path 'C:\Users\salam.SALAM\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psd1'.
```
If that is the case, run this command `Add-PoshGitToProfile -AllHosts` and then your profile will import posh-git whenever you load PS 5.1.  To use posh-git, cd into a Git repo directory and you should see your prompt change to show the branch you're on and give you workspace status.  YOu can also use the providing tab-completion e.g. `git chec<tab>` and `git checkout ma<tab>`.

**Comment by eliassal** [comment]
Thanks, I followed the steps on 2 machines, desktop and laptop. On the laptop where I had the issue, I switch to a git repo, I do't see the right prompt where as on the desktop, on the same git repo , I get the right prompt

on the laptop
![poshgit_003](https://user-images.githubusercontent.com/8447864/78236183-f4158e00-74d9-11ea-98cb-3c060e32321a.jpg)

on the desktop
![poshgit_004](https://user-images.githubusercontent.com/8447864/78236302-114a5c80-74da-11ea-888a-2ac0108136da.jpg)

**Comment by rkeithhill** [comment]
On the laptop, check if you get tab-completion for Git subcommands e.g. `git chec<tab>` should tab complete to `git checkout`.  If that works, then the module is getting imported.  However, the posh-git supplied prompt function isn't being used.  Posh-git will not overwrite the prompt function if it thinks you have your own customized prompt function.  Sometimes other modules (e.g. ZLocation) will customize the prompt which causes posh-git to also not overwrite the prompt function.  What modules do you have loaded on the laptop - post the output of `get-module`.

**Comment by eliassal** [comment]
Here is the output of Get-module

> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Script     0.0        chocolateyProfile                   {TabExpansion, Update-SessionEnvironment, refreshenv}
> Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
> Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
> Script     1.0.0      posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranchName, Get-GitBranchStatusColor...}
> Script     0.0        posh-git
> Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
> Script     21.1.18218 SqlServer                           {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext...}

I have customized the prompt color only in my profile as  follows

$shell.BackgroundColor = "Black"
$shell.ForegroundColor = "Yellow"

$colors = $host.PrivateData
$colors.VerboseForegroundColor = "white"
$colors.VerboseBackgroundColor = "blue"
$colors.WarningForegroundColor = "yellow"
$colors.WarningBackgroundColor = "darkgreen"
$colors.ErrorForegroundColor = "white"
$colors.ErrorBackgroundColor = "red"

**Comment by rkeithhill** [comment]
Looks like you've got posh-git imported twice and that is likely the problem with the prompt not showing.  I'm not sure where that `0.0.0` version is coming from.  Can you see by running:
```
Get-Module posh-git | Format-Table Name,Version,Path
```
That should show the path to the `0.0.0` version. Might just want to remove that version altogether.

**Comment by eliassal** [comment]
Yeh, I know and this is the in the Git repo I showed earlier. How can I remove it? I think it is there since I have setup git, not sure
![Poshgit_002](https://user-images.githubusercontent.com/8447864/78404242-4223b200-75fe-11ea-8c81-55b23734ca96.jpg)

**Comment by eliassal** [comment]
Hold a moment, I have just checked my profile file and found the following

> ## Configure posh-git functionality
> $env:path += ";C:\Users\salam.SALAM\AppData\Local\GitHub\PortableGit_d76a6a98c9315931ec4927243517bc09e9b731a0\cmd"
> $env:path += ";C:\Users\salam.SALAM\AppData\Local\GitHub\PortableGit_d76a6a98c9315931ec4927243517bc09e9b731a0\usr\bin"
> 
> Import-Module C:\Users\salam.SALAM\AppData\Local\GitHub\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\posh-git.psm1

**Comment by rkeithhill** [comment]
Get rid of that last Import-Module and see how things work.

**Comment by eliassal** [comment]
Yes, I commented out the 3 lines, fired a new PS terminal, did "git che tab", it worked , cloned a new repo cd it into it but still not getting the prompt

![Poshgit_003](https://user-images.githubusercontent.com/8447864/78404877-9b401580-75ff-11ea-9c3d-9994ca6bd88b.jpg)

**Comment by rkeithhill** [comment]
What is the output of `Get-Command prompt | % Definition`?

**Comment by eliassal** [comment]
```
$wintitle = $CurrentUser.Name + " " + $Host.Name + " " + $Host.Name
$host.ui.rawui.WindowTitle = $wintitle
Write-Host ("PS " + $(get-location) +">") -nonewline -foregroundcolor Magenta
return " "
```

**Comment by rkeithhill** [comment]
OK, somewhere you or another module has defined a custom prompt function.  As I mentioned before, `posh-git` will not install its prompt function if the user already has a customized prompt function.  You have two options. First, you can remove your custom prompt function and then you'll get the posh-git prompt functionality.  Second, you can replace your Write-Host line with the following line in your prompt function:
```
...
& $GitPromptScriptBlock
" "
```

**Comment by eliassal** [comment]
Yes, I have a prompt function in the profile, I updated it with the following and it is working now. I commented the 3rd line 

```
function prompt
{
    $wintitle = $CurrentUser.Name + " " + $Host.Name + " " + $Host.Name
    $host.ui.rawui.WindowTitle = $wintitle
    # Write-Host ("PS " + $(get-location) +">") -nonewline -foregroundcolor Magenta
    & $GitPromptScriptBlock 
    return " "
}
```
However, I would like to keep the forgroungd in Magenta color as follows, how can this be done? Should it be added in your module?
![Poshgit_005](https://user-images.githubusercontent.com/8447864/78421035-ed5f5600-7654-11ea-8b88-a222cdd3041d.jpg)

**Comment by rkeithhill** [comment]
Try setting these values on $GitPromptSettings right after the Import-Module:
```
$GitPromptSettings.DefaultPromptPath.ForegroundColor = [ConsoleColor]::Magenta
```

**Comment by rkeithhill** [comment]
I'm going to close this issue as you seem to have this working now on your laptop. You can re-open if you think otherwise.

**Comment by dahlbyk** [comment]
> I'm not sure that there is a v1 version of posh-git on Chocolatey - @dahlbyk?

Not yet.

@rkeithhill is correct that the previous AppData install looks like it came from GitHub for Windows.

**Comment by eliassal** [comment]
Nothing works, I added
`$GitPromptSettings.DefaultPromptPath.ForegroundColor = [ConsoleColor]::Magenta`
My terminal gets hanged as follows and never ends

> Loading personal and system profiles took 7955ms.

following it by 
`$GitPromptSettings.DefaultPromptBeforeSuffix = "`n"`
was worse

**Comment by rkeithhill** [comment]
Those settings need to be after the import-module otherwise `$GitPromptSettings` is not defined:
```
Import-Module posh-git
$GitPromptSettings.DefaultPromptPath.ForegroundColor = [ConsoleColor]::Magenta
$GitPromptSettings.DefaultPromptBeforeSuffix = "`n"
```
