### ISSUE TITLE
When using git-status-cache stash settings are not respected

### ISSUE THREAD

**Issue by giggio** [dahlbyk/posh-git#761]
### System Details

- posh-git version/path: latest from master (a160c9a)
- PowerShell version: 7
- Git version: 2.26.0.windows.1
- Operating system name and version: Microsoft Windows [Version 10.0.18363.752]
- posh-git version/path: 1.0.0.0 beta4x C:\p\WindowsPowerShell\Modules\posh-git\src
- PowerShell version: 7.0.0

### Issue Description

Even when `$global:GitPromptSettings.EnableStashStatus` is set to false, if git-status-cache is installed, `StashCount` is reported on `Get-GitStatus`.

**Comment by rkeithhill** [comment]
Thanks for submitting this.  I just created a PR to fix this.

**Comment by giggio** [comment]
Great. It worked. Thanks!
