### ISSUE TITLE
Set prompt path to show only the current folder

### ISSUE THREAD

**Issue by trystanmortimer** [dahlbyk/posh-git#767]
### System Details

- posh-git version/path: 0.7.3  ~\OneDrive\Documents\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.18362.752
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

I would like to set the path to only display the current folder, I have tried setting
 
$GitPromptSettings.DefaultPromptPath = $(Split-Path -leaf -path (Get-Location))

Any help would be appreciated.

**Comment by seburbann** [comment]
@trystanmortimer the below does the trick for me:

> function prompt {
>     $path = Convert-Path . 
>     if ($path -eq "C:\") { 
>         "PS $path >" 
>     } else { 
>         "PS ..\$(Split-Path $path -Leaf) > "
>     } 
>     $Host.UI.RawUI.WindowTitle = Get-Location
>  }

That said, I cannot get posh-git to work whenever I change my displayed working directory. 
Does anybody know why that might be?

**Comment by dahlbyk** [comment]
> I would like to set the path to only display the current folder, I have tried setting
> 
> `$GitPromptSettings.DefaultPromptPath = $(Split-Path -leaf -path (Get-Location))`

You need to wrap in single quotes:

```pwsh
$GitPromptSettings.DefaultPromptPath = '$(Split-Path -leaf -path (Get-Location))'
```

That said, I recommend:

```pwsh
$GitPromptSettings.DefaultPromptPath = '$(Get-PromptPath | Split-Path -Leaf)'
```

We have some smarts built into `Get-PromptPath` that you're missing out on with `Get-Location`.
