### ISSUE TITLE
Folowing readme results in multiple errors

### ISSUE THREAD

**Issue by Akxe** [dahlbyk/posh-git#768]
### System Details

- posh-git version/path: 0.7.x
- PowerShell version: 5.1.18362.752
- git version 2.26.2.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

First error one encounters is that `-AllowPrerelease` is not a valid flag of `PowerShellGet\Install-Module`. 

Second and the part is that `Import-Module` is disabled by default.
```
Import-Module : File C:\Users\...\Documents\WindowsPowerShell\Modules\
posh-git\0.7.3\posh-it.psm1 cannot be loaded because running scripts is disabled 
on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
```

**Comment by rkeithhill** [comment]
For the version of posh-git you are on, you want to use this version of the readme: https://github.com/dahlbyk/posh-git/tree/v0  `master` is set to our latest `v1` version.  Or upgrade to v1.

**Comment by Akxe** [comment]
I was instaling a fresh copy on a computer, but it will not download v1.

Also, there is error if `AllowPrerelease` is present:
```
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:58
+ ... et\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force
+                                                   ~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
   + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module
```

**Comment by rkeithhill** [comment]
Looks like you have an older version of `PowerShellGet`.  You need a newer version of PowerShellGet that supports installing pre-release versions of module.  You can either update PowerShellGet using these [instructions](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7#for-systems-with-powershell-50-or-newer-you-can-install-the-latest-powershellget) OR use Chocolatey to install `posh-git`.

**Comment by Akxe** [comment]
I do have the PowerShell you get with fresh Windows 10 install...

**Comment by rkeithhill** [comment]
What version of PowerShellGet do you have? `Get-Module PowerShellGet -List`

I have 2.2.3 which has the `AllowPrereleaseParameter`:

![image](https://user-images.githubusercontent.com/5177512/81323178-33437b80-9052-11ea-80cf-3ada31d646b3.png)

**Comment by Akxe** [comment]
I have version `2.2.1`, It got installed with my computer around a month ago with fresh install

**Comment by rkeithhill** [comment]
Looks like `AllowPrerelease` got added in either 2.2.2 or 2.2.3.  Follow the instructions I linked to above to get the latest version of PowerShellGet or use Chocolatey.

**Comment by Akxe** [comment]
That's a bummer, not being able to install it right away :/

**Comment by rkeithhill** [comment]
Yeah, PowerShell 7 would have a version of PowerShellGet that supports the `AllowPrerelease` parameter.  This situation will change for PS 5 when we finally release a stable (non-prerelease) version to the PowerShellGallery.
