### ISSUE TITLE
Tab expansion in beta4

### ISSUE THREAD

**Issue by szelpe** [dahlbyk/posh-git#769]
### System Details

- posh-git version/path: v1.0.0-beta4
- PowerShell version: tried with both 6.2.5 and 7.0.0
- Git version: 2.26.2.windows.1
- Operating system name and version: Windows 10, Version 2004

### Issue Description

I am experiencing a problem with the tab expansion.

I have `Set-Alias g git` in my $profile and tab completion with `g` worked in `beta2` and `beta3`, but now broken in `beta4`. Simply does nothing if I type `g fet`<kbd>Tab</kbd>.

Also, if I set the `UseLegacyTabExpansion` to `$True` it starts to work again.

**Comment by rkeithhill** [comment]
It turns out PowerShell's built-in Register-ArgumentCompleter does not take into account aliases to native apps that have registered completers. I think the fix for this is pretty easy.  So we will need to pass in any aliases we discover for git,tgit,gitk.

**Comment by rkeithhill** [comment]
FYI, I'm getting a PR ready to fix this but there is one big caveat.  The code to register argument completers for apps and their aliases, happens once during the load of the module.  So you will need to ensure your aliases are defined in your profile script **before** you import posh-git.
