### ISSUE TITLE
Documentation not up to date?

### ISSUE THREAD

**Issue by shaperilio** [dahlbyk/posh-git#775]
Following your README, I can't make this work:

# [Prerequisites](https://github.com/dahlbyk/posh-git#prerequisites)
1. I am on a brand new Windows 10 machine; PowerShell 5.1

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752
```
2. I execute `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Confirm`.
3. Git is installed and I've been using it.

# [Installation](https://github.com/dahlbyk/posh-git#installing-posh-git-via-powershellget-on-linux-macos-and-windows)

`PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force` gives me `Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:58`. As per your comment, I update PowerShellGet, and then check:

```
 PowerShellGet\Get-InstalledModule

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.4.7      PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way t...
2.2.4.1    PowerShellGet                       PSGallery            PowerShell module with commands for discovering,...

```

Run it again, and `AllowPrerelease` is still not recognized.

Thus I cannot install V1, which the rest of your README describes, and so "nothing works"

You may want to add a step in the installation instructions to verify the version of posh-git people are actually getting.

**Comment by rkeithhill** [comment]
`Get-InstalledModule` will give you the latest version of an installed module but that doesn't necessarily mean that is the version that is imported.  Open Windows PowerShell and run:
```powershell
PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force
Get-Module PowerShellGet
```
What version of PowerShellGet is reported?  FWIW, this is from Windows PowerShell 5.1 and it's on a slightly older version of PowerShellGet (2.2.3):

![image](https://user-images.githubusercontent.com/5177512/83194757-64194c80-a0f6-11ea-9057-5f7e903c2191.png)

**Comment by bobwiller** [comment]
Same issue here - clean install on Win10 - running insider build 19645 

![image](https://user-images.githubusercontent.com/2389999/84568538-0f104400-ad4e-11ea-9bd8-f01dcd789df3.png)

What you need to do is update PowerShellGet (https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7) - note you need to do the install, not the upgrade.

Then close & reopen your powershell window for the upgrade to take effect.
