### ISSUE TITLE
posh-git is still too slow...

### ISSUE THREAD

**Issue by tgoeke** [dahlbyk/posh-git#78]
I'm trying out posh-git, but it's still too slow.  How do I uninstall it?

**Comment by ghostsquad** [comment]
I'm guessing that this still has not been implemented?

**Comment by dahlbyk** [comment]
> I'm guessing that this still has not been implemented?

You guess correctly. However, #208 just dropped and it's looking very promising!

**Comment by edclement** [comment]
removing this line:
`$stashCount = $null | git stash list 2>$null | measure-object | select -expand Count`
from GitUtils.ps1 solved the issue for me. It cut 3 seconds off the prompt return time. Considering that git stash status is disabled by default with posh git, I don't understand why this command is always run anyway....

**Comment by ghostsquad** [comment]
the pipeline is slow. Any areas that can be converted to use standard loops and .NET classes would significantly improve performance.

**Comment by Mellbourn** [comment]
@edclement excellent workaround! That increased the performance for me from unacceptable to no problem at all.

**Comment by DoCode** [comment]
posh-git is still slow on tab completion!
Guys, we must investing in libgit2sharp integration!

**Comment by Tavriets** [comment]
Adding ```--untracked-files=no``` (or just ```-uno```) to the ```git stash list``` mentioned by @edclement makes it much faster for me.

**Comment by ghostsquad** [comment]
@edclement - not sure if your workaround is even valid. if StashStatus is disabled, that line won't execute.

**Comment by edclement** [comment]
@ghostsquad - removing that line from the 0.4.0 release (the latest tagged version) definitely fixed the issue for me. That was the only thing I changed.
looking at the code in that tagged version:
```
if($settings.EnableFileStatus -and !$(InDisabledRepository)) {
    dbg 'Getting status' $sw
    $status = git -c color.status=false status --short --branch 2>$null
    #$stashCount = $null | git stash list 2>$null | measure-object | select -expand Count
} else {
    $status = @()
}
```
I don't see why that command wouldn't execute...

**Comment by ghostsquad** [comment]
oh oh, sorry, we were looking at different versions.

**Comment by serbrech** [comment]
@edclement :+1:  worked for me, this makes it good enough to work with for me too

**Comment by dahlbyk** [comment]
Between #319 and #208 we should be in a better spot performance-wise. I'm going to go ahead an close this, but do keep an eye out for an upcoming release with those improvements and leave a note if you're still having issues.

**Comment by Ramin2c** [comment]
> $GitPromptSettings.EnableFileStatus = $false

Mine was initially true, but setting it once to _false_ and back to _true_ again just fixed my slowness problem.

**Comment by ilpssun** [comment]
@Ramin2c Thanks so much for this advice.  Loading posh-git from my profile took almost 6 seconds.  Changing the FileStatus parameter to false and back to true reduced the loading time to under 1 second.  No idea why, but so much better 😃

**Comment by Ramin2c** [comment]
> @Ramin2c Thanks so much for this advice. Loading posh-git from my profile took almost 6 seconds. Changing the FileStatus parameter to false and back to true reduced the loading time to under 1 second. No idea why, but so much better 😃

Don't worry, no one knows why such so-called fix works, but glad I could help.
