### ISSUE TITLE
Slow import-module -- can we delay loading?

### ISSUE THREAD

**Issue by syntroniks** [dahlbyk/posh-git#784]
### System Details

- posh-git version/path: 
Not sure how to get this information. It is likely to be a new-ish version. I suspect 1.0.0
- PowerShell version:
```Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      20170  1000
```
- Git version:
`git version 2.27.0.windows.1`
- Operating system name and version:
`Windows 10 Pro 20170`

**Can I import-module in the backround or async?** I don't always need it to import immediately, but I don't want to import manually & want to access the terminal faster.

My current profile load times are ~1200ms. posh-git is the majority of those load times.

**Comment by rkeithhill** [comment]
There's not a way to do this that I know of.  Using background/async would execute the import in either another process or another runspace which is not what you want.

**Comment by syntroniks** [comment]
OK, I'm using Windows Terminal and opening multiple tabs at once.

By re-using multiple powershell instances, I won't have to wait for new windows to spin up.
