### ISSUE TITLE
Prompt not displaying correctly in PowerShell ISE

### ISSUE THREAD

**Issue by drullo** [dahlbyk/posh-git#787]
### System Details

- posh-git version/path: 0.7.3
- PowerShell version: 5.1.18362.145
- Git version: 2.15.0.windows.1
- Operating system name and version:  Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

### Issue Description
Prompt works fine in non-ISE PowerShell prompt.  But in ISE, it displays the following HUGE prompt
![PoshGitISEPrompt](https://user-images.githubusercontent.com/10358672/90263440-add42200-de1d-11ea-8854-0a074c53fcab.png)

**Comment by rkeithhill** [comment]
I can't replicate what you're seeing:

![image](https://user-images.githubusercontent.com/5177512/90301509-99b01500-de5d-11ea-81c4-6973b2b31d78.png)

Is it possible ISE is loading a different version of posh-git?  What version number does `gmo posh-git` output in ISE?

**Comment by drullo** [comment]
This is the output.  I thought it was odd that I'm seeing 2 versions (right?).  So I removed and re-installed it and I'm still seeing 2.  Is that normal?

![posh-git-ver](https://user-images.githubusercontent.com/10358672/90301847-37144480-de70-11ea-9514-fa3801eeac03.png)

**Comment by rkeithhill** [comment]
I'm surprised that listed more than one version without specifying `-ListAvailable`.  What do you get for a posh-git version if you execute just `get-module`.

**Comment by drullo** [comment]
Get-Module output:

![posh-git](https://user-images.githubusercontent.com/10358672/90302008-552e7480-de71-11ea-8b99-332068941c56.png)

**Comment by rkeithhill** [comment]
Now that's a real puzzler.  You should have only one imported at a time.  If I import both 0.7.3 and 1.0.0, I get the same, bad prompt behavior.  So look in your `profile.ps1` and `Microsoft.PowerShellISE_profile.ps1` scripts and see if you're importing the module twice somehow.

**Comment by drullo** [comment]
Bingo, that was it!  The CurrentUserAllHosts profile was loading it with `Import-Module posh-git`.  And the CurrentUserCurrentHosts was loading it with a full path:
`Import-Module 'C:\Users\...\posh-git\src\posh-git.psd1'` 

I removed the full path call, and all seems to be normal now.  Thank you for your help!
