### ISSUE TITLE
"git help --all" output breaks $GitTabSettings.AllCommands = $true

### ISSUE THREAD

**Issue by dannoe** [dahlbyk/posh-git#788]
### System Details

- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.0.3
- git version 2.28.0.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### $GitTabSettings.AllCommands = $true doesn't work

I wanted to get autocomplete even for non-porcelain commands (like update-index). So I search the issues and found #443. I tried to set the variable, but even with this setting I wasn't able to autocomplete all commands.
Instead I could autocomplete even less commands (looks like only my aliases). 

I think that this line: https://github.com/dahlbyk/posh-git/blob/66b46b4393d2a11d696b6f4776405a3ad4809a46/src/GitTabExpansion.ps1#L98
is wrong. My git puts 3 spaces in front of the commands from the "git help --all" command.

**Comment by rkeithhill** [comment]
If you change that line to ` Where-Object { $_ -match '^\s{2,}\S.*' } | `, does it work the way you expect?

**Comment by dannoe** [comment]
I fixed it by changing it to ``Where-Object { $_ -match '^   \S.*' }``, but for backwards compatibility yours is better.
Both solutions are working with ``git version 2.28.0.windows.1``

**Comment by rkeithhill** [comment]
Would you like to submit a PR?  If not, I'll make the change.
