### ISSUE TITLE
Remove remote merged branches command

### ISSUE THREAD

**Issue by Haacked** [dahlbyk/posh-git#79]
So we (GHfW) team have a PowerShell script that will list all remote branches that are already merged into a specified branch (it defaults to origin/master if no branch is supplied) and offer to delete them for you.

I'd love to clean it up and add it as a command to `GitUtils.ps1`. Would you be interested in such a thing as part of Posh-Git?

**Comment by bcdady** [comment]
Have @dahlbyk or @JayBazuzi reviewed the pull request (#159) by @tkirill ? 
Unless there's an issue with the proposed functions / enhancements, when might we be able to see this committed / released?

**Comment by tkirill** [comment]
Glad to see there is someone else who interested in this functionality!  I've already thought no one need this.

These cmdlets are totally tested at this moment.  We use them in our team daily and never had a single problem or crash.
