### ISSUE TITLE
New beta release

### ISSUE THREAD

**Issue by musm** [dahlbyk/posh-git#795]
Any plans for a new beta release?  (Or for that matter an official release, albeit I've been exclusively using the beta)

**Comment by rkeithhill** [comment]
I'd love to just release v1.  But only @dahlbyk can do that.

**Comment by dahlbyk** [comment]
Yeah, I'm the bottleneck here. I don't want to release v1 without a plan for Chocolatey installs, but I haven't had a chance to look at that. I'll try to at least get a beta out this weekend.

**Comment by adrianwright109** [comment]
@dahlbyk any update on when we can expect a new release beit beta or official release?

**Comment by dahlbyk** [comment]
v1 was released last month.
