### ISSUE TITLE
Fail to set path color on macOS

### ISSUE THREAD

**Issue by FranklinYu** [dahlbyk/posh-git#798]
### System Details

- posh-git version/path: 0.7.3 `~/.local/share/powershell/Modules/posh-git/0.7.3`
- PowerShell version: 7.0.3
- Git version: 2.24.3 (from macOS)
- Operating system name and version: macOS Catalina (10.15.6)

Note: I manually fill in the operating system version, because `OSVersion` is “Unix 19.6”, which doesn’t seem helpful.

### Issue Description

I cannot set the color of the path segment. I tried

```powershell
$GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500
```

Output:

```text
InvalidOperation: The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
```

Note that the value of `$GitPromptSettings.DefaultPromptPath` in my PowerShell is `$(Get-PromptPath)`; not sure whether that looks normal.

**Comment by dahlbyk** [comment]
You want to upgrade to posh-git v1.0.0-beta4 to get macOS support and the updated settings structure.
