### ISSUE TITLE
PoshGit doesn't show branch info in PowerShell 7.0.3

### ISSUE THREAD

**Issue by Alfetta159** [dahlbyk/posh-git#799]
### System Details

- posh-git version/path: 0.7.3.1
- PowerShell version: 7.0.3
- Git version: 2.27.0
- Operating system name and version: Window 10.

### Issue Description

PoshGit doesn't show branch info (e.g. [master]) . Reinstalled from Chocolatey on PS 7.0.3

**Comment by cwhowell** [comment]
posh-git v0.7.x doesn't support Powershell Core, and the Chocolately package hasn't yet been updated to distribute v1.x. There's a comment on the Chocolatey package page from the author saying he hasn't had time to update it yet (which is fair enough, this is a free tool).

As a workaround I've just used successfully on Powershell Core 7.0.3: Remove the Chocolatey package, and then install posh-git from the Powershell Gallery as described in the README. Then run Add-PoshGitToProfile to automatically include posh-git in every subsequent PS session.

**Comment by Alfetta159** [comment]
Thank you, @cwhowell (and of course @dahlbyk )

I've been using PoshGit since I started using Git and would hate to see it go away.

I'm going to close this because while the Chocolatey install might not be updated, I did get what I wanted out of this. It's nice to be able to use PS 7.x partly because it's the latest version but mostly because it has a black background by default! 😉

**Comment by dahlbyk** [comment]
> but mostly because it has a black background by default! 😉

Here, here.

> I've been using PoshGit since I started using Git and would hate to see it go away.

Definitely not going away, it's just been tough to balance OSS against work and family. We'll get there. 🔜
