### ISSUE TITLE
Feature request: Display branches on autocomplete if there are multiple possible branches

### ISSUE THREAD

**Issue by dannoe** [dahlbyk/posh-git#803]
Example:

Repo with 3 branches:
`master`
`feature/foo`
`feature/bar`

When I enter `git checkout <tab>` I want to see a list of all branches. (`master`+`feature/foo`+`feature/bar`) 
When I enter `git checkout feature/<tab>` I want to see a list of all sub-branches of feature/ (`feature/foo` and `feature/bar`)
Currently it just starts to cycle through all possibilities, which can be tedious if you have a lot of branches.

The display should always trigger if there are multiple possibilities.

This is the default behavior of Git Bash on Windows. 
It would probably be a good idea to make it configurable.

**Comment by dahlbyk** [comment]
posh-git just hooks into PowerShell tab expansion behavior. You can change this behavior with PSReadLine ([usage](https://github.com/PowerShell/PSReadLine#usage)) or other PS modules.

This is a common question, so we should probably put something in the docs about it.

**Comment by dannoe** [comment]
Thanks. I thought I was using the bash PSReadLine configuration, but didn't notice I have to put it into my profile 🤦‍♂️
