### ISSUE TITLE
Branch behind/ahead indicators not showing

### ISSUE THREAD

**Issue by sephirothx** [dahlbyk/posh-git#811]
### System Details

- **posh-git version/path:** latest: ~/src/posh-git
- **PowerShell version:** 7.0.3
- **Git version:** 2.11.0
- **Operating system name and version:** Debian GNU/Linux 9.13

### Issue Description

Despite the setting being `$GitPromptSettings.BranchBehindAndAheadDisplay : Full`, The up and down arrows are not showing whether there are pending commits or not, while the synced ≡ indicator is showing correctly. Is there a known way to fix this?

**Comment by dahlbyk** [comment]
Interesting. Can you share output of `git status -sb` and `$GitStatus` when you are in a state you expect to be ahead or behind?

**Comment by sephirothx** [comment]
Oh thank you, I see where the problem is, damned italian localization. The `$GitStatus` looks fine and that's the one I checked before posting the issue, `git status -sb` is localized tho.
```
## master...origin/master [avanti 1]
``` 
```
Working      : {}
StashCount   : 0
Upstream     : 
BehindBy     : 0
Branch       : master
HasIndex     : False
AheadBy      : 0
UpstreamGone : False
GitDir       : /home/repo/.git
HasWorking   : False
HasUntracked : False
RepoName     : repo
Index        : {}
```

## FIX
`$env:LC_ALL="en_US.UTF-8"` worked for me

**Comment by dahlbyk** [comment]
Seems like we should set `LC_ALL=C` every time we parse git for keywords.

**Comment by dahlbyk** [comment]
I'm going to go ahead and close this since there's a work-around, but the more correct fix is probably to use a porcelain format.
