### ISSUE TITLE
Feature request: Auto-Completion Option

### ISSUE THREAD

**Issue by chkhetiani** [dahlbyk/posh-git#813]
### System Details

- posh-git version/path: v0.7.3.1
- PowerShell version: 5 .1.19041 .546
- Git version: 2.17.1.windows.2
- Operating system name and version: Windows 10, 19041.572

### Issue Description

I want to request feature.

#### Example scenario:
I have two branches:

1.  `feature/first`
2.  `feature/second`

As of now, if I type `f` and hit tab autocompletion gives → `feature/first`.
I want it to give `feature/` and after I type:
`f` then → `feature/first` or if I type `s` → `feature/second`

**Comment by dannoe** [comment]
see https://github.com/dahlbyk/posh-git/issues/803
