### ISSUE TITLE
There's missing auto comlete on some git commands

### ISSUE THREAD

**Issue by mturczyn** [dahlbyk/posh-git#816]
### System Details

- posh-git version/path: 0.7.3  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version:   5.1.19041.546
- Git version: git version 2.29.2.windows.2
- Operating system name and version:  Microsoft Windows NT 10.0.19042.0

### Issue Description

I have noticed that there is missing autocomplete on `git switch` command, which is used to change branches. While autocomplete (tab-complete) works with checkout (it can complete command from "check" and also with tab I can go through suggested branches names), it does not work at all with `git switch` - it cannot autocomplete command itself as well as it doesn't suggest branches.

**Comment by rkeithhill** [comment]
`switch` tab-completion support has been implemented in the v1 beta.  Try updating to that with:
```
Install-Module posh-git -AllowPrerelease -Scope CurrentUser -Force
```
