### ISSUE TITLE
How do I make Posh-Git ignore some files?

### ISSUE THREAD

**Issue by Rod-in-NM** [dahlbyk/posh-git#817]
### System Details

- posh-git version/path: 0.7.3.1  C:\tools\poshgit\dahlbyk-posh-git-9bda399\src
- PowerShell version: 5.1.18362.1171
- Git version: 2.27.0.windows.1
- Operating system name and version: Windows 10 Enterprise 1909 (OS Build 18363.1198) Microsoft Windows NT 10.0.18363.0

### Issue Description

I am experiencing a problem with making posh-git ignore the .suo file that Visual Studio 2019 creates and modifies. Is there a way of making it ignore the .suo file? And if so, how is that done, please?

**Comment by dahlbyk** [comment]
You need a [`.gitignore` file](https://git-scm.com/docs/gitignore). There's a [standard one for VS projects](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore), or you can [have VS generate one for you in Team Explorer](https://elanderson.net/2016/09/add-git-ignore-to-existing-visual-studio-project/).
