### ISSUE TITLE
cannot display 'CHERRY-PICKING' in prompt when conflicting

### ISSUE THREAD

**Issue by NihilityT** [dahlbyk/posh-git#818]
### System Details

- posh-git version/path: 1.0.0 beta4 ~\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.18362.1110
- git version 2.26.2.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

When I cherry-pick a commit, I got many conflict warnings, but the prompt in powershell did not show that I was in cherry-pick mode

### Steps to reproduce

``` powershell
# powershell

mkdir git-test
cd git-test
git init
echo 1 > test.txt
git add *
git commit -am 'first'
git checkout -b 'conflict'
echo 2 > test.txt
git commit -am 'second'
git cherry-pick master
git status
```

**Comment by dahlbyk** [comment]
Thanks for the report/repro!
