### ISSUE TITLE
Non-ascii git branch name garbled,except in VSCode.

### ISSUE THREAD

**Issue by Andy-AO** [dahlbyk/posh-git#820]
### System Details
- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.0
- git version 2.29.2.windows.2
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

Non-ascii git branch name(prompt) garbled,except in VSCode.

As you can see from the picture below, it is normal in PowerShell Integrated Console, but abnormal in pwsh(is same in pwsh.exe ,powershell.exe and Windows Terminal).

![](https://cdn.jsdelivr.net/gh/Andy-AO/GitHubPictureBed/img/20201211122110.png)

It is not caused by other modules and ProFile, even in the virtual machine, this problem still exists.

**Comment by dahlbyk** [comment]
Can you try the latest version from `master`? This might be resolved by #796, which I haven't managed to release yet.

**Comment by Andy-AO** [comment]
> Can you try the latest version from `master`? This might be resolved by #796, which I haven't managed to release yet.

Thank you. The problem has been solved.
