### ISSUE TITLE
Feature request: BeforePath/AfterPath 

### ISSUE THREAD

**Issue by breisfeld** [dahlbyk/posh-git#821]
Great package!

It would be nice to be able to specify characters that surround the path.

For example
```
$GitPromptSettings.BeforePath = '<'
$GitPromptSettings.AfterPath = '>'
```

**Comment by rkeithhill** [comment]
You can already do this e.g.:

```powershell
C:\Users\Keith\GitHub\dahlbyk\posh-git\src [rkeithhill/adj-path-abbrev ≡ +0 ~2 -0 !]
> $GitPromptSettings.DefaultPromptPath = '<<$(Get-PromptPath)>>'
<<C:\Users\Keith\GitHub\dahlbyk\posh-git\src>> [rkeithhill/adj-path-abbrev ≡ +0 ~2 -0 !]
>
```

**Comment by breisfeld** [comment]
I should have been more clear. 

If I use something like 
`$GitPromptSettings.DefaultPromptPath.ForegroundColor = 'Blue'`,
I'd like the theoretical `$GitPromptSettings.BeforePath` and `$GitPromptSettings.AfterPath` segments *not* to inherit this color.

This seems to be the way that `$GitPromptSettings.BeforeStatus` and `$GitPromptSettings.AfterStatus` behave relative to `Status`.

**Comment by breisfeld** [comment]
I created  PR #822 to add this feature.
