### ISSUE TITLE
Use of Write-Prompt leads to wrong colors in Windows Terminal

### ISSUE THREAD

**Issue by mika-fischer** [dahlbyk/posh-git#823]
### System Details

- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.0
- Git version: 2.27.0.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.19041.0

### Issue Description

This is probably not directly caused by posh-git, but I ran into it while setting up posh-git and I since I'm new to PowerShell and Windows Terminal, I don't know how to solve it.

The issue is that posh-git does not seem to respect the color scheme set in Windows Terminal. It always seems to use the default colors.

I broke down the issue to a difference between `Write-Host` and `Write-Prompt`. The former uses the colors from the color scheme, while the latter seems to use the default colors. See below (note that I print the working directory myself with Write-Host, therefore it uses the correct blue):

<img width="515" alt="2020-12-17_17h14_25" src="https://user-images.githubusercontent.com/426158/102513447-828f6700-408b-11eb-919f-90efa1a7402f.png">

I tried working around this by extracting the relevant info from the status returned by `Get-GitStatus` but I'd end up replicating most of posh-git, so I thought I'd ask here first. Any hints or pointers would be appreciated!

**Comment by dahlbyk** [comment]
posh-git favors named HTML colors over Console colors. Try:

```pwsh
Write-Prompt -ForegroundColor ([ConsoleColor]::Blue) ABCDEFG
Write-Prompt -ForegroundColor ([ConsoleColor]::Dark) ABCDEFG
```

This is why we use `[ConsoleColor]` for the various default settings:
https://github.com/dahlbyk/posh-git/blob/4a8cda0bceb6e5c96c177ba430af662912353de3/src/PoshGitTypes.ps1#L230-L257

**Comment by mika-fischer** [comment]
Yes, this helps! Thanks a lot for the pointer 😃
