### ISSUE TITLE
Is https://github.com/cmarcusreid/git-status-cache-posh-client/issues still required for caching?

### ISSUE THREAD

**Issue by sql-sith** [dahlbyk/posh-git#829]
### System Details

- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.1
- git version 2.29.2.windows.2
- hub version 2.14.2
- OS: Microsoft Windows NT 10.0.19042.0

### Issue Description

I have a question about caching and `$GitPromptSettings.EnableFileStatusFromCache`. Is caching built-in now? My confusion is because of the following observations:

- `EnableFileStatusFromCache` is available in `$GitPromptSettings`. This makes me think that caching is built-in.
- On the other hand, to make `Get-GitStatusCacheStatistics` available, I have to import `GitStatusCachePoshClient` from @cmarcusreid . 

If `GitStatusCachePoshClient` is required, which version is best? There are two tagged commits in GitHub, one for v.0.1.3 on Sep 7, 2015, and one for v1.0.0 on Sep 10, 2015. However, on the root of the project it says that there have been no commits since Feb 20, 2017. That agrees with what I see in `git log` locally.  As a final option, it can be installed via `choco`. So I'm having trouble making sense of the versions in the GitHub repo, and don't know if they are superceded by the `choco` installation. 

Sorry to ask a lot of questions about another repo. The main question from the `posh-git` point of view is whether the other repo is even needed anymore, and if not, is there an equivalent to `Get-GetStatusCacheStatistics`?

**Comment by cmarcusreid** [comment]
Caching is not built into posh-git.

For caching, posh-git calls into GitStatusCachePoshClient which is a PowerShell module that communicates with git-status-cache, which is a C++ executable built on libgit2. If you want to use caching, you can follow the setup instructions on the git-status-cache-posh-client repo's readme to get up-and-running; these steps will also setup git-status-cache. The release on github and on chocolatey should be identical.

EnableFileStatusFromCache controls whether posh-git attempts to use caching via git-status-cache-posh-client. By default it this value is set to true if the GitStatusCachePoshClient module is detected.
