### ISSUE TITLE
Why would a function like Write-GitBranchName be exposed outside the module?

### ISSUE THREAD

**Issue by Andy-AO** [dahlbyk/posh-git#830]
Here are some of the questions that bothered me:

I have been using posh-git for a long time. Recently, I found that  a large number of functions have been exported, including `Write-GitBranchName`. 

This function should not be used by users. After reading the help file, it feels like an internal function  After reading README, I didn't find any further introduction to these functions  Functions that are only used inside the module should be hidden inside the module. Unnecessary internal implementation leakage may have bad consequences.

What's the reason?

Is it for the convenience of testing?

**Comment by Andy-AO** [comment]
If I understand it wrong, I would like to know the specific reasons.

If my understanding is right, then I seem to think of a good way to hide the internal implementation while taking into account the test.

**Comment by krokofant** [comment]
It's used by other modules like oh-my-posh. It seems like both the old and the new one:
Old one: https://github.com/JanDeDobbeleer/oh-my-posh2/
New one: https://github.com/JanDeDobbeleer/oh-my-posh/

**Comment by dahlbyk** [comment]
> It's used by other modules like oh-my-posh. It seems like both the old and the new one:
> Old one: https://github.com/JanDeDobbeleer/oh-my-posh2/
> New one: https://github.com/JanDeDobbeleer/oh-my-posh/

Correct. posh-git exports the building blocks of our prompt to allow folks to remix the underlying Git status information in ways we don't directly support in the default `Write-GitStatus` implementation.

Not meant to be used by most people, but not something we want to hide. Unless there's some clever way to semi-hide it, a la `[InternalsVisibleTo]`.
