### ISSUE TITLE
Importing the module results PowerShell dropping to a cmd prompt.

### ISSUE THREAD

**Issue by cdashrowe** [dahlbyk/posh-git#835]
### System Details

- posh-git version/path: 1.0.0 beta4 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.2
- git version 2.30.1.windows.1
- OS: Microsoft Windows NT 10.0.19042.0

### Issue Description

I am experiencing a problem with...

After installing posh-git any attempt at importing the module results in PowerShell dropping back into cmd and the module isn't imported.

I've tried installing elevated and installing non-elevated, i've removed and reinstalled the module countless number of times, and I cannot work out what's going on.

Any attempt to add `Import-Module posh-git` to my PowerShell profile results in the PowerShell window dropping out back to cmd with no errors.

**Comment by rkeithhill** [comment]
Can you try starting PowerShell by running `pwsh -noprofile` and then try `Import-Module posh-git -Verbose`?  If that fails, paste the verbose output back here.

**Comment by cdashrowe** [comment]
Seems the module is importing, but as you can see it immediately drops to cmd without error?

PS C:\Users\cdash> Import-Module posh-git -Verbose
VERBOSE: Loading module from path 'C:\Users\cdash\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module posh-git.
VERBOSE: Loading module from path 'C:\Users\cdash\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psm1'.
VERBOSE: Importing function 'Add-PoshGitToProfile'.
VERBOSE: Importing function 'Expand-GitCommand'.
VERBOSE: Importing function 'Format-GitBranchName'.
VERBOSE: Importing function 'Get-GitBranchStatusColor'.
VERBOSE: Importing function 'Get-GitDirectory'.
VERBOSE: Importing function 'Get-GitStatus'.
VERBOSE: Importing function 'Get-PromptConnectionInfo'.
VERBOSE: Importing function 'Get-PromptPath'.
VERBOSE: Importing function 'New-GitPromptSettings'.
VERBOSE: Importing function 'Remove-GitBranch'.
VERBOSE: Importing function 'tgit'.
VERBOSE: Importing function 'Update-AllBranches'.
VERBOSE: Importing function 'Write-GitBranchName'.
VERBOSE: Importing function 'Write-GitBranchStatus'.
VERBOSE: Importing function 'Write-GitIndexStatus'.
VERBOSE: Importing function 'Write-GitStashCount'.
VERBOSE: Importing function 'Write-GitStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatusSummary'.
VERBOSE: Importing function 'Write-Prompt'.
VERBOSE: Importing variable 'GitPromptScriptBlock'.
C:\Users\cdash>

**Comment by cdashrowe** [comment]
Okay... not sure what's changed but although it appears to be dropping back to cmd, it isn't anymore and powershell commands still work after the import, this wasn't the case yesterday.

Thanks for your assistance, will close now.
