### ISSUE TITLE
Tab completion using aliases

### ISSUE THREAD

**Issue by chiangs** [dahlbyk/posh-git#842]
### System Details

- posh-git version/path: 1.0.0-beta5
- PowerShell version: 7.1.2
- Git version: 2.30.1.windows.1
- Operating system name and version: Windows 10 Pro

### Issue Description

I am experiencing a problem with git path tab auto-completion when using aliases. This works on another machine with the same settings and configuration. So I'm not exactly sure what is wrong. It was installed via `PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force`

based on the tests below, the git config aliases work fine, but the aliasing of git to g in the ps1 doesn't seem to be working 100% as expected.

PS1:
```
Import-Module posh-git
$GitPromptSettings.DefaultPromptPrefix = '$env:USERNAME@$(hostname) '
$GitPromptSettings.DefaultPromptPrefix.ForegroundColor = '#55c6d6'

# Git commands
New-Alias g git
```
GITCONFIG:
```
[alias]
    g = git
    co = checkout
```

Expected outcome:
`g co [tab]` => cycles through branch names
`g [tab]` => cycles through git command names

Actual outcome:
`g co [tab]` => cycles through directory files
`g [tab]` =>  cycles through directory files
`g checkout [tab]` => cycles through directory files
`git co [tab] ` => cycles through the branch names
`g co manuallyTypedOutBranchName` => checks out the branch

**Comment by rkeithhill** [comment]
Move the alias above the posh-git import:
```powershell
# Git commands
New-Alias g git

Import-Module posh-git
$GitPromptSettings.DefaultPromptPrefix = '$env:USERNAME@$(hostname) '
$GitPromptSettings.DefaultPromptPrefix.ForegroundColor = '#55c6d6'
```

**Comment by chiangs** [comment]
Thanks, that worked!
