### ISSUE TITLE
After installing Git "rc" version, PowerShell reports an error

### ISSUE THREAD

**Issue by DustinWin** [dahlbyk/posh-git#845]
**Git version:** 2.31.0-rc2 (all rc version)
**Operating system version:** Windows 10 21H1
**PowerShell version:** comes with the system
**oh-my-posh version:** 3.111.2
**posh-git version:** 1.0.0
**Steps to reproduce:**
1. Run PowerShell as an administrator and run the following command:
```
Set-ExecutionPolicy RemoteSigned
Install-Module posh-git
Install-Module oh-my-posh
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
2. Enter the folder C:\Users\ [your username] \Documents\WindowsPowerShell, edit the text document, and enter the following:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
And save as Microsoft.PowerShell_profile.ps1
3. Close PowerShell, and open PowerShell again
**Expected results:**
PowerShell will not report errors
**Actual results:**
PowerShell reports an error, and the content of the error:
Warning: You appear to have an unsupported Git distribution; setting $GitPromptSettings.AnsiConsole = $false. posh-git recommends Git for Windows.
![111055583-49ac3600-84b2-11eb-879b-b244d468566f](https://user-images.githubusercontent.com/45238096/111063685-0fab5600-84eb-11eb-99a7-ce611bb9e56f.png)
**Remarks:**
If you install Git v2.30.2 version, no error will be reported. I installed the 2.31.0 rc1, 2.31.0 rc0, and 2.30.0 rc2 versions, and all encountered this problem. I installed the 2.30.1 and 2.30.2 version again and did not encounter this problem. After I reported this problem in Git, I was told that it was a posh-git problem. Please see: https://github.com/git-for-windows/git/issues/3111#issuecomment-798873710

**Comment by dahlbyk** [comment]
The regex use to validate the Git version lives here: https://github.com/dahlbyk/posh-git/blob/5a87e8a196d13395f978d774f80dedb40d43b85e/src/CheckRequirements.ps1#L11

The warning is from past issued with folks using the Cygwin build of Git which doesn't include `.windows` in it's `--version`.

You can set `$Env:POSHGIT_CYGWIN_WARNING = "off"` to disable the warning, or we can try to figure out a better way to identify Git for Windows vs other builds.
https://github.com/dahlbyk/posh-git/blob/5a87e8a196d13395f978d774f80dedb40d43b85e/src/CheckRequirements.ps1#L18-L20

**Comment by dscho** [comment]
> ```powershell
>  if ([string](git --version 2> $null) -match '(?<ver>\d+(?:\.\d+)+)(?<g4w>\.windows)?') {
> ```

Extending this in the following way seems to fix the issue for me:

```diff
diff a/src/CheckRequirements.ps1 b/src/CheckRequirements.ps1
--- a/src/CheckRequirements.ps1
+++ b/src/CheckRequirements.ps1 
@@ -10,+3 +10,+3 @@
 
-if ([string](git --version 2> $null) -match '(?<ver>\d+(?:\.\d+)+)(?<g4w>\.windows)?') {
+if ([string](git --version 2> $null) -match '(?<ver>\d+(?:\.\d+)+)(?<g4w>(\.rc\d+)?\.windows)?') {
     $script:GitVersion = [System.Version]$Matches['ver']
```

@DustinWin can you verify that this works for you? If so, would you mind opening the PR?

**Comment by dahlbyk** [comment]
Can you think of a reason not to make this morning forgiving, e.g. `.*(?<g4w>\.windows)?')`?

**Comment by dscho** [comment]
> Can you think of a reason not to make this morning forgiving, e.g. `.*(?<g4w>\.windows)?')`?

That should work!
