### ISSUE TITLE
Invalid characters in prompt:  "master ≡  ~5 ?2"

### ISSUE THREAD

**Issue by spg-iwilson** [dahlbyk/posh-git#846]
### System Details

- posh-git version/path: 0.7.3  ~\OneDrive - Me\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.18362.1171
- git version 2.30.1.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

I am experiencing a problem with...my git status showing an invalid character
![image](https://user-images.githubusercontent.com/25376734/111423090-e0435600-8743-11eb-83c9-32bb9454798f.png)

I have the latest version of the Cascadia Code PL font installed. I also have v3.106.7 of oh-my-posh installed.

**Comment by dahlbyk** [comment]
@JanDeDobbeleer any ideas?

**Comment by JanDeDobbeleer** [comment]
@dahlbyk yes. V3 of oh-my-posh doesn't use posh-git anymore for fetching the git status (although that doesn't impact the font/icons per se) and we've adopted more icons from Nerd Fonts (CCPL isn't as advanced). More info on fonts can be found [here](https://ohmyposh.dev/docs/fonts).

**Comment by spg-iwilson** [comment]
Thank you! I've removed the import-module command for posh-git in my PowerShell profile, installed the MesloLGM Nerd Font and changed my settings to use this prompt. Looking great now 

![image](https://user-images.githubusercontent.com/25376734/111549417-3eb61600-87d0-11eb-8e0a-6b9cde3f89dd.png)
