### ISSUE TITLE
Import-Module posh-git throws error

### ISSUE THREAD

**Issue by nilact** [dahlbyk/posh-git#848]
### System Details

```
You cannot call a method on a null-valued expression.
At line:1 char:55
+ ... e posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.Prerele ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

- posh-git version/path:
- PowerShell version: 5.1.19041.868
- git version 2.31.0.windows.1
- OS: Microsoft Windows NT 10.0.19042.0

However, I can see post-git installed at below path:

C:\Users\5096\OneDrive - TestCompany, Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0

### Issue Description

I am experiencing a problem with the command Import-Module posh-git. It throws the below error:

```
The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psm1:10 char:1
+ . $PSScriptRoot\ConsoleMode.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException

The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psm1:14 char:1
+ . $PSScriptRoot\PoshGitTypes.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException

Unable to find type [PoshGitPromptSettings].
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\GitPrompt.ps1:4 char:29
+ $global:GitPromptSettings = [PoshGitPromptSettings]::new()
+                             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PoshGitPromptSettings:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Unable to find type [PoshGitPromptValues].
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\GitPrompt.ps1:5 char:27
+ $global:GitPromptValues = [PoshGitPromptValues]::new()
+                           ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PoshGitPromptValues:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by rkeithhill** [comment]
Start up a fresh PowerShell session with no profile - `powershell.exe -noprofile`.  Execute `$env:PSModulePath` and copy the output here.  Then run `Get-Module posh-git -ListAvailable | Format-List` and post that here.  Finally, try `Import-Module posh-git -verbose` and post the output from that here.  Thanks.

**Comment by nilact** [comment]
`$env:PSModulePath`

C:\Users\5096\OneDrive - TestCompany, Inc\Documents\WindowsPowerShell\Modules;
C:\Program Files\WindowsPowerShell\Modules;
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell

`Get-Module posh-git -ListAvailable | Format-List`

Name              : posh-git
Path              : C:\Users\5096\OneDrive - TestCompany,
                    Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psd1
Description       : Provides prompt with Git status summary information and tab completion for Git commands,
                    parameters, remotes and branch names.
ModuleType        : Script
Version           : 1.0.0
NestedModules     : {}
ExportedFunctions : {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranchName, Get-GitBranchStatusColor...}
ExportedCmdlets   :
ExportedVariables : GitPromptScriptBlock
ExportedAliases   :

`Import-Module posh-git -verbose`

VERBOSE: Loading module from path 'C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module posh-git.
VERBOSE: Loading module from path 'C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psm1'.
The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psm1:10 char:1
+ . $PSScriptRoot\ConsoleMode.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException

The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\posh-git.psm1:14 char:1
+ . $PSScriptRoot\PoshGitTypes.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException

Unable to find type [PoshGitPromptSettings].
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\GitPrompt.ps1:4 char:29
+ $global:GitPromptSettings = [PoshGitPromptSettings]::new()
+                             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PoshGitPromptSettings:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Unable to find type [PoshGitPromptValues].
At C:\Users\5096\OneDrive - TestCompany,
Inc\Documents\WindowsPowerShell\Modules\posh-git\1.0.0\GitPrompt.ps1:5 char:27
+ $global:GitPromptValues = [PoshGitPromptValues]::new()
+                           ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PoshGitPromptValues:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

VERBOSE: Importing function 'Add-PoshGitToProfile'.
VERBOSE: Importing function 'Expand-GitCommand'.
VERBOSE: Importing function 'Format-GitBranchName'.
VERBOSE: Importing function 'Get-GitBranchStatusColor'.
VERBOSE: Importing function 'Get-GitDirectory'.
VERBOSE: Importing function 'Get-GitStatus'.
VERBOSE: Importing function 'Get-PromptConnectionInfo'.
VERBOSE: Importing function 'Get-PromptPath'.
VERBOSE: Importing function 'New-GitPromptSettings'.
VERBOSE: Importing function 'Remove-GitBranch'.
VERBOSE: Importing function 'TabExpansion'.
VERBOSE: Importing function 'tgit'.
VERBOSE: Importing function 'Update-AllBranches'.
VERBOSE: Importing function 'Write-GitBranchName'.
VERBOSE: Importing function 'Write-GitBranchStatus'.
VERBOSE: Importing function 'Write-GitIndexStatus'.
VERBOSE: Importing function 'Write-GitStashCount'.
VERBOSE: Importing function 'Write-GitStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatus'.
VERBOSE: Importing function 'Write-GitWorkingDirStatusSummary'.
VERBOSE: Importing function 'Write-Prompt'.
VERBOSE: Importing variable 'GitPromptScriptBlock'.

**Comment by dahlbyk** [comment]
Seems to be an issue with PowerShell with loading an assembly from a path that includes a comma:

![image](https://user-images.githubusercontent.com/133987/112360890-cef8cd00-8ca0-11eb-8454-d9a4844a837a.png)

I can't think of anything we could do within the module to work around this.

**Comment by rkeithhill** [comment]
@nilact Can you submit this issue on the PowerShell repo?  https://github.com/PowerShell/PowerShell/issues

**Comment by dahlbyk** [comment]
> @nilact Can you submit this issue on the PowerShell repo? https://github.com/PowerShell/PowerShell/issues

Probably shouldn't since it's an issue with PS 5.1, right?

**Comment by rkeithhill** [comment]
Ah yeah, if this only happens in PS 5.1, then no, don't file an issue on GItHub since they're only tracking PS >= 6 issues there.

**Comment by nilact** [comment]
@rkeithhill @dahlbyk So there's no option to use posh-git with PS 5.1?

**Comment by rkeithhill** [comment]
You can use posh-git on PS 5.1. You just need to install it into a folder without a comma in the path.  For instance, install it into the default location with `install-module posh-git -allowclobber -force`.  You'll need to run that in an elevated console.
![image](https://user-images.githubusercontent.com/5177512/112732458-b3d7c880-8eff-11eb-84b5-7c0defadeeb9.png)
