### ISSUE TITLE
Autocomplete doesn't work with alias of git

### ISSUE THREAD

**Issue by eamodio** [dahlbyk/posh-git#849]
### System Details

- posh-git version/path: `1.0.0  ~\Documents\PowerShell\Modules\posh-git\1.0.0`
- PowerShell version: `7.2.0-preview.4`
- git version `2.31.0.windows.1`
- OS: `Microsoft Windows NT 10.0.19043.0`

### Issue Description

Since upgrading to `1.0.0`, autocomplete doesn't work anymore, and I've tracked it down to my alias of `g` to `git`. If I type `git` then autocomplete works fine, but if I just type `g` then it doesn't. This used to work prior to my upgrade to `1.0.0` (though I can't remember what version I had before that)

**Comment by rkeithhill** [comment]
See if https://github.com/dahlbyk/posh-git/issues/842 helps

**Comment by eamodio** [comment]
Sweet - that fixed it! Thanks!
