### ISSUE TITLE
Custom prompt problem when in git repo directory

### ISSUE THREAD

**Issue by bozho** [dahlbyk/posh-git#850]
### System Details

- posh-git version/path: 1.0.0  ~\.powershell\modules\posh-git\1.0.0
- PowerShell version: 5.1.19041.868
- git version 2.31.0.windows.1
- OS: Microsoft Windows NT 10.0.19042.0

### Issue Description

I've been using a custom prompt function for ages. This is the simplified version which shows the issue:
```
function global:prompt {
	$originalExitCode = $global:LASTEXITCODE
	$global:GitStatus = Get-GitStatus

	$path = $PWD.Path.Replace($env:HOME, '~')
	Write-Host $(Get-Date -Format HH:mm) -ForegroundColor blue -NoNewLine

	Write-Host " [$path]" -ForegroundColor yellow -NoNewLine
	Write-GitStatus $global:GitStatus
	Write-Host "" -ForegroundColor white -NoNewLine

	$global:LASTEXITCODE = $originalExitCode
	return " >"
}
```

There were no issues with previous `posh-git` versions (last one I was using was `0.7.3` before upgrading to `1.0.0`). The prompt in the home directory would look like: `21:40 [~] >` and if I were in a git repo directory, it would look like `21:43 [~\projects\powershell\cChoco] [development ≡] >`

Now, with `1.0.0`, if I'm in a git repo directory, the trailing ` >` is missing. I've tested this in Window Terminal, as well as the "old" console.

**Comment by rkeithhill** [comment]
You can either turn off the ANSI support in posh-git like so:
```
$GitPromptSettings.AnsiConsole = 0
```
or modify your prompt:
```
Write-Host (Write-GitStatus $global:GitStatus) -NoNewLine
```
This is because `Write-GitStatus` returns a string with ANSI seqs if `$GitPromptSettings.AnsiConsole` is set to `$true`.  And a prompt function that outputs multiple strings doesn't honor any but the first one output.
```
> function prompt { "PS", " >" }
PS
```

**Comment by bozho** [comment]
Thank you!

Are there any pros/cons for using `Write-Host` like this vs. using `Write-Prompt`, as in the documentation?

**Comment by rkeithhill** [comment]
If you use `Write-Prompt` in this form:
```powershell
# my profile.ps1
function prompt {
    # Your non-prompt logic here
    $prompt = Write-Prompt "Text before posh-git prompt " -ForegroundColor ([ConsoleColor]::Green)
    $prompt += & $GitPromptScriptBlock
    $prompt += Write-Prompt "Text after posh-git prompt" -ForegroundColor ([ConsoleColor]::Magenta)
    if ($prompt) { "$prompt " } else { " " }
}
```
Then your prompt will work no matter what `$GitPromptSettings.AnsiConsole` is set to.

**Comment by rkeithhill** [comment]
\
