### ISSUE TITLE
version 1 doesn't play well with ConEMU

### ISSUE THREAD

**Issue by cyberbiont** [dahlbyk/posh-git#856]
- posh-git 1.0.0:
- powershell 7.1.3:
- Git 2.31.1.windows.1
- Windows 10 pro x64 1909:

Hi, I thought for a while where to open this issue, but decided to put it here rather than in ConEMU repo because it seems related to the upgrade from v.0.7.3. to v1.0.0
The case is, ConEMU requires some code to be put in PS profile to work properly, see here: https://conemu.github.io/en/PowershellPrompt.html
Of most interest to me is the ability to freely move the cursor with the mouse click.
So, I had the following in my profile.ps
```PowerShell
Import-Module posh-git
function prompt
{
  $prompt += & $GitPromptScriptBlock

  $out = "> "

  # Check for ConEmu existance and ANSI emulation enabled
  $loc = Get-Location
  if ($env:ConEmuANSI -eq "ON") {
    $out += "$([char]27)]9;12$([char]7)"
    if ($loc.Provider.Name -eq "FileSystem") {
      $out += "$([char]27)]9;9;`"$($loc.Path)`"`"$GitPromptScriptBlock`"$([char]7)"
    }
  }

  return $out
}
```
This was working (with the exception that I didn't know how to set prompt color different from other text color.
After the upgrade to version 1.0.0 it doesn't work anymore and anything I tried didn't work either (I tried Write-VcsStatus instead of $prompt), click-moving cursor in ConEMU just doesn't work if I have posh-git prompt enabled.

**Comment by dahlbyk** [comment]
Try something like this: https://github.com/dahlbyk/posh-git/issues/732#issuecomment-599010152?

**Comment by dodmi** [comment]
I doubt, that this worked before. You put the GIT status to `$prompt`, but you don't use this variable afterwards. Replace `$GitPromptScriptBlock` with `$prompt` in the `$out += ...` line. But if you haven't configured the PoSh-Git prompt before, you'll end up with twice the path.

**Comment by cyberbiont** [comment]
@dodmi Believe it or not, this is how it actually worked with Posh-git 0.7.3 and the latest ConEMU version, you can check it out for yourself.
However, after upgrading to 1.0.0 this doesn't work anymore. Replacing $GitPromptScriptBlock with $prompt in the $out += line gives me just ">" as a prompt (maybe I messed up the syntax, Powershell scripts are not the sort of scripts that I usually do)

This: 
```powershell
Write-Host($pwd.ProviderPath) -ForegroundColor Green -nonewline
Write-VcsStatus
 $out = "> "

  $loc = Get-Location
  if ($env:ConEmuANSI -eq "ON") {
    $out += "$([char]27)]9;12$([char]7)"
    if ($loc.Provider.Name -eq "FileSystem") {
      $out += "$([char]27)]9;9;`"$($loc.Path)`"`"$GitPromptScriptBlock`"$([char]7)"
    }
  }
  return $out
```
works, but, as I said, as of posh-git 1.0.0 ConEMU doesn't function properly

**Comment by cyberbiont** [comment]
@dahlbyk  If I literallly copy the code you posted in #https://github.com/dahlbyk/posh-git/issues/732#issuecomment-599010152  to my $profile, it just gives me 'OK' for a prompt. Not sure how close it is... Clicking in ConEMU still doesn't work.
I'm not proficient with PS scripts, so I must admit that I need more detailed guidance.

**Comment by rkeithhill** [comment]
First a bit  of background on `posh-git` 0.x vs 1.0 prompts. The difference between 0.x and 1.0 WRT `Write-Prompt`, which $GitPromptScriptBlock uses, is that in 0.x, `Write-Prompt` always wrote directly to the host via `Write-Host`.  In 1.0, it only uses `Write-Host` if `$GitPromptSettting.AnsiConsole` is set to `$false`.  `posh-git` will set it to `$false` if posh-git detects the PowerShell host does not support Ansi e.g. `$host.UI.SupportsVirtualTerminal` is `$false` and `$env:ConEmuAnsi` is not `ON` e.g.:
```powershell
$AnsiConsole = ($Host.UI.SupportsVirtualTerminal -or ($Env:ConEmuANSI -eq "ON")) -and !$script:GitCygwin
```
When `$GitPromptSettting.AnsiConsole` is `$true`, `Write-Prompt` does NOT use `Write-Host` and instead constructs a string containing the ANSI VT sequences for colors and returns that string. It is up to the consumer to "output" that string as part of their prompt function (as the posh-git provided prompt function does) e.g.:
```powershell
function prompt {
    # Your non-prompt logic here
    $prompt = Write-Prompt "Text before posh-git prompt " -ForegroundColor ([ConsoleColor]::Green)
    $prompt += & $GitPromptScriptBlock
    $prompt += Write-Prompt "Text after posh-git prompt" -ForegroundColor ([ConsoleColor]::Magenta)
    if ($prompt) { "$prompt " } else { " " }
}
```
The implementation above works whether `$GitPromptSettings.AnsiConsole` is enabled or not.  When it's not enabled the `$prompt` variable will be an empty string (all prompt "output" is done via `Write-Host`) and the function returns the string " " which PowerShell expects from a `prompt` function.  If a prompt function does not return a string a least one char long, it will use it's default prompt: `PS>`.  

When AnsiConsole is enabled, `$prompt` contains the full prompt string with embedded VT sequences which the function returns as the "prompt" string to PowerShell.

OK, I don't have ConEmu to test with but  give this a try:
```powershell
function prompt {
    # Get the posh-git base prompt display/text
    $prompt = & $GitPromptScriptBlock

    # Check for ConEmu existance and ANSI emulation enabled
    if ($env:ConEmuANSI -eq "ON") {
        # Let ConEmu know when the prompt ends, to select typed command properly with "Shift+Home", 
        # to change cursor position in the prompt by simple mouse click, etc.
        $prompt += "$([char]27)]9;12$([char]7)"

        # And current working directory (FileSystem)
        # ConEmu may show full path or just current folder name in the Tab label (check Tab templates)
        # Also this knowledge is crucial to process hyperlinks clicks on files in the output from 
        # compilers and source control systems (git, hg, ...)
        $loc = Get-Location
        if ($loc.Provider.Name -eq "FileSystem") {
            $prompt += "$([char]27)]9;9;`"$($loc.Path)`"$([char]7)"
        }
    }

    if ($prompt) { "$prompt " } else { " " }
}
```
If that does not work, another option is to disable AnsiConsole in `posh-git` with `$GitPromptSettings.AnsiConsole = $false`.  This will cause `Write-Prompt` to drop back to using `Write-Host` like it did in version 0.x.

**Comment by dodmi** [comment]
@cyberbiont After the explanations here, I see how it worked, the magic term is `write-host`. And after having a look at the ConEmu Ansi table, I understand, why you didn't notice, that something isn't set up as expected, since text between these ANSI codes ist hidden by ConEmu, so you didn't see, that `$GitPromptScriptBlock` is simply a long string containing PowerShell code.

This has nothing to do with ConEmu (except the special ANSI codes, which are only supported there). As your original prompt function checks for the `ConEmuANSI` variable and doesn't do the ConEmu things if it's not present, you could see, that it won't work in bare PowerShell, too. I guess, the proposed function from the code above displays, what you saw before.

**Comment by cyberbiont** [comment]
@rkeithhill 
We have a winner! Both your solutions work, thanks a lot!
In fact, thanks everybody, I guess rkeithhill's solution may be added to README as an official recipe of how to use posh-git with ConEMU.

**Comment by rkeithhill** [comment]
@cyberbiont Could you try this version to see if it also works?  This makes sure to put the space after the `>` before the ConEmu OSC VT sequences - which depend on knowing where the prompt ends.
```powershell
function prompt {
    # Get the posh-git base prompt display/text
    $prompt = & $GitPromptScriptBlock
    $prompt = if ($prompt -eq " ") { $prompt } else { "$prompt " }
    
    # Check for ConEmu existance and ANSI emulation enabled
    if ($env:ConEmuANSI -eq "ON") {
        # Let ConEmu know when the prompt ends, to select typed command properly with "Shift+Home",
        # to change cursor position in the prompt by simple mouse click, etc.
        $prompt += "$([char]27)]9;12$([char]7)"

        # And current working directory (FileSystem)
        # ConEmu may show full path or just current folder name in the Tab label (check Tab templates)
        # Also this knowledge is crucial to process hyperlinks clicks on files in the output from
        # compilers and source control systems (git, hg, ...)
        $loc = Get-Location
        if ($loc.Provider.Name -eq "FileSystem") {
            $prompt += "$([char]27)]9;9;`"$($loc.Path)`"$([char]7)"
        }
    }

    $prompt
}
```
If this looks good, I'll add it to the README.

**Comment by cyberbiont** [comment]
@rkeithhill Sure, it works, but it seems that spaces around git status are already there and this extra space may be a little... extra.

This is how it was
![before](https://user-images.githubusercontent.com/59398323/115161617-6a663d80-a0a7-11eb-8e87-3584d4e2b8a0.PNG)
And this is what have become
![after](https://user-images.githubusercontent.com/59398323/115161635-88cc3900-a0a7-11eb-939a-07b03d544841.PNG)

**Comment by rkeithhill** [comment]
Good to know. Thanks!
