### ISSUE TITLE
powershell 7.1.3 does not disply posh-git prompt

### ISSUE THREAD

**Issue by jackfoxy** [dahlbyk/posh-git#858]
### System Details

- posh-git version/path: v0.7.3.1-0
- PowerShell version: 7.1.3
- Git version: 2.20.1.windows.1
- Operating system name and version: Windows 10, Version 10.0.19042 Build 19042

### Issue Description

I noticed posh-git prompt does not display in my 7.1.3 shell (both within Windows Terminal and not using WT).
It does display in my PS 5.1 shells.
I tried re-installing from within a 7.1.3 shell using choco, but no change

`choco install poshgit --force`

**Comment by dahlbyk** [comment]
Try `Add-Posh-GitToPrompt` in PS 7. I believe it uses a different `$PROFILE` location.

**Comment by jackfoxy** [comment]
@dahlbyk  you were right about `$PROFILE `being in a different location. Copying my `Microsoft.PowerShell_profile.ps1` to the correct path was the solution.

thanks!
