### ISSUE TITLE
Git with GVFS flagged as unsupported git distribution

### ISSUE THREAD

**Issue by ThadHouse** [dahlbyk/posh-git#860]
### System Details

- posh-git version/path: 1.0.0
- PowerShell version: 7.1.3
- Git version: git version 2.31.0.vfs.0.1
- Operating system name and version: Windows 10

### Issue Description

In Windows development, we use a copy of Git with GVFS enabled, which returns a version "git version 2.31.0.vfs.0.1". This gets flagged as a cygwin git distribution, even though it's not, and fully supports AsciConsole, so shouldn't be flagged as a cygwin version of git.

**Comment by dahlbyk** [comment]
Seems reasonable for us to check for `.vfs` in addition to `.windows` here:
https://github.com/dahlbyk/posh-git/blob/b79c2dc39c9387847642bc3b38fa2186b29f6113/src/CheckRequirements.ps1#L11

In the meantime, you can set `$Env:POSHGIT_CYGWIN_WARNING = 'off'` to disable the warning.

**Comment by ThadHouse** [comment]
I ended up just removing the check completely from my locally installed version, as it seemed like that variable just disabled theessage, but still left off the asci console, as it still set the internal variable. But as a solution I agree probably just add .vfs to the check as well. If you get to that before me I can at least test, otherwise I'll try to write up a fix this week.

**Comment by dahlbyk** [comment]
> it seemed like that variable just disabled the message, but still left off the asci console, as it still set the internal variable.

You're absolutely right: it sets `$script:GitCygwin`, which is part of how we initialize `AnsiConsole`: https://github.com/dahlbyk/posh-git/blob/5a87e8a196d13395f978d774f80dedb40d43b85e/src/PoshGitTypes.ps1#L226

You should still be able to set `$GitPromptSettings.AnsiConsole = $true` explicitly because you better.

**Comment by swiffer** [comment]
The same applies to release candidates like 2.32.0rc0

**Comment by dahlbyk** [comment]
Anyone know of a better way to identify a cygwin build of git? Maybe we could more reliably inspect the command path?

**Comment by rashil2000** [comment]
I'm facing the same issue 

```
WARNING: You appear to have an unsupported Git distribution; setting
$GitPromptSettings.AnsiConsole = $false. posh-git recommends Git for Windows.
Loading personal and system profiles took 1829ms.

PS ❯ git --version
git version 2.32.0.rc1.windows.1
```

**Comment by dahlbyk** [comment]
> I'm also in trouble. I use msys2. How to diable this warning? where to set `$Env:POSHGIT_CYGWIN_WARNING = 'off'`?

@fujiawei-dev what's your `git --version`?

**Comment by fujiawei-dev** [comment]
I had resolved this issue. I just put `Git for Windows` path in front of msys2's path.
