### ISSUE TITLE
The Git Status Summary Information Is Not Being Shown

### ISSUE THREAD

**Issue by genteelmagpie** [dahlbyk/posh-git#861]
### System Details

- posh-git version/path: 1.0.0  D:\GM\System Folders\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.19041.906
- git version 2.31.1.windows.1
- OS: Microsoft Windows NT 10.0.19042.0

### Issue Description

Hello, I recently did a clean install of windows and then installed windows Terminal from windows store. I have installed Cascadia Code Nerd Font and Jet Brains Nerd Font for the terminal powerline and then I followed "https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup' article to the letter and installed posh-git and other modules for the look I want for my terminal but after everything completed and I restarted my terminal, things are looking like before but the only issue is that the powerline is not showing the git status information like it used to just a day ago. The powerline looks like this:

UserName@PC Name > Full Path To The Working Directory > GitBranchName > Python Icon with Version No

and that's it. If I make changes to the current files or delete a file or create a new file and check for: "git status", everything is detected as they should but the powerline is not showing that information like before. What am I missing ?

Thanks for taking the time to help.
Regards

**Comment by tom-mckinney** [comment]
I believe I'm experiencing the same issue. My configuration (which worked prior to updating to `3.157.3`) is now showing this for the `git` segment:
![image](https://user-images.githubusercontent.com/12684522/119842968-1f74ec80-bed5-11eb-8512-4f96f1e2d5e3.png)

I'm using the Cascadia Code Nerd Font with Windows Terminal.

**Comment by rkeithhill** [comment]
Let's verify that `posh-git` by itself is working.  Execute the following and report back what you see:
```powershell
powershell.exe -noprofile
import-module posh-git
get-module
cd <root-of-git-repo>
```

**Comment by tom-mckinney** [comment]
Looks like `posh-git` is working fine by itself with both `powershell.exe` and `pwsh.exe`:
```
C:\Code ❯ powershell.exe -noprofile
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Code> import-module posh-git
C:\Code> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     0.7.3      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, Expan...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


C:\Code> cd .\regi\
C:\Code\regi [39/docker-support ≡]>
```

**Comment by tom-mckinney** [comment]
It also seems to work with the latest `posh-git@1.0.0`:
```powershell
C:\Code ❯ pwsh.exe -noprofile
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Code> import-module posh-git
C:\Code> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     1.0.0                 posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-…
Script     2.0.4                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

C:\Code> cd .\regi\
C:\Code\regi [39/docker-support ≡]>
```

**Comment by rkeithhill** [comment]
This might be an issue with `oh-my-posh`.  In fact, I'm not sure `oh-my-posh` still uses `posh-git` for git status reporting.

**Comment by genteelmagpie** [comment]
@rkeithhill 

I also got the same output as @tom-mckinney. I can see all the git status information when I run the commands you provided, so how do we fix it ?

**Comment by genteelmagpie** [comment]
> 
> 
> This might be an issue with `oh-my-posh`. In fact, I'm not sure `oh-my-posh` still uses `posh-git` for git status reporting.

If this is the case then what can we do to to make it right. Can we downgrade to some other version of oh-my-posh ?

**Comment by rkeithhill** [comment]
Just to see if I could repro this, I started powershell with `powershell.exe -noprofile` and followed Scott's instructions on that website and sure enough I don't see Git status data:

![image](https://user-images.githubusercontent.com/5177512/120079591-ce4e2f80-c071-11eb-9828-591d6baf6c87.png)

However, if I change to another theme like `slimfat` I DO see Git status:

![image](https://user-images.githubusercontent.com/5177512/120080268-466a2480-c075-11eb-9c77-3655fde13bfb.png)

So I'd say this is either a problem with the oh-my-posh `paradox` theme or that theme simply does not display status. You should file an issue on the [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) repo.
