### ISSUE TITLE
No repo status shown

### ISSUE THREAD

**Issue by olabacker** [dahlbyk/posh-git#863]
### System Details

- posh-git version/path: 1.0.0  ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.3
- git version 2.31.1.windows.1
- OS: Microsoft Windows NT 10.0.19043.0

### Issue Description

After installing posh-git the repo status and changes simply wont show. Auto-completion works fine.
![image](https://user-images.githubusercontent.com/4084523/122770826-21e51f00-d2a6-11eb-84eb-45486f6b9de1.png)

I have installed it a couple of times and used it in conjunction with oh-my-posh (also tried without it). It is the first time I see this after installing on a handful of times on other machines.

**Comment by rkeithhill** [comment]
Likely a duplicate of #861

**Comment by olabacker** [comment]
Yes, seems like it. Anyone looking for the same problem should check this out https://ohmyposh.dev/docs/git#sample-configuration
