### ISSUE TITLE
Posh-Git and ssh behaves differently than git in cmd

### ISSUE THREAD

**Issue by jorwoods** [dahlbyk/posh-git#866]
### System Details

- posh-git version/path: 1.0.0  C:\Program Files\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.18362.1593
- git version 2.19.1.windows.1
- OS: Microsoft Windows NT 10.0.18363.0

### Issue Description

I am experiencing a problem with...

When trying to work with a remote repo over ssh, I am getting prompted to validate the known host key, and provide a password repeatedly. The repo is configured to use ssh key pair for its auth. If I switch over to cmd, and run `git pull` it works as expected without prompting for credentials.

**Comment by dahlbyk** [comment]
Interesting. Can you try in a PowerShell session started with `powershell -noprofile` (without posh-git) to confirm if this is actually related to posh-git or just a general Git+PowerShell issue?

**Comment by jorwoods** [comment]
Ran `powershell -noprofile` then `git pull` in the resulting prompt, and it worked with the ssh auth, no prompts.

**Comment by dahlbyk** [comment]
> Ran `powershell -noprofile` then `git pull` in the resulting prompt, and it worked with the ssh auth, no prompts.

Please try again in a `-noprofile` shell after you `Import-Module posh-git`?

**Comment by jorwoods** [comment]
Progressively loading like that, the problem did not re-occur. Tested across a few different repos and it was isolated to only one. Re-cloned, and the problem vanished.
