### ISSUE TITLE
Why can I see Posh-Git in Windows PowerShell, but I can't in PowerShell?

### ISSUE THREAD

**Issue by rfalanga** [dahlbyk/posh-git#871]
### System Details

- posh-git version/path: 1.0.0  ~\OneDrive\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.19041.1237
- git version 2.33.0.windows.2
- OS: Microsoft Windows NT 10.0.19043.0
- 

### Issue Description

I am experiencing a problem with Posh-Git in Windows Terminal. I can see Posh-Git in the Windows PowerShell, but I cannot see it in PowerShell 7.1.4. I found this closed issue No. 858 [powershell 7.1.3 does not disply posh-git prompt](https://github.com/dahlbyk/posh-git/issues/858), but that doesn't seem to cover this. Why does Posh-Git work in one (Windows PowerShell), but not the other (PowerShell 7.1.4)?

**Comment by rkeithhill** [comment]
`posh-git` is typically loaded by the following line in your PowerShell profile script:
```powershell
Import-Module posh-git
```
If you look in `$HOME\Documents\WindowsPowerShell\profile.ps1` (or host-specific profile in the same dir), you should see that line above.  PowerShell 7 is different enough that it does NOT use those profile scripts.  PS 7 has its own directory for separate profiles and module installations.  

You need to make sure you've installed `posh-git` using PowerShell 7 and you need to add that line above to your `$HOME\Documents\PowerShell\profile.ps1` file.   After that, when you start a new PowerShell 7 session, posh-git should be available.

**Comment by dahlbyk** [comment]
> You need to make sure you've installed `posh-git` using PowerShell 7 and you need to add that line above to your `$HOME\Documents\PowerShell\profile.ps1` file.

In other words, run `Add-PoshGitToProfile` from shells that are missing it.
