### ISSUE TITLE
Publish posh-git to Windows Package Manager

### ISSUE THREAD

**Issue by MissakaI-Sentura** [dahlbyk/posh-git#875]
### Publish posh-git to Windows Package Manager

This request is to publish posh-git to Windows Package Manager so that it can be installed via `winget`. Winget is now installed out of the box in Windows 10 and Windows 11 and is stable now.

**Comment by dahlbyk** [comment]
My understanding is winget only supports specific kinds of installers, and is not well suited for PowerShell modules.
