### ISSUE TITLE
Prevent Tab completions for `git add |` from completing entire file path

### ISSUE THREAD

**Issue by th3coop** [dahlbyk/posh-git#876]
### System Details

- posh-git version/path: 1.0.0  ~\OneDrive\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version:  5.1.19041.1320
- Git version: git version 2.28.0.windows.1
- Operating system name and version: Win32NT  10.0.19041.0 Microsoft Windows NT 10.0.19041.0

### Issue Description

I am experiencing a problem with tab completions while performing `git add`.  It completes entire paths by default. What I usually need is to get the default shell behavior of completing the available files and folders in the CWD. 

So in a dir like:
repo root
-> A
  ->a.txt
  ->b.txt
-> B
  -> c.txt
  -> d.txt

I've edited both a.txt and b.txt so I want to do `git add A` but tab competions from posh-git gives me `git add A\a.txt`.  This gets really tedious when I'm adding files that are 4 - 5 directories deep.

I read through the FAQ and this repos README to see if there are any hints at turning this off but I can't find anything.  Is it possible to alter this behavior?

**Comment by dahlbyk** [comment]
Closing as duplicated of #750. From https://github.com/dahlbyk/posh-git/issues/750#issuecomment-601379524, try:

> Set-PSReadLineKeyHandler -Key Tab -Function Complete

Which calls [`Complete`](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7.2#complete):

> Attempt to perform completion on the text surrounding the cursor. If there are multiple possible completions, the longest unambiguous prefix is used for completion. If trying to complete the longest unambiguous completion, a list of possible completions is displayed.

If that works as expected, you can add that line to your `$PROFILE` so it's applied to every shell.

**Comment by th3coop** [comment]
Perfect, thank you very much @dahlbyk.  Amazing tool btw.  Literally use it everyday, numerous times a day.
