### ISSUE TITLE
git commit hashes are not yellow

### ISSUE THREAD

**Issue by SkybuckFlying** [dahlbyk/posh-git#880]
git commit hashes are not yellow, but instead white is there a way to make them yellow ?

**Comment by rkeithhill** [comment]
Can you post a screenshot showing this? If you're referring to commit hashes in `git log` output, `posh-git` has nothing to do with that.

**Comment by SkybuckFlying** [comment]
Thanks for letting me know.

Googling powershell + commit hash not yellow turns up:

https://stackoverflow.com/questions/11515089/why-no-yellow-in-powershell-and-posh-git

I will investigate this soon/probably tomorrow.

**Comment by rkeithhill** [comment]
@SkybuckFlying I'm going to close this for now. Let me know if it needs to be re-opened.
