### ISSUE TITLE
`EnableFileStatus = $false` does NOT fix bad perf in large repo

### ISSUE THREAD

**Issue by AArnott** [dahlbyk/posh-git#882]
### System Details

- posh-git version/path: 1.0.0  ~\OneDrive\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.2.0
- git version 2.34.1.windows.1
- OS: Microsoft Windows NT 10.0.22000.0

### Issue Description

In very large git repos, posh-git perf is abysmal. Even when turning off file status. See here an example:

```
PS C:\VS.r>
PS C:\VS.r> import-module posh-git
C:\VS.r [(0688549...)]> $GitPromptSettings.DefaultPromptEnableTiming = $true
C:\VS.r [(0688549...)] 18952ms> $GitPromptSettings.EnableFileStatus = $false
C:\VS.r [(0688549...)] 14910ms>
```

Turning off file status trims off about 3 seconds of 18, leaving 15 seconds. What is happening during those 15 seconds and how do I turn that off too?

I'd eventually like to use `$GitPromptSettings.RepositoriesInWhichToDisableFileStatus += 'c:\vs.r'` to fix perf for just this repo and use file status for all other repos, but after some analysis I found that even turning it off completely (as above) it doesn't solve the problem.

**Comment by AArnott** [comment]
After `git gc` we're down to 738ms when `EnableFileStatus = $false` and 5849ms when `EnableFileStatus = $true`. 

Still, 738ms is very slow for just looking up the branch name.

**Comment by rkeithhill** [comment]
Could you temporarily move the module out of the OneDrive folder and into your `~\Documents\PowerShell\Modules` folder to see if that makes any difference?

**Comment by AArnott** [comment]
I'm happy to try this out. But there is no Documents folder under my profile path. Literally if I try to navigate to `C:\Users\andarno\Documents\PowerShell` it redirects to `C:\Users\andarno\OneDrive\Documents\PowerShell`. Is there some other location I could try moving the module to? And could I then tell PowerShell to load it directly from there?

**Comment by rkeithhill** [comment]
Gotcha.  In that case, can you try moving the posh-git module folder to `$PSHome\Modules` e.g. ` 'C:\Program Files\PowerShell\7\Modules\'`?

**Comment by AArnott** [comment]
Just tried it. It doesn't seem to make any difference. Although now, no matter which location posh-git is in, the prompt takes only about 100ms to appear, which is perfectly fine. I don't know why yesterday it was taking 738ms.

**Comment by dahlbyk** [comment]
Can we close this?
