### ISSUE TITLE
Completion for "git add" no longer suggests changed files

### ISSUE THREAD

**Issue by thomaslevesque** [dahlbyk/posh-git#883]
### System Details

- posh-git version/path: 1.0.0  ~\OneDrive - MyCompany\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.2.1
- git version 2.34.1.windows.1
- OS: Microsoft Windows NT 10.0.19042.0

(I'm pretty sure the posh-git version is wrong... I installed via PowerShellGet not long ago, and tried to reinstall today, with the same result)

### Issue Description

At some point, the completion for `git add` suggested the paths of modified files. I'm sure it worked, because I used it very frequently. Now it just suggests the names of files and directories in the current directory.
I just installed on a different machine, and I'm seeing the same behavior.
Not sure when it stopped working...

**Comment by encaitor** [comment]
This has also stopped working for me since a while back. Would there be any way to toggle the functionality here if the change is intended?

**Comment by dahlbyk** [comment]
I don't know of anything that has changed in Git or posh-git recently that would cause this.

Can you check the contents of your `$GitStatus` variable in a project that has modifications? You should see the list of modified/staged files from `git status` in the `Index` and `Working` properties:
![image](https://user-images.githubusercontent.com/133987/150173131-7e9271bf-1a3e-4693-9f42-c7618549c9ec.png)

Other tab completion (commands, branch names) is working as expected?

**Comment by thomaslevesque** [comment]
Interesting... my $GitStatus variable is empty.
This seems to be caused by [Oh My Posh](https://ohmyposh.dev/). If I disable it in my PS profile, the problem disappears.
I was under the impression that Oh My Posh used posh-git for git related stuff, but it seems to actually _break_ posh-git...

**Comment by thomaslevesque** [comment]
OK, got it. To be able to use both posh-git and oh my posh, you just need to set the `POSH_GIT_ENABLED` environment variable to true in your PowerShell profile:

```powershell
$env:POSH_GIT_ENABLED = $true
```

This is documented [here](https://ohmyposh.dev/docs/git).

**Comment by dahlbyk** [comment]
Glad you figure it out, @thomaslevesque.

@JanDeDobbeleer, can you think of a reason for the posh-git module not to set `$env:POSH_GIT_ENABLED` on import? Or conversely, would it make sense for oh-my-posh to check `$GitPromptSettings.EnablePromptStatus` instead of needing to set a separate environment variable?

**Comment by JanDeDobbeleer** [comment]
@dahlbyk we could do that yes. Allow me to draft something!
