### ISSUE TITLE
git-posh no longer appears 

### ISSUE THREAD

**Issue by vanweric** [dahlbyk/posh-git#888]
### System Details

- posh-git version/path: 1.0.0  ~\Documents\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.19041.1320
- git version 2.20.1.windows.1
- OS: Microsoft Windows NT 10.0.19043.0

### Issue Description

I had been happily using git-posh for a good while until an unrelated unhappy circumstance required me to wipe two competing copies of python, reinstall them, and bang on some environment variables until they were happy again.  In my ill-informed and poorly executed chop-shop surgery I broke posh-git.

`Import-Module posh-git` immediately returns with no error message.
`Get-GitStatus` from within my git dirs correctly reports branch, repo, gitdir, etc.
Uninstalling did remove the files at the path listed above, and reinstalling replaced them.  The System details listed above are identical before the uninstall and after the reinstall.
`Get-Module` shows posh-git next to Conda, Microsoft Powershell Management&Utility, and PSReadline

From everything I can see, posh-git is installed, it is imported, it sees git... but does not display.

What further information is helpful?

Thank you!

**Comment by dahlbyk** [comment]
Do you get posh-git tab expansion but no prompt? What do you get from `Get-Command prompt -ShowCommandInfo`?

**Comment by vanweric** [comment]
Looks like you might've found the root cause, here is the result:

```
Name          : prompt
ModuleName    : Conda
Module        : @{Name=Conda}
CommandType   : Function
Definition    :
                        if ($Env:CONDA_PROMPT_MODIFIER) {
                            $Env:CONDA_PROMPT_MODIFIER | Write-Host -NoNewline
                        }
                        CondaPromptBackup;

ParameterSets : {@{Name=__AllParameterSets; IsDefault=False; Parameters=System.Management.Automation.PSObject[]}}
```

Looks like Conda took over, even in my powershell.  The previously mentioned "unrelated unhappy circumstance" was that conda's python took over globally.  Apparently my surgery was incomplete.

How should I proceed?
Thank you!

**Comment by dahlbyk** [comment]
Thought Conda sounded familiar… have a look at https://github.com/dahlbyk/posh-git/issues/765#issuecomment-614740121?

**Comment by vanweric** [comment]
Thanks @dahlbyk , the thread in #765 fixed my issue.

my ps1 now reads:

```
Import-Module posh-git

#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\ProgramData\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion
```

I was temporarily confused, as $profile is:
C:\Users\<name>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
but the actual file path is:
C:\Users\<name>\Documents\WindowsPowerShell\profile.ps1

Changing "profile.ps1" as shown above worked.

Thanks again for such a nifty tool!

**Comment by dahlbyk** [comment]
> I was temporarily confused, as $profile is:
> C:\Users<name>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
> but the actual file path is:
> C:\Users<name>\Documents\WindowsPowerShell\profile.ps1

For anyone who might benefit, `~\Documents\WindowsPowerShell\profile.ps1` is `$PROFILE.CurrentUserAllHosts`. `~\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` is `$PROFILE.CurrentUserCurrentHost` (i.e. `$PROFILE`). See [`about_Profiles`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles) for more info.
