### ISSUE TITLE
Can haz websight?

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#90]
http://dahlbyk.github.com/posh-git/

This here project has long since outgrown a readme. Stuff that needs to be documented:
- [ ] What the prompt means (readme may be good enough)
- [ ] Why the prompt might be slow (sigh) and workarounds
- [ ] `$GitPromptSettings` Colors/Delimiters
- [ ] `$GitPromptSettings` Behaviors: `Debug`, `EnableFileStatus`, `RepositoriesInWhichToDisableFileStatus`, etc
- [ ] Supported tab expansions
- [ ] `$GitTabSettings`
- [ ] `ssh-agent` Helpers
- [ ] `Update-AllBranches`

What else?

**Comment by rkeithhill** [comment]
That list looks pretty good.  And the website you point to looks pretty good as well.  Close?
