### ISSUE TITLE
Customization documentation out of date?

### ISSUE THREAD

**Issue by n3wjack** [dahlbyk/posh-git#900]
Recently, my posh-git prompt customizations broke. I'm thinking scripts were probably updated automatically somehow, because the day before it worked fine.

I'm using a line in my PS profile to set the prompt color to green, and I was using this, as mentioned in the docs:

    $GitPromptSettings.DefaultPromptPath.ForegroundColor = [ConsoleColor]::Green

This doesn't work, and throws an error telling me: "The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set."

This does work however:

    $GitPromptSettings.DefaultForegroundColor = [ConsoleColor]::Green

Is the documentation out of date, or is something else at play here?

**Comment by Jaykul** [comment]
Something weird with your config. With posh-git > 1.0 you definitely can do:

```PowerShell
$GitPromptSettings.DefaultPromptPath.ForegroundColor = [ConsoleColor]::Green
# or 
$GitPromptSettings.DefaultPromptPath.ForegroundColor = "LightGreen"
```

**Comment by n3wjack** [comment]
Somehow, on my work laptop, my posh-git version was set to an old 0.7 version, which broke the configuration in my PS profile.
I apparently had two versions of posh-git sitting around, so I removed all of them manually and reinstalled. Now it's back at 1.1.0, and I can use the config as mentioned above.
Thanks for your time!
