### ISSUE TITLE
Setting ForegroundColor not working in macOS Terminal app

### ISSUE THREAD

**Issue by srmagura** [dahlbyk/posh-git#903]
### System Details

- posh-git version/path: 1.1.0
- PowerShell version: 7.2.2
- Git version: 2.36.0
- Operating system name and version: macOS 12.3.1

### Issue Description

I've added the following snippet from the README to my PowerShell profile to set the default prompt color, but it doesn't seem to have any effect.

```pwsh
$GitPromptSettings.DefaultPromptPath.ForegroundColor = 0xFFA500
```

![image](https://user-images.githubusercontent.com/801549/165151032-028e6133-1116-4436-a192-f48949d45832.png)

Interestingly, it does change the color to orange as expected when running in the VSCode integrated terminal:

![image](https://user-images.githubusercontent.com/801549/165151140-f607576c-7862-4599-a6cf-eacdc1df7366.png)

**Comment by dahlbyk** [comment]
Try setting to a standard console color, e.g.

```
$GitPromptSettings.DefaultPromptPath.ForegroundColor = 'Orange'`
```

Not all shells support all the ANSI color options.

**Comment by srmagura** [comment]
Thanks. Still getting no effect with the line of code you provided. Interestingly, if I set the foreground color to `'LightGreen'`, I get a semi-transparent prompt...

![image](https://user-images.githubusercontent.com/801549/165160428-bb659100-fe7b-4632-82d1-a90a2fcf71e4.png)

**Comment by rkeithhill** [comment]
Tried this on my macbook pro and the Apple terminal doesn't seem to work with the VT extended foreground colors.  On my Windows machine, in Windows Terminal, it works as expected:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/5177512/165174376-dc253625-0d95-4819-8986-e451698c3121.png">

Check out this Apple thread on lack of 24-bit color support.  In the mean time, try this:
```powershell
$GitPromptSettings.DefaultPromptPath.ForegroundColor = "`e[38;5;172m"
```
To see all 256 colors available, try this:
```powershell
1..255 | Foreach-Object { "`e[38;5;${_}m Color index ${_}`e[39m" }
```

**Comment by dahlbyk** [comment]
This feels like an artifact of the terminal configuration more so than a posh-git issue, if changing to different colors at least produces a different result. Not sure how else to advise.

**Comment by rkeithhill** [comment]
Seems like an "external" issue and could be closed.
