### ISSUE TITLE
git clang-format broken after installing posh-git

### ISSUE THREAD

**Issue by bernhardmgruber** [dahlbyk/posh-git#925]
### System Details

- posh-git version/path: 1.1.0  C:\Program Files\WindowsPowerShell\Modules\Posh-Git\1.1.0
- PowerShell version: 5.1.19041.1682
- git version 2.36.1.windows.1
- OS: Microsoft Windows NT 10.0.19044.0

### Issue Description

`git clang-format` used to work before installing this extension, but fails now after installing with:
```
>  git clang-format
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

FYI: `git clang-format` invokes the python script `C:\Program Files\LLVM\bin\git-clang-format`, which is shipped with LLVM and in my path.

**Comment by dahlbyk** [comment]
Fascinating. I can't imagine how posh-git might be impacting this. Does it work again if you uninstall and/or remove `Import-Module posh-git` from your `$PROFILE`?

**Comment by bernhardmgruber** [comment]
Thanks for the hint! I removed the `Import-Module` from my profile and the problem persisted. I remember I upgraded LLVM on the same day I installed posh-git, so I have to suspect that something else broke `git clang-format`. I am sorry for the fuzz! It seems posh-git did nothing wrong here!
