### ISSUE TITLE
Bring back Get-GitBranch

### ISSUE THREAD

**Issue by Pxtl** [dahlbyk/posh-git#935]
### System Details

- posh-git version/path:  1.1.0
- PowerShell version: 5.1.19041.1682
- Git version:  2.38.1.windows.1
- OS: Microsoft Windows NT 10.0.19044.0

### Issue Description

The commandlet Get-GitBranch has been removed from the Posh-Git exported commands list.  It's still present in the repo utils but has been left out of the export script.  Get-GitBranch is very useful to my workflow -- every time I push a new branch, I do

`git push -u origin (Get-GitBranch)`

Can this be resurrected?  Otherwise is there a powershell module I should be using instead?

**Comment by hmleal** [comment]
In the mean time you can try something like: `git push -u origin (git rev-parse --abbrev-ref HEAD)`

**Comment by dahlbyk** [comment]
> > every time I push a new branch, I do
> > 
> > `git push -u origin (Get-GitBranch)`
>
> In the mean time you can use something like this: git push -u origin (git rev-parse --abbrev-ref HEAD)

Even better: `git push -u origin HEAD`!

```pwsh
# pnb = push new branch
git config --global alias.pnb "push -u origin HEAD"
```

----------------------------

Removing `Get-GitBranch` was part of a deliberate effort (https://github.com/dahlbyk/posh-git/pull/427) to reduce posh-git's surface area to tab expansion + prompt. You could use If you want PowerShell functions for Git, check out https://github.com/PoshCode/PSGit.
