### ISSUE TITLE
posh-git doesn't work with vscode integrated terminal 

### ISSUE THREAD

**Issue by longtth** [dahlbyk/posh-git#946]
### System Details

- posh-git version: 1.1.0 (install from Powershell Gallery) 
- posh-git path: not sure
- PowerShell version: 7.3.2 
- Git version: git version 2.36.0.windows.1
- Operating system name and version: Windows 10 22H2 

### Issue Description

posh-git works well with default pwsh terminal but doesn't work with vscode integrated terminal 

screenshot: 

![image](https://user-images.githubusercontent.com/1010849/219799571-0fda8efc-735e-46d6-8afe-581d715a3b7f.png)

**Comment by dahlbyk** [comment]
What does `$PROFILE` show in Terminal vs VS Code? It seems likely that posh-git just isn't loading in VS Code.

**Comment by longtth** [comment]
they return the same thing 

![image](https://user-images.githubusercontent.com/1010849/219907159-f7cf8754-7f06-4bb6-ab11-a05a1530929f.png)

**Comment by dahlbyk** [comment]
If you `cat $PROFILE` is that where posh-git is imported?

Does `$Errors` show anything interesting?

**Comment by longtth** [comment]
excuse me for missing your reply, 
after several uninstall / install posh-git and restart, it works well now, 
next time if encounter the issue, I will check follow your guide 
![image](https://user-images.githubusercontent.com/1010849/219998845-e2b8da7e-5be5-4235-bdf2-16d6bd739c45.png)

**Comment by dahlbyk** [comment]
Sorry I couldn't be more help, but glad it's working!
