### ISSUE TITLE
Posh-git Prompt will not show

### ISSUE THREAD

**Issue by AWH1122** [dahlbyk/posh-git#967]
### System Details

- posh-git version/path: C:\Users\Alexander\Documents\WindowsPowerShell\Modules\posh-git\1.1.0\posh-git.psm1
- PowerShell version: 5.1.22621.2506
- Git version:  2.43.0.windows.1
- Operating system name and version: Windows 11 23H2 

### Issue Description

I am experiencing a problem with...

Following the install and setup instructions using both chocolatey and powershell gallery, I cannot get the posh-git prompt to show up when in a folder with an initialised repo.

**Comment by corbob** [comment]
What are you doing to try to get the prompt to display? After the installation, you need to import posh-git in order for it to work.

**Comment by AWH1122** [comment]
I found what was going wrong. I am using miniconda as well as posh git. I changed the import order in my powershell profile and everything now functions correctly.

**Comment by dahlbyk** [comment]
> I changed the import order in my powershell profile and everything now functions correctly.

Did you move posh-git before or after? I generally recommend importing posh-git last because we're careful not to overwrite existing customizations.

**Comment by AWH1122** [comment]
I imported posh-git after miniconda.
